package assets.gui;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: gui/2 Bars
 * Total assets: 21
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class BarAssets {

    private static final String DIR = "Resources/industrial-zone/gui/2 Bars/";

    /** 32x14px | static */
    public static final SpriteAsset GUI_BAR_HEALTHBAR_FULL100PCT_REDORANGEFILLDARKFRAME_HUD = SpriteAsset.single(
        "01_GUI_Bar_HealthBar_Full100pct_RedOrangeFillDarkFrame_HUD.png",
        DIR, 32, 14,
        "UI Element - 01 GUI Bar HealthBar Full100pct RedOrangeFillDarkFrame HUD");

    /** 32x14px | static */
    public static final SpriteAsset GUI_BAR_HEALTHBAR_80PCT_REDORANGEFILL_HUD = SpriteAsset.single(
        "02_GUI_Bar_HealthBar_80pct_RedOrangeFill_HUD.png",
        DIR, 32, 14,
        "UI Element - 02 GUI Bar HealthBar 80pct RedOrangeFill HUD");

    /** 32x14px | static */
    public static final SpriteAsset GUI_BAR_HEALTHBAR_60PCT_REDORANGEFILL_HUD = SpriteAsset.single(
        "03_GUI_Bar_HealthBar_60pct_RedOrangeFill_HUD.png",
        DIR, 32, 14,
        "UI Element - 03 GUI Bar HealthBar 60pct RedOrangeFill HUD");

    /** 32x14px | static */
    public static final SpriteAsset GUI_BAR_HEALTHBAR_40PCT_REDORANGEFILL_HUD = SpriteAsset.single(
        "04_GUI_Bar_HealthBar_40pct_RedOrangeFill_HUD.png",
        DIR, 32, 14,
        "UI Element - 04 GUI Bar HealthBar 40pct RedOrangeFill HUD");

    /** 32x14px | static */
    public static final SpriteAsset GUI_BAR_HEALTHBAR_20PCT_REDORANGEFILL_HUD = SpriteAsset.single(
        "05_GUI_Bar_HealthBar_20pct_RedOrangeFill_HUD.png",
        DIR, 32, 14,
        "UI Element - 05 GUI Bar HealthBar 20pct RedOrangeFill HUD");

    /** 32x14px | static */
    public static final SpriteAsset GUI_BAR_HEALTHBAR_5PCTCRITICAL_REDORANGEFILL_HUD = SpriteAsset.single(
        "06_GUI_Bar_HealthBar_5pctCritical_RedOrangeFill_HUD.png",
        DIR, 32, 14,
        "UI Element - 06 GUI Bar HealthBar 5pctCritical RedOrangeFill HUD");

    /** 32x14px | static */
    public static final SpriteAsset GUI_BAR_HEALTHBAR_EMPTYFRAME_NOFILLCONTAINER_HUD = SpriteAsset.single(
        "07_GUI_Bar_HealthBar_EmptyFrame_NoFillContainer_HUD.png",
        DIR, 32, 14,
        "UI Element - 07 GUI Bar HealthBar EmptyFrame NoFillContainer HUD");

    /** 32x14px | static */
    public static final SpriteAsset GUI_BAR_HEALTHBAR_EMPTYVARIANT_DIFFFRAMESTYLE_HUD = SpriteAsset.single(
        "08_GUI_Bar_HealthBar_EmptyVariant_DiffFrameStyle_HUD.png",
        DIR, 32, 14,
        "UI Element - 08 GUI Bar HealthBar EmptyVariant DiffFrameStyle HUD");

    /** 16x5px | static */
    public static final SpriteAsset GUI_BAR_ENERGYBAR_FULL100PCT_BLUECYANFILLDARKFRAME_HUD = SpriteAsset.single(
        "09_GUI_Bar_EnergyBar_Full100pct_BlueCyanFillDarkFrame_HUD.png",
        DIR, 16, 5,
        "UI Element - 09 GUI Bar EnergyBar Full100pct BlueCyanFillDarkFrame HUD");

    /** 16x5px | static */
    public static final SpriteAsset GUI_BAR_ENERGYBAR_80PCT_BLUECYANFILL_HUD = SpriteAsset.single(
        "10_GUI_Bar_EnergyBar_80pct_BlueCyanFill_HUD.png",
        DIR, 16, 5,
        "UI Element - 10 GUI Bar EnergyBar 80pct BlueCyanFill HUD");

    /** 16x5px | static */
    public static final SpriteAsset GUI_BAR_ENERGYBAR_60PCT_BLUECYANFILL_HUD = SpriteAsset.single(
        "11_GUI_Bar_EnergyBar_60pct_BlueCyanFill_HUD.png",
        DIR, 16, 5,
        "UI Element - 11 GUI Bar EnergyBar 60pct BlueCyanFill HUD");

    /** 16x5px | static */
    public static final SpriteAsset GUI_BAR_ENERGYBAR_40PCT_BLUECYANFILL_HUD = SpriteAsset.single(
        "12_GUI_Bar_EnergyBar_40pct_BlueCyanFill_HUD.png",
        DIR, 16, 5,
        "UI Element - 12 GUI Bar EnergyBar 40pct BlueCyanFill HUD");

    /** 16x5px | static */
    public static final SpriteAsset GUI_BAR_ENERGYBAR_20PCT_BLUECYANFILL_HUD = SpriteAsset.single(
        "13_GUI_Bar_EnergyBar_20pct_BlueCyanFill_HUD.png",
        DIR, 16, 5,
        "UI Element - 13 GUI Bar EnergyBar 20pct BlueCyanFill HUD");

    /** 16x5px | static */
    public static final SpriteAsset GUI_BAR_ENERGYBAR_5PCTCRITICAL_BLUECYANFILL_HUD = SpriteAsset.single(
        "14_GUI_Bar_EnergyBar_5pctCritical_BlueCyanFill_HUD.png",
        DIR, 16, 5,
        "UI Element - 14 GUI Bar EnergyBar 5pctCritical BlueCyanFill HUD");

    /** 16x5px | static */
    public static final SpriteAsset GUI_BAR_ENERGYBAR_EMPTYFRAME_NOFILLCONTAINER_HUD = SpriteAsset.single(
        "15_GUI_Bar_EnergyBar_EmptyFrame_NoFillContainer_HUD.png",
        DIR, 16, 5,
        "UI Element - 15 GUI Bar EnergyBar EmptyFrame NoFillContainer HUD");

    /** 16x5px | static */
    public static final SpriteAsset GUI_BAR_ENERGYBAR_EMPTYVARIANT_DIFFFRAMESTYLE_HUD = SpriteAsset.single(
        "16_GUI_Bar_EnergyBar_EmptyVariant_DiffFrameStyle_HUD.png",
        DIR, 16, 5,
        "UI Element - 16 GUI Bar EnergyBar EmptyVariant DiffFrameStyle HUD");

    /** 32x32px | static */
    public static final SpriteAsset GUI_BAR_SCROLLBAR_NEONPINKBLUEGLOWTALL_SCROLLCONTROL_HUD = SpriteAsset.single(
        "17_GUI_Bar_ScrollBar_NeonPinkBlueGlowTall_ScrollControl_HUD.png",
        DIR, 32, 32,
        "UI Element - 17 GUI Bar ScrollBar NeonPinkBlueGlowTall ScrollControl HUD");

    /** 32x32px | static */
    public static final SpriteAsset GUI_BAR_SCROLLBAR_NEONGLOWVARIANT_SCROLLCONTROL_HUD = SpriteAsset.single(
        "18_GUI_Bar_ScrollBar_NeonGlowVariant_ScrollControl_HUD.png",
        DIR, 32, 32,
        "UI Element - 18 GUI Bar ScrollBar NeonGlowVariant ScrollControl HUD");

    /** 32x32px | static */
    public static final SpriteAsset GUI_BAR_SCROLLBAR_PLAINBLUETALLSTRIP_SCROLLCONTROL_HUD = SpriteAsset.single(
        "19_GUI_Bar_ScrollBar_PlainBlueTallStrip_ScrollControl_HUD.png",
        DIR, 32, 32,
        "UI Element - 19 GUI Bar ScrollBar PlainBlueTallStrip ScrollControl HUD");

    /** 32x32px | static */
    public static final SpriteAsset GUI_BAR_SCROLLBAR_NEONGLOWDECORATIVETALLER_SCROLLCONTROL_HUD = SpriteAsset.single(
        "20_GUI_Bar_ScrollBar_NeonGlowDecorativeTaller_ScrollControl_HUD.png",
        DIR, 32, 32,
        "UI Element - 20 GUI Bar ScrollBar NeonGlowDecorativeTaller ScrollControl HUD");

    /** 200x20px | ~10 frames */
    public static final SpriteAsset HEALTH_BAR_FULL = SpriteAsset.single(
        "health_bar_full.png",
        DIR, 200, 20,
        "Asset - health bar full");

    /** Total number of assets in this group */
    public static final int COUNT = 21;

    private BarAssets() { } // no instantiation
}
