package assets.gui;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: gui/6 Buttons
 * Total assets: 10
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class ButtonAssets {

    private static final String DIR = "Resources/industrial-zone/gui/6 Buttons/";

    /** 128x256px | static */
    public static final SpriteAsset GUI_BUTTONCOLORMAP_VARIANT_01 = SpriteAsset.single(
        "GUI_ButtonColorMap_Variant_01.png",
        DIR, 128, 256,
        "UI Element - GUI ButtonColorMap Variant 01");

    /** 128x256px | static */
    public static final SpriteAsset GUI_BUTTONCOLORMAP_VARIANT_02 = SpriteAsset.single(
        "GUI_ButtonColorMap_Variant_02.png",
        DIR, 128, 256,
        "UI Element - GUI ButtonColorMap Variant 02");

    /** 128x256px | static */
    public static final SpriteAsset GUI_BUTTONCOLORMAP_VARIANT_03 = SpriteAsset.single(
        "GUI_ButtonColorMap_Variant_03.png",
        DIR, 128, 256,
        "UI Element - GUI ButtonColorMap Variant 03");

    /** 128x256px | static */
    public static final SpriteAsset GUI_BUTTONCOLORMAP_VARIANT_04 = SpriteAsset.single(
        "GUI_ButtonColorMap_Variant_04.png",
        DIR, 128, 256,
        "UI Element - GUI ButtonColorMap Variant 04");

    /** 128x256px | static */
    public static final SpriteAsset GUI_BUTTONCOLORMAP_VARIANT_05 = SpriteAsset.single(
        "GUI_ButtonColorMap_Variant_05.png",
        DIR, 128, 256,
        "UI Element - GUI ButtonColorMap Variant 05");

    /** 128x256px | static */
    public static final SpriteAsset GUI_BUTTONCOLORMAP_VARIANT_06 = SpriteAsset.single(
        "GUI_ButtonColorMap_Variant_06.png",
        DIR, 128, 256,
        "UI Element - GUI ButtonColorMap Variant 06");

    /** 128x256px | static */
    public static final SpriteAsset GUI_BUTTONCOLORMAP_VARIANT_07 = SpriteAsset.single(
        "GUI_ButtonColorMap_Variant_07.png",
        DIR, 128, 256,
        "UI Element - GUI ButtonColorMap Variant 07");

    /** 128x256px | static */
    public static final SpriteAsset GUI_BUTTONCOLORMAP_VARIANT_08 = SpriteAsset.single(
        "GUI_ButtonColorMap_Variant_08.png",
        DIR, 128, 256,
        "UI Element - GUI ButtonColorMap Variant 08");

    /** 128x256px | static */
    public static final SpriteAsset GUI_BUTTONCOLORMAP_VARIANT_09 = SpriteAsset.single(
        "GUI_ButtonColorMap_Variant_09.png",
        DIR, 128, 256,
        "UI Element - GUI ButtonColorMap Variant 09");

    /** 128x256px | static */
    public static final SpriteAsset GUI_BUTTONCOLORMAP_VARIANT_10 = SpriteAsset.single(
        "GUI_ButtonColorMap_Variant_10.png",
        DIR, 128, 256,
        "UI Element - GUI ButtonColorMap Variant 10");

    /** Total number of assets in this group */
    public static final int COUNT = 10;

    private ButtonAssets() { } // no instantiation
}
