package assets.gui;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: gui/8 Cursors
 * Total assets: 4
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class CursorAssets {

    private static final String DIR = "Resources/industrial-zone/gui/8 Cursors/";

    /** 14x20px | static */
    public static final SpriteAsset GUI_CURSOR_WHITE_DEFAULTPOINTER = SpriteAsset.single(
        "01_GUI_Cursor_White_DefaultPointer.png",
        DIR, 14, 20,
        "UI Element - 01 GUI Cursor White DefaultPointer");

    /** 15x21px | static */
    public static final SpriteAsset GUI_CURSOR_BLUE_TARGETINGPOINTER = SpriteAsset.single(
        "02_GUI_Cursor_Blue_TargetingPointer.png",
        DIR, 15, 21,
        "UI Element - 02 GUI Cursor Blue TargetingPointer");

    /** 12x20px | static */
    public static final SpriteAsset GUI_CURSOR_RED_ATTACKPOINTER = SpriteAsset.single(
        "03_GUI_Cursor_Red_AttackPointer.png",
        DIR, 12, 20,
        "UI Element - 03 GUI Cursor Red AttackPointer");

    /** 13x19px | static */
    public static final SpriteAsset GUI_CURSOR_GREEN_CONFIRMPOINTER = SpriteAsset.single(
        "04_GUI_Cursor_Green_ConfirmPointer.png",
        DIR, 13, 19,
        "UI Element - 04 GUI Cursor Green ConfirmPointer");

    /** Total number of assets in this group */
    public static final int COUNT = 4;

    private CursorAssets() { } // no instantiation
}
