package assets.gui;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: gui/10 Font
 * Total assets: 64
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class FontAssets {

    private static final String DIR = "Resources/industrial-zone/gui/10 Font/";

    /** 14x14px | static */
    public static final SpriteAsset A_01 = SpriteAsset.single(
        "1_01.png",
        DIR, 14, 14,
        "Asset - 1 01");

    /** 14x14px | static */
    public static final SpriteAsset A_02 = SpriteAsset.single(
        "1_02.png",
        DIR, 14, 14,
        "Asset - 1 02");

    /** 14x14px | static */
    public static final SpriteAsset A_03 = SpriteAsset.single(
        "1_03.png",
        DIR, 14, 14,
        "Asset - 1 03");

    /** 14x14px | static */
    public static final SpriteAsset A_04 = SpriteAsset.single(
        "1_04.png",
        DIR, 14, 14,
        "Asset - 1 04");

    /** 14x14px | static */
    public static final SpriteAsset A_05 = SpriteAsset.single(
        "1_05.png",
        DIR, 14, 14,
        "Asset - 1 05");

    /** 14x14px | static */
    public static final SpriteAsset A_06 = SpriteAsset.single(
        "1_06.png",
        DIR, 14, 14,
        "Asset - 1 06");

    /** 14x14px | static */
    public static final SpriteAsset A_07 = SpriteAsset.single(
        "1_07.png",
        DIR, 14, 14,
        "Asset - 1 07");

    /** 14x14px | static */
    public static final SpriteAsset A_08 = SpriteAsset.single(
        "1_08.png",
        DIR, 14, 14,
        "Asset - 1 08");

    /** 14x14px | static */
    public static final SpriteAsset A_09 = SpriteAsset.single(
        "1_09.png",
        DIR, 14, 14,
        "Asset - 1 09");

    /** 14x14px | static */
    public static final SpriteAsset A_10 = SpriteAsset.single(
        "1_10.png",
        DIR, 14, 14,
        "Asset - 1 10");

    /** 14x14px | static */
    public static final SpriteAsset A_11 = SpriteAsset.single(
        "1_11.png",
        DIR, 14, 14,
        "Asset - 1 11");

    /** 14x14px | static */
    public static final SpriteAsset A_12 = SpriteAsset.single(
        "1_12.png",
        DIR, 14, 14,
        "Asset - 1 12");

    /** 14x14px | static */
    public static final SpriteAsset A_13 = SpriteAsset.single(
        "1_13.png",
        DIR, 14, 14,
        "Asset - 1 13");

    /** 14x14px | static */
    public static final SpriteAsset A_14 = SpriteAsset.single(
        "1_14.png",
        DIR, 14, 14,
        "Asset - 1 14");

    /** 14x14px | static */
    public static final SpriteAsset A_15 = SpriteAsset.single(
        "1_15.png",
        DIR, 14, 14,
        "Asset - 1 15");

    /** 14x14px | static */
    public static final SpriteAsset A_16 = SpriteAsset.single(
        "1_16.png",
        DIR, 14, 14,
        "Asset - 1 16");

    /** 14x14px | static */
    public static final SpriteAsset A_17 = SpriteAsset.single(
        "1_17.png",
        DIR, 14, 14,
        "Asset - 1 17");

    /** 14x14px | static */
    public static final SpriteAsset A_18 = SpriteAsset.single(
        "1_18.png",
        DIR, 14, 14,
        "Asset - 1 18");

    /** 14x14px | static */
    public static final SpriteAsset A_19 = SpriteAsset.single(
        "1_19.png",
        DIR, 14, 14,
        "Asset - 1 19");

    /** 14x14px | static */
    public static final SpriteAsset A_20 = SpriteAsset.single(
        "1_20.png",
        DIR, 14, 14,
        "Asset - 1 20");

    /** 14x14px | static */
    public static final SpriteAsset A_21 = SpriteAsset.single(
        "1_21.png",
        DIR, 14, 14,
        "Asset - 1 21");

    /** 14x14px | static */
    public static final SpriteAsset A_22 = SpriteAsset.single(
        "1_22.png",
        DIR, 14, 14,
        "Asset - 1 22");

    /** 14x14px | static */
    public static final SpriteAsset A_23 = SpriteAsset.single(
        "1_23.png",
        DIR, 14, 14,
        "Asset - 1 23");

    /** 14x14px | static */
    public static final SpriteAsset A_24 = SpriteAsset.single(
        "1_24.png",
        DIR, 14, 14,
        "Asset - 1 24");

    /** 14x14px | static */
    public static final SpriteAsset A_25 = SpriteAsset.single(
        "1_25.png",
        DIR, 14, 14,
        "Asset - 1 25");

    /** 14x14px | static */
    public static final SpriteAsset A_26 = SpriteAsset.single(
        "1_26.png",
        DIR, 14, 14,
        "Asset - 1 26");

    /** 14x14px | static */
    public static final SpriteAsset A_27 = SpriteAsset.single(
        "1_27.png",
        DIR, 14, 14,
        "Asset - 1 27");

    /** 14x14px | static */
    public static final SpriteAsset A_28 = SpriteAsset.single(
        "1_28.png",
        DIR, 14, 14,
        "Asset - 1 28");

    /** 14x14px | static */
    public static final SpriteAsset A_29 = SpriteAsset.single(
        "1_29.png",
        DIR, 14, 14,
        "Asset - 1 29");

    /** 14x14px | static */
    public static final SpriteAsset A_30 = SpriteAsset.single(
        "1_30.png",
        DIR, 14, 14,
        "Asset - 1 30");

    /** 14x14px | static */
    public static final SpriteAsset A_31 = SpriteAsset.single(
        "1_31.png",
        DIR, 14, 14,
        "Asset - 1 31");

    /** 14x14px | static */
    public static final SpriteAsset A_32 = SpriteAsset.single(
        "1_32.png",
        DIR, 14, 14,
        "Asset - 1 32");

    /** 14x14px | static */
    public static final SpriteAsset A_33 = SpriteAsset.single(
        "1_33.png",
        DIR, 14, 14,
        "Asset - 1 33");

    /** 14x14px | static */
    public static final SpriteAsset A_34 = SpriteAsset.single(
        "1_34.png",
        DIR, 14, 14,
        "Asset - 1 34");

    /** 14x14px | static */
    public static final SpriteAsset A_35 = SpriteAsset.single(
        "1_35.png",
        DIR, 14, 14,
        "Asset - 1 35");

    /** 14x14px | static */
    public static final SpriteAsset A_36 = SpriteAsset.single(
        "1_36.png",
        DIR, 14, 14,
        "Asset - 1 36");

    /** 14x14px | static */
    public static final SpriteAsset A_37 = SpriteAsset.single(
        "1_37.png",
        DIR, 14, 14,
        "Asset - 1 37");

    /** 14x14px | static */
    public static final SpriteAsset A_38 = SpriteAsset.single(
        "1_38.png",
        DIR, 14, 14,
        "Asset - 1 38");

    /** 14x14px | static */
    public static final SpriteAsset A_39 = SpriteAsset.single(
        "1_39.png",
        DIR, 14, 14,
        "Asset - 1 39");

    /** 14x14px | static */
    public static final SpriteAsset A_40 = SpriteAsset.single(
        "1_40.png",
        DIR, 14, 14,
        "Asset - 1 40");

    /** 14x14px | static */
    public static final SpriteAsset A_41 = SpriteAsset.single(
        "1_41.png",
        DIR, 14, 14,
        "Asset - 1 41");

    /** 14x14px | static */
    public static final SpriteAsset A_42 = SpriteAsset.single(
        "1_42.png",
        DIR, 14, 14,
        "Asset - 1 42");

    /** 14x14px | static */
    public static final SpriteAsset A_43 = SpriteAsset.single(
        "1_43.png",
        DIR, 14, 14,
        "Asset - 1 43");

    /** 14x14px | static */
    public static final SpriteAsset A_44 = SpriteAsset.single(
        "1_44.png",
        DIR, 14, 14,
        "Asset - 1 44");

    /** 14x14px | static */
    public static final SpriteAsset A_45 = SpriteAsset.single(
        "1_45.png",
        DIR, 14, 14,
        "Asset - 1 45");

    /** 14x14px | static */
    public static final SpriteAsset A_46 = SpriteAsset.single(
        "1_46.png",
        DIR, 14, 14,
        "Asset - 1 46");

    /** 14x14px | static */
    public static final SpriteAsset A_47 = SpriteAsset.single(
        "1_47.png",
        DIR, 14, 14,
        "Asset - 1 47");

    /** 14x14px | static */
    public static final SpriteAsset A_48 = SpriteAsset.single(
        "1_48.png",
        DIR, 14, 14,
        "Asset - 1 48");

    /** 14x14px | static */
    public static final SpriteAsset A_49 = SpriteAsset.single(
        "1_49.png",
        DIR, 14, 14,
        "Asset - 1 49");

    /** 14x14px | static */
    public static final SpriteAsset A_50 = SpriteAsset.single(
        "1_50.png",
        DIR, 14, 14,
        "Asset - 1 50");

    /** 14x14px | static */
    public static final SpriteAsset A_51 = SpriteAsset.single(
        "1_51.png",
        DIR, 14, 14,
        "Asset - 1 51");

    /** 14x14px | static */
    public static final SpriteAsset A_52 = SpriteAsset.single(
        "1_52.png",
        DIR, 14, 14,
        "Asset - 1 52");

    /** 14x14px | static */
    public static final SpriteAsset A_53 = SpriteAsset.single(
        "1_53.png",
        DIR, 14, 14,
        "Asset - 1 53");

    /** 14x14px | static */
    public static final SpriteAsset A_54 = SpriteAsset.single(
        "1_54.png",
        DIR, 14, 14,
        "Asset - 1 54");

    /** 14x14px | static */
    public static final SpriteAsset A_55 = SpriteAsset.single(
        "1_55.png",
        DIR, 14, 14,
        "Asset - 1 55");

    /** 14x14px | static */
    public static final SpriteAsset A_56 = SpriteAsset.single(
        "1_56.png",
        DIR, 14, 14,
        "Asset - 1 56");

    /** 14x14px | static */
    public static final SpriteAsset A_57 = SpriteAsset.single(
        "1_57.png",
        DIR, 14, 14,
        "Asset - 1 57");

    /** 14x14px | static */
    public static final SpriteAsset A_58 = SpriteAsset.single(
        "1_58.png",
        DIR, 14, 14,
        "Asset - 1 58");

    /** 14x14px | static */
    public static final SpriteAsset A_59 = SpriteAsset.single(
        "1_59.png",
        DIR, 14, 14,
        "Asset - 1 59");

    /** 14x14px | static */
    public static final SpriteAsset A_60 = SpriteAsset.single(
        "1_60.png",
        DIR, 14, 14,
        "Asset - 1 60");

    /** 14x14px | static */
    public static final SpriteAsset A_61 = SpriteAsset.single(
        "1_61.png",
        DIR, 14, 14,
        "Asset - 1 61");

    /** 14x14px | static */
    public static final SpriteAsset A_62 = SpriteAsset.single(
        "1_62.png",
        DIR, 14, 14,
        "Asset - 1 62");

    /** 14x14px | static */
    public static final SpriteAsset A_63 = SpriteAsset.single(
        "1_63.png",
        DIR, 14, 14,
        "Asset - 1 63");

    /** 0x0px | static */
    public static final SpriteAsset CYBERPUNKCRAFTPIXPIXEL = SpriteAsset.single(
        "CyberpunkCraftpixPixel.otf",
        DIR, 0, 0,
        "Asset - CyberpunkCraftpixPixel.otf");

    /** Total number of assets in this group */
    public static final int COUNT = 64;

    private FontAssets() { } // no instantiation
}
