package assets.gui;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: gui/1 Frames
 * Total assets: 82
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class FrameAssets {

    private static final String DIR = "Resources/industrial-zone/gui/1 Frames/";

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERTOPLEFT_TALLLSHAPEPIECE_WINDOWCORNER = SpriteAsset.single(
        "01_GUI_Frame_CornerTopLeft_TallLShapePiece_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 01 GUI Frame CornerTopLeft TallLShapePiece WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGETOPBAR_HORIZONTALBLUEACCENTSTRIP_WINDOWTOPEDGE = SpriteAsset.single(
        "02_GUI_Frame_EdgeTopBar_HorizontalBlueAccentStrip_WindowTopEdge.png",
        DIR, 32, 32,
        "UI Element - 02 GUI Frame EdgeTopBar HorizontalBlueAccentStrip WindowTopEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERTOPRIGHT_TALLLSHAPEMIRROR_WINDOWCORNER = SpriteAsset.single(
        "03_GUI_Frame_CornerTopRight_TallLShapeMirror_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 03 GUI Frame CornerTopRight TallLShapeMirror WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERTOPLEFTRIVET_REDDOTACCENTS_WINDOWCORNER = SpriteAsset.single(
        "04_GUI_Frame_CornerTopLeftRivet_RedDotAccents_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 04 GUI Frame CornerTopLeftRivet RedDotAccents WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGELEFTSTRIP_TALLNARROWVERTICALBAR_WINDOWLEFTEDGE = SpriteAsset.single(
        "05_GUI_Frame_EdgeLeftStrip_TallNarrowVerticalBar_WindowLeftEdge.png",
        DIR, 32, 32,
        "UI Element - 05 GUI Frame EdgeLeftStrip TallNarrowVerticalBar WindowLeftEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGERIGHTSTRIP_TALLNARROWVERTICALBAR_WINDOWRIGHTEDGE = SpriteAsset.single(
        "06_GUI_Frame_EdgeRightStrip_TallNarrowVerticalBar_WindowRightEdge.png",
        DIR, 32, 32,
        "UI Element - 06 GUI Frame EdgeRightStrip TallNarrowVerticalBar WindowRightEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDNAVY_LARGEFULLBLOCK_WINDOWFILL = SpriteAsset.single(
        "07_GUI_Frame_FillSolidNavy_LargeFullBlock_WindowFill.png",
        DIR, 32, 32,
        "Tile - 07 GUI Frame FillSolidNavy LargeFullBlock WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELCROSSDIAMOND_BLUEGEOMETRICPATTERN_DECORATIVEFILL = SpriteAsset.single(
        "08_GUI_Frame_PanelCrossDiamond_BlueGeometricPattern_DecorativeFill.png",
        DIR, 32, 32,
        "UI Element - 08 GUI Frame PanelCrossDiamond BlueGeometricPattern DecorativeFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERINSETTOPLEFT_INSETBORDERSQUARE_WINDOWCORNER = SpriteAsset.single(
        "09_GUI_Frame_CornerInsetTopLeft_InsetBorderSquare_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 09 GUI Frame CornerInsetTopLeft InsetBorderSquare WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGELEFTSTRIP_TALLBLUETINTBAR_WINDOWLEFTEDGE = SpriteAsset.single(
        "10_GUI_Frame_EdgeLeftStrip_TallBlueTintBar_WindowLeftEdge.png",
        DIR, 32, 32,
        "UI Element - 10 GUI Frame EdgeLeftStrip TallBlueTintBar WindowLeftEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLDIAGONALTEXTURE_FAINTDIAGLINES_WINDOWFILL = SpriteAsset.single(
        "11_GUI_Frame_FillDiagonalTexture_FaintDiagLines_WindowFill.png",
        DIR, 32, 32,
        "UI Element - 11 GUI Frame FillDiagonalTexture FaintDiagLines WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGELEFTSTRIP_TALLDARKERBAR_WINDOWLEFTEDGE = SpriteAsset.single(
        "12_GUI_Frame_EdgeLeftStrip_TallDarkerBar_WindowLeftEdge.png",
        DIR, 32, 32,
        "UI Element - 12 GUI Frame EdgeLeftStrip TallDarkerBar WindowLeftEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGELEFTSTRIP_TALLTHINLIGHTER_WINDOWLEFTEDGE = SpriteAsset.single(
        "13_GUI_Frame_EdgeLeftStrip_TallThinLighter_WindowLeftEdge.png",
        DIR, 32, 32,
        "UI Element - 13 GUI Frame EdgeLeftStrip TallThinLighter WindowLeftEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGELEFTSTRIP_TALLWIDERWITHTRIM_WINDOWLEFTEDGE = SpriteAsset.single(
        "14_GUI_Frame_EdgeLeftStrip_TallWiderWithTrim_WindowLeftEdge.png",
        DIR, 32, 32,
        "UI Element - 14 GUI Frame EdgeLeftStrip TallWiderWithTrim WindowLeftEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGELEFTSTRIP_TALLLIGHTERBLUETRIM_WINDOWLEFTEDGE = SpriteAsset.single(
        "15_GUI_Frame_EdgeLeftStrip_TallLighterBlueTrim_WindowLeftEdge.png",
        DIR, 32, 32,
        "UI Element - 15 GUI Frame EdgeLeftStrip TallLighterBlueTrim WindowLeftEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELWIDERECT_TEALCYANACCENTSTRIPE_DIVIDERBAR = SpriteAsset.single(
        "16_GUI_Frame_PanelWideRect_TealCyanAccentStripe_DividerBar.png",
        DIR, 32, 32,
        "UI Element - 16 GUI Frame PanelWideRect TealCyanAccentStripe DividerBar");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELWIDERECT_DARKERNOACCENT_DIVIDERBAR = SpriteAsset.single(
        "17_GUI_Frame_PanelWideRect_DarkerNoAccent_DividerBar.png",
        DIR, 32, 32,
        "UI Element - 17 GUI Frame PanelWideRect DarkerNoAccent DividerBar");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGERIGHTSTRIP_TALLBLUEACCENTLINE_WINDOWRIGHTEDGE = SpriteAsset.single(
        "18_GUI_Frame_EdgeRightStrip_TallBlueAccentLine_WindowRightEdge.png",
        DIR, 32, 32,
        "UI Element - 18 GUI Frame EdgeRightStrip TallBlueAccentLine WindowRightEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERBOTTOMLEFT_LSHAPECORNER_WINDOWCORNER = SpriteAsset.single(
        "19_GUI_Frame_CornerBottomLeft_LShapeCorner_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 19 GUI Frame CornerBottomLeft LShapeCorner WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGEBOTTOMBAR_PLAINDARKSTRIP_WINDOWBOTTOMEDGE = SpriteAsset.single(
        "20_GUI_Frame_EdgeBottomBar_PlainDarkStrip_WindowBottomEdge.png",
        DIR, 32, 32,
        "UI Element - 20 GUI Frame EdgeBottomBar PlainDarkStrip WindowBottomEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERBOTTOMLEFTFULL_INSETSQUARECORNER_WINDOWCORNER = SpriteAsset.single(
        "21_GUI_Frame_CornerBottomLeftFull_InsetSquareCorner_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 21 GUI Frame CornerBottomLeftFull InsetSquareCorner WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGERIGHTSTRIP_TALLNARROWPLAIN_WINDOWRIGHTEDGE = SpriteAsset.single(
        "22_GUI_Frame_EdgeRightStrip_TallNarrowPlain_WindowRightEdge.png",
        DIR, 32, 32,
        "UI Element - 22 GUI Frame EdgeRightStrip TallNarrowPlain WindowRightEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELWIDERECT_TECHDOTTEXTURE_DIVIDERBAR = SpriteAsset.single(
        "23_GUI_Frame_PanelWideRect_TechDotTexture_DividerBar.png",
        DIR, 32, 32,
        "UI Element - 23 GUI Frame PanelWideRect TechDotTexture DividerBar");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGEBOTTOMBAR_DOTLINETEXTURE_WINDOWBOTTOMEDGE = SpriteAsset.single(
        "24_GUI_Frame_EdgeBottomBar_DotLineTexture_WindowBottomEdge.png",
        DIR, 32, 32,
        "UI Element - 24 GUI Frame EdgeBottomBar DotLineTexture WindowBottomEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELWIDERECT_WIDERPLAINDARK_DIVIDERBAR = SpriteAsset.single(
        "25_GUI_Frame_PanelWideRect_WiderPlainDark_DividerBar.png",
        DIR, 32, 32,
        "UI Element - 25 GUI Frame PanelWideRect WiderPlainDark DividerBar");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELWIDERECT_DARKERVARIANT_DIVIDERBAR = SpriteAsset.single(
        "26_GUI_Frame_PanelWideRect_DarkerVariant_DividerBar.png",
        DIR, 32, 32,
        "UI Element - 26 GUI Frame PanelWideRect DarkerVariant DividerBar");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERBOTTOMRIGHT_DIAGONALANGLETRIM_WINDOWCORNER = SpriteAsset.single(
        "27_GUI_Frame_CornerBottomRight_DiagonalAngleTrim_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 27 GUI Frame CornerBottomRight DiagonalAngleTrim WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGERIGHTSTRIP_TALLBLUEACCENT_WINDOWRIGHTEDGE = SpriteAsset.single(
        "28_GUI_Frame_EdgeRightStrip_TallBlueAccent_WindowRightEdge.png",
        DIR, 32, 32,
        "UI Element - 28 GUI Frame EdgeRightStrip TallBlueAccent WindowRightEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERBOTTOMRIGHTFULL_BRACKETCORNER_WINDOWCORNER = SpriteAsset.single(
        "29_GUI_Frame_CornerBottomRightFull_BracketCorner_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 29 GUI Frame CornerBottomRightFull BracketCorner WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERTOPRIGHTFULL_BRACKETTSHAPE_WINDOWCORNER = SpriteAsset.single(
        "30_GUI_Frame_CornerTopRightFull_BracketTShape_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 30 GUI Frame CornerTopRightFull BracketTShape WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERTOPRIGHT_SMALLINSETLIGHTTRIM_WINDOWCORNER = SpriteAsset.single(
        "31_GUI_Frame_CornerTopRight_SmallInsetLightTrim_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 31 GUI Frame CornerTopRight SmallInsetLightTrim WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERTOPLEFT_TRIANGLECUT_WINDOWCORNER = SpriteAsset.single(
        "32_GUI_Frame_CornerTopLeft_TriangleCut_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 32 GUI Frame CornerTopLeft TriangleCut WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERTOPRIGHT_TRIANGLECUTMIRROR_WINDOWCORNER = SpriteAsset.single(
        "33_GUI_Frame_CornerTopRight_TriangleCutMirror_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 33 GUI Frame CornerTopRight TriangleCutMirror WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERTOPRIGHT_DIAGONALCUT_WINDOWCORNER = SpriteAsset.single(
        "34_GUI_Frame_CornerTopRight_DiagonalCut_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 34 GUI Frame CornerTopRight DiagonalCut WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELHORIZDIVIDER_TWOROWDARKNAVY_DIVIDERBAR = SpriteAsset.single(
        "35_GUI_Frame_PanelHorizDivider_TwoRowDarkNavy_DividerBar.png",
        DIR, 32, 32,
        "UI Element - 35 GUI Frame PanelHorizDivider TwoRowDarkNavy DividerBar");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGETOPBARVARIANT_LIGHTERSTRIPE_WINDOWTOPEDGE = SpriteAsset.single(
        "36_GUI_Frame_EdgeTopBarVariant_LighterStripe_WindowTopEdge.png",
        DIR, 32, 32,
        "UI Element - 36 GUI Frame EdgeTopBarVariant LighterStripe WindowTopEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELINSETSQUARE_SINGLECELLDARKBORDER_PANELCELL = SpriteAsset.single(
        "37_GUI_Frame_PanelInsetSquare_SingleCellDarkBorder_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 37 GUI Frame PanelInsetSquare SingleCellDarkBorder PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDNAVY_WIDERECTNOBORDER_WINDOWFILL = SpriteAsset.single(
        "38_GUI_Frame_FillSolidNavy_WideRectNoBorder_WindowFill.png",
        DIR, 32, 32,
        "UI Element - 38 GUI Frame FillSolidNavy WideRectNoBorder WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDNAVY_WIDERVARIANT_WINDOWFILL = SpriteAsset.single(
        "39_GUI_Frame_FillSolidNavy_WiderVariant_WindowFill.png",
        DIR, 32, 32,
        "UI Element - 39 GUI Frame FillSolidNavy WiderVariant WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDDARKNAVY_FULLBLOCK_WINDOWFILL = SpriteAsset.single(
        "40_GUI_Frame_FillSolidDarkNavy_FullBlock_WindowFill.png",
        DIR, 32, 32,
        "Tile - 40 GUI Frame FillSolidDarkNavy FullBlock WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANEL2CELL_TWOINSETSQUARES_PANELCELL = SpriteAsset.single(
        "41_GUI_Frame_Panel2Cell_TwoInsetSquares_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 41 GUI Frame Panel2Cell TwoInsetSquares PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANEL2CELLVARIANT_TWOINSETSQUARESDIFFSHADE_PANELCELL = SpriteAsset.single(
        "42_GUI_Frame_Panel2CellVariant_TwoInsetSquaresDiffShade_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 42 GUI Frame Panel2CellVariant TwoInsetSquaresDiffShade PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGELEFTSTRIP_NARROWDARKVERTICAL_WINDOWLEFTEDGE = SpriteAsset.single(
        "43_GUI_Frame_EdgeLeftStrip_NarrowDarkVertical_WindowLeftEdge.png",
        DIR, 32, 32,
        "UI Element - 43 GUI Frame EdgeLeftStrip NarrowDarkVertical WindowLeftEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGEHORIZBAR_DENSEDOTLINETEXTURE_WINDOWEDGE = SpriteAsset.single(
        "44_GUI_Frame_EdgeHorizBar_DenseDotLineTexture_WindowEdge.png",
        DIR, 32, 32,
        "UI Element - 44 GUI Frame EdgeHorizBar DenseDotLineTexture WindowEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDNAVY_PLAINFLATBLOCK_WINDOWFILL = SpriteAsset.single(
        "45_GUI_Frame_FillSolidNavy_PlainFlatBlock_WindowFill.png",
        DIR, 32, 32,
        "Tile - 45 GUI Frame FillSolidNavy PlainFlatBlock WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDNAVY_WIDEFLATRECT_WINDOWFILL = SpriteAsset.single(
        "46_GUI_Frame_FillSolidNavy_WideFlatRect_WindowFill.png",
        DIR, 32, 32,
        "UI Element - 46 GUI Frame FillSolidNavy WideFlatRect WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGEDIAGONALSTRIP_ANGLEDTOPLEFTSLANT_WINDOWEDGE = SpriteAsset.single(
        "47_GUI_Frame_EdgeDiagonalStrip_AngledTopLeftSlant_WindowEdge.png",
        DIR, 32, 32,
        "UI Element - 47 GUI Frame EdgeDiagonalStrip AngledTopLeftSlant WindowEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGERIGHTSTRIP_NARROWVERTICALBAR_WINDOWRIGHTEDGE = SpriteAsset.single(
        "48_GUI_Frame_EdgeRightStrip_NarrowVerticalBar_WindowRightEdge.png",
        DIR, 32, 32,
        "UI Element - 48 GUI Frame EdgeRightStrip NarrowVerticalBar WindowRightEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELHORIZBAR_MEDIUMWIDTH_DIVIDERBAR = SpriteAsset.single(
        "49_GUI_Frame_PanelHorizBar_MediumWidth_DividerBar.png",
        DIR, 32, 32,
        "UI Element - 49 GUI Frame PanelHorizBar MediumWidth DividerBar");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGEBOTTOMBAR_HORIZSTRIPTEXTURE_WINDOWBOTTOMEDGE = SpriteAsset.single(
        "50_GUI_Frame_EdgeBottomBar_HorizStripTexture_WindowBottomEdge.png",
        DIR, 32, 32,
        "UI Element - 50 GUI Frame EdgeBottomBar HorizStripTexture WindowBottomEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELINSETSQUARE_SINGLECELL_PANELCELL = SpriteAsset.single(
        "51_GUI_Frame_PanelInsetSquare_SingleCell_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 51 GUI Frame PanelInsetSquare SingleCell PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANEL2CELLVARIANT2_TWOINSETSQUARES_PANELCELL = SpriteAsset.single(
        "52_GUI_Frame_Panel2CellVariant2_TwoInsetSquares_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 52 GUI Frame Panel2CellVariant2 TwoInsetSquares PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANEL2CELLVARIANT3_TWOINSETSLIGHTBORDERDIFF_PANELCELL = SpriteAsset.single(
        "53_GUI_Frame_Panel2CellVariant3_TwoInsetSlightBorderDiff_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 53 GUI Frame Panel2CellVariant3 TwoInsetSlightBorderDiff PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGEBOTTOMBAR_LIGHTBLUEACCENTLINE_WINDOWBOTTOMEDGE = SpriteAsset.single(
        "54_GUI_Frame_EdgeBottomBar_LightBlueAccentLine_WindowBottomEdge.png",
        DIR, 32, 32,
        "UI Element - 54 GUI Frame EdgeBottomBar LightBlueAccentLine WindowBottomEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGERIGHTSTRIP_NARROWSLIGHTLYWIDER_WINDOWRIGHTEDGE = SpriteAsset.single(
        "55_GUI_Frame_EdgeRightStrip_NarrowSlightlyWider_WindowRightEdge.png",
        DIR, 32, 32,
        "UI Element - 55 GUI Frame EdgeRightStrip NarrowSlightlyWider WindowRightEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGEDIAGONALSTRIP_ANGLEDLINETEXTURE_WINDOWEDGE = SpriteAsset.single(
        "56_GUI_Frame_EdgeDiagonalStrip_AngledLineTexture_WindowEdge.png",
        DIR, 32, 32,
        "UI Element - 56 GUI Frame EdgeDiagonalStrip AngledLineTexture WindowEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGELEFTSTRIP_NARROWDARKSLIGHTVARIANT_WINDOWLEFTEDGE = SpriteAsset.single(
        "57_GUI_Frame_EdgeLeftStrip_NarrowDarkSlightVariant_WindowLeftEdge.png",
        DIR, 32, 32,
        "UI Element - 57 GUI Frame EdgeLeftStrip NarrowDarkSlightVariant WindowLeftEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELWIDERECT_INSETBORDERWIDER_PANELCELL = SpriteAsset.single(
        "58_GUI_Frame_PanelWideRect_InsetBorderWider_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 58 GUI Frame PanelWideRect InsetBorderWider PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDNAVY_WIDEFLATRECT_WINDOWFILL_2 = SpriteAsset.single(
        "59_GUI_Frame_FillSolidNavy_WideFlatRect_WindowFill.png",
        DIR, 32, 32,
        "UI Element - 59 GUI Frame FillSolidNavy WideFlatRect WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELMEDIUM_INSETSQUARETALLER_PANELCELL = SpriteAsset.single(
        "60_GUI_Frame_PanelMedium_InsetSquareTaller_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 60 GUI Frame PanelMedium InsetSquareTaller PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANEL2CELL_TWOINSETSQUARESWITHICONS_PANELCELL = SpriteAsset.single(
        "61_GUI_Frame_Panel2Cell_TwoInsetSquaresWithIcons_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 61 GUI Frame Panel2Cell TwoInsetSquaresWithIcons PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANEL2CELLVARIANT_TWOINSETSQUARESICONSALT_PANELCELL = SpriteAsset.single(
        "62_GUI_Frame_Panel2CellVariant_TwoInsetSquaresIconsAlt_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 62 GUI Frame Panel2CellVariant TwoInsetSquaresIconsAlt PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERHEXAGONAL_LIGHTGREYOCTAGONSHAPE_WINDOWCORNER = SpriteAsset.single(
        "63_GUI_Frame_CornerHexagonal_LightGreyOctagonShape_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 63 GUI Frame CornerHexagonal LightGreyOctagonShape WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERDIAGONALCUTTOPLEFT_WINDOWCORNER = SpriteAsset.single(
        "64_GUI_Frame_CornerDiagonalCutTopLeft_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 64 GUI Frame CornerDiagonalCutTopLeft WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDDARKNAVY_PLAINBLOCK_WINDOWFILL = SpriteAsset.single(
        "65_GUI_Frame_FillSolidDarkNavy_PlainBlock_WindowFill.png",
        DIR, 32, 32,
        "Tile - 65 GUI Frame FillSolidDarkNavy PlainBlock WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDNAVYLIGHTER_SLIGHTLYLIGHTER_WINDOWFILL = SpriteAsset.single(
        "66_GUI_Frame_FillSolidNavyLighter_SlightlyLighter_WindowFill.png",
        DIR, 32, 32,
        "UI Element - 66 GUI Frame FillSolidNavyLighter SlightlyLighter WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGETOPBAR_PLAINBAR_WINDOWTOPEDGE = SpriteAsset.single(
        "67_GUI_Frame_EdgeTopBar_PlainBar_WindowTopEdge.png",
        DIR, 32, 32,
        "UI Element - 67 GUI Frame EdgeTopBar PlainBar WindowTopEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDNAVY_PLAINBLOCK_WINDOWFILL = SpriteAsset.single(
        "68_GUI_Frame_FillSolidNavy_PlainBlock_WindowFill.png",
        DIR, 32, 32,
        "Tile - 68 GUI Frame FillSolidNavy PlainBlock WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGELEFTSTRIP_LEFTEDGEBAR_WINDOWLEFTEDGE = SpriteAsset.single(
        "69_GUI_Frame_EdgeLeftStrip_LeftEdgeBar_WindowLeftEdge.png",
        DIR, 32, 32,
        "UI Element - 69 GUI Frame EdgeLeftStrip LeftEdgeBar WindowLeftEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANEL2CELLWIDEDIVIDER_TWOCELLBLOCK_DIVIDERBAR = SpriteAsset.single(
        "70_GUI_Frame_Panel2CellWideDivider_TwoCellBlock_DividerBar.png",
        DIR, 32, 32,
        "Tile - 70 GUI Frame Panel2CellWideDivider TwoCellBlock DividerBar");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANEL2CELLGRID_TWOCELLGRIDBLOCK_PANELCELL = SpriteAsset.single(
        "71_GUI_Frame_Panel2CellGrid_TwoCellGridBlock_PanelCell.png",
        DIR, 32, 32,
        "Tile - 71 GUI Frame Panel2CellGrid TwoCellGridBlock PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGETHINRIGHTSTRIP_THINVERTICALRIGHT_WINDOWRIGHTEDGE = SpriteAsset.single(
        "72_GUI_Frame_EdgeThinRightStrip_ThinVerticalRight_WindowRightEdge.png",
        DIR, 32, 32,
        "UI Element - 72 GUI Frame EdgeThinRightStrip ThinVerticalRight WindowRightEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERBOTTOMLEFT_PLAINCORNER_WINDOWCORNER = SpriteAsset.single(
        "73_GUI_Frame_CornerBottomLeft_PlainCorner_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 73 GUI Frame CornerBottomLeft PlainCorner WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDNAVY_PLAINBLOCK_WINDOWFILL_2 = SpriteAsset.single(
        "74_GUI_Frame_FillSolidNavy_PlainBlock_WindowFill.png",
        DIR, 32, 32,
        "Tile - 74 GUI Frame FillSolidNavy PlainBlock WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_EDGEBOTTOMBAR_PLAINHORIZSTRIP_WINDOWBOTTOMEDGE = SpriteAsset.single(
        "75_GUI_Frame_EdgeBottomBar_PlainHorizStrip_WindowBottomEdge.png",
        DIR, 32, 32,
        "UI Element - 75 GUI Frame EdgeBottomBar PlainHorizStrip WindowBottomEdge");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERBOTTOMSMALLNOTCH_BOTTOMNOTCHCORNER_WINDOWCORNER = SpriteAsset.single(
        "76_GUI_Frame_CornerBottomSmallNotch_BottomNotchCorner_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 76 GUI Frame CornerBottomSmallNotch BottomNotchCorner WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_FILLSOLIDNAVYDARK_DARKBLOCK_WINDOWFILL = SpriteAsset.single(
        "77_GUI_Frame_FillSolidNavyDark_DarkBlock_WindowFill.png",
        DIR, 32, 32,
        "Tile - 77 GUI Frame FillSolidNavyDark DarkBlock WindowFill");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERBOTTOMRIGHT_PLAINCORNER_WINDOWCORNER = SpriteAsset.single(
        "78_GUI_Frame_CornerBottomRight_PlainCorner_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 78 GUI Frame CornerBottomRight PlainCorner WindowCorner");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELINSETSQUARE_DARKBORDERSQUARE_PANELCELL = SpriteAsset.single(
        "79_GUI_Frame_PanelInsetSquare_DarkBorderSquare_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 79 GUI Frame PanelInsetSquare DarkBorderSquare PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_PANELINSETSQUARE_LIGHTERVARIANT_PANELCELL = SpriteAsset.single(
        "80_GUI_Frame_PanelInsetSquare_LighterVariant_PanelCell.png",
        DIR, 32, 32,
        "UI Element - 80 GUI Frame PanelInsetSquare LighterVariant PanelCell");

    /** 32x32px | static */
    public static final SpriteAsset GUI_FRAME_CORNERTOPRIGHT_LIGHTTRIMCORNER_WINDOWCORNER = SpriteAsset.single(
        "81_GUI_Frame_CornerTopRight_LightTrimCorner_WindowCorner.png",
        DIR, 32, 32,
        "UI Element - 81 GUI Frame CornerTopRight LightTrimCorner WindowCorner");

    /** 288x288px | static */
    public static final SpriteAsset GUI_FRAME_MASTERSPRITESHEET_ALLFRAMEPIECESLAYOUT_REFERENCE = SpriteAsset.single(
        "82_GUI_Frame_MasterSpritesheet_AllFramePiecesLayout_Reference.png",
        DIR, 288, 288,
        "UI Element - 82 GUI Frame MasterSpritesheet AllFramePiecesLayout Reference");

    /** Total number of assets in this group */
    public static final int COUNT = 82;

    private FrameAssets() { } // no instantiation
}
