package assets.gui;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: gui/3 Icons/Buttons2
 * Total assets: 60
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class IconAssets {

    private static final String DIR = "Resources/industrial-zone/gui/3 Icons/Buttons2/";

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_01 = SpriteAsset.single(
        "GUI_Button_State_Variant02_01.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 01");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_02 = SpriteAsset.single(
        "GUI_Button_State_Variant02_02.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 02");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_03 = SpriteAsset.single(
        "GUI_Button_State_Variant02_03.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 03");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_04 = SpriteAsset.single(
        "GUI_Button_State_Variant02_04.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 04");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_05 = SpriteAsset.single(
        "GUI_Button_State_Variant02_05.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 05");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_06 = SpriteAsset.single(
        "GUI_Button_State_Variant02_06.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 06");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_07 = SpriteAsset.single(
        "GUI_Button_State_Variant02_07.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 07");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_08 = SpriteAsset.single(
        "GUI_Button_State_Variant02_08.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 08");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_09 = SpriteAsset.single(
        "GUI_Button_State_Variant02_09.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 09");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_10 = SpriteAsset.single(
        "GUI_Button_State_Variant02_10.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 10");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_11 = SpriteAsset.single(
        "GUI_Button_State_Variant02_11.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 11");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_12 = SpriteAsset.single(
        "GUI_Button_State_Variant02_12.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 12");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_13 = SpriteAsset.single(
        "GUI_Button_State_Variant02_13.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 13");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_14 = SpriteAsset.single(
        "GUI_Button_State_Variant02_14.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 14");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_15 = SpriteAsset.single(
        "GUI_Button_State_Variant02_15.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 15");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_16 = SpriteAsset.single(
        "GUI_Button_State_Variant02_16.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 16");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_17 = SpriteAsset.single(
        "GUI_Button_State_Variant02_17.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 17");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_18 = SpriteAsset.single(
        "GUI_Button_State_Variant02_18.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 18");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_19 = SpriteAsset.single(
        "GUI_Button_State_Variant02_19.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 19");

    /** 16x16px | static */
    public static final SpriteAsset GUI_BUTTON_STATE_VARIANT02_20 = SpriteAsset.single(
        "GUI_Button_State_Variant02_20.png",
        DIR, 16, 16,
        "UI Element - GUI Button State Variant02 20");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_ALERT_EXCLAMATION_15 = SpriteAsset.single(
        "GUI_Icon_Alert_Exclamation_15.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Alert Exclamation 15");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_ARROW_DOWN_06 = SpriteAsset.single(
        "GUI_Icon_Arrow_Down_06.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Arrow Down 06");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_ARROW_LEFT_07 = SpriteAsset.single(
        "GUI_Icon_Arrow_Left_07.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Arrow Left 07");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_ARROW_RIGHT_08 = SpriteAsset.single(
        "GUI_Icon_Arrow_Right_08.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Arrow Right 08");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_ARROW_UP_05 = SpriteAsset.single(
        "GUI_Icon_Arrow_Up_05.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Arrow Up 05");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_BATTERY_POWER_40 = SpriteAsset.single(
        "GUI_Icon_Battery_Power_40.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Battery Power 40");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_BRIGHTNESS_LIGHT_39 = SpriteAsset.single(
        "GUI_Icon_Brightness_Light_39.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Brightness Light 39");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_CHAT_MESSAGE_27 = SpriteAsset.single(
        "GUI_Icon_Chat_Message_27.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Chat Message 27");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_CHECK_CONFIRM_03 = SpriteAsset.single(
        "GUI_Icon_Check_Confirm_03.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Check Confirm 03");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_CROSS_CANCEL_04 = SpriteAsset.single(
        "GUI_Icon_Cross_Cancel_04.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Cross Cancel 04");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_DOWNLOAD_SAVE_30 = SpriteAsset.single(
        "GUI_Icon_Download_Save_30.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Download Save 30");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_EMAIL_MAIL_29 = SpriteAsset.single(
        "GUI_Icon_Email_Mail_29.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Email Mail 29");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_FAST_FORWARD_35 = SpriteAsset.single(
        "GUI_Icon_Fast_Forward_35.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Fast Forward 35");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_HEART_LOVE_22 = SpriteAsset.single(
        "GUI_Icon_Heart_Love_22.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Heart Love 22");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_HOME_HOUSE_12 = SpriteAsset.single(
        "GUI_Icon_Home_House_12.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Home House 12");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_INFO_QUESTION_14 = SpriteAsset.single(
        "GUI_Icon_Info_Question_14.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Info Question 14");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_LOAD_OPEN_20 = SpriteAsset.single(
        "GUI_Icon_Load_Open_20.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Load Open 20");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_LOCK_LOCKED_16 = SpriteAsset.single(
        "GUI_Icon_Lock_Locked_16.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Lock Locked 16");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_MENU_HAMBURGER_09 = SpriteAsset.single(
        "GUI_Icon_Menu_Hamburger_09.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Menu Hamburger 09");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_MINUS_REMOVE_02 = SpriteAsset.single(
        "GUI_Icon_Minus_Remove_02.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Minus Remove 02");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_MUTE_SILENT_38 = SpriteAsset.single(
        "GUI_Icon_Mute_Silent_38.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Mute Silent 38");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_PAUSE_STOP_34 = SpriteAsset.single(
        "GUI_Icon_Pause_Stop_34.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Pause Stop 34");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_PHONE_CALL_28 = SpriteAsset.single(
        "GUI_Icon_Phone_Call_28.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Phone Call 28");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_PLAY_START_33 = SpriteAsset.single(
        "GUI_Icon_Play_Start_33.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Play Start 33");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_PLUS_ADD_01 = SpriteAsset.single(
        "GUI_Icon_Plus_Add_01.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Plus Add 01");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_REFRESH_RELOAD_32 = SpriteAsset.single(
        "GUI_Icon_Refresh_Reload_32.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Refresh Reload 32");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_REWIND_BACK_36 = SpriteAsset.single(
        "GUI_Icon_Rewind_Back_36.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Rewind Back 36");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_SAVE_FLOPPY_19 = SpriteAsset.single(
        "GUI_Icon_Save_Floppy_19.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Save Floppy 19");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_SEARCH_MAGNIFIER_11 = SpriteAsset.single(
        "GUI_Icon_Search_Magnifier_11.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Search Magnifier 11");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_SETTINGS_GEAR_10 = SpriteAsset.single(
        "GUI_Icon_Settings_Gear_10.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Settings Gear 10");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_SETTINGS_WRENCH_13 = SpriteAsset.single(
        "GUI_Icon_Settings_Wrench_13.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Settings Wrench 13");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_SHIELD_DEFENSE_23 = SpriteAsset.single(
        "GUI_Icon_Shield_Defense_23.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Shield Defense 23");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_STAR_FAVORITE_21 = SpriteAsset.single(
        "GUI_Icon_Star_Favorite_21.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Star Favorite 21");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_SWORD_ATTACK_24 = SpriteAsset.single(
        "GUI_Icon_Sword_Attack_24.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Sword Attack 24");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_TRASH_DELETE_18 = SpriteAsset.single(
        "GUI_Icon_Trash_Delete_18.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Trash Delete 18");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_UNLOCK_OPEN_17 = SpriteAsset.single(
        "GUI_Icon_Unlock_Open_17.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Unlock Open 17");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_UPLOAD_SEND_31 = SpriteAsset.single(
        "GUI_Icon_Upload_Send_31.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Upload Send 31");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_USER_PROFILE_25 = SpriteAsset.single(
        "GUI_Icon_User_Profile_25.png",
        DIR, 16, 16,
        "UI Element - GUI Icon User Profile 25");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_USERS_GROUP_26 = SpriteAsset.single(
        "GUI_Icon_Users_Group_26.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Users Group 26");

    /** 16x16px | static */
    public static final SpriteAsset GUI_ICON_VOLUME_SOUND_37 = SpriteAsset.single(
        "GUI_Icon_Volume_Sound_37.png",
        DIR, 16, 16,
        "UI Element - GUI Icon Volume Sound 37");

    /** Total number of assets in this group */
    public static final int COUNT = 60;

    private IconAssets() { } // no instantiation
}
