package assets.gui;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: gui/5 Logo
 * Total assets: 3
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class LogoAssets {

    private static final String DIR = "Resources/industrial-zone/gui/5 Logo/";

    /** 349x115px | ~3 frames */
    public static final SpriteAsset GUI_LOGO_INDUSTRIALZONE_COMPACT = SpriteAsset.single(
        "GUI_Logo_IndustrialZone_Compact.png",
        DIR, 349, 115,
        "UI Element - GUI Logo IndustrialZone Compact");

    /** 285x115px | ~2 frames */
    public static final SpriteAsset GUI_LOGO_INDUSTRIALZONE_FULL = SpriteAsset.single(
        "GUI_Logo_IndustrialZone_Full.png",
        DIR, 285, 115,
        "UI Element - GUI Logo IndustrialZone Full");

    /** 413x115px | ~3 frames */
    public static final SpriteAsset GUI_LOGO_INDUSTRIALZONE_MINIMAL = SpriteAsset.single(
        "GUI_Logo_IndustrialZone_Minimal.png",
        DIR, 413, 115,
        "UI Element - GUI Logo IndustrialZone Minimal");

    /** Total number of assets in this group */
    public static final int COUNT = 3;

    private LogoAssets() { } // no instantiation
}
