package assets.gui;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: gui/7 Numbers
 * Total assets: 17
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class NumberAssets {

    private static final String DIR = "Resources/industrial-zone/gui/7 Numbers/";

    /** 6x9px | static */
    public static final SpriteAsset GUI_NUMBER_DIGIT1_STYLEDGLYPH_DECORATIVE = SpriteAsset.single(
        "01_GUI_Number_Digit1_StyledGlyph_Decorative.png",
        DIR, 6, 9,
        "UI Element - 01 GUI Number Digit1 StyledGlyph Decorative");

    /** 6x9px | static */
    public static final SpriteAsset GUI_NUMBER_DIGIT2_STYLEDGLYPH_DECORATIVE = SpriteAsset.single(
        "02_GUI_Number_Digit2_StyledGlyph_Decorative.png",
        DIR, 6, 9,
        "UI Element - 02 GUI Number Digit2 StyledGlyph Decorative");

    /** 6x9px | static */
    public static final SpriteAsset GUI_NUMBER_DIGIT3_STYLEDGLYPH_DECORATIVE = SpriteAsset.single(
        "03_GUI_Number_Digit3_StyledGlyph_Decorative.png",
        DIR, 6, 9,
        "UI Element - 03 GUI Number Digit3 StyledGlyph Decorative");

    /** 7x9px | static */
    public static final SpriteAsset GUI_NUMBER_DIGIT4_STYLEDGLYPH_DECORATIVE = SpriteAsset.single(
        "04_GUI_Number_Digit4_StyledGlyph_Decorative.png",
        DIR, 7, 9,
        "UI Element - 04 GUI Number Digit4 StyledGlyph Decorative");

    /** 6x9px | static */
    public static final SpriteAsset GUI_NUMBER_DIGIT5_STYLEDGLYPH_DECORATIVE = SpriteAsset.single(
        "05_GUI_Number_Digit5_StyledGlyph_Decorative.png",
        DIR, 6, 9,
        "UI Element - 05 GUI Number Digit5 StyledGlyph Decorative");

    /** 6x9px | static */
    public static final SpriteAsset GUI_NUMBER_DIGIT6_STYLEDGLYPH_DECORATIVE = SpriteAsset.single(
        "06_GUI_Number_Digit6_StyledGlyph_Decorative.png",
        DIR, 6, 9,
        "UI Element - 06 GUI Number Digit6 StyledGlyph Decorative");

    /** 6x9px | static */
    public static final SpriteAsset GUI_NUMBER_DIGIT7_STYLEDGLYPH_DECORATIVE = SpriteAsset.single(
        "07_GUI_Number_Digit7_StyledGlyph_Decorative.png",
        DIR, 6, 9,
        "UI Element - 07 GUI Number Digit7 StyledGlyph Decorative");

    /** 6x9px | static */
    public static final SpriteAsset GUI_NUMBER_DIGIT8_STYLEDGLYPH_DECORATIVE = SpriteAsset.single(
        "08_GUI_Number_Digit8_StyledGlyph_Decorative.png",
        DIR, 6, 9,
        "UI Element - 08 GUI Number Digit8 StyledGlyph Decorative");

    /** 6x9px | static */
    public static final SpriteAsset GUI_NUMBER_DIGIT9_STYLEDGLYPH_DECORATIVE = SpriteAsset.single(
        "09_GUI_Number_Digit9_StyledGlyph_Decorative.png",
        DIR, 6, 9,
        "UI Element - 09 GUI Number Digit9 StyledGlyph Decorative");

    /** 6x9px | static */
    public static final SpriteAsset GUI_NUMBER_DIGIT0_ZERO = SpriteAsset.single(
        "GUI_Number_Digit0_Zero.png",
        DIR, 6, 9,
        "UI Element - GUI Number Digit0 Zero");

    /** 7x9px | static */
    public static final SpriteAsset GUI_NUMBER_SYMBOL_B_THOUSAND = SpriteAsset.single(
        "GUI_Number_Symbol_B_Thousand.png",
        DIR, 7, 9,
        "UI Element - GUI Number Symbol B Thousand");

    /** 4x5px | static */
    public static final SpriteAsset GUI_NUMBER_SYMBOL_COMMA_SEPARATOR = SpriteAsset.single(
        "GUI_Number_Symbol_Comma_Separator.png",
        DIR, 4, 5,
        "UI Element - GUI Number Symbol Comma Separator");

    /** 4x4px | static */
    public static final SpriteAsset GUI_NUMBER_SYMBOL_DOT_DECIMAL = SpriteAsset.single(
        "GUI_Number_Symbol_Dot_Decimal.png",
        DIR, 4, 4,
        "UI Element - GUI Number Symbol Dot Decimal");

    /** 7x9px | static */
    public static final SpriteAsset GUI_NUMBER_SYMBOL_K_SUFFIX = SpriteAsset.single(
        "GUI_Number_Symbol_K_Suffix.png",
        DIR, 7, 9,
        "UI Element - GUI Number Symbol K Suffix");

    /** 9x9px | static */
    public static final SpriteAsset GUI_NUMBER_SYMBOL_M_MILLION = SpriteAsset.single(
        "GUI_Number_Symbol_M_Million.png",
        DIR, 9, 9,
        "UI Element - GUI Number Symbol M Million");

    /** 8x8px | static */
    public static final SpriteAsset GUI_NUMBER_SYMBOL_PLUS_ADDITION = SpriteAsset.single(
        "GUI_Number_Symbol_Plus_Addition.png",
        DIR, 8, 8,
        "UI Element - GUI Number Symbol Plus Addition");

    /** 142x22px | ~6 frames */
    public static final SpriteAsset NUMBERSMAP = SpriteAsset.single(
        "NumbersMap.png",
        DIR, 142, 22,
        "Asset - NumbersMap");

    /** Total number of assets in this group */
    public static final int COUNT = 17;

    private NumberAssets() { } // no instantiation
}
