package assets.gui;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: gui/9 Other/1 Decor
 * Total assets: 28
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class OtherGuiAssets {

    private static final String DIR = "Resources/industrial-zone/gui/9 Other/1 Decor/";

    /** 32x32px | static */
    public static final SpriteAsset GUI_DECOR_GLOWBARS_FOURVERTICALNEONRODS_DECORATION = SpriteAsset.single(
        "01_GUI_Decor_GlowBars_FourVerticalNeonRods_Decoration.png",
        DIR, 32, 32,
        "UI Element - 01 GUI Decor GlowBars FourVerticalNeonRods Decoration");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_EYE_VISIBILITYORREVEAL_SKILLICON = SpriteAsset.single(
        "01_GUI_SkillIcon_Eye_VisibilityOrReveal_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 01 GUI SkillIcon Eye VisibilityOrReveal SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_DECOR_RIBBONZIGZAG_PINKSTACKEDLSHAPE_DECORATION = SpriteAsset.single(
        "02_GUI_Decor_RibbonZigzag_PinkStackedLShape_Decoration.png",
        DIR, 32, 32,
        "UI Element - 02 GUI Decor RibbonZigzag PinkStackedLShape Decoration");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_CHEVRONUP_BOOSTORLEVELUP_SKILLICON = SpriteAsset.single(
        "02_GUI_SkillIcon_ChevronUp_BoostOrLevelUp_SkillIcon.png",
        DIR, 32, 32,
        "Background - 02 GUI SkillIcon ChevronUp BoostOrLevelUp SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_DECOR_CABLETWIST_REDBLUEHELIXWIRE_DECORATION = SpriteAsset.single(
        "03_GUI_Decor_CableTwist_RedBlueHelixWire_Decoration.png",
        DIR, 32, 32,
        "UI Element - 03 GUI Decor CableTwist RedBlueHelixWire Decoration");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_RADIATION_HAZARDORPOISON_SKILLICON = SpriteAsset.single(
        "03_GUI_SkillIcon_Radiation_HazardOrPoison_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 03 GUI SkillIcon Radiation HazardOrPoison SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_DECOR_CABLECONNECTOR_BLUEREDPLUGWIRES_DECORATION = SpriteAsset.single(
        "04_GUI_Decor_CableConnector_BlueRedPlugWires_Decoration.png",
        DIR, 32, 32,
        "UI Element - 04 GUI Decor CableConnector BlueRedPlugWires Decoration");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_MUSHROOM_EXPLOSIONORBLAST_SKILLICON = SpriteAsset.single(
        "04_GUI_SkillIcon_Mushroom_ExplosionOrBlast_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 04 GUI SkillIcon Mushroom ExplosionOrBlast SkillIcon");

    /** 32x64px | static */
    public static final SpriteAsset GUI_DECOR_CABLELOOSE_SINGLEREDWIRE_DECORATION = SpriteAsset.single(
        "05_GUI_Decor_CableLoose_SingleRedWire_Decoration.png",
        DIR, 32, 64,
        "UI Element - 05 GUI Decor CableLoose SingleRedWire Decoration");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_HOURGLASS_TIMERORSLOWTIME_SKILLICON = SpriteAsset.single(
        "05_GUI_SkillIcon_Hourglass_TimerOrSlowTime_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 05 GUI SkillIcon Hourglass TimerOrSlowTime SkillIcon");

    /** 32x64px | static */
    public static final SpriteAsset GUI_DECOR_CABLELOOSE_SINGLETEALWIRE_DECORATION = SpriteAsset.single(
        "06_GUI_Decor_CableLoose_SingleTealWire_Decoration.png",
        DIR, 32, 64,
        "UI Element - 06 GUI Decor CableLoose SingleTealWire Decoration");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_CROSSHAIR_TARGETORAIM_SKILLICON = SpriteAsset.single(
        "06_GUI_SkillIcon_Crosshair_TargetOrAim_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 06 GUI SkillIcon Crosshair TargetOrAim SkillIcon");

    /** 32x64px | static */
    public static final SpriteAsset GUI_DECOR_CABLEPLUG_SINGLEBLUECONNECTOR_DECORATION = SpriteAsset.single(
        "07_GUI_Decor_CablePlug_SingleBlueConnector_Decoration.png",
        DIR, 32, 64,
        "UI Element - 07 GUI Decor CablePlug SingleBlueConnector Decoration");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_HOUSE_BASEORRESPAWN_SKILLICON = SpriteAsset.single(
        "07_GUI_SkillIcon_House_BaseOrRespawn_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 07 GUI SkillIcon House BaseOrRespawn SkillIcon");

    /** 32x64px | static | loop */
    public static final SpriteAsset GUI_DECOR_CABLECOIL_BLUELOOPEDWIRE_DECORATION = SpriteAsset.single(
        "08_GUI_Decor_CableCoil_BlueLoopedWire_Decoration.png",
        DIR, 32, 64,
        "UI Element - 08 GUI Decor CableCoil BlueLoopedWire Decoration");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_DEVICE_TECHORINTERFACE_SKILLICON = SpriteAsset.single(
        "08_GUI_SkillIcon_Device_TechOrInterface_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 08 GUI SkillIcon Device TechOrInterface SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_QUESTION_UNKNOWNORHELP_SKILLICON = SpriteAsset.single(
        "09_GUI_SkillIcon_Question_UnknownOrHelp_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 09 GUI SkillIcon Question UnknownOrHelp SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_EXCLAIM_ALERTORWARNING_SKILLICON = SpriteAsset.single(
        "10_GUI_SkillIcon_Exclaim_AlertOrWarning_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 10 GUI SkillIcon Exclaim AlertOrWarning SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_PLUS_HEALORADDORHEALTH_SKILLICON = SpriteAsset.single(
        "11_GUI_SkillIcon_Plus_HealOrAddOrHealth_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 11 GUI SkillIcon Plus HealOrAddOrHealth SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_DIAGCROSS_CANCELORMULTIPLY_SKILLICON = SpriteAsset.single(
        "12_GUI_SkillIcon_DiagCross_CancelOrMultiply_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 12 GUI SkillIcon DiagCross CancelOrMultiply SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_TICK_CONFIRMORSELECT_SKILLICON = SpriteAsset.single(
        "13_GUI_SkillIcon_Tick_ConfirmOrSelect_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 13 GUI SkillIcon Tick ConfirmOrSelect SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_ARROWUP_UPLOADORJUMP_SKILLICON = SpriteAsset.single(
        "14_GUI_SkillIcon_ArrowUp_UploadOrJump_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 14 GUI SkillIcon ArrowUp UploadOrJump SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_KNIFE_MELEEORATTACK_SKILLICON = SpriteAsset.single(
        "15_GUI_SkillIcon_Knife_MeleeOrAttack_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 15 GUI SkillIcon Knife MeleeOrAttack SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_HEART_HEALTHORLIFE_SKILLICON = SpriteAsset.single(
        "16_GUI_SkillIcon_Heart_HealthOrLife_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 16 GUI SkillIcon Heart HealthOrLife SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_REFRESH_RESETORCOOLDOWN_SKILLICON = SpriteAsset.single(
        "17_GUI_SkillIcon_Refresh_ResetOrCooldown_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 17 GUI SkillIcon Refresh ResetOrCooldown SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_SHIELD_DEFENCEORBLOCK_SKILLICON = SpriteAsset.single(
        "18_GUI_SkillIcon_Shield_DefenceOrBlock_SkillIcon.png",
        DIR, 32, 32,
        "Tile - 18 GUI SkillIcon Shield DefenceOrBlock SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_SKULL_DEATHORDANGER_SKILLICON = SpriteAsset.single(
        "19_GUI_SkillIcon_Skull_DeathOrDanger_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 19 GUI SkillIcon Skull DeathOrDanger SkillIcon");

    /** 32x32px | static */
    public static final SpriteAsset GUI_SKILLICON_ARROWDOWN_DOWNLOADORDROP_SKILLICON = SpriteAsset.single(
        "20_GUI_SkillIcon_ArrowDown_DownloadOrDrop_SkillIcon.png",
        DIR, 32, 32,
        "UI Element - 20 GUI SkillIcon ArrowDown DownloadOrDrop SkillIcon");

    /** Total number of assets in this group */
    public static final int COUNT = 28;

    private OtherGuiAssets() { } // no instantiation
}
