package assets.gui;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: gui/4 Palette
 * Total assets: 1
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class PaletteAssets {

    private static final String DIR = "Resources/industrial-zone/gui/4 Palette/";

    /** 38x18px | ~2 frames */
    public static final SpriteAsset GUI_PALETTE_INDUSTRIALZONE_COLORREFERENCE = SpriteAsset.single(
        "GUI_Palette_IndustrialZone_ColorReference.png",
        DIR, 38, 18,
        "UI Element - GUI Palette IndustrialZone ColorReference");

    /** Total number of assets in this group */
    public static final int COUNT = 1;

    private PaletteAssets() { } // no instantiation
}
