package assets.tiles;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/power-station-level-2/1 Tiles
 * Total assets: 64
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level2TileAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/power-station-level-2/1 Tiles/";

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_BLUEPURPLE_SOLIDWALKABLEFLOOR_PRIMARYPLATFORMTILE = SpriteAsset.single(
        "01_Panel_HorizStripeBrick_BluePurple_SolidWalkableFloor_PrimaryPlatformTile.png",
        DIR, 32, 32,
        "01 Panel HorizStripeBrick BluePurple SolidWalkableFloor PrimaryPlatformTile");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_BLUEPURPLE_SOLIDFLOORVARIANTB = SpriteAsset.single(
        "02_Panel_HorizStripeBrick_BluePurple_SolidFloorVariantB.png",
        DIR, 32, 32,
        "Asset - 02 Panel HorizStripeBrick BluePurple SolidFloorVariantB");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_MIDBLUE_SOLIDFLOORVARIANTC = SpriteAsset.single(
        "03_Panel_HorizStripeBrick_MidBlue_SolidFloorVariantC.png",
        DIR, 32, 32,
        "Asset - 03 Panel HorizStripeBrick MidBlue SolidFloorVariantC");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_DARKBLUE_SOLIDFLOORVARIANTD = SpriteAsset.single(
        "04_Panel_HorizStripeBrick_DarkBlue_SolidFloorVariantD.png",
        DIR, 32, 32,
        "Asset - 04 Panel HorizStripeBrick DarkBlue SolidFloorVariantD");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_DARKPURPLE_SOLIDFLOORVARIANTE = SpriteAsset.single(
        "05_Panel_HorizStripeBrick_DarkPurple_SolidFloorVariantE.png",
        DIR, 32, 32,
        "Asset - 05 Panel HorizStripeBrick DarkPurple SolidFloorVariantE");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_DEEPNAVY_SOLIDFLOORVARIANTF = SpriteAsset.single(
        "06_Panel_HorizStripeBrick_DeepNavy_SolidFloorVariantF.png",
        DIR, 32, 32,
        "Asset - 06 Panel HorizStripeBrick DeepNavy SolidFloorVariantF");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_LIGHTBLUE_SOLIDFLOORVARIANTG = SpriteAsset.single(
        "07_Panel_HorizStripeBrick_LightBlue_SolidFloorVariantG.png",
        DIR, 32, 32,
        "Asset - 07 Panel HorizStripeBrick LightBlue SolidFloorVariantG");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_MEDIUMBLUE_SOLIDFLOORVARIANTH = SpriteAsset.single(
        "08_Panel_HorizStripeBrick_MediumBlue_SolidFloorVariantH.png",
        DIR, 32, 32,
        "Asset - 08 Panel HorizStripeBrick MediumBlue SolidFloorVariantH");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_SLATEPURPLE_SOLIDFLOORVARIANTI = SpriteAsset.single(
        "09_Panel_HorizStripeBrick_SlatePurple_SolidFloorVariantI.png",
        DIR, 32, 32,
        "Asset - 09 Panel HorizStripeBrick SlatePurple SolidFloorVariantI");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_STEELBLUE_SOLIDFLOORVARIANTJ = SpriteAsset.single(
        "10_Panel_HorizStripeBrick_SteelBlue_SolidFloorVariantJ.png",
        DIR, 32, 32,
        "Asset - 10 Panel HorizStripeBrick SteelBlue SolidFloorVariantJ");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_COOLGREY_SOLIDFLOORVARIANTK = SpriteAsset.single(
        "11_Panel_HorizStripeBrick_CoolGrey_SolidFloorVariantK.png",
        DIR, 32, 32,
        "Asset - 11 Panel HorizStripeBrick CoolGrey SolidFloorVariantK");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_INDIGOTONE_SOLIDFLOORVARIANTL = SpriteAsset.single(
        "12_Panel_HorizStripeBrick_IndigoTone_SolidFloorVariantL.png",
        DIR, 32, 32,
        "Asset - 12 Panel HorizStripeBrick IndigoTone SolidFloorVariantL");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_SOFTLAVENDER_SOLIDFLOORVARIANTM = SpriteAsset.single(
        "13_Panel_HorizStripeBrick_SoftLavender_SolidFloorVariantM.png",
        DIR, 32, 32,
        "Asset - 13 Panel HorizStripeBrick SoftLavender SolidFloorVariantM");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_DUSKBLUE_SOLIDFLOORVARIANTN = SpriteAsset.single(
        "14_Panel_HorizStripeBrick_DuskBlue_SolidFloorVariantN.png",
        DIR, 32, 32,
        "Asset - 14 Panel HorizStripeBrick DuskBlue SolidFloorVariantN");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_NIGHTBLUE_SOLIDFLOORVARIANTO = SpriteAsset.single(
        "15_Panel_HorizStripeBrick_NightBlue_SolidFloorVariantO.png",
        DIR, 32, 32,
        "Asset - 15 Panel HorizStripeBrick NightBlue SolidFloorVariantO");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZSTRIPEBRICK_MUTEDTEAL_SOLIDFLOORVARIANTP = SpriteAsset.single(
        "16_Panel_HorizStripeBrick_MutedTeal_SolidFloorVariantP.png",
        DIR, 32, 32,
        "Asset - 16 Panel HorizStripeBrick MutedTeal SolidFloorVariantP");

    /** 32x32px | static */
    public static final SpriteAsset BRICK_SMALLUNIT_BLUEPURPLE_WALLFILLTILEA = SpriteAsset.single(
        "17_Brick_SmallUnit_BluePurple_WallFillTileA.png",
        DIR, 32, 32,
        "Tile - 17 Brick SmallUnit BluePurple WallFillTileA");

    /** 32x32px | static */
    public static final SpriteAsset BRICK_SMALLUNIT_DARKNAVY_WALLFILLTILEB = SpriteAsset.single(
        "18_Brick_SmallUnit_DarkNavy_WallFillTileB.png",
        DIR, 32, 32,
        "Tile - 18 Brick SmallUnit DarkNavy WallFillTileB");

    /** 32x32px | static */
    public static final SpriteAsset BRICK_SMALLUNIT_MIDBLUE_WALLFILLTILEC = SpriteAsset.single(
        "19_Brick_SmallUnit_MidBlue_WallFillTileC.png",
        DIR, 32, 32,
        "Tile - 19 Brick SmallUnit MidBlue WallFillTileC");

    /** 32x32px | static */
    public static final SpriteAsset BRICK_SMALLUNIT_SLATEPURPLE_WALLFILLTILED = SpriteAsset.single(
        "20_Brick_SmallUnit_SlatePurple_WallFillTileD.png",
        DIR, 32, 32,
        "Tile - 20 Brick SmallUnit SlatePurple WallFillTileD");

    /** 32x32px | static */
    public static final SpriteAsset BRICK_SMALLUNIT_DEEPINDIGO_WALLFILLTILEE = SpriteAsset.single(
        "21_Brick_SmallUnit_DeepIndigo_WallFillTileE.png",
        DIR, 32, 32,
        "Tile - 21 Brick SmallUnit DeepIndigo WallFillTileE");

    /** 32x32px | static */
    public static final SpriteAsset BRICK_SMALLUNIT_COOLGREY_WALLFILLTILEF = SpriteAsset.single(
        "22_Brick_SmallUnit_CoolGrey_WallFillTileF.png",
        DIR, 32, 32,
        "Tile - 22 Brick SmallUnit CoolGrey WallFillTileF");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_PANELBORDER_BLUEPURPLE_WALLEDGETOP = SpriteAsset.single(
        "23_Edge_PanelBorder_BluePurple_WallEdgeTop.png",
        DIR, 32, 32,
        "Asset - 23 Edge PanelBorder BluePurple WallEdgeTop");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_PANELBORDER_DARKBLUE_WALLEDGEBOTTOM = SpriteAsset.single(
        "24_Edge_PanelBorder_DarkBlue_WallEdgeBottom.png",
        DIR, 32, 32,
        "Asset - 24 Edge PanelBorder DarkBlue WallEdgeBottom");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_PANELBORDER_MIDBLUE_WALLEDGELEFT = SpriteAsset.single(
        "25_Edge_PanelBorder_MidBlue_WallEdgeLeft.png",
        DIR, 32, 32,
        "Asset - 25 Edge PanelBorder MidBlue WallEdgeLeft");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_PANELBORDER_NAVYTONE_WALLEDGERIGHT = SpriteAsset.single(
        "26_Edge_PanelBorder_NavyTone_WallEdgeRight.png",
        DIR, 32, 32,
        "Asset - 26 Edge PanelBorder NavyTone WallEdgeRight");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_PANELBORDER_SLATEPURPLE_WALLEDGEVARIANTA = SpriteAsset.single(
        "27_Edge_PanelBorder_SlatePurple_WallEdgeVariantA.png",
        DIR, 32, 32,
        "Asset - 27 Edge PanelBorder SlatePurple WallEdgeVariantA");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_PANELBORDER_INDIGOTONE_WALLEDGEVARIANTB = SpriteAsset.single(
        "28_Edge_PanelBorder_IndigoTone_WallEdgeVariantB.png",
        DIR, 32, 32,
        "Asset - 28 Edge PanelBorder IndigoTone WallEdgeVariantB");

    /** 32x32px | static */
    public static final SpriteAsset SOLID_PURPLEBRICK_FULLBLOCK_HEAVYWALLA = SpriteAsset.single(
        "29_Solid_PurpleBrick_FullBlock_HeavyWallA.png",
        DIR, 32, 32,
        "Tile - 29 Solid PurpleBrick FullBlock HeavyWallA");

    /** 32x32px | static */
    public static final SpriteAsset SOLID_PURPLEBRICK_FULLBLOCK_HEAVYWALLB = SpriteAsset.single(
        "30_Solid_PurpleBrick_FullBlock_HeavyWallB.png",
        DIR, 32, 32,
        "Tile - 30 Solid PurpleBrick FullBlock HeavyWallB");

    /** 32x32px | static */
    public static final SpriteAsset SOLID_PURPLEBRICK_FULLBLOCK_HEAVYWALLC = SpriteAsset.single(
        "31_Solid_PurpleBrick_FullBlock_HeavyWallC.png",
        DIR, 32, 32,
        "Tile - 31 Solid PurpleBrick FullBlock HeavyWallC");

    /** 32x32px | static */
    public static final SpriteAsset SOLID_PURPLEBRICK_FULLBLOCK_HEAVYWALLD = SpriteAsset.single(
        "32_Solid_PurpleBrick_FullBlock_HeavyWallD.png",
        DIR, 32, 32,
        "Tile - 32 Solid PurpleBrick FullBlock HeavyWallD");

    /** 32x32px | static */
    public static final SpriteAsset SLOPE_DIAGONALCUT_TOPLEFTTRIANGLE_RAMPUPLEFT = SpriteAsset.single(
        "33_Slope_DiagonalCut_TopLeftTriangle_RampUpLeft.png",
        DIR, 32, 32,
        "Asset - 33 Slope DiagonalCut TopLeftTriangle RampUpLeft");

    /** 32x32px | static */
    public static final SpriteAsset SLOPE_DIAGONALCUT_TOPRIGHTTRIANGLE_RAMPUPRIGHT = SpriteAsset.single(
        "34_Slope_DiagonalCut_TopRightTriangle_RampUpRight.png",
        DIR, 32, 32,
        "Asset - 34 Slope DiagonalCut TopRightTriangle RampUpRight");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_MIXEDEDGE_BLUEGREY_STRUCTURALDETAILA = SpriteAsset.single(
        "35_Panel_MixedEdge_BlueGrey_StructuralDetailA.png",
        DIR, 32, 32,
        "Asset - 35 Panel MixedEdge BlueGrey StructuralDetailA");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_MIXEDEDGE_BLUEGREY_STRUCTURALDETAILB = SpriteAsset.single(
        "36_Panel_MixedEdge_BlueGrey_StructuralDetailB.png",
        DIR, 32, 32,
        "Asset - 36 Panel MixedEdge BlueGrey StructuralDetailB");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_MIXEDEDGE_BLUEGREY_STRUCTURALDETAILC = SpriteAsset.single(
        "37_Panel_MixedEdge_BlueGrey_StructuralDetailC.png",
        DIR, 32, 32,
        "Asset - 37 Panel MixedEdge BlueGrey StructuralDetailC");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_MIXEDEDGE_BLUEGREY_STRUCTURALDETAILD = SpriteAsset.single(
        "38_Panel_MixedEdge_BlueGrey_StructuralDetailD.png",
        DIR, 32, 32,
        "Asset - 38 Panel MixedEdge BlueGrey StructuralDetailD");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_MIXEDEDGE_BLUEGREY_STRUCTURALDETAILE = SpriteAsset.single(
        "39_Panel_MixedEdge_BlueGrey_StructuralDetailE.png",
        DIR, 32, 32,
        "Asset - 39 Panel MixedEdge BlueGrey StructuralDetailE");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_MIXEDEDGE_BLUEGREY_STRUCTURALDETAILF = SpriteAsset.single(
        "40_Panel_MixedEdge_BlueGrey_StructuralDetailF.png",
        DIR, 32, 32,
        "Asset - 40 Panel MixedEdge BlueGrey StructuralDetailF");

    /** 32x32px | static */
    public static final SpriteAsset SLOPE_DARKDIAGONAL_CUTA_STEEPRAMPLEFT = SpriteAsset.single(
        "41_Slope_DarkDiagonal_CutA_SteepRampLeft.png",
        DIR, 32, 32,
        "Asset - 41 Slope DarkDiagonal CutA SteepRampLeft");

    /** 32x32px | static */
    public static final SpriteAsset SLOPE_DARKDIAGONAL_CUTB_STEEPRAMPRIGHT = SpriteAsset.single(
        "42_Slope_DarkDiagonal_CutB_SteepRampRight.png",
        DIR, 32, 32,
        "Asset - 42 Slope DarkDiagonal CutB SteepRampRight");

    /** 32x32px | static */
    public static final SpriteAsset SLOPE_DARKDIAGONAL_CUTC_SHALLOWRAMPLEFT = SpriteAsset.single(
        "43_Slope_DarkDiagonal_CutC_ShallowRampLeft.png",
        DIR, 32, 32,
        "Asset - 43 Slope DarkDiagonal CutC ShallowRampLeft");

    /** 32x32px | static */
    public static final SpriteAsset SLOPE_DARKDIAGONAL_CUTD_SHALLOWRAMPRIGHT = SpriteAsset.single(
        "44_Slope_DarkDiagonal_CutD_ShallowRampRight.png",
        DIR, 32, 32,
        "Asset - 44 Slope DarkDiagonal CutD ShallowRampRight");

    /** 32x32px | static */
    public static final SpriteAsset SOLID_FLATBLUE_FULLBLOCK_CEILINGORPLATFORMA = SpriteAsset.single(
        "45_Solid_FlatBlue_FullBlock_CeilingOrPlatformA.png",
        DIR, 32, 32,
        "Tile - 45 Solid FlatBlue FullBlock CeilingOrPlatformA");

    /** 32x32px | static */
    public static final SpriteAsset SOLID_FLATBLUE_FULLBLOCK_CEILINGORPLATFORMB = SpriteAsset.single(
        "46_Solid_FlatBlue_FullBlock_CeilingOrPlatformB.png",
        DIR, 32, 32,
        "Tile - 46 Solid FlatBlue FullBlock CeilingOrPlatformB");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_INSETDETAIL_BLUETECH_WALLINLAYA = SpriteAsset.single(
        "47_Panel_InsetDetail_BlueTech_WallInlayA.png",
        DIR, 32, 32,
        "Asset - 47 Panel InsetDetail BlueTech WallInlayA");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_INSETDETAIL_BLUETECH_WALLINLAYB = SpriteAsset.single(
        "48_Panel_InsetDetail_BlueTech_WallInlayB.png",
        DIR, 32, 32,
        "Asset - 48 Panel InsetDetail BlueTech WallInlayB");

    /** 32x32px | static */
    public static final SpriteAsset SOLID_MAGENTAPURPLE_FULLBLOCK_ACCENTSTRUCTURE = SpriteAsset.single(
        "49_Solid_MagentaPurple_FullBlock_AccentStructure.png",
        DIR, 32, 32,
        "Tile - 49 Solid MagentaPurple FullBlock AccentStructure");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_GREYTECH_INSETBEVEL_DARKPLATFORMA = SpriteAsset.single(
        "50_Panel_GreyTech_InsetBevel_DarkPlatformA.png",
        DIR, 32, 32,
        "Tile - 50 Panel GreyTech InsetBevel DarkPlatformA");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_GREYTECH_INSETBEVEL_DARKPLATFORMB = SpriteAsset.single(
        "51_Panel_GreyTech_InsetBevel_DarkPlatformB.png",
        DIR, 32, 32,
        "Tile - 51 Panel GreyTech InsetBevel DarkPlatformB");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_GREYTECH_INSETBEVEL_DARKPLATFORMC = SpriteAsset.single(
        "52_Panel_GreyTech_InsetBevel_DarkPlatformC.png",
        DIR, 32, 32,
        "Tile - 52 Panel GreyTech InsetBevel DarkPlatformC");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_GREYTECH_INSETBEVEL_DARKPLATFORMD = SpriteAsset.single(
        "53_Panel_GreyTech_InsetBevel_DarkPlatformD.png",
        DIR, 32, 32,
        "Tile - 53 Panel GreyTech InsetBevel DarkPlatformD");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_GREYTECH_INSETBEVEL_DARKPLATFORME = SpriteAsset.single(
        "54_Panel_GreyTech_InsetBevel_DarkPlatformE.png",
        DIR, 32, 32,
        "Tile - 54 Panel GreyTech InsetBevel DarkPlatformE");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_GREYTECH_INSETBEVEL_DARKPLATFORMF = SpriteAsset.single(
        "55_Panel_GreyTech_InsetBevel_DarkPlatformF.png",
        DIR, 32, 32,
        "Tile - 55 Panel GreyTech InsetBevel DarkPlatformF");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_GREYTECH_INSETBEVEL_DARKPLATFORMG = SpriteAsset.single(
        "56_Panel_GreyTech_InsetBevel_DarkPlatformG.png",
        DIR, 32, 32,
        "Tile - 56 Panel GreyTech InsetBevel DarkPlatformG");

    /** 32x32px | static */
    public static final SpriteAsset DOOR_GATEFRAME_PANELSTYLE_CLOSEDDOORA = SpriteAsset.single(
        "57_Door_GateFrame_PanelStyle_ClosedDoorA.png",
        DIR, 32, 32,
        "Asset - 57 Door GateFrame PanelStyle ClosedDoorA");

    /** 32x32px | static */
    public static final SpriteAsset DOOR_GATEFRAME_PANELSTYLE_CLOSEDDOORB = SpriteAsset.single(
        "58_Door_GateFrame_PanelStyle_ClosedDoorB.png",
        DIR, 32, 32,
        "Asset - 58 Door GateFrame PanelStyle ClosedDoorB");

    /** 32x32px | static */
    public static final SpriteAsset DOOR_GATEFRAME_PANELSTYLE_CLOSEDDOORC = SpriteAsset.single(
        "59_Door_GateFrame_PanelStyle_ClosedDoorC.png",
        DIR, 32, 32,
        "Asset - 59 Door GateFrame PanelStyle ClosedDoorC");

    /** 32x32px | static */
    public static final SpriteAsset DOOR_GATEFRAME_PANELSTYLE_CLOSEDDOORD = SpriteAsset.single(
        "60_Door_GateFrame_PanelStyle_ClosedDoorD.png",
        DIR, 32, 32,
        "Asset - 60 Door GateFrame PanelStyle ClosedDoorD");

    /** 32x32px | static */
    public static final SpriteAsset SOLID_LIGHTGREYBLUE_FLATSTRUCTURAL_CEILINGTILEA = SpriteAsset.single(
        "61_Solid_LightGreyBlue_FlatStructural_CeilingTileA.png",
        DIR, 32, 32,
        "Tile - 61 Solid LightGreyBlue FlatStructural CeilingTileA");

    /** 32x32px | static */
    public static final SpriteAsset SOLID_LIGHTGREYBLUE_FLATSTRUCTURAL_CEILINGTILEB = SpriteAsset.single(
        "62_Solid_LightGreyBlue_FlatStructural_CeilingTileB.png",
        DIR, 32, 32,
        "Tile - 62 Solid LightGreyBlue FlatStructural CeilingTileB");

    /** 32x32px | static */
    public static final SpriteAsset SOLID_LIGHTGREYBLUE_FLATSTRUCTURAL_CEILINGTILEC = SpriteAsset.single(
        "63_Solid_LightGreyBlue_FlatStructural_CeilingTileC.png",
        DIR, 32, 32,
        "Tile - 63 Solid LightGreyBlue FlatStructural CeilingTileC");

    /** 32x32px | static */
    public static final SpriteAsset SOLID_LIGHTGREYBLUE_FLATSTRUCTURAL_CEILINGTILED = SpriteAsset.single(
        "64_Solid_LightGreyBlue_FlatStructural_CeilingTileD.png",
        DIR, 32, 32,
        "Tile - 64 Solid LightGreyBlue FlatStructural CeilingTileD");

    /** Total number of assets in this group */
    public static final int COUNT = 64;

    private Level2TileAssets() { } // no instantiation
}
