package assets.tiles;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/Industrial_zone_level_1/1 Tiles
 * Total assets: 81
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level1TileAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/Industrial_zone_level_1/1 Tiles/";

    /** 32x32px | static */
    public static final SpriteAsset PLATFORM_SOLIDBLOCK_FLATTOPFULL_DARKPURPLE_PRIMARYWALKABLEFLOORTILE = SpriteAsset.single(
        "01_Platform_SolidBlock_FlatTopFull_DarkPurple_PrimaryWalkableFloorTile.png",
        DIR, 32, 32,
        "Tile - 01 Platform SolidBlock FlatTopFull DarkPurple PrimaryWalkableFloorTile");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_BREAKABLEBLOCK_LARGEXCROSSHATCH_PURPLEONDARK_WARNINGSURFACEORDESTRUCTIBLE = SpriteAsset.single(
        "02_Hazard_BreakableBlock_LargeXCrosshatch_PurpleOnDark_WarningSurfaceOrDestructible.png",
        DIR, 32, 32,
        "02 Hazard BreakableBlock LargeXCrosshatch PurpleOnDark WarningSurfaceOrDestructible");

    /** 32x32px | static */
    public static final SpriteAsset PLATFORM_SOLIDBLOCK_FLATTOPMID_MUTEDBLUEPURPLE_STANDARDFLOORFILL = SpriteAsset.single(
        "03_Platform_SolidBlock_FlatTopMid_MutedBluePurple_StandardFloorFill.png",
        DIR, 32, 32,
        "Tile - 03 Platform SolidBlock FlatTopMid MutedBluePurple StandardFloorFill");

    /** 32x32px | static */
    public static final SpriteAsset CORNER_INNERTOPRIGHT_LSHAPECUTOUT_SOLIDEDGE_WALLMEETSFLOORJOINTOPRIGHT = SpriteAsset.single(
        "04_Corner_InnerTopRight_LShapeCutout_SolidEdge_WallMeetsFloorJoinTopRight.png",
        DIR, 32, 32,
        "04 Corner InnerTopRight LShapeCutout SolidEdge WallMeetsFloorJoinTopRight");

    /** 32x32px | static */
    public static final SpriteAsset STRUCTURE_SOLIDBLOCK_SMALLSTAMPTOPRIGHT_OFFSETACCENT_ARCHITECTURALDETAILFILL = SpriteAsset.single(
        "05_Structure_SolidBlock_SmallStampTopRight_OffsetAccent_ArchitecturalDetailFill.png",
        DIR, 32, 32,
        "05 Structure SolidBlock SmallStampTopRight OffsetAccent ArchitecturalDetailFill");

    /** 32x32px | static */
    public static final SpriteAsset CORNER_INNERTOPLEFT_NOTCHEDTOPLEFT_SOLIDEDGE_WALLMEETSFLOORJOINTOPLEFT = SpriteAsset.single(
        "06_Corner_InnerTopLeft_NotchedTopLeft_SolidEdge_WallMeetsFloorJoinTopLeft.png",
        DIR, 32, 32,
        "06 Corner InnerTopLeft NotchedTopLeft SolidEdge WallMeetsFloorJoinTopLeft");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_GRIDSURFACE_2X2QUADDIVIDED_FLATINDUSTRIALFACE_WALLORFLOORPANELFILL = SpriteAsset.single(
        "07_Panel_GridSurface_2x2QuadDivided_FlatIndustrialFace_WallOrFloorPanelFill.png",
        DIR, 32, 32,
        "07 Panel GridSurface 2x2QuadDivided FlatIndustrialFace WallOrFloorPanelFill");

    /** 32x32px | static */
    public static final SpriteAsset WALL_VERTICALCOLUMN_NARROWCENTREALIGNED_TALLRECTANGLE_SHAFTORPILLARMIDFILL = SpriteAsset.single(
        "08_Wall_VerticalColumn_NarrowCentreAligned_TallRectangle_ShaftOrPillarMidFill.png",
        DIR, 32, 32,
        "08 Wall VerticalColumn NarrowCentreAligned TallRectangle ShaftOrPillarMidFill");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_WARNINGSURFACE_SINGLEDIAGONALREDSTRIPE_BLUEBASE_CONTACTDAMAGEHAZARD = SpriteAsset.single(
        "09_Hazard_WarningSurface_SingleDiagonalRedStripe_BlueBase_ContactDamageHazard.png",
        DIR, 32, 32,
        "09 Hazard WarningSurface SingleDiagonalRedStripe BlueBase ContactDamageHazard");

    /** 32x32px | static */
    public static final SpriteAsset CORNER_EXTERIORTOPRIGHT_SMALLDARKSQUARE_OFFSETTOPRIGHT_WALLTOPRIGHTCAPACCENT = SpriteAsset.single(
        "10_Corner_ExteriorTopRight_SmallDarkSquare_OffsetTopRight_WallTopRightCapAccent.png",
        DIR, 32, 32,
        "10 Corner ExteriorTopRight SmallDarkSquare OffsetTopRight WallTopRightCapAccent");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_GRIDSURFACE_2X2LARGEGRID_PROMINENTDIVIDERS_LARGEINDUSTRIALWALLORFLOORPANEL = SpriteAsset.single(
        "11_Panel_GridSurface_2x2LargeGrid_ProminentDividers_LargeIndustrialWallOrFloorPanel.png",
        DIR, 32, 32,
        "11 Panel GridSurface 2x2LargeGrid ProminentDividers LargeIndustrialWallOrFloorPanel");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_DETAILBLOCK_RECTANGULARINSETTOPRIGHT_INDUSTRIALSURFACE_WALLORFLOORFILLDETA = SpriteAsset.single(
        "12_Panel_DetailBlock_RectangularInsetTopRight_IndustrialSurface_WallOrFloorFillDetail.png",
        DIR, 32, 32,
        "12 Panel DetailBlock RectangularInsetTopRight IndustrialSurface WallOrFloorFillDetail");

    /** 32x32px | static */
    public static final SpriteAsset WALL_THINVERTICALCOLUMN_NARROWCENTRESTRIP_TALLSLENDER_PIPECOVERORWALLDIVIDER = SpriteAsset.single(
        "13_Wall_ThinVerticalColumn_NarrowCentreStrip_TallSlender_PipeCoverOrWallDivider.png",
        DIR, 32, 32,
        "13 Wall ThinVerticalColumn NarrowCentreStrip TallSlender PipeCoverOrWallDivider");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_INSETDETAIL_SMALLSQUAREEMBEDDEDTOPRIGHT_RECESSEDACCENT_DECORATIVEWALLFILL = SpriteAsset.single(
        "14_Panel_InsetDetail_SmallSquareEmbeddedTopRight_RecessedAccent_DecorativeWallFill.png",
        DIR, 32, 32,
        "14 Panel InsetDetail SmallSquareEmbeddedTopRight RecessedAccent DecorativeWallFill");

    /** 32x32px | static */
    public static final SpriteAsset WALL_VERTICALEDGESTRIP_NARROWRIGHTALIGNED_TALLDARKBAR_RIGHTWALLEDGECAPTILE = SpriteAsset.single(
        "15_Wall_VerticalEdgeStrip_NarrowRightAligned_TallDarkBar_RightWallEdgeCapTile.png",
        DIR, 32, 32,
        "15 Wall VerticalEdgeStrip NarrowRightAligned TallDarkBar RightWallEdgeCapTile");

    /** 32x32px | static */
    public static final SpriteAsset PLATFORM_SOLIDBLOCK_FLATTOP_FAINTDOTRIVETPATTERN_WORNINDUSTRIALFLOORFILL = SpriteAsset.single(
        "16_Platform_SolidBlock_FlatTop_FaintDotRivetPattern_WornIndustrialFloorFill.png",
        DIR, 32, 32,
        "16 Platform SolidBlock FlatTop FaintDotRivetPattern WornIndustrialFloorFill");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_INSETDETAIL_SMALLSQUAREEMBEDDEDBOTTOMCENTRE_RECESSEDACCENT_LOWERWALLFILL = SpriteAsset.single(
        "17_Panel_InsetDetail_SmallSquareEmbeddedBottomCentre_RecessedAccent_LowerWallFill.png",
        DIR, 32, 32,
        "17 Panel InsetDetail SmallSquareEmbeddedBottomCentre RecessedAccent LowerWallFill");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_HORIZONTALSHELFBAR_NARROWCENTREALIGNED_FLATTOP_LEDGESURFACEORPLATFORMEDGE = SpriteAsset.single(
        "18_Edge_HorizontalShelfBar_NarrowCentreAligned_FlatTop_LedgeSurfaceOrPlatformEdge.png",
        DIR, 32, 32,
        "18 Edge HorizontalShelfBar NarrowCentreAligned FlatTop LedgeSurfaceOrPlatformEdge");

    /** 32x32px | static */
    public static final SpriteAsset CORNER_DIAGONALHALFBLOCK_TOPRIGHTTOBOTTOMLEFT_TWOTONEBLUE_SLOPEDTRANSITIONORDECO = SpriteAsset.single(
        "19_Corner_DiagonalHalfBlock_TopRightToBottomLeft_TwoToneBlue_SlopedTransitionOrDeco.png",
        DIR, 32, 32,
        "19 Corner DiagonalHalfBlock TopRightToBottomLeft TwoToneBlue SlopedTransitionOrDeco");

    /** 32x32px | static */
    public static final SpriteAsset CORNER_EXTERIORTOPRIGHT_SMALLTWOTONESQUARE_OFFSETACCENT_WALLTOPEDGEDECOCAP = SpriteAsset.single(
        "20_Corner_ExteriorTopRight_SmallTwoToneSquare_OffsetAccent_WallTopEdgeDecoCap.png",
        DIR, 32, 32,
        "20 Corner ExteriorTopRight SmallTwoToneSquare OffsetAccent WallTopEdgeDecoCap");

    /** 32x32px | static */
    public static final SpriteAsset STRUCTURE_SOLIDBLOCK_LARGEFULLFLAT_HEAVYDARKTONE_HEAVYSTRUCTURALWALLORFLOOR = SpriteAsset.single(
        "21_Structure_SolidBlock_LargeFullFlat_HeavyDarkTone_HeavyStructuralWallOrFloor.png",
        DIR, 32, 32,
        "21 Structure SolidBlock LargeFullFlat HeavyDarkTone HeavyStructuralWallOrFloor");

    /** 32x32px | static */
    public static final SpriteAsset STRUCTURE_SOLIDBLOCK_SMALLNOTCHTOPRIGHT_EDGEDETAILACCENT_STRUCTURALTRANSITIONCAP = SpriteAsset.single(
        "22_Structure_SolidBlock_SmallNotchTopRight_EdgeDetailAccent_StructuralTransitionCap.png",
        DIR, 32, 32,
        "22 Structure SolidBlock SmallNotchTopRight EdgeDetailAccent StructuralTransitionCap");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_BRACKETSHELF_NARROWHORIZONTALBAR_BOTTOMCENTRENOTCH_INDUSTRIALSUPPORTBRACKET = SpriteAsset.single(
        "23_Edge_BracketShelf_NarrowHorizontalBar_BottomCentreNotch_IndustrialSupportBracket.png",
        DIR, 32, 32,
        "23 Edge BracketShelf NarrowHorizontalBar BottomCentreNotch IndustrialSupportBracket");

    /** 32x32px | static */
    public static final SpriteAsset CORNER_DIAGONALHALFBLOCK_BOTTOMRIGHTTOTOPLEFT_LARGESPLIT_SLOPEDSURFACETRANSITION = SpriteAsset.single(
        "24_Corner_DiagonalHalfBlock_BottomRightToTopLeft_LargeSplit_SlopedSurfaceTransition.png",
        DIR, 32, 32,
        "24 Corner DiagonalHalfBlock BottomRightToTopLeft LargeSplit SlopedSurfaceTransition");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_MINIMALCORNERCAP_THINSTRIPTOPRIGHT_SMALLSQUAREACCENT_CORNEREDGEDETAILTILE = SpriteAsset.single(
        "25_Edge_MinimalCornerCap_ThinStripTopRight_SmallSquareAccent_CornerEdgeDetailTile.png",
        DIR, 32, 32,
        "25 Edge MinimalCornerCap ThinStripTopRight SmallSquareAccent CornerEdgeDetailTile");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_BOLTEDSHELFLEDGE_NARROWHORIZONTAL_BOLTRIVETSIDES_SUPPORTEDINDUSTRIALLEDGE = SpriteAsset.single(
        "26_Edge_BoltedShelfLedge_NarrowHorizontal_BoltRivetSides_SupportedIndustrialLedge.png",
        DIR, 32, 32,
        "26 Edge BoltedShelfLedge NarrowHorizontal BoltRivetSides SupportedIndustrialLedge");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_WIDELEDGEBAR_HORIZONTALWIDEFLAT_FLATWALKABLETOP_LEDGEPLATFORMTRANSITION = SpriteAsset.single(
        "27_Edge_WideLedgeBar_HorizontalWideFlat_FlatWalkableTop_LedgePlatformTransition.png",
        DIR, 32, 32,
        "27 Edge WideLedgeBar HorizontalWideFlat FlatWalkableTop LedgePlatformTransition");

    /** 32x32px | static */
    public static final SpriteAsset CORNER_DIAGONALHALFBLOCK_BOTTOMLEFTTOTOPRIGHT_POINTINGRIGHT_RIGHTFACINGSLOPEBLOC = SpriteAsset.single(
        "28_Corner_DiagonalHalfBlock_BottomLeftToTopRight_PointingRight_RightFacingSlopeBlock.png",
        DIR, 32, 32,
        "28 Corner DiagonalHalfBlock BottomLeftToTopRight PointingRight RightFacingSlopeBlock");

    /** 32x32px | static */
    public static final SpriteAsset CORNER_DIAGONALHALFBLOCK_TOPLEFTTOBOTTOMRIGHT_POINTINGDOWN_LEFTFACINGSLOPEBLOCK = SpriteAsset.single(
        "29_Corner_DiagonalHalfBlock_TopLeftToBottomRight_PointingDown_LeftFacingSlopeBlock.png",
        DIR, 32, 32,
        "29 Corner DiagonalHalfBlock TopLeftToBottomRight PointingDown LeftFacingSlopeBlock");

    /** 32x32px | static */
    public static final SpriteAsset CORNER_SMALLDIAGONAL_TOPRIGHTCORNERONLY_MINORSLOPEDACCENT_TRANSITIONORDECODETAIL = SpriteAsset.single(
        "30_Corner_SmallDiagonal_TopRightCornerOnly_MinorSlopedAccent_TransitionOrDecoDetail.png",
        DIR, 32, 32,
        "30 Corner SmallDiagonal TopRightCornerOnly MinorSlopedAccent TransitionOrDecoDetail");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_FULLSTRIPEBLOCK_DIAGONALREDORANGESTRIPES_FULLCOVERAGE_CONTACTDAMAGEHAZARD = SpriteAsset.single(
        "31_Hazard_FullStripeBlock_DiagonalRedOrangeStripes_FullCoverage_ContactDamageHazardFloor.png",
        DIR, 32, 32,
        "31 Hazard FullStripeBlock DiagonalRedOrangeStripes FullCoverage ContactDamageHazardFloor");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_FULLSTRIPEBLOCK_DIAGONALALTANGLESTRIPES_FULLCOVERAGE_ALTERNATEHAZARDSURFA = SpriteAsset.single(
        "32_Hazard_FullStripeBlock_DiagonalAltAngleStripes_FullCoverage_AlternateHazardSurface.png",
        DIR, 32, 32,
        "32 Hazard FullStripeBlock DiagonalAltAngleStripes FullCoverage AlternateHazardSurface");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_ZIGZAGCRISSCROSSSTRIPE_MULTIDIAGONALPATTERN_FULLCOVERAGE_INTENSIVEHAZARDZ = SpriteAsset.single(
        "33_Hazard_ZigzagCrisscrossStripe_MultiDiagonalPattern_FullCoverage_IntensiveHazardZone.png",
        DIR, 32, 32,
        "33 Hazard ZigzagCrisscrossStripe MultiDiagonalPattern FullCoverage IntensiveHazardZone");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_WIDESPACEDSTRIPEBLOCK_DIAGONALWIDEGAP_CONTACTDAMAGE_MODERATEHAZARDBARRIER = SpriteAsset.single(
        "34_Hazard_WideSpacedStripeBlock_DiagonalWideGap_ContactDamage_ModerateHazardBarrier.png",
        DIR, 32, 32,
        "34 Hazard WideSpacedStripeBlock DiagonalWideGap ContactDamage ModerateHazardBarrier");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_DENSESTRIPEBLOCK_DIAGONALDENSEPACKING_CONTACTDAMAGE_HIGHDENSITYHAZARDSURF = SpriteAsset.single(
        "35_Hazard_DenseStripeBlock_DiagonalDensePacking_ContactDamage_HighDensityHazardSurface.png",
        DIR, 32, 32,
        "35 Hazard DenseStripeBlock DiagonalDensePacking ContactDamage HighDensityHazardSurface");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_CROSSHATCHXBLOCK_LARGEBOLDXPATTERN_CONTACTDAMAGEORBARRIER_NOGOZONEWARNING = SpriteAsset.single(
        "36_Hazard_CrosshatchXBlock_LargeBoldXPattern_ContactDamageOrBarrier_NoGoZoneWarning.png",
        DIR, 32, 32,
        "36 Hazard CrosshatchXBlock LargeBoldXPattern ContactDamageOrBarrier NoGoZoneWarning");

    /** 32x32px | static */
    public static final SpriteAsset DECO_CIRCLEMARKER_LARGESOLIDCIRCLECENTRED_PURPLEONDARK_BUTTONPORTALINTERACTIVEDE = SpriteAsset.single(
        "37_Deco_CircleMarker_LargeSolidCircleCentred_PurpleOnDark_ButtonPortalInteractiveDeco.png",
        DIR, 32, 32,
        "37 Deco CircleMarker LargeSolidCircleCentred PurpleOnDark ButtonPortalInteractiveDeco");

    /** 32x32px | static */
    public static final SpriteAsset CORNER_DIAGONALHALFBLOCK_BOTTOMLEFTTOTOPRIGHT_DARKPURPLETONE_SLOPEDSURFACETRANSI = SpriteAsset.single(
        "38_Corner_DiagonalHalfBlock_BottomLeftToTopRight_DarkPurpleTone_SlopedSurfaceTransition.png",
        DIR, 32, 32,
        "38 Corner DiagonalHalfBlock BottomLeftToTopRight DarkPurpleTone SlopedSurfaceTransition");

    /** 32x32px | static */
    public static final SpriteAsset DECO_CIRCLEMARKER_SOLIDCIRCLECENTREDALTSHADE_SLIGHTLYDIFFERENTPURPLE_PICKUPORDEC = SpriteAsset.single(
        "39_Deco_CircleMarker_SolidCircleCentredAltShade_SlightlyDifferentPurple_PickupOrDecoSpot.png",
        DIR, 32, 32,
        "39 Deco CircleMarker SolidCircleCentredAltShade SlightlyDifferentPurple PickupOrDecoSpot");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_PARTIALSTRIPEBLOCK_DENSEREDSTRIPESRIGHTSIDE_CONTACTDAMAGE_HALFHAZARDTRANS = SpriteAsset.single(
        "40_Hazard_PartialStripeBlock_DenseRedStripesRightSide_ContactDamage_HalfHazardTransition.png",
        DIR, 32, 32,
        "40 Hazard PartialStripeBlock DenseRedStripesRightSide ContactDamage HalfHazardTransition");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_FULLSTRIPEBLOCK_DIAGONALORANGEREDFULL_CONTACTDAMAGE_HAZARDFLOORSURFACE = SpriteAsset.single(
        "41_Hazard_FullStripeBlock_DiagonalOrangeRedFull_ContactDamage_HazardFloorSurface.png",
        DIR, 32, 32,
        "41 Hazard FullStripeBlock DiagonalOrangeRedFull ContactDamage HazardFloorSurface");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_CROSSEDSTRIPEBLOCK_DIAGONALNARROWCROSSED_CONTACTDAMAGE_HAZARDBARRIERVARIA = SpriteAsset.single(
        "42_Hazard_CrossedStripeBlock_DiagonalNarrowCrossed_ContactDamage_HazardBarrierVariant.png",
        DIR, 32, 32,
        "42 Hazard CrossedStripeBlock DiagonalNarrowCrossed ContactDamage HazardBarrierVariant");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_WIDEGAPSTRIPEBLOCK_DIAGONALLARGESPACING_CONTACTDAMAGE_HAZARDZONEMARKERTIL = SpriteAsset.single(
        "43_Hazard_WideGapStripeBlock_DiagonalLargeSpacing_ContactDamage_HazardZoneMarkerTile.png",
        DIR, 32, 32,
        "43 Hazard WideGapStripeBlock DiagonalLargeSpacing ContactDamage HazardZoneMarkerTile");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_THINLINESTRIPEBLOCK_DIAGONALFINELINES_CONTACTDAMAGE_LIGHTHAZARDWARNINGMAR = SpriteAsset.single(
        "44_Hazard_ThinLineStripeBlock_DiagonalFineLines_ContactDamage_LightHazardWarningMarker.png",
        DIR, 32, 32,
        "44 Hazard ThinLineStripeBlock DiagonalFineLines ContactDamage LightHazardWarningMarker");

    /** 32x32px | static */
    public static final SpriteAsset CORNER_EXTERIORTOPRIGHT_SMALLWARMREDORANGE_HAZARDTONE_HAZARDZONETOPRIGHTCORNERCA = SpriteAsset.single(
        "45_Corner_ExteriorTopRight_SmallWarmRedOrange_HazardTone_HazardZoneTopRightCornerCap.png",
        DIR, 32, 32,
        "45 Corner ExteriorTopRight SmallWarmRedOrange HazardTone HazardZoneTopRightCornerCap");

    /** 32x32px | static */
    public static final SpriteAsset WALL_VERTICALEDGESTRIP_NARROWLEFTALIGNED_PURPLETALLBAR_LEFTWALLEDGECAPTILE = SpriteAsset.single(
        "46_Wall_VerticalEdgeStrip_NarrowLeftAligned_PurpleTallBar_LeftWallEdgeCapTile.png",
        DIR, 32, 32,
        "46 Wall VerticalEdgeStrip NarrowLeftAligned PurpleTallBar LeftWallEdgeCapTile");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_HORIZONTALSTRIPEBLOCK_EVENSPACEDLINES_FULLSQUARE_WALLFILLORFLOORSTRIPEPANE = SpriteAsset.single(
        "47_Panel_HorizontalStripeBlock_EvenSpacedLines_FullSquare_WallFillOrFloorStripePanel.png",
        DIR, 32, 32,
        "47 Panel HorizontalStripeBlock EvenSpacedLines FullSquare WallFillOrFloorStripePanel");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_GAPSTRIPEBAR_NARROWHORIZONTALSTRIP_WIDEGAPLINEPATTERN_PIPEEDGEORLEDGEACCENT = SpriteAsset.single(
        "48_Edge_GapStripeBar_NarrowHorizontalStrip_WideGapLinePattern_PipeEdgeOrLedgeAccent.png",
        DIR, 32, 32,
        "48 Edge GapStripeBar NarrowHorizontalStrip WideGapLinePattern PipeEdgeOrLedgeAccent");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_MEDIUMSTRIPEBLOCK_DIAGONALMEDIUMSPACING_CONTACTDAMAGE_MIDINTENSITYHAZARDZ = SpriteAsset.single(
        "49_Hazard_MediumStripeBlock_DiagonalMediumSpacing_ContactDamage_MidIntensityHazardZone.png",
        DIR, 32, 32,
        "49 Hazard MediumStripeBlock DiagonalMediumSpacing ContactDamage MidIntensityHazardZone");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_BRIGHTSTRIPEBLOCK_DIAGONALVIVIDBRIGHT_CONTACTDAMAGE_HIGHVISIBILITYHAZARDZ = SpriteAsset.single(
        "50_Hazard_BrightStripeBlock_DiagonalVividBright_ContactDamage_HighVisibilityHazardZone.png",
        DIR, 32, 32,
        "50 Hazard BrightStripeBlock DiagonalVividBright ContactDamage HighVisibilityHazardZone");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_DENSEORANGESTRIPE_DIAGONALDENSEORANGEPACKED_CONTACTDAMAGE_HOTHAZARDSURFAC = SpriteAsset.single(
        "51_Hazard_DenseOrangeStripe_DiagonalDenseOrangePacked_ContactDamage_HotHazardSurface.png",
        DIR, 32, 32,
        "51 Hazard DenseOrangeStripe DiagonalDenseOrangePacked ContactDamage HotHazardSurface");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_ALTANGLESTRIPEBLOCK_DIAGONALVARIANTANGLE_CONTACTDAMAGE_ALTHAZARDFLOORVARI = SpriteAsset.single(
        "52_Hazard_AltAngleStripeBlock_DiagonalVariantAngle_ContactDamage_AltHazardFloorVariant.png",
        DIR, 32, 32,
        "52 Hazard AltAngleStripeBlock DiagonalVariantAngle ContactDamage AltHazardFloorVariant");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_ELECTRICENERGYSTRIPE_VERTICALLIGHTNINGLINE_INSTANTDAMAGE_ELECTRICSHOCKHAZ = SpriteAsset.single(
        "53_Hazard_ElectricEnergyStripe_VerticalLightningLine_InstantDamage_ElectricShockHazard.png",
        DIR, 32, 32,
        "53 Hazard ElectricEnergyStripe VerticalLightningLine InstantDamage ElectricShockHazard");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_GLOWINGENERGYBAR_VERTICALGRADIENTBRIGHTCENTRE_INSTANTDAMAGE_ENERGYBEAMHAZ = SpriteAsset.single(
        "54_Hazard_GlowingEnergyBar_VerticalGradientBrightCentre_InstantDamage_EnergyBeamHazard.png",
        DIR, 32, 32,
        "54 Hazard GlowingEnergyBar VerticalGradientBrightCentre InstantDamage EnergyBeamHazard");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_SMALLMUTEDCORNERCAP_TOPRIGHTALIGNED_MUTEDTONE_MINIMALTRANSITIONEDGEDETAIL = SpriteAsset.single(
        "55_Edge_SmallMutedCornerCap_TopRightAligned_MutedTone_MinimalTransitionEdgeDetail.png",
        DIR, 32, 32,
        "55 Edge SmallMutedCornerCap TopRightAligned MutedTone MinimalTransitionEdgeDetail");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_INSETDETAIL_SMALLSQUAREEMBEDDEDLEFTCENTRE_RECESSEDACCENT_LEFTWALLDETAILPAN = SpriteAsset.single(
        "56_Panel_InsetDetail_SmallSquareEmbeddedLeftCentre_RecessedAccent_LeftWallDetailPanel.png",
        DIR, 32, 32,
        "56 Panel InsetDetail SmallSquareEmbeddedLeftCentre RecessedAccent LeftWallDetailPanel");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_INSETDETAIL_SMALLSQUAREEMBEDDEDRIGHTCENTRE_RECESSEDACCENT_RIGHTWALLDETAILP = SpriteAsset.single(
        "57_Panel_InsetDetail_SmallSquareEmbeddedRightCentre_RecessedAccent_RightWallDetailPanel.png",
        DIR, 32, 32,
        "57 Panel InsetDetail SmallSquareEmbeddedRightCentre RecessedAccent RightWallDetailPanel");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_FULLSTRIPEBLOCK_DIAGONALREDORANGEVARIANTB_CONTACTDAMAGE_HAZARDFLOORVARIAN = SpriteAsset.single(
        "58_Hazard_FullStripeBlock_DiagonalRedOrangeVariantB_ContactDamage_HazardFloorVariantB.png",
        DIR, 32, 32,
        "58 Hazard FullStripeBlock DiagonalRedOrangeVariantB ContactDamage HazardFloorVariantB");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_NARROWORANGESTRIPEBLOCK_DIAGONALTIGHTSPACING_CONTACTDAMAGE_TIGHTPACKEDHAZ = SpriteAsset.single(
        "59_Hazard_NarrowOrangeStripeBlock_DiagonalTightSpacing_ContactDamage_TightPackedHazard.png",
        DIR, 32, 32,
        "59 Hazard NarrowOrangeStripeBlock DiagonalTightSpacing ContactDamage TightPackedHazard");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_WIDEORANGESTRIPEBLOCK_DIAGONALLOOSESPACING_CONTACTDAMAGE_WIDESPACEDHAZARD = SpriteAsset.single(
        "60_Hazard_WideOrangeStripeBlock_DiagonalLooseSpacing_ContactDamage_WideSpacedHazardZone.png",
        DIR, 32, 32,
        "60 Hazard WideOrangeStripeBlock DiagonalLooseSpacing ContactDamage WideSpacedHazardZone");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_TECHCONTROLDETAIL_SMALLINSETDOTCENTRED_BLUEGREYTONE_MACHINERYCONTROLPANELW = SpriteAsset.single(
        "61_Panel_TechControlDetail_SmallInsetDotCentred_BlueGreyTone_MachineryControlPanelWall.png",
        DIR, 32, 32,
        "61 Panel TechControlDetail SmallInsetDotCentred BlueGreyTone MachineryControlPanelWall");

    /** 32x32px | static */
    public static final SpriteAsset DECO_DIAMONDXGRIDPATTERN_SMALLSCALEREPEATING_PURPLEONDARK_DECORATIVEWALLORFLOORF = SpriteAsset.single(
        "62_Deco_DiamondXGridPattern_SmallScaleRepeating_PurpleOnDark_DecorativeWallOrFloorFill.png",
        DIR, 32, 32,
        "62 Deco DiamondXGridPattern SmallScaleRepeating PurpleOnDark DecorativeWallOrFloorFill");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_ENERGYBARRIERSTRIP_TALLNARROWBRIGHTGRADIENTGLOW_INSTANTDAMAGE_VERTICALENE = SpriteAsset.single(
        "63_Hazard_EnergyBarrierStrip_TallNarrowBrightGradientGlow_InstantDamage_VerticalEnergyBarrier.png",
        DIR, 32, 32,
        "63 Hazard EnergyBarrierStrip TallNarrowBrightGradientGlow InstantDamage VerticalEnergyBarrier");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_INSETDETAIL_MEDIUMSQUAREEMBEDDEDCENTRE_RECESSEDLARGER_CENTRALMACHINEDETAIL = SpriteAsset.single(
        "64_Panel_InsetDetail_MediumSquareEmbeddedCentre_RecessedLarger_CentralMachineDetailPanel.png",
        DIR, 32, 32,
        "64 Panel InsetDetail MediumSquareEmbeddedCentre RecessedLarger CentralMachineDetailPanel");

    /** 32x32px | static */
    public static final SpriteAsset STRUCTURE_SOLIDBLOCK_SMALLRIGHTALIGNED_DARKCOMPACTTONE_COMPACTWALLOREDGEFILLTILE = SpriteAsset.single(
        "65_Structure_SolidBlock_SmallRightAligned_DarkCompactTone_CompactWallOrEdgeFillTile.png",
        DIR, 32, 32,
        "65 Structure SolidBlock SmallRightAligned DarkCompactTone CompactWallOrEdgeFillTile");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_INSETDETAIL_SMALLSQUAREEMBEDDEDBOTTOMLEFT_RECESSEDACCENT_LOWERLEFTWALLDETA = SpriteAsset.single(
        "66_Panel_InsetDetail_SmallSquareEmbeddedBottomLeft_RecessedAccent_LowerLeftWallDetail.png",
        DIR, 32, 32,
        "66 Panel InsetDetail SmallSquareEmbeddedBottomLeft RecessedAccent LowerLeftWallDetail");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_DARKSTRIPEBLOCK_DIAGONALDARKMUTEDTONE_CONTACTDAMAGE_DARKINDUSTRIALHAZARDS = SpriteAsset.single(
        "67_Hazard_DarkStripeBlock_DiagonalDarkMutedTone_ContactDamage_DarkIndustrialHazardSurface.png",
        DIR, 32, 32,
        "67 Hazard DarkStripeBlock DiagonalDarkMutedTone ContactDamage DarkIndustrialHazardSurface");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_DARKSTRIPEVARIANT_DIAGONALALTDARKTONE_CONTACTDAMAGE_ALTERNATEDARKHAZARDSU = SpriteAsset.single(
        "68_Hazard_DarkStripeVariant_DiagonalAltDarkTone_ContactDamage_AlternateDarkHazardSurface.png",
        DIR, 32, 32,
        "68 Hazard DarkStripeVariant DiagonalAltDarkTone ContactDamage AlternateDarkHazardSurface");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_WARMDARKSTRIPEBLOCK_DIAGONALWARMBROWNISHTONE_CONTACTDAMAGE_WARMTONEHAZARD = SpriteAsset.single(
        "69_Hazard_WarmDarkStripeBlock_DiagonalWarmBrownishTone_ContactDamage_WarmToneHazardSurface.png",
        DIR, 32, 32,
        "69 Hazard WarmDarkStripeBlock DiagonalWarmBrownishTone ContactDamage WarmToneHazardSurface");

    /** 32x32px | static */
    public static final SpriteAsset DECO_GRADIENTCOLUMNSTRIP_TALLNARROWPURPLEGRADIENT_BACKGROUNDACCENT_VERTICALDECOD = SpriteAsset.single(
        "70_Deco_GradientColumnStrip_TallNarrowPurpleGradient_BackgroundAccent_VerticalDecoDivider.png",
        DIR, 32, 32,
        "70 Deco GradientColumnStrip TallNarrowPurpleGradient BackgroundAccent VerticalDecoDivider");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_CHUNKYDIAMONDCROSSBLOCK_LARGESCALEXPATTERN_CONTACTDAMAGE_BARRIERORHAZARDI = SpriteAsset.single(
        "71_Hazard_ChunkyDiamondCrossBlock_LargeScaleXPattern_ContactDamage_BarrierOrHazardIndicator.png",
        DIR, 32, 32,
        "71 Hazard ChunkyDiamondCrossBlock LargeScaleXPattern ContactDamage BarrierOrHazardIndicator");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_BOTTOMEDGEBAND_WIDESHORTRECTANGLE_HAZARDSTRIPESBOTTOMEDGE_FLOORLEVELHAZAR = SpriteAsset.single(
        "72_Hazard_BottomEdgeBand_WideShortRectangle_HazardStripesBottomEdge_FloorLevelHazardWarning.png",
        DIR, 32, 32,
        "72 Hazard BottomEdgeBand WideShortRectangle HazardStripesBottomEdge FloorLevelHazardWarning");

    /** 32x32px | static */
    public static final SpriteAsset PANEL_FRAMEDINSETBLOCK_SMALLSQUARECENTREFRAME_RECESSEDSCREEN_TECHMONITORORCONTRO = SpriteAsset.single(
        "73_Panel_FramedInsetBlock_SmallSquareCentreFrame_RecessedScreen_TechMonitorOrControlPanel.png",
        DIR, 32, 32,
        "73 Panel FramedInsetBlock SmallSquareCentreFrame RecessedScreen TechMonitorOrControlPanel");

    /** 32x32px | static */
    public static final SpriteAsset DECO_INDICATORLIGHTSTRIP_WIDESHORTRECTANGLE_REDLIGHTROWSINGLE_MACHINERYSTATUSIND = SpriteAsset.single(
        "74_Deco_IndicatorLightStrip_WideShortRectangle_RedLightRowSingle_MachineryStatusIndicator.png",
        DIR, 32, 32,
        "74 Deco IndicatorLightStrip WideShortRectangle RedLightRowSingle MachineryStatusIndicator");

    /** 32x32px | static */
    public static final SpriteAsset DECO_INDICATORLIGHTSTRIP_WIDESHORTLONGER_REDLIGHTROWEXTENDED_MACHINERYSTATUSBARW = SpriteAsset.single(
        "75_Deco_IndicatorLightStrip_WideShortLonger_RedLightRowExtended_MachineryStatusBarWide.png",
        DIR, 32, 32,
        "75 Deco IndicatorLightStrip WideShortLonger RedLightRowExtended MachineryStatusBarWide");

    /** 32x32px | static */
    public static final SpriteAsset DECO_INDICATORLIGHTSTRIP_WIDESHORTVARIANT_REDLIGHTSSPACEDALT_ALTERNATESTATUSINDI = SpriteAsset.single(
        "76_Deco_IndicatorLightStrip_WideShortVariant_RedLightsSpacedAlt_AlternateStatusIndicator.png",
        DIR, 32, 32,
        "76 Deco IndicatorLightStrip WideShortVariant RedLightsSpacedAlt AlternateStatusIndicator");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_PLAINHORIZONTALDIVIDERBAR_NARROWTHINSTRIP_SOLIDCOLOUR_FLOORCEILINGDIVIDERST = SpriteAsset.single(
        "77_Edge_PlainHorizontalDividerBar_NarrowThinStrip_SolidColour_FloorCeilingDividerStrip.png",
        DIR, 32, 32,
        "77 Edge PlainHorizontalDividerBar NarrowThinStrip SolidColour FloorCeilingDividerStrip");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_WIDEHORIZONTALDIVIDERBAR_NARROWMEDIUMSTRIP_SOLIDCOLOUR_FLOORCEILINGDIVIDERW = SpriteAsset.single(
        "78_Edge_WideHorizontalDividerBar_NarrowMediumStrip_SolidColour_FloorCeilingDividerWide.png",
        DIR, 32, 32,
        "78 Edge WideHorizontalDividerBar NarrowMediumStrip SolidColour FloorCeilingDividerWide");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_ALTSHADEHORIZONTALBAR_NARROWTHINSTRIP_ALTERNATECOLOURTONE_LEDGEORDIVIDEREDG = SpriteAsset.single(
        "79_Edge_AltShadeHorizontalBar_NarrowThinStrip_AlternateColourTone_LedgeOrDividerEdge.png",
        DIR, 32, 32,
        "79 Edge AltShadeHorizontalBar NarrowThinStrip AlternateColourTone LedgeOrDividerEdge");

    /** 32x32px | static */
    public static final SpriteAsset EDGE_REDACCENTHORIZONTALBAR_NARROWTHINSTRIP_REDHIGHLIGHTTONE_HAZARDLEVELINDICATO = SpriteAsset.single(
        "80_Edge_RedAccentHorizontalBar_NarrowThinStrip_RedHighlightTone_HazardLevelIndicatorLine.png",
        DIR, 32, 32,
        "80 Edge RedAccentHorizontalBar NarrowThinStrip RedHighlightTone HazardLevelIndicatorLine");

    /** 32x32px | static */
    public static final SpriteAsset HAZARD_SMALLSTRIPEWIDEBAND_SHORTWIDERECTANGLE_REDMINISTRIPES_LOWLEVELHAZARDTHRES = SpriteAsset.single(
        "81_Hazard_SmallStripeWideBand_ShortWideRectangle_RedMiniStripes_LowLevelHazardThreshold.png",
        DIR, 32, 32,
        "81 Hazard SmallStripeWideBand ShortWideRectangle RedMiniStripes LowLevelHazardThreshold");

    /** Total number of assets in this group */
    public static final int COUNT = 81;

    private Level1TileAssets() { } // no instantiation
}
