package assets.backgrounds;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/power-station-level-2/2 Background_level_2/Night
 * Total assets: 5
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level2BackgroundNightAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/power-station-level-2/2 Background_level_2/Night/";

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER1_SKYBASE_DARKGREYGRADIENT_STATICFILL_DRAWFIRST = SpriteAsset.single(
        "BG_Layer1_SkyBase_DarkGreyGradient_StaticFill_DrawFirst.png",
        DIR, 576, 324,
        "BG Layer1 SkyBase DarkGreyGradient StaticFill DrawFirst");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER2_FACTORYLEFT_DARKGREYSILHOUETTE_PARALLAXFACTOR015 = SpriteAsset.single(
        "BG_Layer2_FactoryLeft_DarkGreySilhouette_ParallaxFactor015.png",
        DIR, 576, 324,
        "BG Layer2 FactoryLeft DarkGreySilhouette ParallaxFactor015");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER3_FACTORYTALL_DARKGREYCENTRE_PARALLAXFACTOR025 = SpriteAsset.single(
        "BG_Layer3_FactoryTall_DarkGreyCentre_ParallaxFactor025.png",
        DIR, 576, 324,
        "BG Layer3 FactoryTall DarkGreyCentre ParallaxFactor025");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER4_DISTANTFACTORY_VERYDARKFAINT_PARALLAXFACTOR040 = SpriteAsset.single(
        "BG_Layer4_DistantFactory_VeryDarkFaint_ParallaxFactor040.png",
        DIR, 576, 324,
        "BG Layer4 DistantFactory VeryDarkFaint ParallaxFactor040");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER5_FACTORYRIGHT_DARKGREYVARIANT_PARALLAXFACTOR060 = SpriteAsset.single(
        "BG_Layer5_FactoryRight_DarkGreyVariant_ParallaxFactor060.png",
        DIR, 576, 324,
        "BG Layer5 FactoryRight DarkGreyVariant ParallaxFactor060");

    /** Total number of assets in this group */
    public static final int COUNT = 5;

    private Level2BackgroundNightAssets() { } // no instantiation
}
