package assets.backgrounds;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/power-station-level-2/2 Background_level_2
 * Total assets: 1
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level2BackgroundAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/power-station-level-2/2 Background_level_2/";

    /** 1800x1200px | ~1 frames */
    public static final SpriteAsset BG_OVERLAY_BLUEYELLOWDIAGONALGRADIENT_COLOURATMOSPHERE_DRAWLAST = SpriteAsset.single(
        "BG_Overlay_BlueYellowDiagonalGradient_ColourAtmosphere_DrawLast.png",
        DIR, 1800, 1200,
        "BG Overlay BlueYellowDiagonalGradient ColourAtmosphere DrawLast");

    /** Total number of assets in this group */
    public static final int COUNT = 1;

    private Level2BackgroundAssets() { } // no instantiation
}
