package assets.backgrounds;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/power-station-level-2/2 Background_level_2/Day
 * Total assets: 5
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level2BackgroundDayAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/power-station-level-2/2 Background_level_2/Day/";

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER1_SKYBASE_LIGHTGREYWHITEGRADIENT_STATICFILL_DRAWFIRST = SpriteAsset.single(
        "BG_Layer1_SkyBase_LightGreyWhiteGradient_StaticFill_DrawFirst.png",
        DIR, 576, 324,
        "BG Layer1 SkyBase LightGreyWhiteGradient StaticFill DrawFirst");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER2_FACTORYLEFT_LIGHTBLUEDETAIL_PARALLAXFACTOR015 = SpriteAsset.single(
        "BG_Layer2_FactoryLeft_LightBlueDetail_ParallaxFactor015.png",
        DIR, 576, 324,
        "Background - BG Layer2 FactoryLeft LightBlueDetail ParallaxFactor015");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER3_FACTORYTALL_LIGHTBLUECHIMNEY_PARALLAXFACTOR025 = SpriteAsset.single(
        "BG_Layer3_FactoryTall_LightBlueChimney_ParallaxFactor025.png",
        DIR, 576, 324,
        "BG Layer3 FactoryTall LightBlueChimney ParallaxFactor025");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER4_DISTANTFACTORY_FAINTSILHOUETTE_PARALLAXFACTOR040 = SpriteAsset.single(
        "BG_Layer4_DistantFactory_FaintSilhouette_ParallaxFactor040.png",
        DIR, 576, 324,
        "BG Layer4 DistantFactory FaintSilhouette ParallaxFactor040");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER5_FACTORYRIGHT_LIGHTBLUEVARIANT_PARALLAXFACTOR060 = SpriteAsset.single(
        "BG_Layer5_FactoryRight_LightBlueVariant_ParallaxFactor060.png",
        DIR, 576, 324,
        "BG Layer5 FactoryRight LightBlueVariant ParallaxFactor060");

    /** Total number of assets in this group */
    public static final int COUNT = 5;

    private Level2BackgroundDayAssets() { } // no instantiation
}
