package assets.backgrounds;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/Industrial_zone_level_1/2 Background_level_1
 * Total assets: 6
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level1BackgroundAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/Industrial_zone_level_1/2 Background_level_1/";

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_COMPOSITE_FULLLAYEREDSKYLINE_ALLLAYERSCOMBINED_SINGLEDRAWFALLBACK = SpriteAsset.single(
        "BG_Composite_FullLayeredSkyline_AllLayersCombined_SingleDrawFallback.png",
        DIR, 576, 324,
        "BG Composite FullLayeredSkyline AllLayersCombined SingleDrawFallback");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER1_SKYBASE_SOLIDLAVENDERGREY_STATICFILL_DRAWFIRSTNOSCROLL = SpriteAsset.single(
        "BG_Layer1_SkyBase_SolidLavenderGrey_StaticFill_DrawFirstNoScroll.png",
        DIR, 576, 324,
        "BG Layer1 SkyBase SolidLavenderGrey StaticFill DrawFirstNoScroll");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER2_FRACTALTREESILHOUETTE_MINTSKYBLACKCRACKS_PARALLAXFACTOR015 = SpriteAsset.single(
        "BG_Layer2_FractalTreeSilhouette_MintSkyBlackCracks_ParallaxFactor015.png",
        DIR, 576, 324,
        "BG Layer2 FractalTreeSilhouette MintSkyBlackCracks ParallaxFactor015");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER3_FARFACTORYSILHOUETTE_LIGHTBLUEINDUSTRIAL_PARALLAXFACTOR025 = SpriteAsset.single(
        "BG_Layer3_FarFactorySilhouette_LightBlueIndustrial_ParallaxFactor025.png",
        DIR, 576, 324,
        "BG Layer3 FarFactorySilhouette LightBlueIndustrial ParallaxFactor025");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER4_MIDFACTORYSILHOUETTE_MEDIUMBLUEPIPEDETAIL_PARALLAXFACTOR040 = SpriteAsset.single(
        "BG_Layer4_MidFactorySilhouette_MediumBluePipeDetail_ParallaxFactor040.png",
        DIR, 576, 324,
        "BG Layer4 MidFactorySilhouette MediumBluePipeDetail ParallaxFactor040");

    /** 576x324px | ~1 frames */
    public static final SpriteAsset BG_LAYER5_NEARFACTORYSILHOUETTE_DARKNAVYLARGETANK_PARALLAXFACTOR060 = SpriteAsset.single(
        "BG_Layer5_NearFactorySilhouette_DarkNavyLargeTank_ParallaxFactor060.png",
        DIR, 576, 324,
        "BG Layer5 NearFactorySilhouette DarkNavyLargeTank ParallaxFactor060");

    /** Total number of assets in this group */
    public static final int COUNT = 6;

    private Level1BackgroundAssets() { } // no instantiation
}
