package assets.characters;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/player/biker
 * Total assets: 24
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class BikerAssets {

    private static final String DIR = "Resources/industrial-zone/characters/player/biker/";

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_BIKER_IDLE_STANDINGBREATHLOOP_DEFAULTIDLE = SpriteAsset.loop(
        "01_Player_Biker_Idle_4Frames1Row_StandingBreathLoop_DefaultIdle_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Character - 01 Player Biker Idle 4Frames1Row StandingBreathLoop DefaultIdle Loop 150ms");

    /** 288x48px | ~6 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_BIKER_IDLE2_ALTERNATESTANDLOOP_SECONDARYIDLE = SpriteAsset.loop(
        "02_Player_Biker_Idle2_6Frames1Row_AlternateStandLoop_SecondaryIdle_Loop_150ms.png",
        DIR, 288, 48, 150,
        "Character - 02 Player Biker Idle2 6Frames1Row AlternateStandLoop SecondaryIdle Loop 150ms");

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset PLAYER_BIKER_WALK_WALKINGCYCLEFORWARD_MOVEMENT = SpriteAsset.loop(
        "03_Player_Biker_Walk_6Frames1Row_WalkingCycleForward_Movement_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Character - 03 Player Biker Walk 6Frames1Row WalkingCycleForward Movement Loop 100ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset PLAYER_BIKER_RUN_FULLRUNCYCLE_FASTMOVEMENT = SpriteAsset.loop(
        "04_Player_Biker_Run_6Frames1Row_FullRunCycle_FastMovement_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Character - 04 Player Biker Run 6Frames1Row FullRunCycle FastMovement Loop 80ms");

    /** 288x48px | ~6 frames | 60ms/f */
    public static final SpriteAsset PLAYER_BIKER_DASH_DASHSLIDEFORWARD_QUICKDASH = SpriteAsset.once(
        "05_Player_Biker_Dash_6Frames1Row_DashSlideForward_QuickDash_PlayOnce_60ms.png",
        DIR, 288, 48, 60,
        "Character - 05 Player Biker Dash 6Frames1Row DashSlideForward QuickDash PlayOnce 60ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset PLAYER_BIKER_JUMP_JUMPRISEARC_JUMPSTART = SpriteAsset.once(
        "06_Player_Biker_Jump_4Frames1Row_JumpRiseArc_JumpStart_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Character - 06 Player Biker Jump 4Frames1Row JumpRiseArc JumpStart PlayOnce 80ms");

    /** 288x48px | ~6 frames | 80ms/f */
    public static final SpriteAsset PLAYER_BIKER_DOUBLEJUMP_MIDAIRFLIPBOOST_SECONDJUMP = SpriteAsset.once(
        "07_Player_Biker_DoubleJump_6Frames1Row_MidAirFlipBoost_SecondJump_PlayOnce_80ms.png",
        DIR, 288, 48, 80,
        "Character - 07 Player Biker DoubleJump 6Frames1Row MidAirFlipBoost SecondJump PlayOnce 80ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset PLAYER_BIKER_FALL_FALLINGDESCEND_AIRFALL = SpriteAsset.loop(
        "08_Player_Biker_Fall_4Frames1Row_FallingDescend_AirFall_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Character - 08 Player Biker Fall 4Frames1Row FallingDescend AirFall Loop 100ms");

    /** 288x48px | ~6 frames | 120ms/f | loop */
    public static final SpriteAsset PLAYER_BIKER_CLIMB_LADDERCLIMBCYCLE_CLIMBLADDER = SpriteAsset.loop(
        "09_Player_Biker_Climb_6Frames1Row_LadderClimbCycle_ClimbLadder_Loop_120ms.png",
        DIR, 288, 48, 120,
        "Character - 09 Player Biker Climb 6Frames1Row LadderClimbCycle ClimbLadder Loop 120ms");

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_BIKER_HANG_LEDGEHANGHOLD_HANGINGIDLE = SpriteAsset.loop(
        "10_Player_Biker_Hang_3Frames1Row_LedgeHangHold_HangingIdle_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Character - 10 Player Biker Hang 3Frames1Row LedgeHangHold HangingIdle Loop 150ms");

    /** 288x96px | ~3 frames | 80ms/f */
    public static final SpriteAsset PLAYER_BIKER_PULLUP_PULLUPFROMLEDGE_LEDGEPULLUP = SpriteAsset.once(
        "11_Player_Biker_Pullup_6Frames1Row_PullUpFromLedge_LedgePullup_PlayOnce_80ms.png",
        DIR, 288, 96, 80,
        "Character - 11 Player Biker Pullup 6Frames1Row PullUpFromLedge LedgePullup PlayOnce 80ms");

    /** 288x48px | ~6 frames | 70ms/f */
    public static final SpriteAsset PLAYER_BIKER_PUNCH_STANDINGPUNCHCOMBO_MELEEATTACK = SpriteAsset.once(
        "12_Player_Biker_Punch_5Frames1Row_StandingPunchCombo_MeleeAttack_PlayOnce_70ms.png",
        DIR, 288, 48, 70,
        "Character - 12 Player Biker Punch 5Frames1Row StandingPunchCombo MeleeAttack PlayOnce 70ms");

    /** 288x48px | ~6 frames | 70ms/f */
    public static final SpriteAsset PLAYER_BIKER_ATTACK1_COMBOHIT1SWING_ATTACK1 = SpriteAsset.once(
        "13_Player_Biker_Attack1_5Frames1Row_ComboHit1Swing_Attack1_PlayOnce_70ms.png",
        DIR, 288, 48, 70,
        "Character - 13 Player Biker Attack1 5Frames1Row ComboHit1Swing Attack1 PlayOnce 70ms");

    /** 384x48px | ~8 frames | 70ms/f */
    public static final SpriteAsset PLAYER_BIKER_ATTACK2_GUITARSWINGCOMBO_ATTACK2 = SpriteAsset.once(
        "14_Player_Biker_Attack2_5Frames1Row_GuitarSwingCombo_Attack2_PlayOnce_70ms.png",
        DIR, 384, 48, 70,
        "Character - 14 Player Biker Attack2 5Frames1Row GuitarSwingCombo Attack2 PlayOnce 70ms");

    /** 384x48px | ~8 frames | 70ms/f */
    public static final SpriteAsset PLAYER_BIKER_ATTACK3_ENERGYWAVERELEASE_ATTACK3 = SpriteAsset.once(
        "15_Player_Biker_Attack3_7Frames1Row_EnergyWaveRelease_Attack3_PlayOnce_70ms.png",
        DIR, 384, 48, 70,
        "Character - 15 Player Biker Attack3 7Frames1Row EnergyWaveRelease Attack3 PlayOnce 70ms");

    /** 288x48px | ~6 frames | 80ms/f */
    public static final SpriteAsset PLAYER_BIKER_WALKATTACK_WALKINGATTACKSWING_MOVEATTACK = SpriteAsset.once(
        "16_Player_Biker_WalkAttack_5Frames1Row_WalkingAttackSwing_MoveAttack_PlayOnce_80ms.png",
        DIR, 288, 48, 80,
        "Character - 16 Player Biker WalkAttack 5Frames1Row WalkingAttackSwing MoveAttack PlayOnce 80ms");

    /** 288x48px | ~6 frames | 70ms/f */
    public static final SpriteAsset PLAYER_BIKER_RUNATTACK_RUNNINGATTACKSWING_RUNATTACK = SpriteAsset.once(
        "17_Player_Biker_RunAttack_5Frames1Row_RunningAttackSwing_RunAttack_PlayOnce_70ms.png",
        DIR, 288, 48, 70,
        "Character - 17 Player Biker RunAttack 5Frames1Row RunningAttackSwing RunAttack PlayOnce 70ms");

    /** 96x48px | ~2 frames | 100ms/f */
    public static final SpriteAsset PLAYER_BIKER_HURT_HITREACTIONGHOSTFLINCH_TAKEDAMAGE = SpriteAsset.once(
        "18_Player_Biker_Hurt_2Frames1Row_HitReactionGhostFlinch_TakeDamage_PlayOnce_100ms.png",
        DIR, 96, 48, 100,
        "Character - 18 Player Biker Hurt 2Frames1Row HitReactionGhostFlinch TakeDamage PlayOnce 100ms");

    /** 288x48px | ~6 frames | 120ms/f */
    public static final SpriteAsset PLAYER_BIKER_DEATH_DEATHFALLSEQUENCE_PLAYERDEATH = SpriteAsset.once(
        "19_Player_Biker_Death_6Frames1Row_DeathFallSequence_PlayerDeath_PlayOnce_120ms.png",
        DIR, 288, 48, 120,
        "Character - 19 Player Biker Death 6Frames1Row DeathFallSequence PlayerDeath PlayOnce 120ms");

    /** 288x48px | ~6 frames | 100ms/f */
    public static final SpriteAsset PLAYER_BIKER_USE_INTERACTUSEOBJECT_INTERACT = SpriteAsset.once(
        "20_Player_Biker_Use_5Frames1Row_InteractUseObject_Interact_PlayOnce_100ms.png",
        DIR, 288, 48, 100,
        "Character - 20 Player Biker Use 5Frames1Row InteractUseObject Interact PlayOnce 100ms");

    /** 192x48px | ~4 frames | 120ms/f */
    public static final SpriteAsset PLAYER_BIKER_SITDOWN_SITDOWNTRANSITION_SIT = SpriteAsset.once(
        "21_Player_Biker_Sitdown_3Frames1Row_SitDownTransition_Sit_PlayOnce_120ms.png",
        DIR, 192, 48, 120,
        "Character - 21 Player Biker Sitdown 3Frames1Row SitDownTransition Sit PlayOnce 120ms");

    /** 288x48px | ~6 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_BIKER_ANGRY_ANGRYEXPRESSIONEMOTE_EMOTE = SpriteAsset.loop(
        "22_Player_Biker_Angry_5Frames1Row_AngryExpressionEmote_Emote_Loop_150ms.png",
        DIR, 288, 48, 150,
        "Character - 22 Player Biker Angry 5Frames1Row AngryExpressionEmote Emote Loop 150ms");

    /** 288x48px | ~6 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_BIKER_HAPPY_HAPPYEXPRESSIONEMOTE_EMOTE = SpriteAsset.loop(
        "23_Player_Biker_Happy_5Frames1Row_HappyExpressionEmote_Emote_Loop_150ms.png",
        DIR, 288, 48, 150,
        "Character - 23 Player Biker Happy 5Frames1Row HappyExpressionEmote Emote Loop 150ms");

    /** 288x48px | ~6 frames | 120ms/f | loop */
    public static final SpriteAsset PLAYER_BIKER_TALK_TALKINGMOUTHMOVE_DIALOGUE = SpriteAsset.loop(
        "24_Player_Biker_Talk_5Frames1Row_TalkingMouthMove_Dialogue_Loop_120ms.png",
        DIR, 288, 48, 120,
        "Character - 24 Player Biker Talk 5Frames1Row TalkingMouthMove Dialogue Loop 120ms");

    /** Total number of assets in this group */
    public static final int COUNT = 24;

    private BikerAssets() { } // no instantiation
}
