package assets.characters;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/player/cyborg
 * Total assets: 24
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class CyborgAssets {

    private static final String DIR = "Resources/industrial-zone/characters/player/cyborg/";

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_CYBORG_IDLE_STANDINGBREATHLOOP_DEFAULTIDLE = SpriteAsset.loop(
        "01_Player_Cyborg_Idle_4Frames1Row_StandingBreathLoop_DefaultIdle_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Character - 01 Player Cyborg Idle 4Frames1Row StandingBreathLoop DefaultIdle Loop 150ms");

    /** 288x48px | ~6 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_CYBORG_IDLE2_ALTERNATESTANDLOOP_SECONDARYIDLE = SpriteAsset.loop(
        "02_Player_Cyborg_Idle2_5Frames1Row_AlternateStandLoop_SecondaryIdle_Loop_150ms.png",
        DIR, 288, 48, 150,
        "Character - 02 Player Cyborg Idle2 5Frames1Row AlternateStandLoop SecondaryIdle Loop 150ms");

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset PLAYER_CYBORG_WALK_WALKINGCYCLEFORWARD_MOVEMENT = SpriteAsset.loop(
        "03_Player_Cyborg_Walk_5Frames1Row_WalkingCycleForward_Movement_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Character - 03 Player Cyborg Walk 5Frames1Row WalkingCycleForward Movement Loop 100ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset PLAYER_CYBORG_RUN_FULLRUNCYCLE_FASTMOVEMENT = SpriteAsset.loop(
        "04_Player_Cyborg_Run_5Frames1Row_FullRunCycle_FastMovement_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Character - 04 Player Cyborg Run 5Frames1Row FullRunCycle FastMovement Loop 80ms");

    /** 288x48px | ~6 frames | 60ms/f */
    public static final SpriteAsset PLAYER_CYBORG_DASH_DASHTRAILFORWARD_QUICKDASH = SpriteAsset.once(
        "05_Player_Cyborg_Dash_4Frames1Row_DashTrailForward_QuickDash_PlayOnce_60ms.png",
        DIR, 288, 48, 60,
        "Character - 05 Player Cyborg Dash 4Frames1Row DashTrailForward QuickDash PlayOnce 60ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset PLAYER_CYBORG_JUMP_JUMPRISEARC_JUMPSTART = SpriteAsset.once(
        "06_Player_Cyborg_Jump_3Frames1Row_JumpRiseArc_JumpStart_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Character - 06 Player Cyborg Jump 3Frames1Row JumpRiseArc JumpStart PlayOnce 80ms");

    /** 288x48px | ~6 frames | 80ms/f */
    public static final SpriteAsset PLAYER_CYBORG_DOUBLEJUMP_MIDAIRBOOSTFLIP_SECONDJUMP = SpriteAsset.once(
        "07_Player_Cyborg_DoubleJump_5Frames1Row_MidAirBoostFlip_SecondJump_PlayOnce_80ms.png",
        DIR, 288, 48, 80,
        "Character - 07 Player Cyborg DoubleJump 5Frames1Row MidAirBoostFlip SecondJump PlayOnce 80ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset PLAYER_CYBORG_FALL_FALLINGDESCEND_AIRFALL = SpriteAsset.loop(
        "08_Player_Cyborg_Fall_3Frames1Row_FallingDescend_AirFall_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Character - 08 Player Cyborg Fall 3Frames1Row FallingDescend AirFall Loop 100ms");

    /** 288x48px | ~6 frames | 120ms/f | loop */
    public static final SpriteAsset PLAYER_CYBORG_CLIMB_LADDERCLIMBCYCLE_CLIMBLADDER = SpriteAsset.loop(
        "09_Player_Cyborg_Climb_4Frames1Row_LadderClimbCycle_ClimbLadder_Loop_120ms.png",
        DIR, 288, 48, 120,
        "Character - 09 Player Cyborg Climb 4Frames1Row LadderClimbCycle ClimbLadder Loop 120ms");

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_CYBORG_HANG_LEDGEHANGHOLD_HANGINGIDLE = SpriteAsset.loop(
        "10_Player_Cyborg_Hang_3Frames1Row_LedgeHangHold_HangingIdle_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Character - 10 Player Cyborg Hang 3Frames1Row LedgeHangHold HangingIdle Loop 150ms");

    /** 288x96px | ~3 frames | 80ms/f */
    public static final SpriteAsset PLAYER_CYBORG_PULLUP_PULLUPFROMLEDGE_LEDGEPULLUP = SpriteAsset.once(
        "11_Player_Cyborg_Pullup_7Frames1Row_PullUpFromLedge_LedgePullup_PlayOnce_80ms.png",
        DIR, 288, 96, 80,
        "Character - 11 Player Cyborg Pullup 7Frames1Row PullUpFromLedge LedgePullup PlayOnce 80ms");

    /** 288x48px | ~6 frames | 70ms/f */
    public static final SpriteAsset PLAYER_CYBORG_PUNCH_STANDINGPUNCHCOMBO_MELEEATTACK = SpriteAsset.once(
        "12_Player_Cyborg_Punch_5Frames1Row_StandingPunchCombo_MeleeAttack_PlayOnce_70ms.png",
        DIR, 288, 48, 70,
        "Character - 12 Player Cyborg Punch 5Frames1Row StandingPunchCombo MeleeAttack PlayOnce 70ms");

    /** 288x48px | ~6 frames | 70ms/f */
    public static final SpriteAsset PLAYER_CYBORG_ATTACK1_PUNCHFORWARD_ATTACK1 = SpriteAsset.once(
        "13_Player_Cyborg_Attack1_5Frames1Row_PunchForward_Attack1_PlayOnce_70ms.png",
        DIR, 288, 48, 70,
        "Character - 13 Player Cyborg Attack1 5Frames1Row PunchForward Attack1 PlayOnce 70ms");

    /** 384x48px | ~8 frames | 70ms/f */
    public static final SpriteAsset PLAYER_CYBORG_ATTACK2_EXTENDEDPUNCHREACH_ATTACK2 = SpriteAsset.once(
        "14_Player_Cyborg_Attack2_5Frames1Row_ExtendedPunchReach_Attack2_PlayOnce_70ms.png",
        DIR, 384, 48, 70,
        "Character - 14 Player Cyborg Attack2 5Frames1Row ExtendedPunchReach Attack2 PlayOnce 70ms");

    /** 384x48px | ~8 frames | 70ms/f */
    public static final SpriteAsset PLAYER_CYBORG_ATTACK3_ENERGYRINGRELEASE_ATTACK3 = SpriteAsset.once(
        "15_Player_Cyborg_Attack3_5Frames1Row_EnergyRingRelease_Attack3_PlayOnce_70ms.png",
        DIR, 384, 48, 70,
        "Character - 15 Player Cyborg Attack3 5Frames1Row EnergyRingRelease Attack3 PlayOnce 70ms");

    /** 288x48px | ~6 frames | 80ms/f */
    public static final SpriteAsset PLAYER_CYBORG_WALKATTACK_WALKINGATTACKSWING_MOVEATTACK = SpriteAsset.once(
        "16_Player_Cyborg_WalkAttack_5Frames1Row_WalkingAttackSwing_MoveAttack_PlayOnce_80ms.png",
        DIR, 288, 48, 80,
        "Character - 16 Player Cyborg WalkAttack 5Frames1Row WalkingAttackSwing MoveAttack PlayOnce 80ms");

    /** 288x48px | ~6 frames | 70ms/f */
    public static final SpriteAsset PLAYER_CYBORG_RUNATTACK_RUNNINGATTACKSWING_RUNATTACK = SpriteAsset.once(
        "17_Player_Cyborg_RunAttack_5Frames1Row_RunningAttackSwing_RunAttack_PlayOnce_70ms.png",
        DIR, 288, 48, 70,
        "Character - 17 Player Cyborg RunAttack 5Frames1Row RunningAttackSwing RunAttack PlayOnce 70ms");

    /** 96x48px | ~2 frames | 100ms/f */
    public static final SpriteAsset PLAYER_CYBORG_HURT_HITREACTIONGHOSTFLINCH_TAKEDAMAGE = SpriteAsset.once(
        "18_Player_Cyborg_Hurt_2Frames1Row_HitReactionGhostFlinch_TakeDamage_PlayOnce_100ms.png",
        DIR, 96, 48, 100,
        "Character - 18 Player Cyborg Hurt 2Frames1Row HitReactionGhostFlinch TakeDamage PlayOnce 100ms");

    /** 288x48px | ~6 frames | 120ms/f */
    public static final SpriteAsset PLAYER_CYBORG_DEATH_DEATHFALLSEQUENCE_PLAYERDEATH = SpriteAsset.once(
        "19_Player_Cyborg_Death_5Frames1Row_DeathFallSequence_PlayerDeath_PlayOnce_120ms.png",
        DIR, 288, 48, 120,
        "Character - 19 Player Cyborg Death 5Frames1Row DeathFallSequence PlayerDeath PlayOnce 120ms");

    /** 288x48px | ~6 frames | 100ms/f */
    public static final SpriteAsset PLAYER_CYBORG_USE_INTERACTUSEOBJECT_INTERACT = SpriteAsset.once(
        "20_Player_Cyborg_Use_5Frames1Row_InteractUseObject_Interact_PlayOnce_100ms.png",
        DIR, 288, 48, 100,
        "Character - 20 Player Cyborg Use 5Frames1Row InteractUseObject Interact PlayOnce 100ms");

    /** 192x48px | ~4 frames | 120ms/f */
    public static final SpriteAsset PLAYER_CYBORG_SITDOWN_SITDOWNTRANSITION_SIT = SpriteAsset.once(
        "21_Player_Cyborg_Sitdown_3Frames1Row_SitDownTransition_Sit_PlayOnce_120ms.png",
        DIR, 192, 48, 120,
        "Character - 21 Player Cyborg Sitdown 3Frames1Row SitDownTransition Sit PlayOnce 120ms");

    /** 288x48px | ~6 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_CYBORG_ANGRY_ANGRYEXPRESSIONEMOTE_EMOTE = SpriteAsset.loop(
        "22_Player_Cyborg_Angry_5Frames1Row_AngryExpressionEmote_Emote_Loop_150ms.png",
        DIR, 288, 48, 150,
        "Character - 22 Player Cyborg Angry 5Frames1Row AngryExpressionEmote Emote Loop 150ms");

    /** 288x48px | ~6 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_CYBORG_HAPPY_HAPPYEXPRESSIONEMOTE_EMOTE = SpriteAsset.loop(
        "23_Player_Cyborg_Happy_5Frames1Row_HappyExpressionEmote_Emote_Loop_150ms.png",
        DIR, 288, 48, 150,
        "Character - 23 Player Cyborg Happy 5Frames1Row HappyExpressionEmote Emote Loop 150ms");

    /** 288x48px | ~6 frames | 120ms/f | loop */
    public static final SpriteAsset PLAYER_CYBORG_TALK_TALKINGMOUTHMOVE_DIALOGUE = SpriteAsset.loop(
        "24_Player_Cyborg_Talk_5Frames1Row_TalkingMouthMove_Dialogue_Loop_120ms.png",
        DIR, 288, 48, 120,
        "Character - 24 Player Cyborg Talk 5Frames1Row TalkingMouthMove Dialogue Loop 120ms");

    /** Total number of assets in this group */
    public static final int COUNT = 24;

    private CyborgAssets() { } // no instantiation
}
