package assets.characters;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/player/punk
 * Total assets: 24
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class PunkAssets {

    private static final String DIR = "Resources/industrial-zone/characters/player/punk/";

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_PUNK_IDLE_STANDINGBREATHLOOP_DEFAULTIDLE = SpriteAsset.loop(
        "01_Player_Punk_Idle_5Frames1Row_StandingBreathLoop_DefaultIdle_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Character - 01 Player Punk Idle 5Frames1Row StandingBreathLoop DefaultIdle Loop 150ms");

    /** 288x48px | ~6 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_PUNK_IDLE2_ALTERNATESTANDLOOP_SECONDARYIDLE = SpriteAsset.loop(
        "02_Player_Punk_Idle2_5Frames1Row_AlternateStandLoop_SecondaryIdle_Loop_150ms.png",
        DIR, 288, 48, 150,
        "Character - 02 Player Punk Idle2 5Frames1Row AlternateStandLoop SecondaryIdle Loop 150ms");

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset PLAYER_PUNK_WALK_WALKINGCYCLEFORWARD_MOVEMENT = SpriteAsset.loop(
        "03_Player_Punk_Walk_5Frames1Row_WalkingCycleForward_Movement_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Character - 03 Player Punk Walk 5Frames1Row WalkingCycleForward Movement Loop 100ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset PLAYER_PUNK_RUN_FULLRUNCYCLE_FASTMOVEMENT = SpriteAsset.loop(
        "04_Player_Punk_Run_6Frames1Row_FullRunCycle_FastMovement_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Character - 04 Player Punk Run 6Frames1Row FullRunCycle FastMovement Loop 80ms");

    /** 288x48px | ~6 frames | 60ms/f */
    public static final SpriteAsset PLAYER_PUNK_DASH_DASHSLIDEFORWARD_QUICKDASH = SpriteAsset.once(
        "05_Player_Punk_Dash_4Frames1Row_DashSlideForward_QuickDash_PlayOnce_60ms.png",
        DIR, 288, 48, 60,
        "Character - 05 Player Punk Dash 4Frames1Row DashSlideForward QuickDash PlayOnce 60ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset PLAYER_PUNK_JUMP_JUMPRISEARC_JUMPSTART = SpriteAsset.once(
        "06_Player_Punk_Jump_3Frames1Row_JumpRiseArc_JumpStart_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Character - 06 Player Punk Jump 3Frames1Row JumpRiseArc JumpStart PlayOnce 80ms");

    /** 288x48px | ~6 frames | 80ms/f */
    public static final SpriteAsset PLAYER_PUNK_DOUBLEJUMP_MIDAIRFLIPBOOST_SECONDJUMP = SpriteAsset.once(
        "07_Player_Punk_DoubleJump_4Frames1Row_MidAirFlipBoost_SecondJump_PlayOnce_80ms.png",
        DIR, 288, 48, 80,
        "Character - 07 Player Punk DoubleJump 4Frames1Row MidAirFlipBoost SecondJump PlayOnce 80ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset PLAYER_PUNK_FALL_FALLINGDESCEND_AIRFALL = SpriteAsset.loop(
        "08_Player_Punk_Fall_3Frames1Row_FallingDescend_AirFall_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Character - 08 Player Punk Fall 3Frames1Row FallingDescend AirFall Loop 100ms");

    /** 288x48px | ~6 frames | 120ms/f | loop */
    public static final SpriteAsset PLAYER_PUNK_CLIMB_LADDERCLIMBCYCLE_CLIMBLADDER = SpriteAsset.loop(
        "09_Player_Punk_Climb_4Frames1Row_LadderClimbCycle_ClimbLadder_Loop_120ms.png",
        DIR, 288, 48, 120,
        "Character - 09 Player Punk Climb 4Frames1Row LadderClimbCycle ClimbLadder Loop 120ms");

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_PUNK_HANG_LEDGEHANGHOLD_HANGINGIDLE = SpriteAsset.loop(
        "10_Player_Punk_Hang_4Frames1Row_LedgeHangHold_HangingIdle_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Character - 10 Player Punk Hang 4Frames1Row LedgeHangHold HangingIdle Loop 150ms");

    /** 288x96px | ~3 frames | 80ms/f */
    public static final SpriteAsset PLAYER_PUNK_PULLUP_PULLUPFROMLEDGE_LEDGEPULLUP = SpriteAsset.once(
        "11_Player_Punk_Pullup_7Frames1Row_PullUpFromLedge_LedgePullup_PlayOnce_80ms.png",
        DIR, 288, 96, 80,
        "Character - 11 Player Punk Pullup 7Frames1Row PullUpFromLedge LedgePullup PlayOnce 80ms");

    /** 288x48px | ~6 frames | 70ms/f */
    public static final SpriteAsset PLAYER_PUNK_PUNCH_STANDINGPUNCHCOMBO_MELEEATTACK = SpriteAsset.once(
        "12_Player_Punk_Punch_6Frames1Row_StandingPunchCombo_MeleeAttack_PlayOnce_70ms.png",
        DIR, 288, 48, 70,
        "Character - 12 Player Punk Punch 6Frames1Row StandingPunchCombo MeleeAttack PlayOnce 70ms");

    /** 288x48px | ~6 frames | 70ms/f */
    public static final SpriteAsset PLAYER_PUNK_ATTACK1_COMBOHIT1SWING_ATTACK1 = SpriteAsset.once(
        "13_Player_Punk_Attack1_5Frames1Row_ComboHit1Swing_Attack1_PlayOnce_70ms.png",
        DIR, 288, 48, 70,
        "Character - 13 Player Punk Attack1 5Frames1Row ComboHit1Swing Attack1 PlayOnce 70ms");

    /** 384x48px | ~8 frames | 70ms/f */
    public static final SpriteAsset PLAYER_PUNK_ATTACK2_COMBOHIT2SWING_ATTACK2 = SpriteAsset.once(
        "14_Player_Punk_Attack2_6Frames1Row_ComboHit2Swing_Attack2_PlayOnce_70ms.png",
        DIR, 384, 48, 70,
        "Character - 14 Player Punk Attack2 6Frames1Row ComboHit2Swing Attack2 PlayOnce 70ms");

    /** 384x48px | ~8 frames | 70ms/f */
    public static final SpriteAsset PLAYER_PUNK_ATTACK3_COMBOHIT3PROJECTILE_ATTACK3 = SpriteAsset.once(
        "15_Player_Punk_Attack3_6Frames1Row_ComboHit3Projectile_Attack3_PlayOnce_70ms.png",
        DIR, 384, 48, 70,
        "Tile - 15 Player Punk Attack3 6Frames1Row ComboHit3Projectile Attack3 PlayOnce 70ms");

    /** 288x48px | ~6 frames | 80ms/f */
    public static final SpriteAsset PLAYER_PUNK_WALKATTACK_WALKINGATTACKSWING_MOVEATTACK = SpriteAsset.once(
        "16_Player_Punk_WalkAttack_5Frames1Row_WalkingAttackSwing_MoveAttack_PlayOnce_80ms.png",
        DIR, 288, 48, 80,
        "Character - 16 Player Punk WalkAttack 5Frames1Row WalkingAttackSwing MoveAttack PlayOnce 80ms");

    /** 288x48px | ~6 frames | 70ms/f */
    public static final SpriteAsset PLAYER_PUNK_RUNATTACK_RUNNINGATTACKSWING_RUNATTACK = SpriteAsset.once(
        "17_Player_Punk_RunAttack_6Frames1Row_RunningAttackSwing_RunAttack_PlayOnce_70ms.png",
        DIR, 288, 48, 70,
        "Character - 17 Player Punk RunAttack 6Frames1Row RunningAttackSwing RunAttack PlayOnce 70ms");

    /** 96x48px | ~2 frames | 100ms/f */
    public static final SpriteAsset PLAYER_PUNK_HURT_HITREACTIONFLINCH_TAKEDAMAGE = SpriteAsset.once(
        "18_Player_Punk_Hurt_2Frames1Row_HitReactionFlinch_TakeDamage_PlayOnce_100ms.png",
        DIR, 96, 48, 100,
        "Character - 18 Player Punk Hurt 2Frames1Row HitReactionFlinch TakeDamage PlayOnce 100ms");

    /** 288x48px | ~6 frames | 120ms/f */
    public static final SpriteAsset PLAYER_PUNK_DEATH_DEATHFALLSEQUENCE_PLAYERDEATH = SpriteAsset.once(
        "19_Player_Punk_Death_5Frames1Row_DeathFallSequence_PlayerDeath_PlayOnce_120ms.png",
        DIR, 288, 48, 120,
        "Character - 19 Player Punk Death 5Frames1Row DeathFallSequence PlayerDeath PlayOnce 120ms");

    /** 288x48px | ~6 frames | 100ms/f */
    public static final SpriteAsset PLAYER_PUNK_USE_INTERACTUSEOBJECT_INTERACT = SpriteAsset.once(
        "20_Player_Punk_Use_5Frames1Row_InteractUseObject_Interact_PlayOnce_100ms.png",
        DIR, 288, 48, 100,
        "Character - 20 Player Punk Use 5Frames1Row InteractUseObject Interact PlayOnce 100ms");

    /** 192x48px | ~4 frames | 120ms/f */
    public static final SpriteAsset PLAYER_PUNK_SITDOWN_SITDOWNTRANSITION_SIT = SpriteAsset.once(
        "21_Player_Punk_Sitdown_3Frames1Row_SitDownTransition_Sit_PlayOnce_120ms.png",
        DIR, 192, 48, 120,
        "Character - 21 Player Punk Sitdown 3Frames1Row SitDownTransition Sit PlayOnce 120ms");

    /** 288x48px | ~6 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_PUNK_ANGRY_ANGRYEXPRESSIONEMOTE_EMOTE = SpriteAsset.loop(
        "22_Player_Punk_Angry_5Frames1Row_AngryExpressionEmote_Emote_Loop_150ms.png",
        DIR, 288, 48, 150,
        "Character - 22 Player Punk Angry 5Frames1Row AngryExpressionEmote Emote Loop 150ms");

    /** 288x48px | ~6 frames | 150ms/f | loop */
    public static final SpriteAsset PLAYER_PUNK_HAPPY_HAPPYEXPRESSIONEMOTE_EMOTE = SpriteAsset.loop(
        "23_Player_Punk_Happy_5Frames1Row_HappyExpressionEmote_Emote_Loop_150ms.png",
        DIR, 288, 48, 150,
        "Character - 23 Player Punk Happy 5Frames1Row HappyExpressionEmote Emote Loop 150ms");

    /** 288x48px | ~6 frames | 120ms/f | loop */
    public static final SpriteAsset PLAYER_PUNK_TALK_TALKINGMOUTHMOVE_DIALOGUE = SpriteAsset.loop(
        "24_Player_Punk_Talk_5Frames1Row_TalkingMouthMove_Dialogue_Loop_120ms.png",
        DIR, 288, 48, 120,
        "Character - 24 Player Punk Talk 5Frames1Row TalkingMouthMove Dialogue Loop 120ms");

    /** Total number of assets in this group */
    public static final int COUNT = 24;

    private PunkAssets() { } // no instantiation
}
