package assets.objects;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/power-station-level-2/3 Objects/1 Tube
 * Total assets: 11
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level2TubeAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/power-station-level-2/3 Objects/1 Tube/";

    /** 50x25px | ~2 frames | loop */
    public static final SpriteAsset PROP_PIPE_ARCHLOOP_REDMETAL_CURVEDSECTION_WALLDECO = SpriteAsset.single(
        "Prop_Pipe_ArchLoop_RedMetal_CurvedSection_WallDeco.png",
        DIR, 50, 25,
        "Asset - Prop Pipe ArchLoop RedMetal CurvedSection WallDeco");

    /** 26x64px | static */
    public static final SpriteAsset PROP_PIPE_CONNECTOR_DARKBLUE_SMALLJOINTVARIANT_PIPEJOINB = SpriteAsset.single(
        "Prop_Pipe_Connector_DarkBlue_SmallJointVariant_PipeJoinB.png",
        DIR, 26, 64,
        "Asset - Prop Pipe Connector DarkBlue SmallJointVariant PipeJoinB");

    /** 35x22px | ~1 frames */
    public static final SpriteAsset PROP_PIPE_CONNECTOR_DARKBLUE_SMALLJOINT_PIPEJOINA = SpriteAsset.single(
        "Prop_Pipe_Connector_DarkBlue_SmallJoint_PipeJoinA.png",
        DIR, 35, 22,
        "Asset - Prop Pipe Connector DarkBlue SmallJoint PipeJoinA");

    /** 45x16px | ~2 frames */
    public static final SpriteAsset PROP_PIPE_ELBOWBEND_DARKBLUEGREY_LBEND_CORNERJOIN = SpriteAsset.single(
        "Prop_Pipe_ElbowBend_DarkBlueGrey_LBend_CornerJoin.png",
        DIR, 45, 16,
        "Asset - Prop Pipe ElbowBend DarkBlueGrey LBend CornerJoin");

    /** 12x21px | static */
    public static final SpriteAsset PROP_PIPE_ENDCAP_DARKBLUE_SMALLCAP_PIPETERMINATORB = SpriteAsset.single(
        "Prop_Pipe_EndCap_DarkBlue_SmallCap_PipeTerminatorB.png",
        DIR, 12, 21,
        "Asset - Prop Pipe EndCap DarkBlue SmallCap PipeTerminatorB");

    /** 21x11px | static */
    public static final SpriteAsset PROP_PIPE_ENDCAP_DARKNAVY_SMALLCAP_PIPETERMINATORA = SpriteAsset.single(
        "Prop_Pipe_EndCap_DarkNavy_SmallCap_PipeTerminatorA.png",
        DIR, 21, 11,
        "Asset - Prop Pipe EndCap DarkNavy SmallCap PipeTerminatorA");

    /** 22x57px | static */
    public static final SpriteAsset PROP_PIPE_HORIZONTAL_BLUEWITHCLAMP_BRACKETEDRUN_WALLMOUNT = SpriteAsset.single(
        "Prop_Pipe_Horizontal_BlueWithClamp_BracketedRun_WallMount.png",
        DIR, 22, 57,
        "Asset - Prop Pipe Horizontal BlueWithClamp BracketedRun WallMount");

    /** 22x11px | static */
    public static final SpriteAsset PROP_PIPE_TJUNCTION_DARKNAVY_THREEWAYCONNECTOR_PIPEHUB = SpriteAsset.single(
        "Prop_Pipe_TJunction_DarkNavy_ThreeWayConnector_PipeHub.png",
        DIR, 22, 11,
        "Asset - Prop Pipe TJunction DarkNavy ThreeWayConnector PipeHub");

    /** 103x42px | ~2 frames */
    public static final SpriteAsset PROP_PIPE_VERTICAL_REDMETAL_STRAIGHTSEGMENT_WALLRUN = SpriteAsset.single(
        "Prop_Pipe_Vertical_RedMetal_StraightSegment_WallRun.png",
        DIR, 103, 42,
        "Asset - Prop Pipe Vertical RedMetal StraightSegment WallRun");

    /** 45x11px | ~4 frames */
    public static final SpriteAsset PROP_PIPE_VERTICAL_TALLBLUE_FULLHEIGHTRUN_BACKGROUNDPIPE = SpriteAsset.single(
        "Prop_Pipe_Vertical_TallBlue_FullHeightRun_BackgroundPipe.png",
        DIR, 45, 11,
        "Background - Prop Pipe Vertical TallBlue FullHeightRun BackgroundPipe");

    /** 45x7px | ~6 frames */
    public static final SpriteAsset PROP_PIPE_VERTICAL_THINDARKBLUE_STRIPRUN_WALLDETAIL = SpriteAsset.single(
        "Prop_Pipe_Vertical_ThinDarkBlue_StripRun_WallDetail.png",
        DIR, 45, 7,
        "Asset - Prop Pipe Vertical ThinDarkBlue StripRun WallDetail");

    /** Total number of assets in this group */
    public static final int COUNT = 11;

    private Level2TubeAssets() { } // no instantiation
}
