package assets.objects;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/Industrial_zone_level_1/3 Objects
 * Total assets: 44
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level1ObjectAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/Industrial_zone_level_1/3 Objects/";

    /** 18x26px | static */
    public static final SpriteAsset PROP_BARREL_SMALLDAMAGEDTIPPED_REDWITHSPILL_FLOORHAZARDDECO_DAMAGEDVARIANT = SpriteAsset.single(
        "Prop_Barrel_SmallDamagedTipped_RedWithSpill_FloorHazardDeco_DamagedVariant.png",
        DIR, 18, 26,
        "Prop Barrel SmallDamagedTipped RedWithSpill FloorHazardDeco DamagedVariant");

    /** 18x26px | static */
    public static final SpriteAsset PROP_BARREL_TALLDARKRED_WORNINDUSTRIAL_FLOORDECORORPUSHABLE_TALLVARIANT = SpriteAsset.single(
        "Prop_Barrel_TallDarkRed_WornIndustrial_FloorDecorOrPushable_TallVariant.png",
        DIR, 18, 26,
        "Prop Barrel TallDarkRed WornIndustrial FloorDecorOrPushable TallVariant");

    /** 18x26px | static */
    public static final SpriteAsset PROP_BARREL_UPRIGHTREDMETAL_ALTLABELVARIANT_FLOORDECORORPUSHABLE_VARIANTB = SpriteAsset.single(
        "Prop_Barrel_UprightRedMetal_AltLabelVariant_FloorDecorOrPushable_VariantB.png",
        DIR, 18, 26,
        "Prop Barrel UprightRedMetal AltLabelVariant FloorDecorOrPushable VariantB");

    /** 18x26px | static */
    public static final SpriteAsset PROP_BARREL_UPRIGHTREDMETAL_STANDARDLABEL_FLOORDECORORPUSHABLE_VARIANTA = SpriteAsset.single(
        "Prop_Barrel_UprightRedMetal_StandardLabel_FloorDecorOrPushable_VariantA.png",
        DIR, 18, 26,
        "Prop Barrel UprightRedMetal StandardLabel FloorDecorOrPushable VariantA");

    /** 32x36px | static */
    public static final SpriteAsset PROP_BENCH_BLUEMETAL_FLATTOPWORKBENCH_WALLPLACEDDECO_INDUSTRIALFURNITURE = SpriteAsset.single(
        "Prop_Bench_BlueMetal_FlatTopWorkbench_WallPlacedDeco_IndustrialFurniture.png",
        DIR, 32, 36,
        "Prop Bench BlueMetal FlatTopWorkbench WallPlacedDeco IndustrialFurniture");

    /** 32x32px | static */
    public static final SpriteAsset PROP_BOARD_DOUBLEWOODENNOTICEBOARD_MOREPAPERS_WALLMOUNTEDDECO_VARIANTB = SpriteAsset.single(
        "Prop_Board_DoubleWoodenNoticeBoard_MorePapers_WallMountedDeco_VariantB.png",
        DIR, 32, 32,
        "Prop Board DoubleWoodenNoticeBoard MorePapers WallMountedDeco VariantB");

    /** 32x32px | static */
    public static final SpriteAsset PROP_BOARD_SINGLEWOODENNOTICEBOARD_PAPERSONWALL_WALLMOUNTEDDECO_VARIANTA = SpriteAsset.single(
        "Prop_Board_SingleWoodenNoticeBoard_PapersOnWall_WallMountedDeco_VariantA.png",
        DIR, 32, 32,
        "Prop Board SingleWoodenNoticeBoard PapersOnWall WallMountedDeco VariantA");

    /** 32x32px | static */
    public static final SpriteAsset PROP_BOARD_TWINPANELWOODENBOARDS_SIDEBYSIDE_WALLMOUNTEDDECO_VARIANTC = SpriteAsset.single(
        "Prop_Board_TwinPanelWoodenBoards_SideBySide_WallMountedDeco_VariantC.png",
        DIR, 32, 32,
        "Asset - Prop Board TwinPanelWoodenBoards SideBySide WallMountedDeco VariantC");

    /** 32x32px | static */
    public static final SpriteAsset PROP_BOX_CARDBOARDLIGHT_MEDIUMLIGHTER_FLOORSTACKABLE_CARDBOARDVARIANTD = SpriteAsset.single(
        "Prop_Box_CardboardLight_MediumLighter_FloorStackable_CardboardVariantD.png",
        DIR, 32, 32,
        "Prop Box CardboardLight MediumLighter FloorStackable CardboardVariantD");

    /** 32x32px | static */
    public static final SpriteAsset PROP_BOX_CARDBOARDTAPED_MEDIUMBROWN_FLOORSTACKABLE_CARDBOARDVARIANTC = SpriteAsset.single(
        "Prop_Box_CardboardTaped_MediumBrown_FloorStackable_CardboardVariantC.png",
        DIR, 32, 32,
        "Asset - Prop Box CardboardTaped MediumBrown FloorStackable CardboardVariantC");

    /** 32x32px | static */
    public static final SpriteAsset PROP_BOX_OPENTOPCOLOURED_ITEMSVISIBLE_FLOORDECO_OPENBOXWITHCONTENTS = SpriteAsset.single(
        "Prop_Box_OpenTopColoured_ItemsVisible_FloorDeco_OpenBoxWithContents.png",
        DIR, 32, 32,
        "Asset - Prop Box OpenTopColoured ItemsVisible FloorDeco OpenBoxWithContents");

    /** 32x32px | static */
    public static final SpriteAsset PROP_BOX_SQUASHEDFLAT_BROKENEMPTY_FLOORDEBRISDECO_CRUSHEDBOX = SpriteAsset.single(
        "Prop_Box_SquashedFlat_BrokenEmpty_FloorDebrisDeco_CrushedBox.png",
        DIR, 32, 32,
        "Asset - Prop Box SquashedFlat BrokenEmpty FloorDebrisDeco CrushedBox");

    /** 32x32px | static */
    public static final SpriteAsset PROP_BOX_THINFLATPLANK_NARROWLOW_FLOORDECO_FLATPLANKORLIDPIECE = SpriteAsset.single(
        "Prop_Box_ThinFlatPlank_NarrowLow_FloorDeco_FlatPlankOrLidPiece.png",
        DIR, 32, 32,
        "Asset - Prop Box ThinFlatPlank NarrowLow FloorDeco FlatPlankOrLidPiece");

    /** 32x36px | static */
    public static final SpriteAsset PROP_BUCKET_SMALLBLUEWITHHANDLE_FLOORCLUTTER_AMBIENTDECO_JANITORIALPROP = SpriteAsset.single(
        "Prop_Bucket_SmallBlueWithHandle_FloorClutter_AmbientDeco_JanitorialProp.png",
        DIR, 32, 36,
        "Prop Bucket SmallBlueWithHandle FloorClutter AmbientDeco JanitorialProp");

    /** 32x32px | static */
    public static final SpriteAsset PROP_CRATE_DARKWOODSEALED_SMALLSQUARE_FLOORSTACKABLE_STANDARDCRATEA = SpriteAsset.single(
        "Prop_Crate_DarkWoodSealed_SmallSquare_FloorStackable_StandardCrateA.png",
        DIR, 32, 32,
        "Asset - Prop Crate DarkWoodSealed SmallSquare FloorStackable StandardCrateA");

    /** 32x32px | static */
    public static final SpriteAsset PROP_CRATE_LIGHTWOODPANELLED_MEDIUMSQUARE_FLOORSTACKABLE_LIGHTWOODVARIANTB = SpriteAsset.single(
        "Prop_Crate_LightWoodPanelled_MediumSquare_FloorStackable_LightWoodVariantB.png",
        DIR, 32, 32,
        "Prop Crate LightWoodPanelled MediumSquare FloorStackable LightWoodVariantB");

    /** 32x32px | static */
    public static final SpriteAsset PROP_CRATE_REDLOCKEDCLASP_SECUREDCONTAINER_INTERACTIVEORDECO_LOCKEDCRATE = SpriteAsset.single(
        "Prop_Crate_RedLockedClasp_SecuredContainer_InteractiveOrDeco_LockedCrate.png",
        DIR, 32, 32,
        "Prop Crate RedLockedClasp SecuredContainer InteractiveOrDeco LockedCrate");

    /** 32x32px | static */
    public static final SpriteAsset PROP_DESK_WOODENWORKSTATION_DRAWERSANDSURFACE_FLOORPLACEDDECO_WORKSTATIONDESK = SpriteAsset.single(
        "Prop_Desk_WoodenWorkstation_DrawersAndSurface_FloorPlacedDeco_WorkstationDesk.png",
        DIR, 32, 32,
        "Prop Desk WoodenWorkstation DrawersAndSurface FloorPlacedDeco WorkstationDesk");

    /** 32x32px | static */
    public static final SpriteAsset PROP_FENCE_SINGLELARGEFRAME_GATESHAPE_ZONEENTRANCEDECO_FENCEGATEFRAME = SpriteAsset.single(
        "Prop_Fence_SingleLargeFrame_GateShape_ZoneEntranceDeco_FenceGateFrame.png",
        DIR, 32, 32,
        "Prop Fence SingleLargeFrame GateShape ZoneEntranceDeco FenceGateFrame");

    /** 32x32px | static */
    public static final SpriteAsset PROP_FENCE_THREEREDPOSTSWIRE_WIDERSEGMENT_ZONEDIVIDERDECO_FENCESEGMENTB = SpriteAsset.single(
        "Prop_Fence_ThreeRedPostsWire_WiderSegment_ZoneDividerDeco_FenceSegmentB.png",
        DIR, 32, 32,
        "Prop Fence ThreeRedPostsWire WiderSegment ZoneDividerDeco FenceSegmentB");

    /** 32x32px | static */
    public static final SpriteAsset PROP_FENCE_TWOREDPOSTSWIRE_SHORTSEGMENT_ZONEDIVIDERDECO_FENCESEGMENTA = SpriteAsset.single(
        "Prop_Fence_TwoRedPostsWire_ShortSegment_ZoneDividerDeco_FenceSegmentA.png",
        DIR, 32, 32,
        "Prop Fence TwoRedPostsWire ShortSegment ZoneDividerDeco FenceSegmentA");

    /** 32x36px | static */
    public static final SpriteAsset PROP_FIREEXTINGUISHER_ACTIVESPRAYINGFLAME_INUSEDECO_SAFETYPROPACTIVE = SpriteAsset.single(
        "Prop_FireExtinguisher_ActiveSprayingFlame_InUseDeco_SafetyPropActive.png",
        DIR, 32, 36,
        "UI Element - Prop FireExtinguisher ActiveSprayingFlame InUseDeco SafetyPropActive");

    /** 32x36px | static */
    public static final SpriteAsset PROP_FIREEXTINGUISHER_SMALLKNOCKEDOVER_FLOORDEBRIS_SAFETYPROPDAMAGED = SpriteAsset.single(
        "Prop_FireExtinguisher_SmallKnockedOver_FloorDebris_SafetyPropDamaged.png",
        DIR, 32, 36,
        "UI Element - Prop FireExtinguisher SmallKnockedOver FloorDebris SafetyPropDamaged");

    /** 32x36px | static */
    public static final SpriteAsset PROP_FIREEXTINGUISHER_STANDARDUPRIGHTRED_WALLMOUNTEDDECO_SAFETYPROPA = SpriteAsset.single(
        "Prop_FireExtinguisher_StandardUprightRed_WallMountedDeco_SafetyPropA.png",
        DIR, 32, 36,
        "UI Element - Prop FireExtinguisher StandardUprightRed WallMountedDeco SafetyPropA");

    /** 32x64px | static */
    public static final SpriteAsset PROP_FLAG_TALLREDBANNERPOLE_GOLDEMBLEM_CHECKPOINTORBOSSGATELANDMARK = SpriteAsset.single(
        "Prop_Flag_TallRedBannerPole_GoldEmblem_CheckpointOrBossGateLandmark.png",
        DIR, 32, 64,
        "Asset - Prop Flag TallRedBannerPole GoldEmblem CheckpointOrBossGateLandmark");

    /** 32x32px | static */
    public static final SpriteAsset PROP_LADDER_SHORTHORIZONTALRUNG_BLUECROSSBAR_PLATFORMCONNECTOR_SHORT = SpriteAsset.single(
        "Prop_Ladder_ShortHorizontalRung_BlueCrossbar_PlatformConnector_Short.png",
        DIR, 32, 32,
        "Tile - Prop Ladder ShortHorizontalRung BlueCrossbar PlatformConnector Short");

    /** 32x32px | static */
    public static final SpriteAsset PROP_LADDER_TALLALTSPACING_BLUEGREYRUNGS_SHAFTWALLCLIMB_CLIMBABLEB = SpriteAsset.single(
        "Prop_Ladder_TallAltSpacing_BlueGreyRungs_ShaftWallClimb_ClimbableB.png",
        DIR, 32, 32,
        "Asset - Prop Ladder TallAltSpacing BlueGreyRungs ShaftWallClimb ClimbableB");

    /** 32x32px | static */
    public static final SpriteAsset PROP_LADDER_TALLFULLHEIGHT_BLUEGREYRUNGS_SHAFTWALLCLIMB_CLIMBABLEA = SpriteAsset.single(
        "Prop_Ladder_TallFullHeight_BlueGreyRungs_ShaftWallClimb_ClimbableA.png",
        DIR, 32, 32,
        "Asset - Prop Ladder TallFullHeight BlueGreyRungs ShaftWallClimb ClimbableA");

    /** 32x36px | static */
    public static final SpriteAsset PROP_LOCKER_BLUEDOUBLEDOOR_TALLMETAL_WALLPLACEDDECO_INDUSTRIALLOCKERBLUE = SpriteAsset.single(
        "Prop_Locker_BlueDoubleDoor_TallMetal_WallPlacedDeco_IndustrialLockerBlue.png",
        DIR, 32, 36,
        "Prop Locker BlueDoubleDoor TallMetal WallPlacedDeco IndustrialLockerBlue");

    /** 32x32px | static */
    public static final SpriteAsset PROP_LOCKER_REDDOUBLEDOOR_TALLMETAL_WALLPLACEDDECO_INDUSTRIALLOCKERA = SpriteAsset.single(
        "Prop_Locker_RedDoubleDoor_TallMetal_WallPlacedDeco_IndustrialLockerA.png",
        DIR, 32, 32,
        "Asset - Prop Locker RedDoubleDoor TallMetal WallPlacedDeco IndustrialLockerA");

    /** 32x32px | static */
    public static final SpriteAsset PROP_LOCKER_REDSINGLEOPENDOOR_TALLMETAL_WALLPLACEDDECO_INDUSTRIALLOCKEROPEN = SpriteAsset.single(
        "Prop_Locker_RedSingleOpenDoor_TallMetal_WallPlacedDeco_IndustrialLockerOpen.png",
        DIR, 32, 32,
        "Prop Locker RedSingleOpenDoor TallMetal WallPlacedDeco IndustrialLockerOpen");

    /** 32x36px | static */
    public static final SpriteAsset PROP_MOP_WOODENHANDLEBROWNHEAD_FLOORLEANINGDECO_JANITORIALAMBIENTPROP = SpriteAsset.single(
        "Prop_Mop_WoodenHandleBrownHead_FloorLeaningDeco_JanitorialAmbientProp.png",
        DIR, 32, 36,
        "Prop Mop WoodenHandleBrownHead FloorLeaningDeco JanitorialAmbientProp");

    /** 32x32px | static */
    public static final SpriteAsset PROP_SIGN_REDLOLLIPOPQUESTIONMARK_HINTORMYSTERY_FLOORPOLESIGN_DIRECTIONALB = SpriteAsset.single(
        "Prop_Sign_RedLollipopQuestionMark_HintOrMystery_FloorPoleSign_DirectionalB.png",
        DIR, 32, 32,
        "Prop Sign RedLollipopQuestionMark HintOrMystery FloorPoleSign DirectionalB");

    /** 32x32px | static */
    public static final SpriteAsset PROP_SIGN_REDWARNINGTRIANGLE_HAZARDAHEADWARNING_FLOORPOLESIGN_DIRECTIONALA = SpriteAsset.single(
        "Prop_Sign_RedWarningTriangle_HazardAheadWarning_FloorPoleSign_DirectionalA.png",
        DIR, 32, 32,
        "Prop Sign RedWarningTriangle HazardAheadWarning FloorPoleSign DirectionalA");

    /** 32x36px | static */
    public static final SpriteAsset UI_DIGIT_EIGHT_GREYPIXELFONT_HUDSCOREDISPLAY_SINGLEGLYPH = SpriteAsset.single(
        "UI_Digit_Eight_GreyPixelFont_HUDScoreDisplay_SingleGlyph.png",
        DIR, 32, 36,
        "UI Element - UI Digit Eight GreyPixelFont HUDScoreDisplay SingleGlyph");

    /** 32x36px | static */
    public static final SpriteAsset UI_DIGIT_FIVE_GREYPIXELFONT_HUDSCOREDISPLAY_SINGLEGLYPH = SpriteAsset.single(
        "UI_Digit_Five_GreyPixelFont_HUDScoreDisplay_SingleGlyph.png",
        DIR, 32, 36,
        "UI Element - UI Digit Five GreyPixelFont HUDScoreDisplay SingleGlyph");

    /** 32x36px | static */
    public static final SpriteAsset UI_DIGIT_FOUR_GREYPIXELFONT_HUDSCOREDISPLAY_SINGLEGLYPH = SpriteAsset.single(
        "UI_Digit_Four_GreyPixelFont_HUDScoreDisplay_SingleGlyph.png",
        DIR, 32, 36,
        "UI Element - UI Digit Four GreyPixelFont HUDScoreDisplay SingleGlyph");

    /** 32x36px | static */
    public static final SpriteAsset UI_DIGIT_NINE_GREYPIXELFONT_HUDSCOREDISPLAY_SINGLEGLYPH = SpriteAsset.single(
        "UI_Digit_Nine_GreyPixelFont_HUDScoreDisplay_SingleGlyph.png",
        DIR, 32, 36,
        "UI Element - UI Digit Nine GreyPixelFont HUDScoreDisplay SingleGlyph");

    /** 32x36px | static */
    public static final SpriteAsset UI_DIGIT_ONE_GREYPIXELFONT_HUDSCOREDISPLAY_SINGLEGLYPH = SpriteAsset.single(
        "UI_Digit_One_GreyPixelFont_HUDScoreDisplay_SingleGlyph.png",
        DIR, 32, 36,
        "UI Element - UI Digit One GreyPixelFont HUDScoreDisplay SingleGlyph");

    /** 32x36px | static */
    public static final SpriteAsset UI_DIGIT_SEVEN_GREYPIXELFONT_HUDSCOREDISPLAY_SINGLEGLYPH = SpriteAsset.single(
        "UI_Digit_Seven_GreyPixelFont_HUDScoreDisplay_SingleGlyph.png",
        DIR, 32, 36,
        "UI Element - UI Digit Seven GreyPixelFont HUDScoreDisplay SingleGlyph");

    /** 32x36px | static */
    public static final SpriteAsset UI_DIGIT_SIX_GREYPIXELFONT_HUDSCOREDISPLAY_SINGLEGLYPH = SpriteAsset.single(
        "UI_Digit_Six_GreyPixelFont_HUDScoreDisplay_SingleGlyph.png",
        DIR, 32, 36,
        "UI Element - UI Digit Six GreyPixelFont HUDScoreDisplay SingleGlyph");

    /** 32x36px | static */
    public static final SpriteAsset UI_DIGIT_THREE_GREYPIXELFONT_HUDSCOREDISPLAY_SINGLEGLYPH = SpriteAsset.single(
        "UI_Digit_Three_GreyPixelFont_HUDScoreDisplay_SingleGlyph.png",
        DIR, 32, 36,
        "UI Element - UI Digit Three GreyPixelFont HUDScoreDisplay SingleGlyph");

    /** 32x36px | static */
    public static final SpriteAsset UI_DIGIT_TWO_GREYPIXELFONT_HUDSCOREDISPLAY_SINGLEGLYPH = SpriteAsset.single(
        "UI_Digit_Two_GreyPixelFont_HUDScoreDisplay_SingleGlyph.png",
        DIR, 32, 36,
        "UI Element - UI Digit Two GreyPixelFont HUDScoreDisplay SingleGlyph");

    /** 32x36px | static */
    public static final SpriteAsset UI_DIGIT_ZERO_GREYPIXELFONT_HUDSCOREDISPLAY_SINGLEGLYPH = SpriteAsset.single(
        "UI_Digit_Zero_GreyPixelFont_HUDScoreDisplay_SingleGlyph.png",
        DIR, 32, 36,
        "UI Element - UI Digit Zero GreyPixelFont HUDScoreDisplay SingleGlyph");

    /** Total number of assets in this group */
    public static final int COUNT = 44;

    private Level1ObjectAssets() { } // no instantiation
}
