package assets.objects;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/power-station-level-2/3 Objects/2 Decoration
 * Total assets: 27
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level2DecorationAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/power-station-level-2/3 Objects/2 Decoration/";

    /** 35x6px | ~5 frames */
    public static final SpriteAsset PROP_ANTENNA_SMALLBRACKET_HORIZONTALMOUNT_ROOFTOPAERIALB = SpriteAsset.single(
        "Prop_Antenna_SmallBracket_HorizontalMount_RooftopAerialB.png",
        DIR, 35, 6,
        "Asset - Prop Antenna SmallBracket HorizontalMount RooftopAerialB");

    /** 7x22px | static */
    public static final SpriteAsset PROP_ANTENNA_TALLPOLE_THINVERTICAL_ROOFTOPAERIALA = SpriteAsset.single(
        "Prop_Antenna_TallPole_ThinVertical_RooftopAerialA.png",
        DIR, 7, 22,
        "Asset - Prop Antenna TallPole ThinVertical RooftopAerialA");

    /** 68x48px | ~1 frames */
    public static final SpriteAsset PROP_BUILDING_FACTORYSTRUCTUREA_LARGEBACKDROP_SCENERYA = SpriteAsset.single(
        "Prop_Building_FactoryStructureA_LargeBackdrop_SceneryA.png",
        DIR, 68, 48,
        "UI Element - Prop Building FactoryStructureA LargeBackdrop SceneryA");

    /** 78x35px | ~2 frames */
    public static final SpriteAsset PROP_BUILDING_FACTORYSTRUCTUREB_LARGEBACKDROP_SCENERYB = SpriteAsset.single(
        "Prop_Building_FactoryStructureB_LargeBackdrop_SceneryB.png",
        DIR, 78, 35,
        "UI Element - Prop Building FactoryStructureB LargeBackdrop SceneryB");

    /** 5x3px | static */
    public static final SpriteAsset PROP_DECO_RIVET_TINYDOTVARIANT_BOLTDETAIL_WALLRIVETB = SpriteAsset.single(
        "Prop_Deco_Rivet_TinyDotVariant_BoltDetail_WallRivetB.png",
        DIR, 5, 3,
        "Asset - Prop Deco Rivet TinyDotVariant BoltDetail WallRivetB");

    /** 5x6px | static */
    public static final SpriteAsset PROP_DECO_RIVET_TINYDOT_BOLTDETAIL_WALLRIVETA = SpriteAsset.single(
        "Prop_Deco_Rivet_TinyDot_BoltDetail_WallRivetA.png",
        DIR, 5, 6,
        "Asset - Prop Deco Rivet TinyDot BoltDetail WallRivetA");

    /** 32x6px | static */
    public static final SpriteAsset PROP_DECO_SHELF_COLOUREDRACK_SMALLSHELFUNIT_WALLMOUNTA = SpriteAsset.single(
        "Prop_Deco_Shelf_ColouredRack_SmallShelfUnit_WallMountA.png",
        DIR, 32, 6,
        "Asset - Prop Deco Shelf ColouredRack SmallShelfUnit WallMountA");

    /** 11x16px | static */
    public static final SpriteAsset PROP_DECO_SMALLDEVICE_COLOURED_MISCEQUIPMENT_FLOORDECO = SpriteAsset.single(
        "Prop_Deco_SmallDevice_Coloured_MiscEquipment_FloorDeco.png",
        DIR, 11, 16,
        "UI Element - Prop Deco SmallDevice Coloured MiscEquipment FloorDeco");

    /** 32x8px | static */
    public static final SpriteAsset PROP_DECO_SMALLITEM_ACCESSORY_MISCDETAIL_FLOORORWALL = SpriteAsset.single(
        "Prop_Deco_SmallItem_Accessory_MiscDetail_FloorOrWall.png",
        DIR, 32, 8,
        "Asset - Prop Deco SmallItem Accessory MiscDetail FloorOrWall");

    /** 13x17px | static */
    public static final SpriteAsset PROP_DECO_TABLET_SMALLBLUE_TECHDEVICE_WALLORFLOOR = SpriteAsset.single(
        "Prop_Deco_Tablet_SmallBlue_TechDevice_WallOrFloor.png",
        DIR, 13, 17,
        "Asset - Prop Deco Tablet SmallBlue TechDevice WallOrFloor");

    /** 17x3px | static */
    public static final SpriteAsset PROP_DECO_WAVEARCH_DARKBLUE_ARCHSHAPE_CEILINGDECO = SpriteAsset.single(
        "Prop_Deco_WaveArch_DarkBlue_ArchShape_CeilingDeco.png",
        DIR, 17, 3,
        "Asset - Prop Deco WaveArch DarkBlue ArchShape CeilingDeco");

    /** 32x17px | static */
    public static final SpriteAsset PROP_DECO_WIRESEGMENT_TINYHORIZONTAL_CABLEDETAIL_WALLA = SpriteAsset.single(
        "Prop_Deco_WireSegment_TinyHorizontal_CableDetail_WallA.png",
        DIR, 32, 17,
        "Asset - Prop Deco WireSegment TinyHorizontal CableDetail WallA");

    /** 32x14px | static */
    public static final SpriteAsset PROP_DECO_WIRESEGMENT_TINYVARIANT_CABLEDETAILB_WALLB = SpriteAsset.single(
        "Prop_Deco_WireSegment_TinyVariant_CableDetailB_WallB.png",
        DIR, 32, 14,
        "Asset - Prop Deco WireSegment TinyVariant CableDetailB WallB");

    /** 35x19px | ~1 frames */
    public static final SpriteAsset PROP_FURNITURE_FILINGCABINET_GREEN_OFFICESTORAGE_FLOORPROP = SpriteAsset.single(
        "Prop_Furniture_FilingCabinet_Green_OfficeStorage_FloorProp.png",
        DIR, 35, 19,
        "Prop Furniture FilingCabinet Green OfficeStorage FloorProp");

    /** 19x24px | static */
    public static final SpriteAsset PROP_FURNITURE_OFFICECHAIR_BLUESEAT_BREAKROOMPROP = SpriteAsset.single(
        "Prop_Furniture_OfficeChair_BlueSeat_BreakRoomProp.png",
        DIR, 19, 24,
        "Asset - Prop Furniture OfficeChair BlueSeat BreakRoomProp");

    /** 65x16px | ~4 frames */
    public static final SpriteAsset PROP_FURNITURE_SHELF_METALNARROW_INDUSTRIALRACKA = SpriteAsset.single(
        "Prop_Furniture_Shelf_MetalNarrow_IndustrialRackA.png",
        DIR, 65, 16,
        "Asset - Prop Furniture Shelf MetalNarrow IndustrialRackA");

    /** 49x16px | ~3 frames */
    public static final SpriteAsset PROP_FURNITURE_SHELF_METALWIDE_INDUSTRIALRACKB = SpriteAsset.single(
        "Prop_Furniture_Shelf_MetalWide_IndustrialRackB.png",
        DIR, 49, 16,
        "Asset - Prop Furniture Shelf MetalWide IndustrialRackB");

    /** 57x26px | ~2 frames */
    public static final SpriteAsset PROP_SCREEN_CONTROLPANEL_LARGEMULTISCREEN_COLOURFULCONSOLE = SpriteAsset.single(
        "Prop_Screen_ControlPanel_LargeMultiScreen_ColourfulConsole.png",
        DIR, 57, 26,
        "Prop Screen ControlPanel LargeMultiScreen ColourfulConsole");

    /** 57x26px | ~2 frames */
    public static final SpriteAsset PROP_SCREEN_CONTROLPANEL_LARGEPINKHIGHLIGHT_ALTCONSOLE = SpriteAsset.single(
        "Prop_Screen_ControlPanel_LargePinkHighlight_AltConsole.png",
        DIR, 57, 26,
        "Asset - Prop Screen ControlPanel LargePinkHighlight AltConsole");

    /** 57x26px | ~2 frames */
    public static final SpriteAsset PROP_SCREEN_MONITORDETAIL_TECHPANEL_WALLSCREENC = SpriteAsset.single(
        "Prop_Screen_MonitorDetail_TechPanel_WallScreenC.png",
        DIR, 57, 26,
        "Asset - Prop Screen MonitorDetail TechPanel WallScreenC");

    /** 57x26px | ~2 frames */
    public static final SpriteAsset PROP_SCREEN_MONITORDOUBLE_TECHPANEL_WALLSCREENB = SpriteAsset.single(
        "Prop_Screen_MonitorDouble_TechPanel_WallScreenB.png",
        DIR, 57, 26,
        "Asset - Prop Screen MonitorDouble TechPanel WallScreenB");

    /** 26x18px | static */
    public static final SpriteAsset PROP_SCREEN_MONITORSINGLE_TECHPANEL_WALLSCREENA = SpriteAsset.single(
        "Prop_Screen_MonitorSingle_TechPanel_WallScreenA.png",
        DIR, 26, 18,
        "Asset - Prop Screen MonitorSingle TechPanel WallScreenA");

    /** 13x22px | static */
    public static final SpriteAsset PROP_SIGN_WARNING_YELLOWSMALL_HAZARDNOTICEC = SpriteAsset.single(
        "Prop_Sign_Warning_YellowSmall_HazardNoticeC.png",
        DIR, 13, 22,
        "Asset - Prop Sign Warning YellowSmall HazardNoticeC");

    /** 32x22px | static */
    public static final SpriteAsset PROP_SIGN_WARNING_YELLOWTYPEA_HAZARDNOTICEA = SpriteAsset.single(
        "Prop_Sign_Warning_YellowTypeA_HazardNoticeA.png",
        DIR, 32, 22,
        "Asset - Prop Sign Warning YellowTypeA HazardNoticeA");

    /** 24x22px | static */
    public static final SpriteAsset PROP_SIGN_WARNING_YELLOWTYPEB_HAZARDNOTICEB = SpriteAsset.single(
        "Prop_Sign_Warning_YellowTypeB_HazardNoticeB.png",
        DIR, 24, 22,
        "Asset - Prop Sign Warning YellowTypeB HazardNoticeB");

    /** 68x76px | static */
    public static final SpriteAsset PROP_TANK_INDUSTRIAL_LABELLEDAC3_LARGETANKA = SpriteAsset.single(
        "Prop_Tank_Industrial_LabelledAC3_LargeTankA.png",
        DIR, 68, 76,
        "Asset - Prop Tank Industrial LabelledAC3 LargeTankA");

    /** 68x77px | static */
    public static final SpriteAsset PROP_TANK_INDUSTRIAL_LABELLEDEFG2_LARGETANKB = SpriteAsset.single(
        "Prop_Tank_Industrial_LabelledEFG2_LargeTankB.png",
        DIR, 68, 77,
        "Asset - Prop Tank Industrial LabelledEFG2 LargeTankB");

    /** Total number of assets in this group */
    public static final int COUNT = 27;

    private Level2DecorationAssets() { } // no instantiation
}
