package assets.objects;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/power-station-level-2/3 Objects/3 Power lines
 * Total assets: 9
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level2PowerLineAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/power-station-level-2/3 Objects/3 Power lines/";

    /** 63x39px | ~1 frames */
    public static final SpriteAsset PROP_PYLON_BASEONLY_SHORTSTUBBY_BLUEMETAL_PYLONFEETSECTION = SpriteAsset.single(
        "Prop_Pylon_BaseOnly_ShortStubby_BlueMetal_PylonFeetSection.png",
        DIR, 63, 39,
        "Prop Pylon BaseOnly ShortStubby BlueMetal PylonFeetSection");

    /** 16x7px | static */
    public static final SpriteAsset PROP_PYLON_BASEONLY_VARIANTB_BLUEMETAL_PYLONFEETALT = SpriteAsset.single(
        "Prop_Pylon_BaseOnly_VariantB_BlueMetal_PylonFeetAlt.png",
        DIR, 16, 7,
        "Asset - Prop Pylon BaseOnly VariantB BlueMetal PylonFeetAlt");

    /** 69x192px | static */
    public static final SpriteAsset PROP_PYLON_FULLTALL_ALTTOPVARIANT_BLUEMETAL_PYLONFULLB = SpriteAsset.single(
        "Prop_Pylon_FullTall_AltTopVariant_BlueMetal_PylonFullB.png",
        DIR, 69, 192,
        "Asset - Prop Pylon FullTall AltTopVariant BlueMetal PylonFullB");

    /** 61x192px | static */
    public static final SpriteAsset PROP_PYLON_FULLTALL_WITHANTENNATOP_BLUEMETAL_PYLONFULLA = SpriteAsset.single(
        "Prop_Pylon_FullTall_WithAntennaTop_BlueMetal_PylonFullA.png",
        DIR, 61, 192,
        "Asset - Prop Pylon FullTall WithAntennaTop BlueMetal PylonFullA");

    /** 73x64px | ~1 frames */
    public static final SpriteAsset PROP_PYLON_LOWERHALF_MEDIUMHEIGHT_BLUEMETAL_PYLONBODYA = SpriteAsset.single(
        "Prop_Pylon_LowerHalf_MediumHeight_BlueMetal_PylonBodyA.png",
        DIR, 73, 64,
        "Asset - Prop Pylon LowerHalf MediumHeight BlueMetal PylonBodyA");

    /** 16x5px | static */
    public static final SpriteAsset PROP_PYLON_LOWERHALF_VARIANTB_BLUEMETAL_PYLONBODYB = SpriteAsset.single(
        "Prop_Pylon_LowerHalf_VariantB_BlueMetal_PylonBodyB.png",
        DIR, 16, 5,
        "Asset - Prop Pylon LowerHalf VariantB BlueMetal PylonBodyB");

    /** 16x4px | static */
    public static final SpriteAsset PROP_PYLON_MIDSECTION_VARIANTB_BLUEMETAL_PYLONMIDBODY = SpriteAsset.single(
        "Prop_Pylon_MidSection_VariantB_BlueMetal_PylonMidBody.png",
        DIR, 16, 4,
        "Asset - Prop Pylon MidSection VariantB BlueMetal PylonMidBody");

    /** 16x11px | static */
    public static final SpriteAsset PROP_WIRE_DIAGONALCABLE_THINALTANGLE_POWERLINESEGMENTB = SpriteAsset.single(
        "Prop_Wire_DiagonalCable_ThinAltAngle_PowerLineSegmentB.png",
        DIR, 16, 11,
        "Asset - Prop Wire DiagonalCable ThinAltAngle PowerLineSegmentB");

    /** 13x13px | static */
    public static final SpriteAsset PROP_WIRE_DIAGONALCABLE_THINSINGLE_POWERLINESEGMENTA = SpriteAsset.single(
        "Prop_Wire_DiagonalCable_ThinSingle_PowerLineSegmentA.png",
        DIR, 13, 13,
        "Asset - Prop Wire DiagonalCable ThinSingle PowerLineSegmentA");

    /** Total number of assets in this group */
    public static final int COUNT = 9;

    private Level2PowerLineAssets() { } // no instantiation
}
