package enums;

/**
 * Audio Assets
 * Auto-generated from assets-manifest.json
 * Total: 70 assets
 * Date: 2026-04-14
 */
public enum AudioAssets {

    ASSET___ALTERNATIVE_THEME_CHINESE_STREET("Resources/industrial-zone/audio/music_wav/._Alternative_theme_Chinese_Street.wav"),
    ASSET___BATTLE_THEME_CHINESE_STREET("Resources/industrial-zone/audio/music_wav/._Battle_theme_Chinese_Street.wav"),
    ASSET___BELL_ON_THE_DOOR("Resources/industrial-zone/audio/music_wav/._Bell_on_the_door.wav"),
    ASSET___BOMB_DROP("Resources/industrial-zone/audio/music_wav/._Bomb_drop.wav"),
    ASSET___CALM_THEME_CHINESE_STREET("Resources/industrial-zone/audio/music_wav/._Calm_theme_Chinese_Street.wav"),
    ASSET___CLICK_DIGITAL_1("Resources/industrial-zone/audio/music_wav/._Click_digital_1.wav"),
    ASSET___CLICK_DIGITAL_2("Resources/industrial-zone/audio/music_wav/._Click_digital_2.wav"),
    ASSET___CREAKING_WOODEN_DOOR("Resources/industrial-zone/audio/music_wav/._Creaking_wooden_door.wav"),
    ASSET___DOOR_WITH_PASSWORD("Resources/industrial-zone/audio/music_wav/._Door_with_password.wav"),
    ASSET___ELEVATOR_MOTOR("Resources/industrial-zone/audio/music_wav/._Elevator_motor.wav"),
    ASSET___EXPLOSION("Resources/industrial-zone/audio/music_wav/._Explosion.wav"),
    ASSET___FLYING_PLATFORM_ATTAK_1("Resources/industrial-zone/audio/music_wav/._Flying_platform_attak_1.wav"),
    ASSET___FLYING_PLATFORM_ATTAK_2("Resources/industrial-zone/audio/music_wav/._Flying_platform_attak_2.wav"),
    ASSET___HOVERING_ROBOT_STING("Resources/industrial-zone/audio/music_wav/._Hovering_robot_sting.wav"),
    ASSET___HOVERING_ROBOT_WALK_LOOPABLE("Resources/industrial-zone/audio/music_wav/._Hovering_robot_walk_loopable.wav"),
    ASSET___KARATEKA_ATTACK("Resources/industrial-zone/audio/music_wav/._Karateka_attack.wav"),
    ASSET___LASER_SWORD_1("Resources/industrial-zone/audio/music_wav/._Laser_sword_1.wav"),
    ASSET___LASER_SWORD_2("Resources/industrial-zone/audio/music_wav/._Laser_sword_2.wav"),
    ASSET___LIFT_MECHANISM("Resources/industrial-zone/audio/music_wav/._Lift_mechanism.wav"),
    ASSET___MAIN_THEME_CHINESE_STREET("Resources/industrial-zone/audio/music_wav/._Main_theme_Chinese_Street.wav"),
    ASSET___MELODY_OF_ATTRACTION_LOOPABLE("Resources/industrial-zone/audio/music_wav/._Melody_of_attraction_loopable.wav"),
    ASSET___MELODY_OF_THE_WIN("Resources/industrial-zone/audio/music_wav/._Melody_of_the_win.wav"),
    ASSET___PORTAL_1("Resources/industrial-zone/audio/music_wav/._Portal_1.wav"),
    ASSET___PORTAL_2("Resources/industrial-zone/audio/music_wav/._Portal_2.wav"),
    ASSET___PORTAL_CLOSING("Resources/industrial-zone/audio/music_wav/._Portal_closing.wav"),
    ASSET___PORTAL_MOVING("Resources/industrial-zone/audio/music_wav/._Portal_moving.wav"),
    ASSET___PUSH_SLIDE_DOOR("Resources/industrial-zone/audio/music_wav/._Push_slide_door.wav"),
    ASSET___ROLLER_DOORS("Resources/industrial-zone/audio/music_wav/._Roller_doors.wav"),
    ASSET___SAMURAI_DEATH("Resources/industrial-zone/audio/music_wav/._Samurai_death.wav"),
    ASSET___SAMURAI_FOOTSTEP_1("Resources/industrial-zone/audio/music_wav/._Samurai_footstep_1.wav"),
    ASSET___SAMURAI_FOOTSTEP_2("Resources/industrial-zone/audio/music_wav/._Samurai_footstep_2.wav"),
    ASSET___SLIDING_DOORS("Resources/industrial-zone/audio/music_wav/._Sliding_doors.wav"),
    ASSET___STEALTHY_THEME_LOOPABLE("Resources/industrial-zone/audio/music_wav/._Stealthy_theme_loopable.wav"),
    ASSET___UNLOCKED_CHEST("Resources/industrial-zone/audio/music_wav/._Unlocked_chest.wav"),
    ASSET___ZIPLINE_LOOPABLE("Resources/industrial-zone/audio/music_wav/._Zipline_loopable.wav"),
    ASSET___ALTERNATIVE_THEME_CHINESE_STREET("Resources/industrial-zone/audio/sfx/._Alternative_theme_Chinese_Street.wav"),
    ASSET___BATTLE_THEME_CHINESE_STREET("Resources/industrial-zone/audio/sfx/._Battle_theme_Chinese_Street.wav"),
    ASSET___BELL_ON_THE_DOOR("Resources/industrial-zone/audio/sfx/._Bell_on_the_door.wav"),
    ASSET___BOMB_DROP("Resources/industrial-zone/audio/sfx/._Bomb_drop.wav"),
    ASSET___CALM_THEME_CHINESE_STREET("Resources/industrial-zone/audio/sfx/._Calm_theme_Chinese_Street.wav"),
    ASSET___CLICK_DIGITAL_1("Resources/industrial-zone/audio/sfx/._Click_digital_1.wav"),
    ASSET___CLICK_DIGITAL_2("Resources/industrial-zone/audio/sfx/._Click_digital_2.wav"),
    ASSET___CREAKING_WOODEN_DOOR("Resources/industrial-zone/audio/sfx/._Creaking_wooden_door.wav"),
    ASSET___DOOR_WITH_PASSWORD("Resources/industrial-zone/audio/sfx/._Door_with_password.wav"),
    ASSET___ELEVATOR_MOTOR("Resources/industrial-zone/audio/sfx/._Elevator_motor.wav"),
    ASSET___EXPLOSION("Resources/industrial-zone/audio/sfx/._Explosion.wav"),
    ASSET___FLYING_PLATFORM_ATTAK_1("Resources/industrial-zone/audio/sfx/._Flying_platform_attak_1.wav"),
    ASSET___FLYING_PLATFORM_ATTAK_2("Resources/industrial-zone/audio/sfx/._Flying_platform_attak_2.wav"),
    ASSET___HOVERING_ROBOT_STING("Resources/industrial-zone/audio/sfx/._Hovering_robot_sting.wav"),
    ASSET___HOVERING_ROBOT_WALK_LOOPABLE("Resources/industrial-zone/audio/sfx/._Hovering_robot_walk_loopable.wav"),
    ASSET___KARATEKA_ATTACK("Resources/industrial-zone/audio/sfx/._Karateka_attack.wav"),
    ASSET___LASER_SWORD_1("Resources/industrial-zone/audio/sfx/._Laser_sword_1.wav"),
    ASSET___LASER_SWORD_2("Resources/industrial-zone/audio/sfx/._Laser_sword_2.wav"),
    ASSET___LIFT_MECHANISM("Resources/industrial-zone/audio/sfx/._Lift_mechanism.wav"),
    ASSET___MAIN_THEME_CHINESE_STREET("Resources/industrial-zone/audio/sfx/._Main_theme_Chinese_Street.wav"),
    ASSET___MELODY_OF_ATTRACTION_LOOPABLE("Resources/industrial-zone/audio/sfx/._Melody_of_attraction_loopable.wav"),
    ASSET___MELODY_OF_THE_WIN("Resources/industrial-zone/audio/sfx/._Melody_of_the_win.wav"),
    ASSET___PORTAL_1("Resources/industrial-zone/audio/sfx/._Portal_1.wav"),
    ASSET___PORTAL_2("Resources/industrial-zone/audio/sfx/._Portal_2.wav"),
    ASSET___PORTAL_CLOSING("Resources/industrial-zone/audio/sfx/._Portal_closing.wav"),
    ASSET___PORTAL_MOVING("Resources/industrial-zone/audio/sfx/._Portal_moving.wav"),
    ASSET___PUSH_SLIDE_DOOR("Resources/industrial-zone/audio/sfx/._Push_slide_door.wav"),
    ASSET___ROLLER_DOORS("Resources/industrial-zone/audio/sfx/._Roller_doors.wav"),
    ASSET___SAMURAI_DEATH("Resources/industrial-zone/audio/sfx/._Samurai_death.wav"),
    ASSET___SAMURAI_FOOTSTEP_1("Resources/industrial-zone/audio/sfx/._Samurai_footstep_1.wav"),
    ASSET___SAMURAI_FOOTSTEP_2("Resources/industrial-zone/audio/sfx/._Samurai_footstep_2.wav"),
    ASSET___SLIDING_DOORS("Resources/industrial-zone/audio/sfx/._Sliding_doors.wav"),
    ASSET___STEALTHY_THEME_LOOPABLE("Resources/industrial-zone/audio/sfx/._Stealthy_theme_loopable.wav"),
    ASSET___UNLOCKED_CHEST("Resources/industrial-zone/audio/sfx/._Unlocked_chest.wav"),
    ASSET___ZIPLINE_LOOPABLE("Resources/industrial-zone/audio/sfx/._Zipline_loopable.wav")
;
}
