/**
 * GUI Assets
 * Auto-generated from assets-manifest.json
 * Total: 290 assets
 * Date: 2026-04-14
 */
public enum GUIAssets {

    ASSET_01_GUI_FRAME_CORNERTOPLEFT_TALLLSHAPEPIECE_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/01_GUI_Frame_CornerTopLeft_TallLShapePiece_WindowCorner.png"),
    ASSET_02_GUI_FRAME_EDGETOPBAR_HORIZONTALBLUEACCENTSTRIP_WINDOWTOPEDGE("Resources/industrial-zone/gui/1 Frames/02_GUI_Frame_EdgeTopBar_HorizontalBlueAccentStrip_WindowTopEdge.png"),
    ASSET_03_GUI_FRAME_CORNERTOPRIGHT_TALLLSHAPEMIRROR_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/03_GUI_Frame_CornerTopRight_TallLShapeMirror_WindowCorner.png"),
    ASSET_04_GUI_FRAME_CORNERTOPLEFTRIVET_REDDOTACCENTS_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/04_GUI_Frame_CornerTopLeftRivet_RedDotAccents_WindowCorner.png"),
    ASSET_05_GUI_FRAME_EDGELEFTSTRIP_TALLNARROWVERTICALBAR_WINDOWLEFTEDGE("Resources/industrial-zone/gui/1 Frames/05_GUI_Frame_EdgeLeftStrip_TallNarrowVerticalBar_WindowLeftEdge.png"),
    ASSET_06_GUI_FRAME_EDGERIGHTSTRIP_TALLNARROWVERTICALBAR_WINDOWRIGHTEDGE("Resources/industrial-zone/gui/1 Frames/06_GUI_Frame_EdgeRightStrip_TallNarrowVerticalBar_WindowRightEdge.png"),
    ASSET_07_GUI_FRAME_FILLSOLIDNAVY_LARGEFULLBLOCK_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/07_GUI_Frame_FillSolidNavy_LargeFullBlock_WindowFill.png"),
    ASSET_08_GUI_FRAME_PANELCROSSDIAMOND_BLUEGEOMETRICPATTERN_DECORATIVEFILL("Resources/industrial-zone/gui/1 Frames/08_GUI_Frame_PanelCrossDiamond_BlueGeometricPattern_DecorativeFill.png"),
    ASSET_09_GUI_FRAME_CORNERINSETTOPLEFT_INSETBORDERSQUARE_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/09_GUI_Frame_CornerInsetTopLeft_InsetBorderSquare_WindowCorner.png"),
    ASSET_10_GUI_FRAME_EDGELEFTSTRIP_TALLBLUETINTBAR_WINDOWLEFTEDGE("Resources/industrial-zone/gui/1 Frames/10_GUI_Frame_EdgeLeftStrip_TallBlueTintBar_WindowLeftEdge.png"),
    ASSET_11_GUI_FRAME_FILLDIAGONALTEXTURE_FAINTDIAGLINES_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/11_GUI_Frame_FillDiagonalTexture_FaintDiagLines_WindowFill.png"),
    ASSET_12_GUI_FRAME_EDGELEFTSTRIP_TALLDARKERBAR_WINDOWLEFTEDGE("Resources/industrial-zone/gui/1 Frames/12_GUI_Frame_EdgeLeftStrip_TallDarkerBar_WindowLeftEdge.png"),
    ASSET_13_GUI_FRAME_EDGELEFTSTRIP_TALLTHINLIGHTER_WINDOWLEFTEDGE("Resources/industrial-zone/gui/1 Frames/13_GUI_Frame_EdgeLeftStrip_TallThinLighter_WindowLeftEdge.png"),
    ASSET_14_GUI_FRAME_EDGELEFTSTRIP_TALLWIDERWITHTRIM_WINDOWLEFTEDGE("Resources/industrial-zone/gui/1 Frames/14_GUI_Frame_EdgeLeftStrip_TallWiderWithTrim_WindowLeftEdge.png"),
    ASSET_15_GUI_FRAME_EDGELEFTSTRIP_TALLLIGHTERBLUETRIM_WINDOWLEFTEDGE("Resources/industrial-zone/gui/1 Frames/15_GUI_Frame_EdgeLeftStrip_TallLighterBlueTrim_WindowLeftEdge.png"),
    ASSET_16_GUI_FRAME_PANELWIDERECT_TEALCYANACCENTSTRIPE_DIVIDERBAR("Resources/industrial-zone/gui/1 Frames/16_GUI_Frame_PanelWideRect_TealCyanAccentStripe_DividerBar.png"),
    ASSET_17_GUI_FRAME_PANELWIDERECT_DARKERNOACCENT_DIVIDERBAR("Resources/industrial-zone/gui/1 Frames/17_GUI_Frame_PanelWideRect_DarkerNoAccent_DividerBar.png"),
    ASSET_18_GUI_FRAME_EDGERIGHTSTRIP_TALLBLUEACCENTLINE_WINDOWRIGHTEDGE("Resources/industrial-zone/gui/1 Frames/18_GUI_Frame_EdgeRightStrip_TallBlueAccentLine_WindowRightEdge.png"),
    ASSET_19_GUI_FRAME_CORNERBOTTOMLEFT_LSHAPECORNER_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/19_GUI_Frame_CornerBottomLeft_LShapeCorner_WindowCorner.png"),
    ASSET_20_GUI_FRAME_EDGEBOTTOMBAR_PLAINDARKSTRIP_WINDOWBOTTOMEDGE("Resources/industrial-zone/gui/1 Frames/20_GUI_Frame_EdgeBottomBar_PlainDarkStrip_WindowBottomEdge.png"),
    ASSET_21_GUI_FRAME_CORNERBOTTOMLEFTFULL_INSETSQUARECORNER_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/21_GUI_Frame_CornerBottomLeftFull_InsetSquareCorner_WindowCorner.png"),
    ASSET_22_GUI_FRAME_EDGERIGHTSTRIP_TALLNARROWPLAIN_WINDOWRIGHTEDGE("Resources/industrial-zone/gui/1 Frames/22_GUI_Frame_EdgeRightStrip_TallNarrowPlain_WindowRightEdge.png"),
    ASSET_23_GUI_FRAME_PANELWIDERECT_TECHDOTTEXTURE_DIVIDERBAR("Resources/industrial-zone/gui/1 Frames/23_GUI_Frame_PanelWideRect_TechDotTexture_DividerBar.png"),
    ASSET_24_GUI_FRAME_EDGEBOTTOMBAR_DOTLINETEXTURE_WINDOWBOTTOMEDGE("Resources/industrial-zone/gui/1 Frames/24_GUI_Frame_EdgeBottomBar_DotLineTexture_WindowBottomEdge.png"),
    ASSET_25_GUI_FRAME_PANELWIDERECT_WIDERPLAINDARK_DIVIDERBAR("Resources/industrial-zone/gui/1 Frames/25_GUI_Frame_PanelWideRect_WiderPlainDark_DividerBar.png"),
    ASSET_26_GUI_FRAME_PANELWIDERECT_DARKERVARIANT_DIVIDERBAR("Resources/industrial-zone/gui/1 Frames/26_GUI_Frame_PanelWideRect_DarkerVariant_DividerBar.png"),
    ASSET_27_GUI_FRAME_CORNERBOTTOMRIGHT_DIAGONALANGLETRIM_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/27_GUI_Frame_CornerBottomRight_DiagonalAngleTrim_WindowCorner.png"),
    ASSET_28_GUI_FRAME_EDGERIGHTSTRIP_TALLBLUEACCENT_WINDOWRIGHTEDGE("Resources/industrial-zone/gui/1 Frames/28_GUI_Frame_EdgeRightStrip_TallBlueAccent_WindowRightEdge.png"),
    ASSET_29_GUI_FRAME_CORNERBOTTOMRIGHTFULL_BRACKETCORNER_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/29_GUI_Frame_CornerBottomRightFull_BracketCorner_WindowCorner.png"),
    ASSET_30_GUI_FRAME_CORNERTOPRIGHTFULL_BRACKETTSHAPE_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/30_GUI_Frame_CornerTopRightFull_BracketTShape_WindowCorner.png"),
    ASSET_31_GUI_FRAME_CORNERTOPRIGHT_SMALLINSETLIGHTTRIM_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/31_GUI_Frame_CornerTopRight_SmallInsetLightTrim_WindowCorner.png"),
    ASSET_32_GUI_FRAME_CORNERTOPLEFT_TRIANGLECUT_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/32_GUI_Frame_CornerTopLeft_TriangleCut_WindowCorner.png"),
    ASSET_33_GUI_FRAME_CORNERTOPRIGHT_TRIANGLECUTMIRROR_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/33_GUI_Frame_CornerTopRight_TriangleCutMirror_WindowCorner.png"),
    ASSET_34_GUI_FRAME_CORNERTOPRIGHT_DIAGONALCUT_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/34_GUI_Frame_CornerTopRight_DiagonalCut_WindowCorner.png"),
    ASSET_35_GUI_FRAME_PANELHORIZDIVIDER_TWOROWDARKNAVY_DIVIDERBAR("Resources/industrial-zone/gui/1 Frames/35_GUI_Frame_PanelHorizDivider_TwoRowDarkNavy_DividerBar.png"),
    ASSET_36_GUI_FRAME_EDGETOPBARVARIANT_LIGHTERSTRIPE_WINDOWTOPEDGE("Resources/industrial-zone/gui/1 Frames/36_GUI_Frame_EdgeTopBarVariant_LighterStripe_WindowTopEdge.png"),
    ASSET_37_GUI_FRAME_PANELINSETSQUARE_SINGLECELLDARKBORDER_PANELCELL("Resources/industrial-zone/gui/1 Frames/37_GUI_Frame_PanelInsetSquare_SingleCellDarkBorder_PanelCell.png"),
    ASSET_38_GUI_FRAME_FILLSOLIDNAVY_WIDERECTNOBORDER_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/38_GUI_Frame_FillSolidNavy_WideRectNoBorder_WindowFill.png"),
    ASSET_39_GUI_FRAME_FILLSOLIDNAVY_WIDERVARIANT_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/39_GUI_Frame_FillSolidNavy_WiderVariant_WindowFill.png"),
    ASSET_40_GUI_FRAME_FILLSOLIDDARKNAVY_FULLBLOCK_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/40_GUI_Frame_FillSolidDarkNavy_FullBlock_WindowFill.png"),
    ASSET_41_GUI_FRAME_PANEL2CELL_TWOINSETSQUARES_PANELCELL("Resources/industrial-zone/gui/1 Frames/41_GUI_Frame_Panel2Cell_TwoInsetSquares_PanelCell.png"),
    ASSET_42_GUI_FRAME_PANEL2CELLVARIANT_TWOINSETSQUARESDIFFSHADE_PANELCELL("Resources/industrial-zone/gui/1 Frames/42_GUI_Frame_Panel2CellVariant_TwoInsetSquaresDiffShade_PanelCell.png"),
    ASSET_43_GUI_FRAME_EDGELEFTSTRIP_NARROWDARKVERTICAL_WINDOWLEFTEDGE("Resources/industrial-zone/gui/1 Frames/43_GUI_Frame_EdgeLeftStrip_NarrowDarkVertical_WindowLeftEdge.png"),
    ASSET_44_GUI_FRAME_EDGEHORIZBAR_DENSEDOTLINETEXTURE_WINDOWEDGE("Resources/industrial-zone/gui/1 Frames/44_GUI_Frame_EdgeHorizBar_DenseDotLineTexture_WindowEdge.png"),
    ASSET_45_GUI_FRAME_FILLSOLIDNAVY_PLAINFLATBLOCK_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/45_GUI_Frame_FillSolidNavy_PlainFlatBlock_WindowFill.png"),
    ASSET_46_GUI_FRAME_FILLSOLIDNAVY_WIDEFLATRECT_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/46_GUI_Frame_FillSolidNavy_WideFlatRect_WindowFill.png"),
    ASSET_47_GUI_FRAME_EDGEDIAGONALSTRIP_ANGLEDTOPLEFTSLANT_WINDOWEDGE("Resources/industrial-zone/gui/1 Frames/47_GUI_Frame_EdgeDiagonalStrip_AngledTopLeftSlant_WindowEdge.png"),
    ASSET_48_GUI_FRAME_EDGERIGHTSTRIP_NARROWVERTICALBAR_WINDOWRIGHTEDGE("Resources/industrial-zone/gui/1 Frames/48_GUI_Frame_EdgeRightStrip_NarrowVerticalBar_WindowRightEdge.png"),
    ASSET_49_GUI_FRAME_PANELHORIZBAR_MEDIUMWIDTH_DIVIDERBAR("Resources/industrial-zone/gui/1 Frames/49_GUI_Frame_PanelHorizBar_MediumWidth_DividerBar.png"),
    ASSET_50_GUI_FRAME_EDGEBOTTOMBAR_HORIZSTRIPTEXTURE_WINDOWBOTTOMEDGE("Resources/industrial-zone/gui/1 Frames/50_GUI_Frame_EdgeBottomBar_HorizStripTexture_WindowBottomEdge.png"),
    ASSET_51_GUI_FRAME_PANELINSETSQUARE_SINGLECELL_PANELCELL("Resources/industrial-zone/gui/1 Frames/51_GUI_Frame_PanelInsetSquare_SingleCell_PanelCell.png"),
    ASSET_52_GUI_FRAME_PANEL2CELLVARIANT2_TWOINSETSQUARES_PANELCELL("Resources/industrial-zone/gui/1 Frames/52_GUI_Frame_Panel2CellVariant2_TwoInsetSquares_PanelCell.png"),
    ASSET_53_GUI_FRAME_PANEL2CELLVARIANT3_TWOINSETSLIGHTBORDERDIFF_PANELCELL("Resources/industrial-zone/gui/1 Frames/53_GUI_Frame_Panel2CellVariant3_TwoInsetSlightBorderDiff_PanelCell.png"),
    ASSET_54_GUI_FRAME_EDGEBOTTOMBAR_LIGHTBLUEACCENTLINE_WINDOWBOTTOMEDGE("Resources/industrial-zone/gui/1 Frames/54_GUI_Frame_EdgeBottomBar_LightBlueAccentLine_WindowBottomEdge.png"),
    ASSET_55_GUI_FRAME_EDGERIGHTSTRIP_NARROWSLIGHTLYWIDER_WINDOWRIGHTEDGE("Resources/industrial-zone/gui/1 Frames/55_GUI_Frame_EdgeRightStrip_NarrowSlightlyWider_WindowRightEdge.png"),
    ASSET_56_GUI_FRAME_EDGEDIAGONALSTRIP_ANGLEDLINETEXTURE_WINDOWEDGE("Resources/industrial-zone/gui/1 Frames/56_GUI_Frame_EdgeDiagonalStrip_AngledLineTexture_WindowEdge.png"),
    ASSET_57_GUI_FRAME_EDGELEFTSTRIP_NARROWDARKSLIGHTVARIANT_WINDOWLEFTEDGE("Resources/industrial-zone/gui/1 Frames/57_GUI_Frame_EdgeLeftStrip_NarrowDarkSlightVariant_WindowLeftEdge.png"),
    ASSET_58_GUI_FRAME_PANELWIDERECT_INSETBORDERWIDER_PANELCELL("Resources/industrial-zone/gui/1 Frames/58_GUI_Frame_PanelWideRect_InsetBorderWider_PanelCell.png"),
    ASSET_59_GUI_FRAME_FILLSOLIDNAVY_WIDEFLATRECT_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/59_GUI_Frame_FillSolidNavy_WideFlatRect_WindowFill.png"),
    ASSET_60_GUI_FRAME_PANELMEDIUM_INSETSQUARETALLER_PANELCELL("Resources/industrial-zone/gui/1 Frames/60_GUI_Frame_PanelMedium_InsetSquareTaller_PanelCell.png"),
    ASSET_61_GUI_FRAME_PANEL2CELL_TWOINSETSQUARESWITHICONS_PANELCELL("Resources/industrial-zone/gui/1 Frames/61_GUI_Frame_Panel2Cell_TwoInsetSquaresWithIcons_PanelCell.png"),
    ASSET_62_GUI_FRAME_PANEL2CELLVARIANT_TWOINSETSQUARESICONSALT_PANELCELL("Resources/industrial-zone/gui/1 Frames/62_GUI_Frame_Panel2CellVariant_TwoInsetSquaresIconsAlt_PanelCell.png"),
    ASSET_63_GUI_FRAME_CORNERHEXAGONAL_LIGHTGREYOCTAGONSHAPE_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/63_GUI_Frame_CornerHexagonal_LightGreyOctagonShape_WindowCorner.png"),
    ASSET_64_GUI_FRAME_CORNERDIAGONALCUTTOPLEFT_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/64_GUI_Frame_CornerDiagonalCutTopLeft_WindowCorner.png"),
    ASSET_65_GUI_FRAME_FILLSOLIDDARKNAVY_PLAINBLOCK_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/65_GUI_Frame_FillSolidDarkNavy_PlainBlock_WindowFill.png"),
    ASSET_66_GUI_FRAME_FILLSOLIDNAVYLIGHTER_SLIGHTLYLIGHTER_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/66_GUI_Frame_FillSolidNavyLighter_SlightlyLighter_WindowFill.png"),
    ASSET_67_GUI_FRAME_EDGETOPBAR_PLAINBAR_WINDOWTOPEDGE("Resources/industrial-zone/gui/1 Frames/67_GUI_Frame_EdgeTopBar_PlainBar_WindowTopEdge.png"),
    ASSET_68_GUI_FRAME_FILLSOLIDNAVY_PLAINBLOCK_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/68_GUI_Frame_FillSolidNavy_PlainBlock_WindowFill.png"),
    ASSET_69_GUI_FRAME_EDGELEFTSTRIP_LEFTEDGEBAR_WINDOWLEFTEDGE("Resources/industrial-zone/gui/1 Frames/69_GUI_Frame_EdgeLeftStrip_LeftEdgeBar_WindowLeftEdge.png"),
    ASSET_70_GUI_FRAME_PANEL2CELLWIDEDIVIDER_TWOCELLBLOCK_DIVIDERBAR("Resources/industrial-zone/gui/1 Frames/70_GUI_Frame_Panel2CellWideDivider_TwoCellBlock_DividerBar.png"),
    ASSET_71_GUI_FRAME_PANEL2CELLGRID_TWOCELLGRIDBLOCK_PANELCELL("Resources/industrial-zone/gui/1 Frames/71_GUI_Frame_Panel2CellGrid_TwoCellGridBlock_PanelCell.png"),
    ASSET_72_GUI_FRAME_EDGETHINRIGHTSTRIP_THINVERTICALRIGHT_WINDOWRIGHTEDGE("Resources/industrial-zone/gui/1 Frames/72_GUI_Frame_EdgeThinRightStrip_ThinVerticalRight_WindowRightEdge.png"),
    ASSET_73_GUI_FRAME_CORNERBOTTOMLEFT_PLAINCORNER_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/73_GUI_Frame_CornerBottomLeft_PlainCorner_WindowCorner.png"),
    ASSET_74_GUI_FRAME_FILLSOLIDNAVY_PLAINBLOCK_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/74_GUI_Frame_FillSolidNavy_PlainBlock_WindowFill.png"),
    ASSET_75_GUI_FRAME_EDGEBOTTOMBAR_PLAINHORIZSTRIP_WINDOWBOTTOMEDGE("Resources/industrial-zone/gui/1 Frames/75_GUI_Frame_EdgeBottomBar_PlainHorizStrip_WindowBottomEdge.png"),
    ASSET_76_GUI_FRAME_CORNERBOTTOMSMALLNOTCH_BOTTOMNOTCHCORNER_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/76_GUI_Frame_CornerBottomSmallNotch_BottomNotchCorner_WindowCorner.png"),
    ASSET_77_GUI_FRAME_FILLSOLIDNAVYDARK_DARKBLOCK_WINDOWFILL("Resources/industrial-zone/gui/1 Frames/77_GUI_Frame_FillSolidNavyDark_DarkBlock_WindowFill.png"),
    ASSET_78_GUI_FRAME_CORNERBOTTOMRIGHT_PLAINCORNER_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/78_GUI_Frame_CornerBottomRight_PlainCorner_WindowCorner.png"),
    ASSET_79_GUI_FRAME_PANELINSETSQUARE_DARKBORDERSQUARE_PANELCELL("Resources/industrial-zone/gui/1 Frames/79_GUI_Frame_PanelInsetSquare_DarkBorderSquare_PanelCell.png"),
    ASSET_80_GUI_FRAME_PANELINSETSQUARE_LIGHTERVARIANT_PANELCELL("Resources/industrial-zone/gui/1 Frames/80_GUI_Frame_PanelInsetSquare_LighterVariant_PanelCell.png"),
    ASSET_81_GUI_FRAME_CORNERTOPRIGHT_LIGHTTRIMCORNER_WINDOWCORNER("Resources/industrial-zone/gui/1 Frames/81_GUI_Frame_CornerTopRight_LightTrimCorner_WindowCorner.png"),
    ASSET_82_GUI_FRAME_MASTERSPRITESHEET_ALLFRAMEPIECESLAYOUT_REFERENCE("Resources/industrial-zone/gui/1 Frames/82_GUI_Frame_MasterSpritesheet_AllFramePiecesLayout_Reference.png"),
    ASSET_CYBERPUNKCRAFTPIXPIXEL_OTF("Resources/industrial-zone/gui/10 Font/CyberpunkCraftpixPixel.otf"),
    ASSET_1_01("Resources/industrial-zone/gui/10 Font/images/1_01.png"),
    ASSET_1_02("Resources/industrial-zone/gui/10 Font/images/1_02.png"),
    ASSET_1_03("Resources/industrial-zone/gui/10 Font/images/1_03.png"),
    ASSET_1_04("Resources/industrial-zone/gui/10 Font/images/1_04.png"),
    ASSET_1_05("Resources/industrial-zone/gui/10 Font/images/1_05.png"),
    ASSET_1_06("Resources/industrial-zone/gui/10 Font/images/1_06.png"),
    ASSET_1_07("Resources/industrial-zone/gui/10 Font/images/1_07.png"),
    ASSET_1_08("Resources/industrial-zone/gui/10 Font/images/1_08.png"),
    ASSET_1_09("Resources/industrial-zone/gui/10 Font/images/1_09.png"),
    ASSET_1_10("Resources/industrial-zone/gui/10 Font/images/1_10.png"),
    ASSET_1_11("Resources/industrial-zone/gui/10 Font/images/1_11.png"),
    ASSET_1_12("Resources/industrial-zone/gui/10 Font/images/1_12.png"),
    ASSET_1_13("Resources/industrial-zone/gui/10 Font/images/1_13.png"),
    ASSET_1_14("Resources/industrial-zone/gui/10 Font/images/1_14.png"),
    ASSET_1_15("Resources/industrial-zone/gui/10 Font/images/1_15.png"),
    ASSET_1_16("Resources/industrial-zone/gui/10 Font/images/1_16.png"),
    ASSET_1_17("Resources/industrial-zone/gui/10 Font/images/1_17.png"),
    ASSET_1_18("Resources/industrial-zone/gui/10 Font/images/1_18.png"),
    ASSET_1_19("Resources/industrial-zone/gui/10 Font/images/1_19.png"),
    ASSET_1_20("Resources/industrial-zone/gui/10 Font/images/1_20.png"),
    ASSET_1_21("Resources/industrial-zone/gui/10 Font/images/1_21.png"),
    ASSET_1_22("Resources/industrial-zone/gui/10 Font/images/1_22.png"),
    ASSET_1_23("Resources/industrial-zone/gui/10 Font/images/1_23.png"),
    ASSET_1_24("Resources/industrial-zone/gui/10 Font/images/1_24.png"),
    ASSET_1_25("Resources/industrial-zone/gui/10 Font/images/1_25.png"),
    ASSET_1_26("Resources/industrial-zone/gui/10 Font/images/1_26.png"),
    ASSET_1_27("Resources/industrial-zone/gui/10 Font/images/1_27.png"),
    ASSET_1_28("Resources/industrial-zone/gui/10 Font/images/1_28.png"),
    ASSET_1_29("Resources/industrial-zone/gui/10 Font/images/1_29.png"),
    ASSET_1_30("Resources/industrial-zone/gui/10 Font/images/1_30.png"),
    ASSET_1_31("Resources/industrial-zone/gui/10 Font/images/1_31.png"),
    ASSET_1_32("Resources/industrial-zone/gui/10 Font/images/1_32.png"),
    ASSET_1_33("Resources/industrial-zone/gui/10 Font/images/1_33.png"),
    ASSET_1_34("Resources/industrial-zone/gui/10 Font/images/1_34.png"),
    ASSET_1_35("Resources/industrial-zone/gui/10 Font/images/1_35.png"),
    ASSET_1_36("Resources/industrial-zone/gui/10 Font/images/1_36.png"),
    ASSET_1_37("Resources/industrial-zone/gui/10 Font/images/1_37.png"),
    ASSET_1_38("Resources/industrial-zone/gui/10 Font/images/1_38.png"),
    ASSET_1_39("Resources/industrial-zone/gui/10 Font/images/1_39.png"),
    ASSET_1_40("Resources/industrial-zone/gui/10 Font/images/1_40.png"),
    ASSET_1_41("Resources/industrial-zone/gui/10 Font/images/1_41.png"),
    ASSET_1_42("Resources/industrial-zone/gui/10 Font/images/1_42.png"),
    ASSET_1_43("Resources/industrial-zone/gui/10 Font/images/1_43.png"),
    ASSET_1_44("Resources/industrial-zone/gui/10 Font/images/1_44.png"),
    ASSET_1_45("Resources/industrial-zone/gui/10 Font/images/1_45.png"),
    ASSET_1_46("Resources/industrial-zone/gui/10 Font/images/1_46.png"),
    ASSET_1_47("Resources/industrial-zone/gui/10 Font/images/1_47.png"),
    ASSET_1_48("Resources/industrial-zone/gui/10 Font/images/1_48.png"),
    ASSET_1_49("Resources/industrial-zone/gui/10 Font/images/1_49.png"),
    ASSET_1_50("Resources/industrial-zone/gui/10 Font/images/1_50.png"),
    ASSET_1_51("Resources/industrial-zone/gui/10 Font/images/1_51.png"),
    ASSET_1_52("Resources/industrial-zone/gui/10 Font/images/1_52.png"),
    ASSET_1_53("Resources/industrial-zone/gui/10 Font/images/1_53.png"),
    ASSET_1_54("Resources/industrial-zone/gui/10 Font/images/1_54.png"),
    ASSET_1_55("Resources/industrial-zone/gui/10 Font/images/1_55.png"),
    ASSET_1_56("Resources/industrial-zone/gui/10 Font/images/1_56.png"),
    ASSET_1_57("Resources/industrial-zone/gui/10 Font/images/1_57.png"),
    ASSET_1_58("Resources/industrial-zone/gui/10 Font/images/1_58.png"),
    ASSET_1_59("Resources/industrial-zone/gui/10 Font/images/1_59.png"),
    ASSET_1_60("Resources/industrial-zone/gui/10 Font/images/1_60.png"),
    ASSET_1_61("Resources/industrial-zone/gui/10 Font/images/1_61.png"),
    ASSET_1_62("Resources/industrial-zone/gui/10 Font/images/1_62.png"),
    ASSET_1_63("Resources/industrial-zone/gui/10 Font/images/1_63.png"),
    ASSET_01_GUI_BAR_HEALTHBAR_FULL100PCT_REDORANGEFILLDARKFRAME_HUD("Resources/industrial-zone/gui/2 Bars/01_GUI_Bar_HealthBar_Full100pct_RedOrangeFillDarkFrame_HUD.png"),
    ASSET_02_GUI_BAR_HEALTHBAR_80PCT_REDORANGEFILL_HUD("Resources/industrial-zone/gui/2 Bars/02_GUI_Bar_HealthBar_80pct_RedOrangeFill_HUD.png"),
    ASSET_03_GUI_BAR_HEALTHBAR_60PCT_REDORANGEFILL_HUD("Resources/industrial-zone/gui/2 Bars/03_GUI_Bar_HealthBar_60pct_RedOrangeFill_HUD.png"),
    ASSET_04_GUI_BAR_HEALTHBAR_40PCT_REDORANGEFILL_HUD("Resources/industrial-zone/gui/2 Bars/04_GUI_Bar_HealthBar_40pct_RedOrangeFill_HUD.png"),
    ASSET_05_GUI_BAR_HEALTHBAR_20PCT_REDORANGEFILL_HUD("Resources/industrial-zone/gui/2 Bars/05_GUI_Bar_HealthBar_20pct_RedOrangeFill_HUD.png"),
    ASSET_06_GUI_BAR_HEALTHBAR_5PCTCRITICAL_REDORANGEFILL_HUD("Resources/industrial-zone/gui/2 Bars/06_GUI_Bar_HealthBar_5pctCritical_RedOrangeFill_HUD.png"),
    ASSET_07_GUI_BAR_HEALTHBAR_EMPTYFRAME_NOFILLCONTAINER_HUD("Resources/industrial-zone/gui/2 Bars/07_GUI_Bar_HealthBar_EmptyFrame_NoFillContainer_HUD.png"),
    ASSET_08_GUI_BAR_HEALTHBAR_EMPTYVARIANT_DIFFFRAMESTYLE_HUD("Resources/industrial-zone/gui/2 Bars/08_GUI_Bar_HealthBar_EmptyVariant_DiffFrameStyle_HUD.png"),
    ASSET_09_GUI_BAR_ENERGYBAR_FULL100PCT_BLUECYANFILLDARKFRAME_HUD("Resources/industrial-zone/gui/2 Bars/09_GUI_Bar_EnergyBar_Full100pct_BlueCyanFillDarkFrame_HUD.png"),
    ASSET_10_GUI_BAR_ENERGYBAR_80PCT_BLUECYANFILL_HUD("Resources/industrial-zone/gui/2 Bars/10_GUI_Bar_EnergyBar_80pct_BlueCyanFill_HUD.png"),
    ASSET_11_GUI_BAR_ENERGYBAR_60PCT_BLUECYANFILL_HUD("Resources/industrial-zone/gui/2 Bars/11_GUI_Bar_EnergyBar_60pct_BlueCyanFill_HUD.png"),
    ASSET_12_GUI_BAR_ENERGYBAR_40PCT_BLUECYANFILL_HUD("Resources/industrial-zone/gui/2 Bars/12_GUI_Bar_EnergyBar_40pct_BlueCyanFill_HUD.png"),
    ASSET_13_GUI_BAR_ENERGYBAR_20PCT_BLUECYANFILL_HUD("Resources/industrial-zone/gui/2 Bars/13_GUI_Bar_EnergyBar_20pct_BlueCyanFill_HUD.png"),
    ASSET_14_GUI_BAR_ENERGYBAR_5PCTCRITICAL_BLUECYANFILL_HUD("Resources/industrial-zone/gui/2 Bars/14_GUI_Bar_EnergyBar_5pctCritical_BlueCyanFill_HUD.png"),
    ASSET_15_GUI_BAR_ENERGYBAR_EMPTYFRAME_NOFILLCONTAINER_HUD("Resources/industrial-zone/gui/2 Bars/15_GUI_Bar_EnergyBar_EmptyFrame_NoFillContainer_HUD.png"),
    ASSET_16_GUI_BAR_ENERGYBAR_EMPTYVARIANT_DIFFFRAMESTYLE_HUD("Resources/industrial-zone/gui/2 Bars/16_GUI_Bar_EnergyBar_EmptyVariant_DiffFrameStyle_HUD.png"),
    ASSET_17_GUI_BAR_SCROLLBAR_NEONPINKBLUEGLOWTALL_SCROLLCONTROL_HUD("Resources/industrial-zone/gui/2 Bars/17_GUI_Bar_ScrollBar_NeonPinkBlueGlowTall_ScrollControl_HUD.png"),
    ASSET_18_GUI_BAR_SCROLLBAR_NEONGLOWVARIANT_SCROLLCONTROL_HUD("Resources/industrial-zone/gui/2 Bars/18_GUI_Bar_ScrollBar_NeonGlowVariant_ScrollControl_HUD.png"),
    ASSET_19_GUI_BAR_SCROLLBAR_PLAINBLUETALLSTRIP_SCROLLCONTROL_HUD("Resources/industrial-zone/gui/2 Bars/19_GUI_Bar_ScrollBar_PlainBlueTallStrip_ScrollControl_HUD.png"),
    ASSET_20_GUI_BAR_SCROLLBAR_NEONGLOWDECORATIVETALLER_SCROLLCONTROL_HUD("Resources/industrial-zone/gui/2 Bars/20_GUI_Bar_ScrollBar_NeonGlowDecorativeTaller_ScrollControl_HUD.png"),
    ASSET_HEALTH_BAR_FULL("Resources/industrial-zone/gui/2 Bars/health_bar_full.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_01("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_01.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_02("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_02.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_03("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_03.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_04("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_04.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_05("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_05.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_06("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_06.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_07("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_07.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_08("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_08.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_09("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_09.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_10("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_10.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_11("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_11.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_12("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_12.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_13("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_13.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_14("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_14.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_15("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_15.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_16("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_16.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_17("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_17.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_18("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_18.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_19("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_19.png"),
    ASSET_GUI_BUTTON_STATE_VARIANT02_20("Resources/industrial-zone/gui/3 Icons/Buttons2/GUI_Button_State_Variant02_20.png"),
    ASSET_GUI_ICON_ALERT_EXCLAMATION_15("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Alert_Exclamation_15.png"),
    ASSET_GUI_ICON_ARROW_DOWN_06("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Arrow_Down_06.png"),
    ASSET_GUI_ICON_ARROW_LEFT_07("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Arrow_Left_07.png"),
    ASSET_GUI_ICON_ARROW_RIGHT_08("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Arrow_Right_08.png"),
    ASSET_GUI_ICON_ARROW_UP_05("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Arrow_Up_05.png"),
    ASSET_GUI_ICON_BATTERY_POWER_40("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Battery_Power_40.png"),
    ASSET_GUI_ICON_BRIGHTNESS_LIGHT_39("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Brightness_Light_39.png"),
    ASSET_GUI_ICON_CHAT_MESSAGE_27("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Chat_Message_27.png"),
    ASSET_GUI_ICON_CHECK_CONFIRM_03("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Check_Confirm_03.png"),
    ASSET_GUI_ICON_CROSS_CANCEL_04("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Cross_Cancel_04.png"),
    ASSET_GUI_ICON_DOWNLOAD_SAVE_30("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Download_Save_30.png"),
    ASSET_GUI_ICON_EMAIL_MAIL_29("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Email_Mail_29.png"),
    ASSET_GUI_ICON_FAST_FORWARD_35("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Fast_Forward_35.png"),
    ASSET_GUI_ICON_HEART_LOVE_22("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Heart_Love_22.png"),
    ASSET_GUI_ICON_HOME_HOUSE_12("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Home_House_12.png"),
    ASSET_GUI_ICON_INFO_QUESTION_14("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Info_Question_14.png"),
    ASSET_GUI_ICON_LOAD_OPEN_20("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Load_Open_20.png"),
    ASSET_GUI_ICON_LOCK_LOCKED_16("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Lock_Locked_16.png"),
    ASSET_GUI_ICON_MENU_HAMBURGER_09("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Menu_Hamburger_09.png"),
    ASSET_GUI_ICON_MINUS_REMOVE_02("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Minus_Remove_02.png"),
    ASSET_GUI_ICON_MUTE_SILENT_38("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Mute_Silent_38.png"),
    ASSET_GUI_ICON_PAUSE_STOP_34("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Pause_Stop_34.png"),
    ASSET_GUI_ICON_PHONE_CALL_28("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Phone_Call_28.png"),
    ASSET_GUI_ICON_PLAY_START_33("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Play_Start_33.png"),
    ASSET_GUI_ICON_PLUS_ADD_01("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Plus_Add_01.png"),
    ASSET_GUI_ICON_REFRESH_RELOAD_32("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Refresh_Reload_32.png"),
    ASSET_GUI_ICON_REWIND_BACK_36("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Rewind_Back_36.png"),
    ASSET_GUI_ICON_SAVE_FLOPPY_19("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Save_Floppy_19.png"),
    ASSET_GUI_ICON_SEARCH_MAGNIFIER_11("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Search_Magnifier_11.png"),
    ASSET_GUI_ICON_SETTINGS_GEAR_10("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Settings_Gear_10.png"),
    ASSET_GUI_ICON_SETTINGS_WRENCH_13("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Settings_Wrench_13.png"),
    ASSET_GUI_ICON_SHIELD_DEFENSE_23("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Shield_Defense_23.png"),
    ASSET_GUI_ICON_STAR_FAVORITE_21("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Star_Favorite_21.png"),
    ASSET_GUI_ICON_SWORD_ATTACK_24("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Sword_Attack_24.png"),
    ASSET_GUI_ICON_TRASH_DELETE_18("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Trash_Delete_18.png"),
    ASSET_GUI_ICON_UNLOCK_OPEN_17("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Unlock_Open_17.png"),
    ASSET_GUI_ICON_UPLOAD_SEND_31("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Upload_Send_31.png"),
    ASSET_GUI_ICON_USERS_GROUP_26("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Users_Group_26.png"),
    ASSET_GUI_ICON_USER_PROFILE_25("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_User_Profile_25.png"),
    ASSET_GUI_ICON_VOLUME_SOUND_37("Resources/industrial-zone/gui/3 Icons/Icons/GUI_Icon_Volume_Sound_37.png"),
    ASSET_GUI_PALETTE_INDUSTRIALZONE_COLORREFERENCE("Resources/industrial-zone/gui/4 Palette/GUI_Palette_IndustrialZone_ColorReference.png"),
    ASSET_GUI_LOGO_INDUSTRIALZONE_COMPACT("Resources/industrial-zone/gui/5 Logo/GUI_Logo_IndustrialZone_Compact.png"),
    ASSET_GUI_LOGO_INDUSTRIALZONE_FULL("Resources/industrial-zone/gui/5 Logo/GUI_Logo_IndustrialZone_Full.png"),
    ASSET_GUI_LOGO_INDUSTRIALZONE_MINIMAL("Resources/industrial-zone/gui/5 Logo/GUI_Logo_IndustrialZone_Minimal.png"),
    ASSET_GUI_BUTTONCOLORMAP_VARIANT_01("Resources/industrial-zone/gui/6 Buttons/GUI_ButtonColorMap_Variant_01.png"),
    ASSET_GUI_BUTTONCOLORMAP_VARIANT_02("Resources/industrial-zone/gui/6 Buttons/GUI_ButtonColorMap_Variant_02.png"),
    ASSET_GUI_BUTTONCOLORMAP_VARIANT_03("Resources/industrial-zone/gui/6 Buttons/GUI_ButtonColorMap_Variant_03.png"),
    ASSET_GUI_BUTTONCOLORMAP_VARIANT_04("Resources/industrial-zone/gui/6 Buttons/GUI_ButtonColorMap_Variant_04.png"),
    ASSET_GUI_BUTTONCOLORMAP_VARIANT_05("Resources/industrial-zone/gui/6 Buttons/GUI_ButtonColorMap_Variant_05.png"),
    ASSET_GUI_BUTTONCOLORMAP_VARIANT_06("Resources/industrial-zone/gui/6 Buttons/GUI_ButtonColorMap_Variant_06.png"),
    ASSET_GUI_BUTTONCOLORMAP_VARIANT_07("Resources/industrial-zone/gui/6 Buttons/GUI_ButtonColorMap_Variant_07.png"),
    ASSET_GUI_BUTTONCOLORMAP_VARIANT_08("Resources/industrial-zone/gui/6 Buttons/GUI_ButtonColorMap_Variant_08.png"),
    ASSET_GUI_BUTTONCOLORMAP_VARIANT_09("Resources/industrial-zone/gui/6 Buttons/GUI_ButtonColorMap_Variant_09.png"),
    ASSET_GUI_BUTTONCOLORMAP_VARIANT_10("Resources/industrial-zone/gui/6 Buttons/GUI_ButtonColorMap_Variant_10.png"),
    ASSET_01_GUI_NUMBER_DIGIT1_STYLEDGLYPH_DECORATIVE("Resources/industrial-zone/gui/7 Numbers/01_GUI_Number_Digit1_StyledGlyph_Decorative.png"),
    ASSET_02_GUI_NUMBER_DIGIT2_STYLEDGLYPH_DECORATIVE("Resources/industrial-zone/gui/7 Numbers/02_GUI_Number_Digit2_StyledGlyph_Decorative.png"),
    ASSET_03_GUI_NUMBER_DIGIT3_STYLEDGLYPH_DECORATIVE("Resources/industrial-zone/gui/7 Numbers/03_GUI_Number_Digit3_StyledGlyph_Decorative.png"),
    ASSET_04_GUI_NUMBER_DIGIT4_STYLEDGLYPH_DECORATIVE("Resources/industrial-zone/gui/7 Numbers/04_GUI_Number_Digit4_StyledGlyph_Decorative.png"),
    ASSET_05_GUI_NUMBER_DIGIT5_STYLEDGLYPH_DECORATIVE("Resources/industrial-zone/gui/7 Numbers/05_GUI_Number_Digit5_StyledGlyph_Decorative.png"),
    ASSET_06_GUI_NUMBER_DIGIT6_STYLEDGLYPH_DECORATIVE("Resources/industrial-zone/gui/7 Numbers/06_GUI_Number_Digit6_StyledGlyph_Decorative.png"),
    ASSET_07_GUI_NUMBER_DIGIT7_STYLEDGLYPH_DECORATIVE("Resources/industrial-zone/gui/7 Numbers/07_GUI_Number_Digit7_StyledGlyph_Decorative.png"),
    ASSET_08_GUI_NUMBER_DIGIT8_STYLEDGLYPH_DECORATIVE("Resources/industrial-zone/gui/7 Numbers/08_GUI_Number_Digit8_StyledGlyph_Decorative.png"),
    ASSET_09_GUI_NUMBER_DIGIT9_STYLEDGLYPH_DECORATIVE("Resources/industrial-zone/gui/7 Numbers/09_GUI_Number_Digit9_StyledGlyph_Decorative.png"),
    ASSET_GUI_NUMBER_DIGIT0_ZERO("Resources/industrial-zone/gui/7 Numbers/GUI_Number_Digit0_Zero.png"),
    ASSET_GUI_NUMBER_SYMBOL_B_THOUSAND("Resources/industrial-zone/gui/7 Numbers/GUI_Number_Symbol_B_Thousand.png"),
    ASSET_GUI_NUMBER_SYMBOL_COMMA_SEPARATOR("Resources/industrial-zone/gui/7 Numbers/GUI_Number_Symbol_Comma_Separator.png"),
    ASSET_GUI_NUMBER_SYMBOL_DOT_DECIMAL("Resources/industrial-zone/gui/7 Numbers/GUI_Number_Symbol_Dot_Decimal.png"),
    ASSET_GUI_NUMBER_SYMBOL_K_SUFFIX("Resources/industrial-zone/gui/7 Numbers/GUI_Number_Symbol_K_Suffix.png"),
    ASSET_GUI_NUMBER_SYMBOL_M_MILLION("Resources/industrial-zone/gui/7 Numbers/GUI_Number_Symbol_M_Million.png"),
    ASSET_GUI_NUMBER_SYMBOL_PLUS_ADDITION("Resources/industrial-zone/gui/7 Numbers/GUI_Number_Symbol_Plus_Addition.png"),
    ASSET_NUMBERSMAP("Resources/industrial-zone/gui/7 Numbers/NumbersMap.png"),
    ASSET_01_GUI_CURSOR_WHITE_DEFAULTPOINTER("Resources/industrial-zone/gui/8 Cursors/01_GUI_Cursor_White_DefaultPointer.png"),
    ASSET_02_GUI_CURSOR_BLUE_TARGETINGPOINTER("Resources/industrial-zone/gui/8 Cursors/02_GUI_Cursor_Blue_TargetingPointer.png"),
    ASSET_03_GUI_CURSOR_RED_ATTACKPOINTER("Resources/industrial-zone/gui/8 Cursors/03_GUI_Cursor_Red_AttackPointer.png"),
    ASSET_04_GUI_CURSOR_GREEN_CONFIRMPOINTER("Resources/industrial-zone/gui/8 Cursors/04_GUI_Cursor_Green_ConfirmPointer.png"),
    ASSET_01_GUI_DECOR_GLOWBARS_FOURVERTICALNEONRODS_DECORATION("Resources/industrial-zone/gui/9 Other/1 Decor/01_GUI_Decor_GlowBars_FourVerticalNeonRods_Decoration.png"),
    ASSET_02_GUI_DECOR_RIBBONZIGZAG_PINKSTACKEDLSHAPE_DECORATION("Resources/industrial-zone/gui/9 Other/1 Decor/02_GUI_Decor_RibbonZigzag_PinkStackedLShape_Decoration.png"),
    ASSET_03_GUI_DECOR_CABLETWIST_REDBLUEHELIXWIRE_DECORATION("Resources/industrial-zone/gui/9 Other/1 Decor/03_GUI_Decor_CableTwist_RedBlueHelixWire_Decoration.png"),
    ASSET_04_GUI_DECOR_CABLECONNECTOR_BLUEREDPLUGWIRES_DECORATION("Resources/industrial-zone/gui/9 Other/1 Decor/04_GUI_Decor_CableConnector_BlueRedPlugWires_Decoration.png"),
    ASSET_05_GUI_DECOR_CABLELOOSE_SINGLEREDWIRE_DECORATION("Resources/industrial-zone/gui/9 Other/1 Decor/05_GUI_Decor_CableLoose_SingleRedWire_Decoration.png"),
    ASSET_06_GUI_DECOR_CABLELOOSE_SINGLETEALWIRE_DECORATION("Resources/industrial-zone/gui/9 Other/1 Decor/06_GUI_Decor_CableLoose_SingleTealWire_Decoration.png"),
    ASSET_07_GUI_DECOR_CABLEPLUG_SINGLEBLUECONNECTOR_DECORATION("Resources/industrial-zone/gui/9 Other/1 Decor/07_GUI_Decor_CablePlug_SingleBlueConnector_Decoration.png"),
    ASSET_08_GUI_DECOR_CABLECOIL_BLUELOOPEDWIRE_DECORATION("Resources/industrial-zone/gui/9 Other/1 Decor/08_GUI_Decor_CableCoil_BlueLoopedWire_Decoration.png"),
    ASSET_01_GUI_SKILLICON_EYE_VISIBILITYORREVEAL_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/01_GUI_SkillIcon_Eye_VisibilityOrReveal_SkillIcon.png"),
    ASSET_02_GUI_SKILLICON_CHEVRONUP_BOOSTORLEVELUP_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/02_GUI_SkillIcon_ChevronUp_BoostOrLevelUp_SkillIcon.png"),
    ASSET_03_GUI_SKILLICON_RADIATION_HAZARDORPOISON_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/03_GUI_SkillIcon_Radiation_HazardOrPoison_SkillIcon.png"),
    ASSET_04_GUI_SKILLICON_MUSHROOM_EXPLOSIONORBLAST_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/04_GUI_SkillIcon_Mushroom_ExplosionOrBlast_SkillIcon.png"),
    ASSET_05_GUI_SKILLICON_HOURGLASS_TIMERORSLOWTIME_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/05_GUI_SkillIcon_Hourglass_TimerOrSlowTime_SkillIcon.png"),
    ASSET_06_GUI_SKILLICON_CROSSHAIR_TARGETORAIM_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/06_GUI_SkillIcon_Crosshair_TargetOrAim_SkillIcon.png"),
    ASSET_07_GUI_SKILLICON_HOUSE_BASEORRESPAWN_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/07_GUI_SkillIcon_House_BaseOrRespawn_SkillIcon.png"),
    ASSET_08_GUI_SKILLICON_DEVICE_TECHORINTERFACE_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/08_GUI_SkillIcon_Device_TechOrInterface_SkillIcon.png"),
    ASSET_09_GUI_SKILLICON_QUESTION_UNKNOWNORHELP_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/09_GUI_SkillIcon_Question_UnknownOrHelp_SkillIcon.png"),
    ASSET_10_GUI_SKILLICON_EXCLAIM_ALERTORWARNING_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/10_GUI_SkillIcon_Exclaim_AlertOrWarning_SkillIcon.png"),
    ASSET_11_GUI_SKILLICON_PLUS_HEALORADDORHEALTH_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/11_GUI_SkillIcon_Plus_HealOrAddOrHealth_SkillIcon.png"),
    ASSET_12_GUI_SKILLICON_DIAGCROSS_CANCELORMULTIPLY_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/12_GUI_SkillIcon_DiagCross_CancelOrMultiply_SkillIcon.png"),
    ASSET_13_GUI_SKILLICON_TICK_CONFIRMORSELECT_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/13_GUI_SkillIcon_Tick_ConfirmOrSelect_SkillIcon.png"),
    ASSET_14_GUI_SKILLICON_ARROWUP_UPLOADORJUMP_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/14_GUI_SkillIcon_ArrowUp_UploadOrJump_SkillIcon.png"),
    ASSET_15_GUI_SKILLICON_KNIFE_MELEEORATTACK_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/15_GUI_SkillIcon_Knife_MeleeOrAttack_SkillIcon.png"),
    ASSET_16_GUI_SKILLICON_HEART_HEALTHORLIFE_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/16_GUI_SkillIcon_Heart_HealthOrLife_SkillIcon.png"),
    ASSET_17_GUI_SKILLICON_REFRESH_RESETORCOOLDOWN_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/17_GUI_SkillIcon_Refresh_ResetOrCooldown_SkillIcon.png"),
    ASSET_18_GUI_SKILLICON_SHIELD_DEFENCEORBLOCK_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/18_GUI_SkillIcon_Shield_DefenceOrBlock_SkillIcon.png"),
    ASSET_19_GUI_SKILLICON_SKULL_DEATHORDANGER_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/19_GUI_SkillIcon_Skull_DeathOrDanger_SkillIcon.png"),
    ASSET_20_GUI_SKILLICON_ARROWDOWN_DOWNLOADORDROP_SKILLICON("Resources/industrial-zone/gui/9 Other/2 Skill icons/20_GUI_SkillIcon_ArrowDown_DownloadOrDrop_SkillIcon.png")
;
}
