package enums;
/**
 * Weapon Assets
 * Auto-generated from assets-manifest.json
 * Total: 212 assets
 * Date: 2026-04-14
 */
public enum WeaponAssets {

    ASSET_01_WEAPON_BIKER_IDLE_VARIANTA_4FRAMES1ROW_WEAPONIDLESTAND_LOOP_150MS("Resources/industrial-zone/weapons/1/1 Characters/1 Biker/01_Weapon_Biker_Idle_VariantA_4Frames1Row_WeaponIdleStand_Loop_150ms.png"),
    ASSET_02_WEAPON_BIKER_IDLE_VARIANTB_4FRAMES1ROW_WEAPONIDLESTAND_LOOP_150MS("Resources/industrial-zone/weapons/1/1 Characters/1 Biker/02_Weapon_Biker_Idle_VariantB_4Frames1Row_WeaponIdleStand_Loop_150ms.png"),
    ASSET_03_WEAPON_BIKER_JUMP_VARIANTA_3FRAMES1ROW_WEAPONJUMPARC_PLAYONCE_80MS("Resources/industrial-zone/weapons/1/1 Characters/1 Biker/03_Weapon_Biker_Jump_VariantA_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png"),
    ASSET_04_WEAPON_BIKER_JUMP_VARIANTB_3FRAMES1ROW_WEAPONJUMPARC_PLAYONCE_80MS("Resources/industrial-zone/weapons/1/1 Characters/1 Biker/04_Weapon_Biker_Jump_VariantB_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png"),
    ASSET_05_WEAPON_BIKER_RUN_VARIANTA_5FRAMES1ROW_WEAPONRUNCYCLE_LOOP_80MS("Resources/industrial-zone/weapons/1/1 Characters/1 Biker/05_Weapon_Biker_Run_VariantA_5Frames1Row_WeaponRunCycle_Loop_80ms.png"),
    ASSET_06_WEAPON_BIKER_RUN_VARIANTB_5FRAMES1ROW_WEAPONRUNCYCLE_LOOP_80MS("Resources/industrial-zone/weapons/1/1 Characters/1 Biker/06_Weapon_Biker_Run_VariantB_5Frames1Row_WeaponRunCycle_Loop_80ms.png"),
    ASSET_07_WEAPON_BIKER_SITDOWN_VARIANTA_4FRAMES1ROW_WEAPONSITDOWN_PLAYONCE_120MS("Resources/industrial-zone/weapons/1/1 Characters/1 Biker/07_Weapon_Biker_Sitdown_VariantA_4Frames1Row_WeaponSitDown_PlayOnce_120ms.png"),
    ASSET_08_WEAPON_BIKER_SITDOWN_VARIANTB_4FRAMES1ROW_WEAPONSITDOWN_PLAYONCE_120MS("Resources/industrial-zone/weapons/1/1 Characters/1 Biker/08_Weapon_Biker_Sitdown_VariantB_4Frames1Row_WeaponSitDown_PlayOnce_120ms.png"),
    ASSET_09_WEAPON_BIKER_WALK_VARIANTA_4FRAMES1ROW_WEAPONWALKCYCLE_LOOP_100MS("Resources/industrial-zone/weapons/1/1 Characters/1 Biker/09_Weapon_Biker_Walk_VariantA_4Frames1Row_WeaponWalkCycle_Loop_100ms.png"),
    ASSET_10_WEAPON_BIKER_WALK_VARIANTB_4FRAMES1ROW_WEAPONWALKCYCLE_LOOP_100MS("Resources/industrial-zone/weapons/1/1 Characters/1 Biker/10_Weapon_Biker_Walk_VariantB_4Frames1Row_WeaponWalkCycle_Loop_100ms.png"),
    ASSET_01_WEAPON_PUNK_IDLE_VARIANTA_3FRAMES1ROW_WEAPONIDLESTAND_LOOP_150MS("Resources/industrial-zone/weapons/1/1 Characters/2 Punk/01_Weapon_Punk_Idle_VariantA_3Frames1Row_WeaponIdleStand_Loop_150ms.png"),
    ASSET_02_WEAPON_PUNK_IDLE_VARIANTB_3FRAMES1ROW_WEAPONIDLESTAND_LOOP_150MS("Resources/industrial-zone/weapons/1/1 Characters/2 Punk/02_Weapon_Punk_Idle_VariantB_3Frames1Row_WeaponIdleStand_Loop_150ms.png"),
    ASSET_03_WEAPON_PUNK_JUMP_VARIANTA_3FRAMES1ROW_WEAPONJUMPARC_PLAYONCE_80MS("Resources/industrial-zone/weapons/1/1 Characters/2 Punk/03_Weapon_Punk_Jump_VariantA_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png"),
    ASSET_04_WEAPON_PUNK_JUMP_VARIANTB_3FRAMES1ROW_WEAPONJUMPARC_PLAYONCE_80MS("Resources/industrial-zone/weapons/1/1 Characters/2 Punk/04_Weapon_Punk_Jump_VariantB_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png"),
    ASSET_05_WEAPON_PUNK_RUN_VARIANTA_5FRAMES1ROW_WEAPONRUNCYCLE_LOOP_80MS("Resources/industrial-zone/weapons/1/1 Characters/2 Punk/05_Weapon_Punk_Run_VariantA_5Frames1Row_WeaponRunCycle_Loop_80ms.png"),
    ASSET_06_WEAPON_PUNK_RUN_VARIANTB_5FRAMES1ROW_WEAPONRUNCYCLE_LOOP_80MS("Resources/industrial-zone/weapons/1/1 Characters/2 Punk/06_Weapon_Punk_Run_VariantB_5Frames1Row_WeaponRunCycle_Loop_80ms.png"),
    ASSET_07_WEAPON_PUNK_SITDOWN_VARIANTA_3FRAMES1ROW_WEAPONSITDOWN_PLAYONCE_120MS("Resources/industrial-zone/weapons/1/1 Characters/2 Punk/07_Weapon_Punk_Sitdown_VariantA_3Frames1Row_WeaponSitDown_PlayOnce_120ms.png"),
    ASSET_08_WEAPON_PUNK_SITDOWN_VARIANTB_3FRAMES1ROW_WEAPONSITDOWN_PLAYONCE_120MS("Resources/industrial-zone/weapons/1/1 Characters/2 Punk/08_Weapon_Punk_Sitdown_VariantB_3Frames1Row_WeaponSitDown_PlayOnce_120ms.png"),
    ASSET_09_WEAPON_PUNK_WALK_VARIANTA_4FRAMES1ROW_WEAPONWALKCYCLE_LOOP_100MS("Resources/industrial-zone/weapons/1/1 Characters/2 Punk/09_Weapon_Punk_Walk_VariantA_4Frames1Row_WeaponWalkCycle_Loop_100ms.png"),
    ASSET_10_WEAPON_PUNK_WALK_VARIANTB_4FRAMES1ROW_WEAPONWALKCYCLE_LOOP_100MS("Resources/industrial-zone/weapons/1/1 Characters/2 Punk/10_Weapon_Punk_Walk_VariantB_4Frames1Row_WeaponWalkCycle_Loop_100ms.png"),
    ASSET_01_WEAPON_CYBORG_IDLE_VARIANTA_3FRAMES1ROW_WEAPONIDLESTAND_LOOP_150MS("Resources/industrial-zone/weapons/1/1 Characters/3 Cyborg/01_Weapon_Cyborg_Idle_VariantA_3Frames1Row_WeaponIdleStand_Loop_150ms.png"),
    ASSET_02_WEAPON_CYBORG_IDLE_VARIANTB_3FRAMES1ROW_WEAPONIDLESTAND_LOOP_150MS("Resources/industrial-zone/weapons/1/1 Characters/3 Cyborg/02_Weapon_Cyborg_Idle_VariantB_3Frames1Row_WeaponIdleStand_Loop_150ms.png"),
    ASSET_03_WEAPON_CYBORG_JUMP_VARIANTA_3FRAMES1ROW_WEAPONJUMPARC_PLAYONCE_80MS("Resources/industrial-zone/weapons/1/1 Characters/3 Cyborg/03_Weapon_Cyborg_Jump_VariantA_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png"),
    ASSET_04_WEAPON_CYBORG_JUMP_VARIANTB_3FRAMES1ROW_WEAPONJUMPARC_PLAYONCE_80MS("Resources/industrial-zone/weapons/1/1 Characters/3 Cyborg/04_Weapon_Cyborg_Jump_VariantB_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png"),
    ASSET_05_WEAPON_CYBORG_RUN_VARIANTA_5FRAMES1ROW_WEAPONRUNCYCLE_LOOP_80MS("Resources/industrial-zone/weapons/1/1 Characters/3 Cyborg/05_Weapon_Cyborg_Run_VariantA_5Frames1Row_WeaponRunCycle_Loop_80ms.png"),
    ASSET_06_WEAPON_CYBORG_RUN_VARIANTB_5FRAMES1ROW_WEAPONRUNCYCLE_LOOP_80MS("Resources/industrial-zone/weapons/1/1 Characters/3 Cyborg/06_Weapon_Cyborg_Run_VariantB_5Frames1Row_WeaponRunCycle_Loop_80ms.png"),
    ASSET_07_WEAPON_CYBORG_SITDOWN_VARIANTA_3FRAMES1ROW_WEAPONSITDOWN_PLAYONCE_120MS("Resources/industrial-zone/weapons/1/1 Characters/3 Cyborg/07_Weapon_Cyborg_Sitdown_VariantA_3Frames1Row_WeaponSitDown_PlayOnce_120ms.png"),
    ASSET_08_WEAPON_CYBORG_SITDOWN_VARIANTB_3FRAMES1ROW_WEAPONSITDOWN_PLAYONCE_120MS("Resources/industrial-zone/weapons/1/1 Characters/3 Cyborg/08_Weapon_Cyborg_Sitdown_VariantB_3Frames1Row_WeaponSitDown_PlayOnce_120ms.png"),
    ASSET_09_WEAPON_CYBORG_WALK_VARIANTA_4FRAMES1ROW_WEAPONWALKCYCLE_LOOP_100MS("Resources/industrial-zone/weapons/1/1 Characters/3 Cyborg/09_Weapon_Cyborg_Walk_VariantA_4Frames1Row_WeaponWalkCycle_Loop_100ms.png"),
    ASSET_10_WEAPON_CYBORG_WALK_VARIANTB_4FRAMES1ROW_WEAPONWALKCYCLE_LOOP_100MS("Resources/industrial-zone/weapons/1/1 Characters/3 Cyborg/10_Weapon_Cyborg_Walk_VariantB_4Frames1Row_WeaponWalkCycle_Loop_100ms.png"),
    ASSET_01_WEAPON_GUN_PISTOL_TYPEA_VARIANTDARK_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/01_Weapon_Gun_Pistol_TypeA_VariantDark_StaticSprite.png"),
    ASSET_02_WEAPON_GUN_PISTOL_TYPEA_VARIANTLIGHT_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/02_Weapon_Gun_Pistol_TypeA_VariantLight_StaticSprite.png"),
    ASSET_03_WEAPON_GUN_PISTOL_TYPEB_VARIANTDARK_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/03_Weapon_Gun_Pistol_TypeB_VariantDark_StaticSprite.png"),
    ASSET_04_WEAPON_GUN_PISTOL_TYPEB_VARIANTLIGHT_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/04_Weapon_Gun_Pistol_TypeB_VariantLight_StaticSprite.png"),
    ASSET_05_WEAPON_GUN_COMPACT_TYPEC_VARIANTDARK_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/05_Weapon_Gun_Compact_TypeC_VariantDark_StaticSprite.png"),
    ASSET_06_WEAPON_GUN_COMPACT_TYPEC_VARIANTLIGHT_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/06_Weapon_Gun_Compact_TypeC_VariantLight_StaticSprite.png"),
    ASSET_07_WEAPON_GUN_COMPACT_TYPED_VARIANTDARK_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/07_Weapon_Gun_Compact_TypeD_VariantDark_StaticSprite.png"),
    ASSET_08_WEAPON_GUN_COMPACT_TYPED_VARIANTLIGHT_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/08_Weapon_Gun_Compact_TypeD_VariantLight_StaticSprite.png"),
    ASSET_09_WEAPON_GUN_COMPACT_TYPEE_VARIANTDARK_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/09_Weapon_Gun_Compact_TypeE_VariantDark_StaticSprite.png"),
    ASSET_10_WEAPON_GUN_COMPACT_TYPEE_VARIANTLIGHT_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/10_Weapon_Gun_Compact_TypeE_VariantLight_StaticSprite.png"),
    ASSET_11_WEAPON_GUN_DETAIL_TYPEF_VARIANTDARK_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/11_Weapon_Gun_Detail_TypeF_VariantDark_StaticSprite.png"),
    ASSET_12_WEAPON_GUN_DETAIL_TYPEF_VARIANTLIGHT_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/12_Weapon_Gun_Detail_TypeF_VariantLight_StaticSprite.png"),
    ASSET_13_WEAPON_GUN_RIFLE_TYPEG_VARIANTDARK_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/13_Weapon_Gun_Rifle_TypeG_VariantDark_StaticSprite.png"),
    ASSET_14_WEAPON_GUN_RIFLE_TYPEG_VARIANTLIGHT_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/14_Weapon_Gun_Rifle_TypeG_VariantLight_StaticSprite.png"),
    ASSET_15_WEAPON_GUN_RIFLE_TYPEH_VARIANTDARK_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/15_Weapon_Gun_Rifle_TypeH_VariantDark_StaticSprite.png"),
    ASSET_16_WEAPON_GUN_RIFLE_TYPEH_VARIANTLIGHT_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/16_Weapon_Gun_Rifle_TypeH_VariantLight_StaticSprite.png"),
    ASSET_17_WEAPON_GUN_RIFLE_TYPEI_VARIANTBLUE_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/17_Weapon_Gun_Rifle_TypeI_VariantBlue_StaticSprite.png"),
    ASSET_18_WEAPON_GUN_RIFLE_TYPEI_VARIANTBLUEALT_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/18_Weapon_Gun_Rifle_TypeI_VariantBlueAlt_StaticSprite.png"),
    ASSET_19_WEAPON_GUN_SPECIAL_TYPEJ_VARIANTTEAL_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/19_Weapon_Gun_Special_TypeJ_VariantTeal_StaticSprite.png"),
    ASSET_20_WEAPON_GUN_SPECIAL_TYPEJ_VARIANTRED_STATICSPRITE("Resources/industrial-zone/weapons/1/2 Guns/20_Weapon_Gun_Special_TypeJ_VariantRed_StaticSprite.png"),
    ASSET_01_WEAPON_HAND_BIKER_GRIPHORIZONTAL_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/1 Biker/01_Weapon_Hand_Biker_GripHorizontal_WeaponHoldPose_StaticSprite.png"),
    ASSET_02_WEAPON_HAND_BIKER_GRIPDIAGONALDOWN_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/1 Biker/02_Weapon_Hand_Biker_GripDiagonalDown_WeaponHoldPose_StaticSprite.png"),
    ASSET_03_WEAPON_HAND_BIKER_GRIPVERTICALUP_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/1 Biker/03_Weapon_Hand_Biker_GripVerticalUp_WeaponHoldPose_StaticSprite.png"),
    ASSET_04_WEAPON_HAND_BIKER_GRIPVERTICALALT_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/1 Biker/04_Weapon_Hand_Biker_GripVerticalAlt_WeaponHoldPose_StaticSprite.png"),
    ASSET_05_WEAPON_HAND_BIKER_GRIPANGLEDOWN_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/1 Biker/05_Weapon_Hand_Biker_GripAngleDown_WeaponHoldPose_StaticSprite.png"),
    ASSET_06_WEAPON_HAND_BIKER_GRIPLOW_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/1 Biker/06_Weapon_Hand_Biker_GripLow_WeaponHoldPose_StaticSprite.png"),
    ASSET_07_WEAPON_HAND_BIKER_GRIPANGLEUPLEFT_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/1 Biker/07_Weapon_Hand_Biker_GripAngleUpLeft_WeaponHoldPose_StaticSprite.png"),
    ASSET_08_WEAPON_HAND_BIKER_GRIPVERTICALB_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/1 Biker/08_Weapon_Hand_Biker_GripVerticalB_WeaponHoldPose_StaticSprite.png"),
    ASSET_09_WEAPON_HAND_BIKER_GRIPHORIZONTALB_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/1 Biker/09_Weapon_Hand_Biker_GripHorizontalB_WeaponHoldPose_StaticSprite.png"),
    ASSET_10_WEAPON_HAND_BIKER_GRIPDIAGONALLONG_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/1 Biker/10_Weapon_Hand_Biker_GripDiagonalLong_WeaponHoldPose_StaticSprite.png"),
    ASSET_01_WEAPON_HAND_PUNK_GRIPVERTICAL_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/2 Punk/01_Weapon_Hand_Punk_GripVertical_WeaponHoldPose_StaticSprite.png"),
    ASSET_02_WEAPON_HAND_PUNK_GRIPDIAGONALDOWN_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/2 Punk/02_Weapon_Hand_Punk_GripDiagonalDown_WeaponHoldPose_StaticSprite.png"),
    ASSET_03_WEAPON_HAND_PUNK_GRIPHORIZONTAL_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/2 Punk/03_Weapon_Hand_Punk_GripHorizontal_WeaponHoldPose_StaticSprite.png"),
    ASSET_04_WEAPON_HAND_PUNK_GRIPDIAGONALALT_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/2 Punk/04_Weapon_Hand_Punk_GripDiagonalAlt_WeaponHoldPose_StaticSprite.png"),
    ASSET_05_WEAPON_HAND_PUNK_GRIPVERTICALUP_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/2 Punk/05_Weapon_Hand_Punk_GripVerticalUp_WeaponHoldPose_StaticSprite.png"),
    ASSET_06_WEAPON_HAND_PUNK_GRIPVERTICALB_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/2 Punk/06_Weapon_Hand_Punk_GripVerticalB_WeaponHoldPose_StaticSprite.png"),
    ASSET_07_WEAPON_HAND_PUNK_GRIPDIAGONALLONG_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/2 Punk/07_Weapon_Hand_Punk_GripDiagonalLong_WeaponHoldPose_StaticSprite.png"),
    ASSET_08_WEAPON_HAND_PUNK_GRIPHORIZONTALRED_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/2 Punk/08_Weapon_Hand_Punk_GripHorizontalRed_WeaponHoldPose_StaticSprite.png"),
    ASSET_09_WEAPON_HAND_PUNK_GRIPCOMPACTANGLE_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/2 Punk/09_Weapon_Hand_Punk_GripCompactAngle_WeaponHoldPose_StaticSprite.png"),
    ASSET_10_WEAPON_HAND_PUNK_GRIPLONGBLUERED_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/2 Punk/10_Weapon_Hand_Punk_GripLongBlueRed_WeaponHoldPose_StaticSprite.png"),
    ASSET_01_WEAPON_HAND_CYBORG_GRIPVERTICAL_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/3 Cyborg/01_Weapon_Hand_Cyborg_GripVertical_WeaponHoldPose_StaticSprite.png"),
    ASSET_02_WEAPON_HAND_CYBORG_GRIPDIAGONALDOWN_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/3 Cyborg/02_Weapon_Hand_Cyborg_GripDiagonalDown_WeaponHoldPose_StaticSprite.png"),
    ASSET_03_WEAPON_HAND_CYBORG_GRIPHORIZONTAL_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/3 Cyborg/03_Weapon_Hand_Cyborg_GripHorizontal_WeaponHoldPose_StaticSprite.png"),
    ASSET_04_WEAPON_HAND_CYBORG_GRIPDIAGONALALT_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/3 Cyborg/04_Weapon_Hand_Cyborg_GripDiagonalAlt_WeaponHoldPose_StaticSprite.png"),
    ASSET_05_WEAPON_HAND_CYBORG_GRIPVERTICALUP_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/3 Cyborg/05_Weapon_Hand_Cyborg_GripVerticalUp_WeaponHoldPose_StaticSprite.png"),
    ASSET_06_WEAPON_HAND_CYBORG_GRIPVERTICALB_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/3 Cyborg/06_Weapon_Hand_Cyborg_GripVerticalB_WeaponHoldPose_StaticSprite.png"),
    ASSET_07_WEAPON_HAND_CYBORG_GRIPDIAGONALLONG_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/3 Cyborg/07_Weapon_Hand_Cyborg_GripDiagonalLong_WeaponHoldPose_StaticSprite.png"),
    ASSET_08_WEAPON_HAND_CYBORG_GRIPHORIZONTALBLUE_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/3 Cyborg/08_Weapon_Hand_Cyborg_GripHorizontalBlue_WeaponHoldPose_StaticSprite.png"),
    ASSET_09_WEAPON_HAND_CYBORG_GRIPCOMPACTANGLE_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/3 Cyborg/09_Weapon_Hand_Cyborg_GripCompactAngle_WeaponHoldPose_StaticSprite.png"),
    ASSET_10_WEAPON_HAND_CYBORG_GRIPLONGBLUE_WEAPONHOLDPOSE_STATICSPRITE("Resources/industrial-zone/weapons/1/3 Hands/3 Cyborg/10_Weapon_Hand_Cyborg_GripLongBlue_WeaponHoldPose_StaticSprite.png"),
    ASSET_01_WEAPON_SHOOTFX_TRACER_TYPEA_VARIANTNARROW_STATICSPRITE("Resources/industrial-zone/weapons/1/4 Shoot_effects/01_Weapon_ShootFX_Tracer_TypeA_VariantNarrow_StaticSprite.png"),
    ASSET_02_WEAPON_SHOOTFX_TRACER_TYPEA_VARIANTSCATTER_STATICSPRITE("Resources/industrial-zone/weapons/1/4 Shoot_effects/02_Weapon_ShootFX_Tracer_TypeA_VariantScatter_StaticSprite.png"),
    ASSET_03_WEAPON_SHOOTFX_TRACER_TYPEB_VARIANTDOTTED_STATICSPRITE("Resources/industrial-zone/weapons/1/4 Shoot_effects/03_Weapon_ShootFX_Tracer_TypeB_VariantDotted_StaticSprite.png"),
    ASSET_04_WEAPON_SHOOTFX_TRACER_TYPEB_VARIANTSLASH_STATICSPRITE("Resources/industrial-zone/weapons/1/4 Shoot_effects/04_Weapon_ShootFX_Tracer_TypeB_VariantSlash_StaticSprite.png"),
    ASSET_05_WEAPON_SHOOTFX_TRACER_TYPEC_VARIANTHEAVY_STATICSPRITE("Resources/industrial-zone/weapons/1/4 Shoot_effects/05_Weapon_ShootFX_Tracer_TypeC_VariantHeavy_StaticSprite.png"),
    ASSET_06_WEAPON_SHOOTFX_TRACER_TYPEC_VARIANTBOLD_STATICSPRITE("Resources/industrial-zone/weapons/1/4 Shoot_effects/06_Weapon_ShootFX_Tracer_TypeC_VariantBold_StaticSprite.png"),
    ASSET_07_WEAPON_SHOOTFX_TRACER_TYPED_VARIANTWAVE_STATICSPRITE("Resources/industrial-zone/weapons/1/4 Shoot_effects/07_Weapon_ShootFX_Tracer_TypeD_VariantWave_StaticSprite.png"),
    ASSET_08_WEAPON_SHOOTFX_TRACER_TYPED_VARIANTJAGGED_STATICSPRITE("Resources/industrial-zone/weapons/1/4 Shoot_effects/08_Weapon_ShootFX_Tracer_TypeD_VariantJagged_StaticSprite.png"),
    ASSET_09_WEAPON_SHOOTFX_TRACER_TYPEE_VARIANTLASER_STATICSPRITE("Resources/industrial-zone/weapons/1/4 Shoot_effects/09_Weapon_ShootFX_Tracer_TypeE_VariantLaser_StaticSprite.png"),
    ASSET_10_WEAPON_SHOOTFX_TRACER_TYPEE_VARIANTOUTLINE_STATICSPRITE("Resources/industrial-zone/weapons/1/4 Shoot_effects/10_Weapon_ShootFX_Tracer_TypeE_VariantOutline_StaticSprite.png"),
    ASSET_01_WEAPON_BULLET_TYPEA_SINGLE_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/01_Weapon_Bullet_TypeA_Single_StaticSprite.png"),
    ASSET_02_WEAPON_BULLET_TYPEB_SINGLE_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/02_Weapon_Bullet_TypeB_Single_StaticSprite.png"),
    ASSET_03_WEAPON_BULLET_TYPEC_SINGLE_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/03_Weapon_Bullet_TypeC_Single_StaticSprite.png"),
    ASSET_04_WEAPON_BULLET_TYPED_VARIANTA_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/04_Weapon_Bullet_TypeD_VariantA_StaticSprite.png"),
    ASSET_05_WEAPON_BULLET_TYPED_VARIANTB_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/05_Weapon_Bullet_TypeD_VariantB_StaticSprite.png"),
    ASSET_06_WEAPON_BULLET_TYPEE_VARIANTA_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/06_Weapon_Bullet_TypeE_VariantA_StaticSprite.png"),
    ASSET_07_WEAPON_BULLET_TYPEE_VARIANTB_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/07_Weapon_Bullet_TypeE_VariantB_StaticSprite.png"),
    ASSET_08_WEAPON_BULLET_TYPEF_SINGLE_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/08_Weapon_Bullet_TypeF_Single_StaticSprite.png"),
    ASSET_09_WEAPON_BULLET_TYPEG_VARIANTA_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/09_Weapon_Bullet_TypeG_VariantA_StaticSprite.png"),
    ASSET_10_WEAPON_BULLET_TYPEG_VARIANTB_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/10_Weapon_Bullet_TypeG_VariantB_StaticSprite.png"),
    ASSET_11_WEAPON_BULLET_TYPEH_SINGLE_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/11_Weapon_Bullet_TypeH_Single_StaticSprite.png"),
    ASSET_12_WEAPON_BULLET_TYPEI_SINGLE_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/12_Weapon_Bullet_TypeI_Single_StaticSprite.png"),
    ASSET_13_WEAPON_BULLET_TYPEJ_SINGLE_STATICSPRITE("Resources/industrial-zone/weapons/1/5 Bullets/13_Weapon_Bullet_TypeJ_Single_StaticSprite.png"),
    ASSET_IDLE1("Resources/industrial-zone/weapons/2/1 Characters/1 Biker/Idle1.png"),
    ASSET_IDLE2("Resources/industrial-zone/weapons/2/1 Characters/1 Biker/Idle2.png"),
    ASSET_JUMP1("Resources/industrial-zone/weapons/2/1 Characters/1 Biker/Jump1.png"),
    ASSET_JUMP2("Resources/industrial-zone/weapons/2/1 Characters/1 Biker/Jump2.png"),
    ASSET_RUN1("Resources/industrial-zone/weapons/2/1 Characters/1 Biker/Run1.png"),
    ASSET_RUN2("Resources/industrial-zone/weapons/2/1 Characters/1 Biker/Run2.png"),
    ASSET_SITDOWN1("Resources/industrial-zone/weapons/2/1 Characters/1 Biker/Sitdown1.png"),
    ASSET_SITDOWN2("Resources/industrial-zone/weapons/2/1 Characters/1 Biker/Sitdown2.png"),
    ASSET_WALK1("Resources/industrial-zone/weapons/2/1 Characters/1 Biker/Walk1.png"),
    ASSET_WALK2("Resources/industrial-zone/weapons/2/1 Characters/1 Biker/Walk2.png"),
    ASSET_IDLE1("Resources/industrial-zone/weapons/2/1 Characters/2 Punk/Idle1.png"),
    ASSET_IDLE2("Resources/industrial-zone/weapons/2/1 Characters/2 Punk/Idle2.png"),
    ASSET_JUMP1("Resources/industrial-zone/weapons/2/1 Characters/2 Punk/Jump1.png"),
    ASSET_JUMP2("Resources/industrial-zone/weapons/2/1 Characters/2 Punk/Jump2.png"),
    ASSET_RUN1("Resources/industrial-zone/weapons/2/1 Characters/2 Punk/Run1.png"),
    ASSET_RUN2("Resources/industrial-zone/weapons/2/1 Characters/2 Punk/Run2.png"),
    ASSET_SITDOWN1("Resources/industrial-zone/weapons/2/1 Characters/2 Punk/Sitdown1.png"),
    ASSET_SITDOWN2("Resources/industrial-zone/weapons/2/1 Characters/2 Punk/Sitdown2.png"),
    ASSET_WALK1("Resources/industrial-zone/weapons/2/1 Characters/2 Punk/Walk1.png"),
    ASSET_WALK2("Resources/industrial-zone/weapons/2/1 Characters/2 Punk/Walk2.png"),
    ASSET_IDLE1("Resources/industrial-zone/weapons/2/1 Characters/3 Cyborg/Idle1.png"),
    ASSET_IDLE2("Resources/industrial-zone/weapons/2/1 Characters/3 Cyborg/Idle2.png"),
    ASSET_JUMP1("Resources/industrial-zone/weapons/2/1 Characters/3 Cyborg/Jump1.png"),
    ASSET_JUMP2("Resources/industrial-zone/weapons/2/1 Characters/3 Cyborg/Jump2.png"),
    ASSET_RUN1("Resources/industrial-zone/weapons/2/1 Characters/3 Cyborg/Run1.png"),
    ASSET_RUN2("Resources/industrial-zone/weapons/2/1 Characters/3 Cyborg/Run2.png"),
    ASSET_SITDOWN1("Resources/industrial-zone/weapons/2/1 Characters/3 Cyborg/Sitdown1.png"),
    ASSET_SITDOWN2("Resources/industrial-zone/weapons/2/1 Characters/3 Cyborg/Sitdown2.png"),
    ASSET_WALK1("Resources/industrial-zone/weapons/2/1 Characters/3 Cyborg/Walk1.png"),
    ASSET_WALK2("Resources/industrial-zone/weapons/2/1 Characters/3 Cyborg/Walk2.png"),
    ASSET_10_1("Resources/industrial-zone/weapons/2/2 Guns/10_1.png"),
    ASSET_10_2("Resources/industrial-zone/weapons/2/2 Guns/10_2.png"),
    ASSET_1_1("Resources/industrial-zone/weapons/2/2 Guns/1_1.png"),
    ASSET_1_2("Resources/industrial-zone/weapons/2/2 Guns/1_2.png"),
    ASSET_2_1("Resources/industrial-zone/weapons/2/2 Guns/2_1.png"),
    ASSET_2_2("Resources/industrial-zone/weapons/2/2 Guns/2_2.png"),
    ASSET_3_1("Resources/industrial-zone/weapons/2/2 Guns/3_1.png"),
    ASSET_3_2("Resources/industrial-zone/weapons/2/2 Guns/3_2.png"),
    ASSET_4_1("Resources/industrial-zone/weapons/2/2 Guns/4_1.png"),
    ASSET_4_2("Resources/industrial-zone/weapons/2/2 Guns/4_2.png"),
    ASSET_5_1("Resources/industrial-zone/weapons/2/2 Guns/5_1.png"),
    ASSET_5_2("Resources/industrial-zone/weapons/2/2 Guns/5_2.png"),
    ASSET_6_1("Resources/industrial-zone/weapons/2/2 Guns/6_1.png"),
    ASSET_6_2("Resources/industrial-zone/weapons/2/2 Guns/6_2.png"),
    ASSET_7_1("Resources/industrial-zone/weapons/2/2 Guns/7_1.png"),
    ASSET_7_2("Resources/industrial-zone/weapons/2/2 Guns/7_2.png"),
    ASSET_8_1("Resources/industrial-zone/weapons/2/2 Guns/8_1.png"),
    ASSET_8_2("Resources/industrial-zone/weapons/2/2 Guns/8_2.png"),
    ASSET_9_1("Resources/industrial-zone/weapons/2/2 Guns/9_1.png"),
    ASSET_9_2("Resources/industrial-zone/weapons/2/2 Guns/9_2.png"),
    ASSET_1("Resources/industrial-zone/weapons/2/3 Hands/1 Biker/1.png"),
    ASSET_10("Resources/industrial-zone/weapons/2/3 Hands/1 Biker/10.png"),
    ASSET_2("Resources/industrial-zone/weapons/2/3 Hands/1 Biker/2.png"),
    ASSET_3("Resources/industrial-zone/weapons/2/3 Hands/1 Biker/3.png"),
    ASSET_4("Resources/industrial-zone/weapons/2/3 Hands/1 Biker/4.png"),
    ASSET_5("Resources/industrial-zone/weapons/2/3 Hands/1 Biker/5.png"),
    ASSET_6("Resources/industrial-zone/weapons/2/3 Hands/1 Biker/6.png"),
    ASSET_7("Resources/industrial-zone/weapons/2/3 Hands/1 Biker/7.png"),
    ASSET_8("Resources/industrial-zone/weapons/2/3 Hands/1 Biker/8.png"),
    ASSET_9("Resources/industrial-zone/weapons/2/3 Hands/1 Biker/9.png"),
    ASSET_1("Resources/industrial-zone/weapons/2/3 Hands/2 Punk/1.png"),
    ASSET_10("Resources/industrial-zone/weapons/2/3 Hands/2 Punk/10.png"),
    ASSET_2("Resources/industrial-zone/weapons/2/3 Hands/2 Punk/2.png"),
    ASSET_3("Resources/industrial-zone/weapons/2/3 Hands/2 Punk/3.png"),
    ASSET_4("Resources/industrial-zone/weapons/2/3 Hands/2 Punk/4.png"),
    ASSET_5("Resources/industrial-zone/weapons/2/3 Hands/2 Punk/5.png"),
    ASSET_6("Resources/industrial-zone/weapons/2/3 Hands/2 Punk/6.png"),
    ASSET_7("Resources/industrial-zone/weapons/2/3 Hands/2 Punk/7.png"),
    ASSET_8("Resources/industrial-zone/weapons/2/3 Hands/2 Punk/8.png"),
    ASSET_9("Resources/industrial-zone/weapons/2/3 Hands/2 Punk/9.png"),
    ASSET_1("Resources/industrial-zone/weapons/2/3 Hands/3 Cyborg/1.png"),
    ASSET_10("Resources/industrial-zone/weapons/2/3 Hands/3 Cyborg/10.png"),
    ASSET_2("Resources/industrial-zone/weapons/2/3 Hands/3 Cyborg/2.png"),
    ASSET_3("Resources/industrial-zone/weapons/2/3 Hands/3 Cyborg/3.png"),
    ASSET_4("Resources/industrial-zone/weapons/2/3 Hands/3 Cyborg/4.png"),
    ASSET_5("Resources/industrial-zone/weapons/2/3 Hands/3 Cyborg/5.png"),
    ASSET_6("Resources/industrial-zone/weapons/2/3 Hands/3 Cyborg/6.png"),
    ASSET_7("Resources/industrial-zone/weapons/2/3 Hands/3 Cyborg/7.png"),
    ASSET_8("Resources/industrial-zone/weapons/2/3 Hands/3 Cyborg/8.png"),
    ASSET_9("Resources/industrial-zone/weapons/2/3 Hands/3 Cyborg/9.png"),
    ASSET_10_1("Resources/industrial-zone/weapons/2/4 Shoot_effects/10_1.png"),
    ASSET_10_2("Resources/industrial-zone/weapons/2/4 Shoot_effects/10_2.png"),
    ASSET_6_1("Resources/industrial-zone/weapons/2/4 Shoot_effects/6_1.png"),
    ASSET_6_2("Resources/industrial-zone/weapons/2/4 Shoot_effects/6_2.png"),
    ASSET_7_1("Resources/industrial-zone/weapons/2/4 Shoot_effects/7_1.png"),
    ASSET_7_2("Resources/industrial-zone/weapons/2/4 Shoot_effects/7_2.png"),
    ASSET_8_1("Resources/industrial-zone/weapons/2/4 Shoot_effects/8_1.png"),
    ASSET_8_2("Resources/industrial-zone/weapons/2/4 Shoot_effects/8_2.png"),
    ASSET_9_1("Resources/industrial-zone/weapons/2/4 Shoot_effects/9_1.png"),
    ASSET_9_2("Resources/industrial-zone/weapons/2/4 Shoot_effects/9_2.png"),
    ASSET_1("Resources/industrial-zone/weapons/2/5 Bullets/1.png"),
    ASSET_10("Resources/industrial-zone/weapons/2/5 Bullets/10.png"),
    ASSET_10_2("Resources/industrial-zone/weapons/2/5 Bullets/10_2.png"),
    ASSET_1_2("Resources/industrial-zone/weapons/2/5 Bullets/1_2.png"),
    ASSET_2("Resources/industrial-zone/weapons/2/5 Bullets/2.png"),
    ASSET_2_2("Resources/industrial-zone/weapons/2/5 Bullets/2_2.png"),
    ASSET_3("Resources/industrial-zone/weapons/2/5 Bullets/3.png"),
    ASSET_3_2("Resources/industrial-zone/weapons/2/5 Bullets/3_2.png"),
    ASSET_4("Resources/industrial-zone/weapons/2/5 Bullets/4.png"),
    ASSET_4_2("Resources/industrial-zone/weapons/2/5 Bullets/4_2.png"),
    ASSET_5("Resources/industrial-zone/weapons/2/5 Bullets/5.png"),
    ASSET_5_2("Resources/industrial-zone/weapons/2/5 Bullets/5_2.png"),
    ASSET_6("Resources/industrial-zone/weapons/2/5 Bullets/6.png"),
    ASSET_6_2("Resources/industrial-zone/weapons/2/5 Bullets/6_2.png"),
    ASSET_7("Resources/industrial-zone/weapons/2/5 Bullets/7.png"),
    ASSET_7_2("Resources/industrial-zone/weapons/2/5 Bullets/7_2.png"),
    ASSET_8("Resources/industrial-zone/weapons/2/5 Bullets/8.png"),
    ASSET_9("Resources/industrial-zone/weapons/2/5 Bullets/9.png"),
    ASSET_9_2("Resources/industrial-zone/weapons/2/5 Bullets/9_2.png")
;
}
