package assets.vfx;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: vfx/2 Blood
 * Total assets: 8
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class BloodVfxAssets {

    private static final String DIR = "Resources/industrial-zone/vfx/2 Blood/";

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_BLOOD_SPLATTER_SMALLWIDESPREAD_IMPACT = SpriteAsset.once(
        "01_VFX_Blood_Splatter_4Frames1Row_SmallWideSpread_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 01 VFX Blood Splatter 4Frames1Row SmallWideSpread Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_BLOOD_SPLATTER_SMALLLOOSEPARTICLES_IMPACT = SpriteAsset.once(
        "02_VFX_Blood_Splatter_4Frames1Row_SmallLooseParticles_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 02 VFX Blood Splatter 4Frames1Row SmallLooseParticles Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_BLOOD_SPLATTER_MEDIUMBLOBSHAPES_IMPACT = SpriteAsset.once(
        "03_VFX_Blood_Splatter_4Frames1Row_MediumBlobShapes_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 03 VFX Blood Splatter 4Frames1Row MediumBlobShapes Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_BLOOD_SPLATTER_TINYFINEDOTS_IMPACT = SpriteAsset.once(
        "04_VFX_Blood_Splatter_4Frames1Row_TinyFineDots_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 04 VFX Blood Splatter 4Frames1Row TinyFineDots Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_BLOOD_SPLATTER_MEDIUMCHUNKS_IMPACT = SpriteAsset.once(
        "05_VFX_Blood_Splatter_4Frames1Row_MediumChunks_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 05 VFX Blood Splatter 4Frames1Row MediumChunks Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_BLOOD_SPLATTER_LARGEBOLDIMPACT_IMPACT = SpriteAsset.once(
        "06_VFX_Blood_Splatter_4Frames1Row_LargeBoldImpact_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 06 VFX Blood Splatter 4Frames1Row LargeBoldImpact Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_BLOOD_SPLATTER_HORIZONTALELONGATED_IMPACT = SpriteAsset.once(
        "07_VFX_Blood_Splatter_4Frames1Row_HorizontalElongated_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 07 VFX Blood Splatter 4Frames1Row HorizontalElongated Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_BLOOD_SPLATTER_ARCSWIPESHAPE_IMPACT = SpriteAsset.once(
        "08_VFX_Blood_Splatter_4Frames1Row_ArcSwipeShape_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 08 VFX Blood Splatter 4Frames1Row ArcSwipeShape Impact PlayOnce 80ms");

    /** Total number of assets in this group */
    public static final int COUNT = 8;

    private BloodVfxAssets() { } // no instantiation
}
