package assets.vfx;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: vfx/6 Extra/Character
 * Total assets: 24
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class ExtraVfxAssets {

    private static final String DIR = "Resources/industrial-zone/vfx/6 Extra/Character/";

    /** 28x28px | static | 100ms/f */
    public static final SpriteAsset VFX_BOX1_DESTROY_FRAME01_CRATEINTACT_DESTROYANIM = SpriteAsset.once(
        "01_VFX_Box1_Destroy_Frame01_CrateIntact_DestroyAnim_PlayOnce_100ms.png",
        DIR, 28, 28, 100,
        "Visual Effect - 01 VFX Box1 Destroy Frame01 CrateIntact DestroyAnim PlayOnce 100ms");

    /** 27x20px | static | 100ms/f */
    public static final SpriteAsset VFX_BUSH_FRAME01_LARGEFULLBUSH_DECOORDESTROY = SpriteAsset.once(
        "01_VFX_Bush_Frame01_LargeFullBush_DecoOrDestroy_PlayOnce_100ms.png",
        DIR, 27, 20, 100,
        "Visual Effect - 01 VFX Bush Frame01 LargeFullBush DecoOrDestroy PlayOnce 100ms");

    /** 50x48px | ~1 frames | 100ms/f */
    public static final SpriteAsset VFX_CAPSULE_FRAME01_CAPSULEINTACT_DESTROYANIM = SpriteAsset.once(
        "01_VFX_Capsule_Frame01_CapsuleIntact_DestroyAnim_PlayOnce_100ms.png",
        DIR, 50, 48, 100,
        "Visual Effect - 01 VFX Capsule Frame01 CapsuleIntact DestroyAnim PlayOnce 100ms");

    /** 288x48px | ~6 frames | 120ms/f */
    public static final SpriteAsset VFX_CHAR_BIKER_DEATH_DEATHTUMBLECOLOURVFX = SpriteAsset.once(
        "01_VFX_Char_Biker_Death_6Frames1Row_DeathTumbleColourVFX_PlayOnce_120ms.png",
        DIR, 288, 48, 120,
        "Visual Effect - 01 VFX Char Biker Death 6Frames1Row DeathTumbleColourVFX PlayOnce 120ms");

    /** 28x28px | static | 100ms/f */
    public static final SpriteAsset VFX_BOX1_DESTROY_FRAME02_CRATESLIGHTDAMAGE_DESTROYANIM = SpriteAsset.once(
        "02_VFX_Box1_Destroy_Frame02_CrateSlightDamage_DestroyAnim_PlayOnce_100ms.png",
        DIR, 28, 28, 100,
        "Visual Effect - 02 VFX Box1 Destroy Frame02 CrateSlightDamage DestroyAnim PlayOnce 100ms");

    /** 21x14px | static | 100ms/f */
    public static final SpriteAsset VFX_BUSH_FRAME02_MEDIUMBUSH_DECOORDESTROY = SpriteAsset.once(
        "02_VFX_Bush_Frame02_MediumBush_DecoOrDestroy_PlayOnce_100ms.png",
        DIR, 21, 14, 100,
        "Visual Effect - 02 VFX Bush Frame02 MediumBush DecoOrDestroy PlayOnce 100ms");

    /** 50x48px | ~1 frames | 100ms/f */
    public static final SpriteAsset VFX_CAPSULE_FRAME02_CAPSULECRACKED_DESTROYANIM = SpriteAsset.once(
        "02_VFX_Capsule_Frame02_CapsuleCracked_DestroyAnim_PlayOnce_100ms.png",
        DIR, 50, 48, 100,
        "Visual Effect - 02 VFX Capsule Frame02 CapsuleCracked DestroyAnim PlayOnce 100ms");

    /** 288x48px | ~6 frames | 80ms/f */
    public static final SpriteAsset VFX_CHAR_BIKER_DOUBLEJUMP_MIDAIRFLIPCOLOURVFX = SpriteAsset.once(
        "02_VFX_Char_Biker_DoubleJump_6Frames1Row_MidAirFlipColourVFX_PlayOnce_80ms.png",
        DIR, 288, 48, 80,
        "Visual Effect - 02 VFX Char Biker DoubleJump 6Frames1Row MidAirFlipColourVFX PlayOnce 80ms");

    /** 28x28px | static | 100ms/f */
    public static final SpriteAsset VFX_BOX1_DESTROY_FRAME03_CRATEBREAKING_DESTROYANIM = SpriteAsset.once(
        "03_VFX_Box1_Destroy_Frame03_CrateBreaking_DestroyAnim_PlayOnce_100ms.png",
        DIR, 28, 28, 100,
        "Visual Effect - 03 VFX Box1 Destroy Frame03 CrateBreaking DestroyAnim PlayOnce 100ms");

    /** 21x11px | static | 100ms/f */
    public static final SpriteAsset VFX_BUSH_FRAME03_SMALLBUSH_DECOORDESTROY = SpriteAsset.once(
        "03_VFX_Bush_Frame03_SmallBush_DecoOrDestroy_PlayOnce_100ms.png",
        DIR, 21, 11, 100,
        "Visual Effect - 03 VFX Bush Frame03 SmallBush DecoOrDestroy PlayOnce 100ms");

    /** 50x48px | ~1 frames | 100ms/f */
    public static final SpriteAsset VFX_CAPSULE_FRAME03_CAPSULEBREAKING_DESTROYANIM = SpriteAsset.once(
        "03_VFX_Capsule_Frame03_CapsuleBreaking_DestroyAnim_PlayOnce_100ms.png",
        DIR, 50, 48, 100,
        "Visual Effect - 03 VFX Capsule Frame03 CapsuleBreaking DestroyAnim PlayOnce 100ms");

    /** 96x48px | ~2 frames | 100ms/f */
    public static final SpriteAsset VFX_CHAR_BIKER_HURT_HURTFLINCHREDGHOSTVFX = SpriteAsset.once(
        "03_VFX_Char_Biker_Hurt_2Frames1Row_HurtFlinchRedGhostVFX_PlayOnce_100ms.png",
        DIR, 96, 48, 100,
        "Visual Effect - 03 VFX Char Biker Hurt 2Frames1Row HurtFlinchRedGhostVFX PlayOnce 100ms");

    /** 28x28px | static | 100ms/f */
    public static final SpriteAsset VFX_BOX1_DESTROY_FRAME04_CRATEMOSTLYGONE_DESTROYANIM = SpriteAsset.once(
        "04_VFX_Box1_Destroy_Frame04_CrateMostlyGone_DestroyAnim_PlayOnce_100ms.png",
        DIR, 28, 28, 100,
        "Visual Effect - 04 VFX Box1 Destroy Frame04 CrateMostlyGone DestroyAnim PlayOnce 100ms");

    /** 10x6px | static | 100ms/f */
    public static final SpriteAsset VFX_BUSH_FRAME04_TINYBUSHSHRUB_DECOORDESTROY = SpriteAsset.once(
        "04_VFX_Bush_Frame04_TinyBushShrub_DecoOrDestroy_PlayOnce_100ms.png",
        DIR, 10, 6, 100,
        "Visual Effect - 04 VFX Bush Frame04 TinyBushShrub DecoOrDestroy PlayOnce 100ms");

    /** 50x48px | ~1 frames | 100ms/f */
    public static final SpriteAsset VFX_CAPSULE_FRAME04_CAPSULEDEBRISFLAT_DESTROYANIM = SpriteAsset.once(
        "04_VFX_Capsule_Frame04_CapsuleDebrisFlat_DestroyAnim_PlayOnce_100ms.png",
        DIR, 50, 48, 100,
        "Visual Effect - 04 VFX Capsule Frame04 CapsuleDebrisFlat DestroyAnim PlayOnce 100ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_CHAR_BIKER_JUMP_JUMPARCCOLOURVFX = SpriteAsset.once(
        "04_VFX_Char_Biker_Jump_4Frames1Row_JumpArcColourVFX_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 04 VFX Char Biker Jump 4Frames1Row JumpArcColourVFX PlayOnce 80ms");

    /** 28x28px | static | 100ms/f */
    public static final SpriteAsset VFX_BOX1_DESTROY_FRAME05_CRATEDEBRISFLAT_DESTROYANIM = SpriteAsset.once(
        "05_VFX_Box1_Destroy_Frame05_CrateDebrisFlat_DestroyAnim_PlayOnce_100ms.png",
        DIR, 28, 28, 100,
        "Visual Effect - 05 VFX Box1 Destroy Frame05 CrateDebrisFlat DestroyAnim PlayOnce 100ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_CHAR_BIKER_RUN_RUNCYCLECOLOURVFX = SpriteAsset.loop(
        "05_VFX_Char_Biker_Run_5Frames1Row_RunCycleColourVFX_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Visual Effect - 05 VFX Char Biker Run 5Frames1Row RunCycleColourVFX Loop 80ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_CHAR_GENERIC_FALL_ARMSUPFALLVFX = SpriteAsset.loop(
        "06_VFX_Char_Generic_Fall_4Frames1Row_ArmsUpFallVFX_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 06 VFX Char Generic Fall 4Frames1Row ArmsUpFallVFX Loop 100ms");

    /** 96x48px | ~2 frames | 100ms/f */
    public static final SpriteAsset VFX_CHAR_GENERIC_HURT_HURTFLASHVFX = SpriteAsset.once(
        "07_VFX_Char_Generic_Hurt_2Frames1Row_HurtFlashVFX_PlayOnce_100ms.png",
        DIR, 96, 48, 100,
        "Visual Effect - 07 VFX Char Generic Hurt 2Frames1Row HurtFlashVFX PlayOnce 100ms");

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_CHAR_GENERIC_WALK_WALKCYCLECOLOURVFX = SpriteAsset.loop(
        "08_VFX_Char_Generic_Walk_5Frames1Row_WalkCycleColourVFX_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Visual Effect - 08 VFX Char Generic Walk 5Frames1Row WalkCycleColourVFX Loop 100ms");

    /** 32x32px | static */
    public static final SpriteAsset A_1 = SpriteAsset.single(
        "1.png",
        DIR, 32, 32,
        "Asset - 1");

    /** 32x32px | static */
    public static final SpriteAsset A_2 = SpriteAsset.single(
        "2.png",
        DIR, 32, 32,
        "Asset - 2");

    /** 32x32px | static */
    public static final SpriteAsset A_3 = SpriteAsset.single(
        "3.png",
        DIR, 32, 32,
        "Asset - 3");

    /** Total number of assets in this group */
    public static final int COUNT = 24;

    private ExtraVfxAssets() { } // no instantiation
}
