package assets.vfx;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: vfx/5 Other
 * Total assets: 12
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class OtherVfxAssets {

    private static final String DIR = "Resources/industrial-zone/vfx/5 Other/";

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_STARS_BURST_TINYGOLDSPARSE_AMBIENT = SpriteAsset.loop(
        "01_VFX_Stars_Burst_6Frames1Row_TinyGoldSparse_Ambient_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Visual Effect - 01 VFX Stars Burst 6Frames1Row TinyGoldSparse Ambient Loop 100ms");

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_STARS_BURST_SMALLGOLDUNIFORM_AMBIENT = SpriteAsset.loop(
        "02_VFX_Stars_Burst_6Frames1Row_SmallGoldUniform_Ambient_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Visual Effect - 02 VFX Stars Burst 6Frames1Row SmallGoldUniform Ambient Loop 100ms");

    /** 384x48px | ~8 frames | 80ms/f */
    public static final SpriteAsset VFX_STARS_BURST_MULTISIZEGROWSEQUENCE_IMPACT = SpriteAsset.once(
        "03_VFX_Stars_Burst_14Frames1Row_MultiSizeGrowSequence_Impact_PlayOnce_80ms.png",
        DIR, 384, 48, 80,
        "Visual Effect - 03 VFX Stars Burst 14Frames1Row MultiSizeGrowSequence Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_STARS_BURST_SMALLSTARMORPH_AMBIENT = SpriteAsset.loop(
        "04_VFX_Stars_Burst_4Frames1Row_SmallStarMorph_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 04 VFX Stars Burst 4Frames1Row SmallStarMorph Ambient Loop 100ms");

    /** 288x48px | ~6 frames | 80ms/f */
    public static final SpriteAsset VFX_CYANSHARDS_SCATTER_ENERGYSHARDSCATTERED_IMPACT = SpriteAsset.once(
        "05_VFX_CyanShards_Scatter_8Frames1Row_EnergyShardScattered_Impact_PlayOnce_80ms.png",
        DIR, 288, 48, 80,
        "Visual Effect - 05 VFX CyanShards Scatter 8Frames1Row EnergyShardScattered Impact PlayOnce 80ms");

    /** 288x48px | ~6 frames | 80ms/f */
    public static final SpriteAsset VFX_CYANSHARDS_SCATTER_ENERGYLINESSPARSE_IMPACT = SpriteAsset.once(
        "06_VFX_CyanShards_Scatter_6Frames1Row_EnergyLinesSparse_Impact_PlayOnce_80ms.png",
        DIR, 288, 48, 80,
        "Visual Effect - 06 VFX CyanShards Scatter 6Frames1Row EnergyLinesSparse Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_CYANSHARDS_SCATTER_CROSSSHARDVERYSPARSE_IMPACT = SpriteAsset.once(
        "07_VFX_CyanShards_Scatter_4Frames1Row_CrossShardVerySparse_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 07 VFX CyanShards Scatter 4Frames1Row CrossShardVerySparse Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_CYANSHARDS_SCATTER_GROUNDENERGYSHAPES_IMPACT = SpriteAsset.once(
        "08_VFX_CyanShards_Scatter_4Frames1Row_GroundEnergyShapes_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 08 VFX CyanShards Scatter 4Frames1Row GroundEnergyShapes Impact PlayOnce 80ms");

    /** 576x96px | ~6 frames | 100ms/f */
    public static final SpriteAsset VFX_PORTAL_FRAME01_LARGEPORTALOPENINGA_PORTAL = SpriteAsset.once(
        "09_VFX_Portal_Frame01_LargePortalOpeningA_Portal_PlayOnce_100ms.png",
        DIR, 576, 96, 100,
        "Visual Effect - 09 VFX Portal Frame01 LargePortalOpeningA Portal PlayOnce 100ms");

    /** 576x96px | ~6 frames | 100ms/f */
    public static final SpriteAsset VFX_PORTAL_FRAME02_LARGEPORTALOPENINGB_PORTAL = SpriteAsset.once(
        "10_VFX_Portal_Frame02_LargePortalOpeningB_Portal_PlayOnce_100ms.png",
        DIR, 576, 96, 100,
        "Visual Effect - 10 VFX Portal Frame02 LargePortalOpeningB Portal PlayOnce 100ms");

    /** 576x96px | ~6 frames | 120ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_WISPS_TALLTEALWISPVARIANTA_AMBIENT = SpriteAsset.loop(
        "11_VFX_Smoke_Wisps_6Frames1Row_TallTealWispVariantA_Ambient_Loop_120ms.png",
        DIR, 576, 96, 120,
        "Visual Effect - 11 VFX Smoke Wisps 6Frames1Row TallTealWispVariantA Ambient Loop 120ms");

    /** 576x96px | ~6 frames | 120ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_WISPS_TALLTEALWISPVARIANTB_AMBIENT = SpriteAsset.loop(
        "12_VFX_Smoke_Wisps_6Frames1Row_TallTealWispVariantB_Ambient_Loop_120ms.png",
        DIR, 576, 96, 120,
        "Visual Effect - 12 VFX Smoke Wisps 6Frames1Row TallTealWispVariantB Ambient Loop 120ms");

    /** Total number of assets in this group */
    public static final int COUNT = 12;

    private OtherVfxAssets() { } // no instantiation
}
