package assets.vfx;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: vfx/4 Particles
 * Total assets: 12
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class ParticleVfxAssets {

    private static final String DIR = "Resources/industrial-zone/vfx/4 Particles/";

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_GREEN_TINYGREENSPARSE_AMBIENT = SpriteAsset.loop(
        "01_VFX_Particles_Green_4Frames1Row_TinyGreenSparse_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 01 VFX Particles Green 4Frames1Row TinyGreenSparse Ambient Loop 100ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_GREEN_SMALLGREENMEDIUM_AMBIENT = SpriteAsset.loop(
        "02_VFX_Particles_Green_4Frames1Row_SmallGreenMedium_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 02 VFX Particles Green 4Frames1Row SmallGreenMedium Ambient Loop 100ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_GREEN_GREENWIDESPREAD_AMBIENT = SpriteAsset.loop(
        "03_VFX_Particles_Green_4Frames1Row_GreenWideSpread_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 03 VFX Particles Green 4Frames1Row GreenWideSpread Ambient Loop 100ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_BLUE_TINYBLUESPARSE_AMBIENT = SpriteAsset.loop(
        "04_VFX_Particles_Blue_4Frames1Row_TinyBlueSparse_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 04 VFX Particles Blue 4Frames1Row TinyBlueSparse Ambient Loop 100ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_BLUE_SMALLBLUEMEDIUM_AMBIENT = SpriteAsset.loop(
        "05_VFX_Particles_Blue_4Frames1Row_SmallBlueMedium_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 05 VFX Particles Blue 4Frames1Row SmallBlueMedium Ambient Loop 100ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_BLUE_BLUEWIDESPREAD_AMBIENT = SpriteAsset.loop(
        "06_VFX_Particles_Blue_4Frames1Row_BlueWideSpread_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 06 VFX Particles Blue 4Frames1Row BlueWideSpread Ambient Loop 100ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_ORANGE_TINYORANGESPARSE_AMBIENT = SpriteAsset.loop(
        "07_VFX_Particles_Orange_4Frames1Row_TinyOrangeSparse_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 07 VFX Particles Orange 4Frames1Row TinyOrangeSparse Ambient Loop 100ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_ORANGE_SMALLORANGEMEDIUM_AMBIENT = SpriteAsset.loop(
        "08_VFX_Particles_Orange_4Frames1Row_SmallOrangeMedium_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 08 VFX Particles Orange 4Frames1Row SmallOrangeMedium Ambient Loop 100ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_ORANGE_ORANGEWIDESCATTER_AMBIENT = SpriteAsset.loop(
        "09_VFX_Particles_Orange_4Frames1Row_OrangeWideScatter_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 09 VFX Particles Orange 4Frames1Row OrangeWideScatter Ambient Loop 100ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_YELLOW_TINYYELLOWSPARSE_AMBIENT = SpriteAsset.loop(
        "10_VFX_Particles_Yellow_4Frames1Row_TinyYellowSparse_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 10 VFX Particles Yellow 4Frames1Row TinyYellowSparse Ambient Loop 100ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_YELLOW_SMALLYELLOWMEDIUM_AMBIENT = SpriteAsset.loop(
        "11_VFX_Particles_Yellow_4Frames1Row_SmallYellowMedium_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 11 VFX Particles Yellow 4Frames1Row SmallYellowMedium Ambient Loop 100ms");

    /** 192x48px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset VFX_PARTICLES_YELLOW_YELLOWWIDESCATTER_AMBIENT = SpriteAsset.loop(
        "12_VFX_Particles_Yellow_4Frames1Row_YellowWideScatter_Ambient_Loop_100ms.png",
        DIR, 192, 48, 100,
        "Visual Effect - 12 VFX Particles Yellow 4Frames1Row YellowWideScatter Ambient Loop 100ms");

    /** Total number of assets in this group */
    public static final int COUNT = 12;

    private ParticleVfxAssets() { } // no instantiation
}
