package assets.vfx;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: vfx/1 Smoke
 * Total assets: 18
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class SmokeVfxAssets {

    private static final String DIR = "Resources/industrial-zone/vfx/1 Smoke/";

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME01_DENSETHICKCLOUD_SMOKEANIM = SpriteAsset.loop(
        "01_VFX_Smoke_Frame01_DenseThickCloud_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 01 VFX Smoke Frame01 DenseThickCloud SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME02_DENSECLOUD_SMOKEANIM = SpriteAsset.loop(
        "02_VFX_Smoke_Frame02_DenseCloud_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 02 VFX Smoke Frame02 DenseCloud SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME03_DENSECLOUD_SMOKEANIM = SpriteAsset.loop(
        "03_VFX_Smoke_Frame03_DenseCloud_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 03 VFX Smoke Frame03 DenseCloud SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME04_DENSEWITHWISPS_SMOKEANIM = SpriteAsset.loop(
        "04_VFX_Smoke_Frame04_DenseWithWisps_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 04 VFX Smoke Frame04 DenseWithWisps SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME05_DISSIPATINGWISPS_SMOKEANIM = SpriteAsset.loop(
        "05_VFX_Smoke_Frame05_DissipatingWisps_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 05 VFX Smoke Frame05 DissipatingWisps SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME06_DISSIPATINGLARGER_SMOKEANIM = SpriteAsset.loop(
        "06_VFX_Smoke_Frame06_DissipatingLarger_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 06 VFX Smoke Frame06 DissipatingLarger SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME07_THINNINGCLOUD_SMOKEANIM = SpriteAsset.loop(
        "07_VFX_Smoke_Frame07_ThinningCloud_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 07 VFX Smoke Frame07 ThinningCloud SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME08_SPARSEDOTS_SMOKEANIM = SpriteAsset.loop(
        "08_VFX_Smoke_Frame08_SparseDots_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 08 VFX Smoke Frame08 SparseDots SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME09_VERYSPARSEDOTS_SMOKEANIM = SpriteAsset.loop(
        "09_VFX_Smoke_Frame09_VerySparseDots_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 09 VFX Smoke Frame09 VerySparseDots SmokeAnim Loop 80ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME10_FINEPARTICLES_SMOKEANIM = SpriteAsset.loop(
        "10_VFX_Smoke_Frame10_FineParticles_SmokeAnim_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Visual Effect - 10 VFX Smoke Frame10 FineParticles SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME11_MEDIUMDENSITY_SMOKEANIM = SpriteAsset.loop(
        "11_VFX_Smoke_Frame11_MediumDensity_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 11 VFX Smoke Frame11 MediumDensity SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME12_MEDIUMWISPS_SMOKEANIM = SpriteAsset.loop(
        "12_VFX_Smoke_Frame12_MediumWisps_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 12 VFX Smoke Frame12 MediumWisps SmokeAnim Loop 80ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME13_WIDESPARSE_SMOKEANIM = SpriteAsset.loop(
        "13_VFX_Smoke_Frame13_WideSparse_SmokeAnim_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Visual Effect - 13 VFX Smoke Frame13 WideSparse SmokeAnim Loop 80ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME14_FAINTPARTICLES_SMOKEANIM = SpriteAsset.loop(
        "14_VFX_Smoke_Frame14_FaintParticles_SmokeAnim_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Visual Effect - 14 VFX Smoke Frame14 FaintParticles SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME15_NEARTRANSPARENT_SMOKEANIM = SpriteAsset.loop(
        "15_VFX_Smoke_Frame15_NearTransparent_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 15 VFX Smoke Frame15 NearTransparent SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME16_FADINGTHIN_SMOKEANIM = SpriteAsset.loop(
        "16_VFX_Smoke_Frame16_FadingThin_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 16 VFX Smoke Frame16 FadingThin SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME17_ALMOSTGONE_SMOKEANIM = SpriteAsset.loop(
        "17_VFX_Smoke_Frame17_AlmostGone_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 17 VFX Smoke Frame17 AlmostGone SmokeAnim Loop 80ms");

    /** 192x48px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset VFX_SMOKE_FRAME18_LASTFAINTEST_SMOKEANIM = SpriteAsset.loop(
        "18_VFX_Smoke_Frame18_LastFaintest_SmokeAnim_Loop_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 18 VFX Smoke Frame18 LastFaintest SmokeAnim Loop 80ms");

    /** Total number of assets in this group */
    public static final int COUNT = 18;

    private SmokeVfxAssets() { } // no instantiation
}
