package assets.vfx;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: vfx/3 Sparks
 * Total assets: 8
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class SparkVfxAssets {

    private static final String DIR = "Resources/industrial-zone/vfx/3 Sparks/";

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_SPARKS_BURST_SMALLSPARSEGOLD_IMPACT = SpriteAsset.once(
        "01_VFX_Sparks_Burst_4Frames1Row_SmallSparseGold_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 01 VFX Sparks Burst 4Frames1Row SmallSparseGold Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_SPARKS_BURST_SMALLDENSEGOLD_IMPACT = SpriteAsset.once(
        "02_VFX_Sparks_Burst_4Frames1Row_SmallDenseGold_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 02 VFX Sparks Burst 4Frames1Row SmallDenseGold Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_SPARKS_BURST_WIDETHINSCATTER_IMPACT = SpriteAsset.once(
        "03_VFX_Sparks_Burst_4Frames1Row_WideThinScatter_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 03 VFX Sparks Burst 4Frames1Row WideThinScatter Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_SPARKS_BURST_SMALLANGLEDUPWARD_IMPACT = SpriteAsset.once(
        "04_VFX_Sparks_Burst_4Frames1Row_SmallAngledUpward_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 04 VFX Sparks Burst 4Frames1Row SmallAngledUpward Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_SPARKS_BURST_MEDIUMBOLDBURST_IMPACT = SpriteAsset.once(
        "05_VFX_Sparks_Burst_4Frames1Row_MediumBoldBurst_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 05 VFX Sparks Burst 4Frames1Row MediumBoldBurst Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_SPARKS_BURST_TINYFAINTTRAIL_IMPACT = SpriteAsset.once(
        "06_VFX_Sparks_Burst_4Frames1Row_TinyFaintTrail_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 06 VFX Sparks Burst 4Frames1Row TinyFaintTrail Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_SPARKS_BURST_MEDIUMMIXEDANGLES_IMPACT = SpriteAsset.once(
        "07_VFX_Sparks_Burst_4Frames1Row_MediumMixedAngles_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 07 VFX Sparks Burst 4Frames1Row MediumMixedAngles Impact PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset VFX_SPARKS_BURST_LARGEWIDESCATTER_IMPACT = SpriteAsset.once(
        "08_VFX_Sparks_Burst_4Frames1Row_LargeWideScatter_Impact_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Visual Effect - 08 VFX Sparks Burst 4Frames1Row LargeWideScatter Impact PlayOnce 80ms");

    /** Total number of assets in this group */
    public static final int COUNT = 8;

    private SparkVfxAssets() { } // no instantiation
}
