package assets.weapons;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: weapons/1/3 Hands/1 Biker
 * Total assets: 30
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class WeaponSet1HandAssets {

    private static final String DIR = "Resources/industrial-zone/weapons/1/3 Hands/1 Biker/";

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_BIKER_GRIPHORIZONTAL_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "01_Weapon_Hand_Biker_GripHorizontal_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 01 Weapon Hand Biker GripHorizontal WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_CYBORG_GRIPVERTICAL_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "01_Weapon_Hand_Cyborg_GripVertical_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 01 Weapon Hand Cyborg GripVertical WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_PUNK_GRIPVERTICAL_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "01_Weapon_Hand_Punk_GripVertical_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 01 Weapon Hand Punk GripVertical WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_BIKER_GRIPDIAGONALDOWN_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "02_Weapon_Hand_Biker_GripDiagonalDown_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 02 Weapon Hand Biker GripDiagonalDown WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_CYBORG_GRIPDIAGONALDOWN_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "02_Weapon_Hand_Cyborg_GripDiagonalDown_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 02 Weapon Hand Cyborg GripDiagonalDown WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_PUNK_GRIPDIAGONALDOWN_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "02_Weapon_Hand_Punk_GripDiagonalDown_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 02 Weapon Hand Punk GripDiagonalDown WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_BIKER_GRIPVERTICALUP_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "03_Weapon_Hand_Biker_GripVerticalUp_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 03 Weapon Hand Biker GripVerticalUp WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_CYBORG_GRIPHORIZONTAL_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "03_Weapon_Hand_Cyborg_GripHorizontal_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 03 Weapon Hand Cyborg GripHorizontal WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_PUNK_GRIPHORIZONTAL_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "03_Weapon_Hand_Punk_GripHorizontal_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 03 Weapon Hand Punk GripHorizontal WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_BIKER_GRIPVERTICALALT_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "04_Weapon_Hand_Biker_GripVerticalAlt_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 04 Weapon Hand Biker GripVerticalAlt WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_CYBORG_GRIPDIAGONALALT_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "04_Weapon_Hand_Cyborg_GripDiagonalAlt_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 04 Weapon Hand Cyborg GripDiagonalAlt WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_PUNK_GRIPDIAGONALALT_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "04_Weapon_Hand_Punk_GripDiagonalAlt_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 04 Weapon Hand Punk GripDiagonalAlt WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_BIKER_GRIPANGLEDOWN_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "05_Weapon_Hand_Biker_GripAngleDown_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 05 Weapon Hand Biker GripAngleDown WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_CYBORG_GRIPVERTICALUP_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "05_Weapon_Hand_Cyborg_GripVerticalUp_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 05 Weapon Hand Cyborg GripVerticalUp WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_PUNK_GRIPVERTICALUP_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "05_Weapon_Hand_Punk_GripVerticalUp_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 05 Weapon Hand Punk GripVerticalUp WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_BIKER_GRIPLOW_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "06_Weapon_Hand_Biker_GripLow_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 06 Weapon Hand Biker GripLow WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_CYBORG_GRIPVERTICALB_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "06_Weapon_Hand_Cyborg_GripVerticalB_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 06 Weapon Hand Cyborg GripVerticalB WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_PUNK_GRIPVERTICALB_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "06_Weapon_Hand_Punk_GripVerticalB_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 06 Weapon Hand Punk GripVerticalB WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_BIKER_GRIPANGLEUPLEFT_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "07_Weapon_Hand_Biker_GripAngleUpLeft_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 07 Weapon Hand Biker GripAngleUpLeft WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_CYBORG_GRIPDIAGONALLONG_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "07_Weapon_Hand_Cyborg_GripDiagonalLong_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 07 Weapon Hand Cyborg GripDiagonalLong WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_PUNK_GRIPDIAGONALLONG_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "07_Weapon_Hand_Punk_GripDiagonalLong_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 07 Weapon Hand Punk GripDiagonalLong WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_BIKER_GRIPVERTICALB_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "08_Weapon_Hand_Biker_GripVerticalB_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 08 Weapon Hand Biker GripVerticalB WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_CYBORG_GRIPHORIZONTALBLUE_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "08_Weapon_Hand_Cyborg_GripHorizontalBlue_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 08 Weapon Hand Cyborg GripHorizontalBlue WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_PUNK_GRIPHORIZONTALRED_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "08_Weapon_Hand_Punk_GripHorizontalRed_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 08 Weapon Hand Punk GripHorizontalRed WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_BIKER_GRIPHORIZONTALB_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "09_Weapon_Hand_Biker_GripHorizontalB_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 09 Weapon Hand Biker GripHorizontalB WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_CYBORG_GRIPCOMPACTANGLE_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "09_Weapon_Hand_Cyborg_GripCompactAngle_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 09 Weapon Hand Cyborg GripCompactAngle WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_PUNK_GRIPCOMPACTANGLE_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "09_Weapon_Hand_Punk_GripCompactAngle_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 09 Weapon Hand Punk GripCompactAngle WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_BIKER_GRIPDIAGONALLONG_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "10_Weapon_Hand_Biker_GripDiagonalLong_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 10 Weapon Hand Biker GripDiagonalLong WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_CYBORG_GRIPLONGBLUE_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "10_Weapon_Hand_Cyborg_GripLongBlue_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 10 Weapon Hand Cyborg GripLongBlue WeaponHoldPose StaticSprite");

    /** 32x32px | static */
    public static final SpriteAsset WEAPON_HAND_PUNK_GRIPLONGBLUERED_WEAPONHOLDPOSE_STATICSPRITE = SpriteAsset.single(
        "10_Weapon_Hand_Punk_GripLongBlueRed_WeaponHoldPose_StaticSprite.png",
        DIR, 32, 32,
        "Sprite - 10 Weapon Hand Punk GripLongBlueRed WeaponHoldPose StaticSprite");

    /** Total number of assets in this group */
    public static final int COUNT = 30;

    private WeaponSet1HandAssets() { } // no instantiation
}
