package assets.weapons;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: weapons/2/3 Hands/1 Biker
 * Total assets: 30
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class WeaponSet2HandAssets {

    private static final String DIR = "Resources/industrial-zone/weapons/2/3 Hands/1 Biker/";

    /** 32x32px | static */
    public static final SpriteAsset A_1 = SpriteAsset.single(
        "1.png",
        DIR, 32, 32,
        "Asset - 1");

    /** 32x32px | static */
    public static final SpriteAsset A_1_2 = SpriteAsset.single(
        "1.png",
        DIR, 32, 32,
        "Asset - 1");

    /** 32x32px | static */
    public static final SpriteAsset A_1_3 = SpriteAsset.single(
        "1.png",
        DIR, 32, 32,
        "Asset - 1");

    /** 32x32px | static */
    public static final SpriteAsset A_10 = SpriteAsset.single(
        "10.png",
        DIR, 32, 32,
        "Asset - 10");

    /** 32x32px | static */
    public static final SpriteAsset A_10_2 = SpriteAsset.single(
        "10.png",
        DIR, 32, 32,
        "Asset - 10");

    /** 32x32px | static */
    public static final SpriteAsset A_10_3 = SpriteAsset.single(
        "10.png",
        DIR, 32, 32,
        "Asset - 10");

    /** 32x32px | static */
    public static final SpriteAsset A_2 = SpriteAsset.single(
        "2.png",
        DIR, 32, 32,
        "Asset - 2");

    /** 32x32px | static */
    public static final SpriteAsset A_2_2 = SpriteAsset.single(
        "2.png",
        DIR, 32, 32,
        "Asset - 2");

    /** 32x32px | static */
    public static final SpriteAsset A_2_3 = SpriteAsset.single(
        "2.png",
        DIR, 32, 32,
        "Asset - 2");

    /** 32x32px | static */
    public static final SpriteAsset A_3 = SpriteAsset.single(
        "3.png",
        DIR, 32, 32,
        "Asset - 3");

    /** 32x32px | static */
    public static final SpriteAsset A_3_2 = SpriteAsset.single(
        "3.png",
        DIR, 32, 32,
        "Asset - 3");

    /** 32x32px | static */
    public static final SpriteAsset A_3_3 = SpriteAsset.single(
        "3.png",
        DIR, 32, 32,
        "Asset - 3");

    /** 32x32px | static */
    public static final SpriteAsset A_4 = SpriteAsset.single(
        "4.png",
        DIR, 32, 32,
        "Asset - 4");

    /** 32x32px | static */
    public static final SpriteAsset A_4_2 = SpriteAsset.single(
        "4.png",
        DIR, 32, 32,
        "Asset - 4");

    /** 32x32px | static */
    public static final SpriteAsset A_4_3 = SpriteAsset.single(
        "4.png",
        DIR, 32, 32,
        "Asset - 4");

    /** 32x32px | static */
    public static final SpriteAsset A_5 = SpriteAsset.single(
        "5.png",
        DIR, 32, 32,
        "Asset - 5");

    /** 32x32px | static */
    public static final SpriteAsset A_5_2 = SpriteAsset.single(
        "5.png",
        DIR, 32, 32,
        "Asset - 5");

    /** 32x32px | static */
    public static final SpriteAsset A_5_3 = SpriteAsset.single(
        "5.png",
        DIR, 32, 32,
        "Asset - 5");

    /** 32x32px | static */
    public static final SpriteAsset A_6 = SpriteAsset.single(
        "6.png",
        DIR, 32, 32,
        "Asset - 6");

    /** 32x32px | static */
    public static final SpriteAsset A_6_2 = SpriteAsset.single(
        "6.png",
        DIR, 32, 32,
        "Asset - 6");

    /** 32x32px | static */
    public static final SpriteAsset A_6_3 = SpriteAsset.single(
        "6.png",
        DIR, 32, 32,
        "Asset - 6");

    /** 32x32px | static */
    public static final SpriteAsset A_7 = SpriteAsset.single(
        "7.png",
        DIR, 32, 32,
        "Asset - 7");

    /** 32x32px | static */
    public static final SpriteAsset A_7_2 = SpriteAsset.single(
        "7.png",
        DIR, 32, 32,
        "Asset - 7");

    /** 32x32px | static */
    public static final SpriteAsset A_7_3 = SpriteAsset.single(
        "7.png",
        DIR, 32, 32,
        "Asset - 7");

    /** 32x32px | static */
    public static final SpriteAsset A_8 = SpriteAsset.single(
        "8.png",
        DIR, 32, 32,
        "Asset - 8");

    /** 32x32px | static */
    public static final SpriteAsset A_8_2 = SpriteAsset.single(
        "8.png",
        DIR, 32, 32,
        "Asset - 8");

    /** 32x32px | static */
    public static final SpriteAsset A_8_3 = SpriteAsset.single(
        "8.png",
        DIR, 32, 32,
        "Asset - 8");

    /** 32x32px | static */
    public static final SpriteAsset A_9 = SpriteAsset.single(
        "9.png",
        DIR, 32, 32,
        "Asset - 9");

    /** 32x32px | static */
    public static final SpriteAsset A_9_2 = SpriteAsset.single(
        "9.png",
        DIR, 32, 32,
        "Asset - 9");

    /** 32x32px | static */
    public static final SpriteAsset A_9_3 = SpriteAsset.single(
        "9.png",
        DIR, 32, 32,
        "Asset - 9");

    /** Total number of assets in this group */
    public static final int COUNT = 30;

    private WeaponSet2HandAssets() { } // no instantiation
}
