package assets.weapons;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: weapons/1/5 Bullets
 * Total assets: 13
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class WeaponSet1BulletAssets {

    private static final String DIR = "Resources/industrial-zone/weapons/1/5 Bullets/";

    /** 3x3px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPEA_SINGLE_STATICSPRITE = SpriteAsset.single(
        "01_Weapon_Bullet_TypeA_Single_StaticSprite.png",
        DIR, 3, 3,
        "Sprite - 01 Weapon Bullet TypeA Single StaticSprite");

    /** 4x4px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPEB_SINGLE_STATICSPRITE = SpriteAsset.single(
        "02_Weapon_Bullet_TypeB_Single_StaticSprite.png",
        DIR, 4, 4,
        "Sprite - 02 Weapon Bullet TypeB Single StaticSprite");

    /** 4x4px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPEC_SINGLE_STATICSPRITE = SpriteAsset.single(
        "03_Weapon_Bullet_TypeC_Single_StaticSprite.png",
        DIR, 4, 4,
        "Sprite - 03 Weapon Bullet TypeC Single StaticSprite");

    /** 6x4px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPED_VARIANTA_STATICSPRITE = SpriteAsset.single(
        "04_Weapon_Bullet_TypeD_VariantA_StaticSprite.png",
        DIR, 6, 4,
        "Sprite - 04 Weapon Bullet TypeD VariantA StaticSprite");

    /** 6x6px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPED_VARIANTB_STATICSPRITE = SpriteAsset.single(
        "05_Weapon_Bullet_TypeD_VariantB_StaticSprite.png",
        DIR, 6, 6,
        "Sprite - 05 Weapon Bullet TypeD VariantB StaticSprite");

    /** 5x4px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPEE_VARIANTA_STATICSPRITE = SpriteAsset.single(
        "06_Weapon_Bullet_TypeE_VariantA_StaticSprite.png",
        DIR, 5, 4,
        "Sprite - 06 Weapon Bullet TypeE VariantA StaticSprite");

    /** 5x5px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPEE_VARIANTB_STATICSPRITE = SpriteAsset.single(
        "07_Weapon_Bullet_TypeE_VariantB_StaticSprite.png",
        DIR, 5, 5,
        "Sprite - 07 Weapon Bullet TypeE VariantB StaticSprite");

    /** 4x4px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPEF_SINGLE_STATICSPRITE = SpriteAsset.single(
        "08_Weapon_Bullet_TypeF_Single_StaticSprite.png",
        DIR, 4, 4,
        "Sprite - 08 Weapon Bullet TypeF Single StaticSprite");

    /** 5x3px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPEG_VARIANTA_STATICSPRITE = SpriteAsset.single(
        "09_Weapon_Bullet_TypeG_VariantA_StaticSprite.png",
        DIR, 5, 3,
        "Sprite - 09 Weapon Bullet TypeG VariantA StaticSprite");

    /** 5x5px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPEG_VARIANTB_STATICSPRITE = SpriteAsset.single(
        "10_Weapon_Bullet_TypeG_VariantB_StaticSprite.png",
        DIR, 5, 5,
        "Sprite - 10 Weapon Bullet TypeG VariantB StaticSprite");

    /** 3x3px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPEH_SINGLE_STATICSPRITE = SpriteAsset.single(
        "11_Weapon_Bullet_TypeH_Single_StaticSprite.png",
        DIR, 3, 3,
        "Sprite - 11 Weapon Bullet TypeH Single StaticSprite");

    /** 5x5px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPEI_SINGLE_STATICSPRITE = SpriteAsset.single(
        "12_Weapon_Bullet_TypeI_Single_StaticSprite.png",
        DIR, 5, 5,
        "Sprite - 12 Weapon Bullet TypeI Single StaticSprite");

    /** 6x6px | static */
    public static final SpriteAsset WEAPON_BULLET_TYPEJ_SINGLE_STATICSPRITE = SpriteAsset.single(
        "13_Weapon_Bullet_TypeJ_Single_StaticSprite.png",
        DIR, 6, 6,
        "Sprite - 13 Weapon Bullet TypeJ Single StaticSprite");

    /** Total number of assets in this group */
    public static final int COUNT = 13;

    private WeaponSet1BulletAssets() { } // no instantiation
}
