package assets.weapons;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: weapons/2/5 Bullets
 * Total assets: 19
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class WeaponSet2BulletAssets {

    private static final String DIR = "Resources/industrial-zone/weapons/2/5 Bullets/";

    /** 6x3px | static */
    public static final SpriteAsset A_1 = SpriteAsset.single(
        "1.png",
        DIR, 6, 3,
        "Asset - 1");

    /** 6x3px | static */
    public static final SpriteAsset A_10 = SpriteAsset.single(
        "10.png",
        DIR, 6, 3,
        "Asset - 10");

    /** 5x5px | static */
    public static final SpriteAsset A_2 = SpriteAsset.single(
        "10_2.png",
        DIR, 5, 5,
        "Asset - 10 2");

    /** 6x6px | static */
    public static final SpriteAsset A_2_2 = SpriteAsset.single(
        "1_2.png",
        DIR, 6, 6,
        "Asset - 1 2");

    /** 6x2px | static */
    public static final SpriteAsset A_2_3 = SpriteAsset.single(
        "2.png",
        DIR, 6, 2,
        "Asset - 2");

    /** 5x5px | static */
    public static final SpriteAsset A_2_4 = SpriteAsset.single(
        "2_2.png",
        DIR, 5, 5,
        "Asset - 2 2");

    /** 7x2px | static */
    public static final SpriteAsset A_3 = SpriteAsset.single(
        "3.png",
        DIR, 7, 2,
        "Asset - 3");

    /** 6x6px | static */
    public static final SpriteAsset A_2_5 = SpriteAsset.single(
        "3_2.png",
        DIR, 6, 6,
        "Asset - 3 2");

    /** 10x1px | static */
    public static final SpriteAsset A_4 = SpriteAsset.single(
        "4.png",
        DIR, 10, 1,
        "Asset - 4");

    /** 8x8px | static */
    public static final SpriteAsset A_2_6 = SpriteAsset.single(
        "4_2.png",
        DIR, 8, 8,
        "Asset - 4 2");

    /** 15x4px | static */
    public static final SpriteAsset A_5 = SpriteAsset.single(
        "5.png",
        DIR, 15, 4,
        "Asset - 5");

    /** 12x12px | static */
    public static final SpriteAsset A_2_7 = SpriteAsset.single(
        "5_2.png",
        DIR, 12, 12,
        "Asset - 5 2");

    /** 10x3px | static */
    public static final SpriteAsset A_6 = SpriteAsset.single(
        "6.png",
        DIR, 10, 3,
        "Asset - 6");

    /** 8x8px | static */
    public static final SpriteAsset A_2_8 = SpriteAsset.single(
        "6_2.png",
        DIR, 8, 8,
        "Asset - 6 2");

    /** 4x3px | static */
    public static final SpriteAsset A_7 = SpriteAsset.single(
        "7.png",
        DIR, 4, 3,
        "Asset - 7");

    /** 4x4px | static */
    public static final SpriteAsset A_2_9 = SpriteAsset.single(
        "7_2.png",
        DIR, 4, 4,
        "Asset - 7 2");

    /** 6x6px | static */
    public static final SpriteAsset A_8 = SpriteAsset.single(
        "8.png",
        DIR, 6, 6,
        "Asset - 8");

    /** 13x3px | static */
    public static final SpriteAsset A_9 = SpriteAsset.single(
        "9.png",
        DIR, 13, 3,
        "Asset - 9");

    /** 10x11px | static */
    public static final SpriteAsset A_2_10 = SpriteAsset.single(
        "9_2.png",
        DIR, 10, 11,
        "Asset - 9 2");

    /** Total number of assets in this group */
    public static final int COUNT = 19;

    private WeaponSet2BulletAssets() { } // no instantiation
}
