package assets.weapons;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: weapons/2/1 Characters/1 Biker
 * Total assets: 30
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class WeaponSet2CharAssets {

    private static final String DIR = "Resources/industrial-zone/weapons/2/1 Characters/1 Biker/";

    /** 192x48px | ~4 frames */
    public static final SpriteAsset IDLE1 = SpriteAsset.single(
        "Idle1.png",
        DIR, 192, 48,
        "Asset - Idle1");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset IDLE1_2 = SpriteAsset.single(
        "Idle1.png",
        DIR, 192, 48,
        "Asset - Idle1");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset IDLE1_3 = SpriteAsset.single(
        "Idle1.png",
        DIR, 192, 48,
        "Asset - Idle1");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset IDLE2 = SpriteAsset.single(
        "Idle2.png",
        DIR, 192, 48,
        "Asset - Idle2");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset IDLE2_2 = SpriteAsset.single(
        "Idle2.png",
        DIR, 192, 48,
        "Asset - Idle2");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset IDLE2_3 = SpriteAsset.single(
        "Idle2.png",
        DIR, 192, 48,
        "Asset - Idle2");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset JUMP1 = SpriteAsset.single(
        "Jump1.png",
        DIR, 192, 48,
        "Asset - Jump1");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset JUMP1_2 = SpriteAsset.single(
        "Jump1.png",
        DIR, 192, 48,
        "Asset - Jump1");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset JUMP1_3 = SpriteAsset.single(
        "Jump1.png",
        DIR, 192, 48,
        "Asset - Jump1");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset JUMP2 = SpriteAsset.single(
        "Jump2.png",
        DIR, 192, 48,
        "Asset - Jump2");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset JUMP2_2 = SpriteAsset.single(
        "Jump2.png",
        DIR, 192, 48,
        "Asset - Jump2");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset JUMP2_3 = SpriteAsset.single(
        "Jump2.png",
        DIR, 192, 48,
        "Asset - Jump2");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset RUN1 = SpriteAsset.single(
        "Run1.png",
        DIR, 288, 48,
        "Asset - Run1");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset RUN1_2 = SpriteAsset.single(
        "Run1.png",
        DIR, 288, 48,
        "Asset - Run1");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset RUN1_3 = SpriteAsset.single(
        "Run1.png",
        DIR, 288, 48,
        "Asset - Run1");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset RUN2 = SpriteAsset.single(
        "Run2.png",
        DIR, 288, 48,
        "Asset - Run2");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset RUN2_2 = SpriteAsset.single(
        "Run2.png",
        DIR, 288, 48,
        "Asset - Run2");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset RUN2_3 = SpriteAsset.single(
        "Run2.png",
        DIR, 288, 48,
        "Asset - Run2");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset SITDOWN1 = SpriteAsset.single(
        "Sitdown1.png",
        DIR, 192, 48,
        "Asset - Sitdown1");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset SITDOWN1_2 = SpriteAsset.single(
        "Sitdown1.png",
        DIR, 192, 48,
        "Asset - Sitdown1");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset SITDOWN1_3 = SpriteAsset.single(
        "Sitdown1.png",
        DIR, 192, 48,
        "Asset - Sitdown1");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset SITDOWN2 = SpriteAsset.single(
        "Sitdown2.png",
        DIR, 192, 48,
        "Asset - Sitdown2");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset SITDOWN2_2 = SpriteAsset.single(
        "Sitdown2.png",
        DIR, 192, 48,
        "Asset - Sitdown2");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset SITDOWN2_3 = SpriteAsset.single(
        "Sitdown2.png",
        DIR, 192, 48,
        "Asset - Sitdown2");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WALK1 = SpriteAsset.single(
        "Walk1.png",
        DIR, 288, 48,
        "Asset - Walk1");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WALK1_2 = SpriteAsset.single(
        "Walk1.png",
        DIR, 288, 48,
        "Asset - Walk1");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WALK1_3 = SpriteAsset.single(
        "Walk1.png",
        DIR, 288, 48,
        "Asset - Walk1");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WALK2 = SpriteAsset.single(
        "Walk2.png",
        DIR, 288, 48,
        "Asset - Walk2");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WALK2_2 = SpriteAsset.single(
        "Walk2.png",
        DIR, 288, 48,
        "Asset - Walk2");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WALK2_3 = SpriteAsset.single(
        "Walk2.png",
        DIR, 288, 48,
        "Asset - Walk2");

    /** Total number of assets in this group */
    public static final int COUNT = 30;

    private WeaponSet2CharAssets() { } // no instantiation
}
