package assets.weapons;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: weapons/2/4 Shoot_effects
 * Total assets: 10
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class WeaponSet2ShootAssets {

    private static final String DIR = "Resources/industrial-zone/weapons/2/4 Shoot_effects/";

    /** 288x48px | ~6 frames */
    public static final SpriteAsset A_1 = SpriteAsset.single(
        "10_1.png",
        DIR, 288, 48,
        "Asset - 10 1");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset A_2 = SpriteAsset.single(
        "10_2.png",
        DIR, 288, 48,
        "Asset - 10 2");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset A_1_2 = SpriteAsset.single(
        "6_1.png",
        DIR, 288, 48,
        "Asset - 6 1");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset A_2_2 = SpriteAsset.single(
        "6_2.png",
        DIR, 288, 48,
        "Asset - 6 2");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset A_1_3 = SpriteAsset.single(
        "7_1.png",
        DIR, 288, 48,
        "Asset - 7 1");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset A_2_3 = SpriteAsset.single(
        "7_2.png",
        DIR, 288, 48,
        "Asset - 7 2");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset A_1_4 = SpriteAsset.single(
        "8_1.png",
        DIR, 288, 48,
        "Asset - 8 1");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset A_2_4 = SpriteAsset.single(
        "8_2.png",
        DIR, 288, 48,
        "Asset - 8 2");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset A_1_5 = SpriteAsset.single(
        "9_1.png",
        DIR, 288, 48,
        "Asset - 9 1");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset A_2_5 = SpriteAsset.single(
        "9_2.png",
        DIR, 288, 48,
        "Asset - 9 2");

    /** Total number of assets in this group */
    public static final int COUNT = 10;

    private WeaponSet2ShootAssets() { } // no instantiation
}
