package assets.weapons;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: weapons/1/1 Characters/1 Biker
 * Total assets: 30
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class WeaponSet1CharAssets {

    private static final String DIR = "Resources/industrial-zone/weapons/1/1 Characters/1 Biker/";

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset WEAPON_BIKER_IDLE_VARIANTA_WEAPONIDLESTAND = SpriteAsset.loop(
        "01_Weapon_Biker_Idle_VariantA_4Frames1Row_WeaponIdleStand_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Asset - 01 Weapon Biker Idle VariantA 4Frames1Row WeaponIdleStand Loop 150ms");

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset WEAPON_CYBORG_IDLE_VARIANTA_WEAPONIDLESTAND = SpriteAsset.loop(
        "01_Weapon_Cyborg_Idle_VariantA_3Frames1Row_WeaponIdleStand_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Asset - 01 Weapon Cyborg Idle VariantA 3Frames1Row WeaponIdleStand Loop 150ms");

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset WEAPON_PUNK_IDLE_VARIANTA_WEAPONIDLESTAND = SpriteAsset.loop(
        "01_Weapon_Punk_Idle_VariantA_3Frames1Row_WeaponIdleStand_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Asset - 01 Weapon Punk Idle VariantA 3Frames1Row WeaponIdleStand Loop 150ms");

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset WEAPON_BIKER_IDLE_VARIANTB_WEAPONIDLESTAND = SpriteAsset.loop(
        "02_Weapon_Biker_Idle_VariantB_4Frames1Row_WeaponIdleStand_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Asset - 02 Weapon Biker Idle VariantB 4Frames1Row WeaponIdleStand Loop 150ms");

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset WEAPON_CYBORG_IDLE_VARIANTB_WEAPONIDLESTAND = SpriteAsset.loop(
        "02_Weapon_Cyborg_Idle_VariantB_3Frames1Row_WeaponIdleStand_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Asset - 02 Weapon Cyborg Idle VariantB 3Frames1Row WeaponIdleStand Loop 150ms");

    /** 192x48px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset WEAPON_PUNK_IDLE_VARIANTB_WEAPONIDLESTAND = SpriteAsset.loop(
        "02_Weapon_Punk_Idle_VariantB_3Frames1Row_WeaponIdleStand_Loop_150ms.png",
        DIR, 192, 48, 150,
        "Asset - 02 Weapon Punk Idle VariantB 3Frames1Row WeaponIdleStand Loop 150ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset WEAPON_BIKER_JUMP_VARIANTA_WEAPONJUMPARC = SpriteAsset.once(
        "03_Weapon_Biker_Jump_VariantA_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Asset - 03 Weapon Biker Jump VariantA 3Frames1Row WeaponJumpArc PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset WEAPON_CYBORG_JUMP_VARIANTA_WEAPONJUMPARC = SpriteAsset.once(
        "03_Weapon_Cyborg_Jump_VariantA_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Asset - 03 Weapon Cyborg Jump VariantA 3Frames1Row WeaponJumpArc PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset WEAPON_PUNK_JUMP_VARIANTA_WEAPONJUMPARC = SpriteAsset.once(
        "03_Weapon_Punk_Jump_VariantA_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Asset - 03 Weapon Punk Jump VariantA 3Frames1Row WeaponJumpArc PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset WEAPON_BIKER_JUMP_VARIANTB_WEAPONJUMPARC = SpriteAsset.once(
        "04_Weapon_Biker_Jump_VariantB_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Asset - 04 Weapon Biker Jump VariantB 3Frames1Row WeaponJumpArc PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset WEAPON_CYBORG_JUMP_VARIANTB_WEAPONJUMPARC = SpriteAsset.once(
        "04_Weapon_Cyborg_Jump_VariantB_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Asset - 04 Weapon Cyborg Jump VariantB 3Frames1Row WeaponJumpArc PlayOnce 80ms");

    /** 192x48px | ~4 frames | 80ms/f */
    public static final SpriteAsset WEAPON_PUNK_JUMP_VARIANTB_WEAPONJUMPARC = SpriteAsset.once(
        "04_Weapon_Punk_Jump_VariantB_3Frames1Row_WeaponJumpArc_PlayOnce_80ms.png",
        DIR, 192, 48, 80,
        "Asset - 04 Weapon Punk Jump VariantB 3Frames1Row WeaponJumpArc PlayOnce 80ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset WEAPON_BIKER_RUN_VARIANTA_WEAPONRUNCYCLE = SpriteAsset.loop(
        "05_Weapon_Biker_Run_VariantA_5Frames1Row_WeaponRunCycle_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Asset - 05 Weapon Biker Run VariantA 5Frames1Row WeaponRunCycle Loop 80ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset WEAPON_CYBORG_RUN_VARIANTA_WEAPONRUNCYCLE = SpriteAsset.loop(
        "05_Weapon_Cyborg_Run_VariantA_5Frames1Row_WeaponRunCycle_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Asset - 05 Weapon Cyborg Run VariantA 5Frames1Row WeaponRunCycle Loop 80ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset WEAPON_PUNK_RUN_VARIANTA_WEAPONRUNCYCLE = SpriteAsset.loop(
        "05_Weapon_Punk_Run_VariantA_5Frames1Row_WeaponRunCycle_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Asset - 05 Weapon Punk Run VariantA 5Frames1Row WeaponRunCycle Loop 80ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset WEAPON_BIKER_RUN_VARIANTB_WEAPONRUNCYCLE = SpriteAsset.loop(
        "06_Weapon_Biker_Run_VariantB_5Frames1Row_WeaponRunCycle_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Asset - 06 Weapon Biker Run VariantB 5Frames1Row WeaponRunCycle Loop 80ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset WEAPON_CYBORG_RUN_VARIANTB_WEAPONRUNCYCLE = SpriteAsset.loop(
        "06_Weapon_Cyborg_Run_VariantB_5Frames1Row_WeaponRunCycle_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Asset - 06 Weapon Cyborg Run VariantB 5Frames1Row WeaponRunCycle Loop 80ms");

    /** 288x48px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset WEAPON_PUNK_RUN_VARIANTB_WEAPONRUNCYCLE = SpriteAsset.loop(
        "06_Weapon_Punk_Run_VariantB_5Frames1Row_WeaponRunCycle_Loop_80ms.png",
        DIR, 288, 48, 80,
        "Asset - 06 Weapon Punk Run VariantB 5Frames1Row WeaponRunCycle Loop 80ms");

    /** 192x48px | ~4 frames | 120ms/f */
    public static final SpriteAsset WEAPON_BIKER_SITDOWN_VARIANTA_WEAPONSITDOWN = SpriteAsset.once(
        "07_Weapon_Biker_Sitdown_VariantA_4Frames1Row_WeaponSitDown_PlayOnce_120ms.png",
        DIR, 192, 48, 120,
        "Asset - 07 Weapon Biker Sitdown VariantA 4Frames1Row WeaponSitDown PlayOnce 120ms");

    /** 192x48px | ~4 frames | 120ms/f */
    public static final SpriteAsset WEAPON_CYBORG_SITDOWN_VARIANTA_WEAPONSITDOWN = SpriteAsset.once(
        "07_Weapon_Cyborg_Sitdown_VariantA_3Frames1Row_WeaponSitDown_PlayOnce_120ms.png",
        DIR, 192, 48, 120,
        "Asset - 07 Weapon Cyborg Sitdown VariantA 3Frames1Row WeaponSitDown PlayOnce 120ms");

    /** 192x48px | ~4 frames | 120ms/f */
    public static final SpriteAsset WEAPON_PUNK_SITDOWN_VARIANTA_WEAPONSITDOWN = SpriteAsset.once(
        "07_Weapon_Punk_Sitdown_VariantA_3Frames1Row_WeaponSitDown_PlayOnce_120ms.png",
        DIR, 192, 48, 120,
        "Asset - 07 Weapon Punk Sitdown VariantA 3Frames1Row WeaponSitDown PlayOnce 120ms");

    /** 192x48px | ~4 frames | 120ms/f */
    public static final SpriteAsset WEAPON_BIKER_SITDOWN_VARIANTB_WEAPONSITDOWN = SpriteAsset.once(
        "08_Weapon_Biker_Sitdown_VariantB_4Frames1Row_WeaponSitDown_PlayOnce_120ms.png",
        DIR, 192, 48, 120,
        "Asset - 08 Weapon Biker Sitdown VariantB 4Frames1Row WeaponSitDown PlayOnce 120ms");

    /** 192x48px | ~4 frames | 120ms/f */
    public static final SpriteAsset WEAPON_CYBORG_SITDOWN_VARIANTB_WEAPONSITDOWN = SpriteAsset.once(
        "08_Weapon_Cyborg_Sitdown_VariantB_3Frames1Row_WeaponSitDown_PlayOnce_120ms.png",
        DIR, 192, 48, 120,
        "Asset - 08 Weapon Cyborg Sitdown VariantB 3Frames1Row WeaponSitDown PlayOnce 120ms");

    /** 192x48px | ~4 frames | 120ms/f */
    public static final SpriteAsset WEAPON_PUNK_SITDOWN_VARIANTB_WEAPONSITDOWN = SpriteAsset.once(
        "08_Weapon_Punk_Sitdown_VariantB_3Frames1Row_WeaponSitDown_PlayOnce_120ms.png",
        DIR, 192, 48, 120,
        "Asset - 08 Weapon Punk Sitdown VariantB 3Frames1Row WeaponSitDown PlayOnce 120ms");

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset WEAPON_BIKER_WALK_VARIANTA_WEAPONWALKCYCLE = SpriteAsset.loop(
        "09_Weapon_Biker_Walk_VariantA_4Frames1Row_WeaponWalkCycle_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Asset - 09 Weapon Biker Walk VariantA 4Frames1Row WeaponWalkCycle Loop 100ms");

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset WEAPON_CYBORG_WALK_VARIANTA_WEAPONWALKCYCLE = SpriteAsset.loop(
        "09_Weapon_Cyborg_Walk_VariantA_4Frames1Row_WeaponWalkCycle_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Asset - 09 Weapon Cyborg Walk VariantA 4Frames1Row WeaponWalkCycle Loop 100ms");

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset WEAPON_PUNK_WALK_VARIANTA_WEAPONWALKCYCLE = SpriteAsset.loop(
        "09_Weapon_Punk_Walk_VariantA_4Frames1Row_WeaponWalkCycle_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Asset - 09 Weapon Punk Walk VariantA 4Frames1Row WeaponWalkCycle Loop 100ms");

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset WEAPON_BIKER_WALK_VARIANTB_WEAPONWALKCYCLE = SpriteAsset.loop(
        "10_Weapon_Biker_Walk_VariantB_4Frames1Row_WeaponWalkCycle_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Asset - 10 Weapon Biker Walk VariantB 4Frames1Row WeaponWalkCycle Loop 100ms");

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset WEAPON_CYBORG_WALK_VARIANTB_WEAPONWALKCYCLE = SpriteAsset.loop(
        "10_Weapon_Cyborg_Walk_VariantB_4Frames1Row_WeaponWalkCycle_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Asset - 10 Weapon Cyborg Walk VariantB 4Frames1Row WeaponWalkCycle Loop 100ms");

    /** 288x48px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset WEAPON_PUNK_WALK_VARIANTB_WEAPONWALKCYCLE = SpriteAsset.loop(
        "10_Weapon_Punk_Walk_VariantB_4Frames1Row_WeaponWalkCycle_Loop_100ms.png",
        DIR, 288, 48, 100,
        "Asset - 10 Weapon Punk Walk VariantB 4Frames1Row WeaponWalkCycle Loop 100ms");

    /** Total number of assets in this group */
    public static final int COUNT = 30;

    private WeaponSet1CharAssets() { } // no instantiation
}
