package assets.weapons;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: weapons/1/2 Guns
 * Total assets: 20
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class WeaponSet1GunAssets {

    private static final String DIR = "Resources/industrial-zone/weapons/1/2 Guns/";

    /** 6x5px | static */
    public static final SpriteAsset WEAPON_GUN_PISTOL_TYPEA_VARIANTDARK_STATICSPRITE = SpriteAsset.single(
        "01_Weapon_Gun_Pistol_TypeA_VariantDark_StaticSprite.png",
        DIR, 6, 5,
        "Sprite - 01 Weapon Gun Pistol TypeA VariantDark StaticSprite");

    /** 6x5px | static */
    public static final SpriteAsset WEAPON_GUN_PISTOL_TYPEA_VARIANTLIGHT_STATICSPRITE = SpriteAsset.single(
        "02_Weapon_Gun_Pistol_TypeA_VariantLight_StaticSprite.png",
        DIR, 6, 5,
        "Sprite - 02 Weapon Gun Pistol TypeA VariantLight StaticSprite");

    /** 8x7px | static */
    public static final SpriteAsset WEAPON_GUN_PISTOL_TYPEB_VARIANTDARK_STATICSPRITE = SpriteAsset.single(
        "03_Weapon_Gun_Pistol_TypeB_VariantDark_StaticSprite.png",
        DIR, 8, 7,
        "Sprite - 03 Weapon Gun Pistol TypeB VariantDark StaticSprite");

    /** 10x7px | static */
    public static final SpriteAsset WEAPON_GUN_PISTOL_TYPEB_VARIANTLIGHT_STATICSPRITE = SpriteAsset.single(
        "04_Weapon_Gun_Pistol_TypeB_VariantLight_StaticSprite.png",
        DIR, 10, 7,
        "Sprite - 04 Weapon Gun Pistol TypeB VariantLight StaticSprite");

    /** 9x6px | static */
    public static final SpriteAsset WEAPON_GUN_COMPACT_TYPEC_VARIANTDARK_STATICSPRITE = SpriteAsset.single(
        "05_Weapon_Gun_Compact_TypeC_VariantDark_StaticSprite.png",
        DIR, 9, 6,
        "Sprite - 05 Weapon Gun Compact TypeC VariantDark StaticSprite");

    /** 9x8px | static */
    public static final SpriteAsset WEAPON_GUN_COMPACT_TYPEC_VARIANTLIGHT_STATICSPRITE = SpriteAsset.single(
        "06_Weapon_Gun_Compact_TypeC_VariantLight_StaticSprite.png",
        DIR, 9, 8,
        "Sprite - 06 Weapon Gun Compact TypeC VariantLight StaticSprite");

    /** 11x7px | static */
    public static final SpriteAsset WEAPON_GUN_COMPACT_TYPED_VARIANTDARK_STATICSPRITE = SpriteAsset.single(
        "07_Weapon_Gun_Compact_TypeD_VariantDark_StaticSprite.png",
        DIR, 11, 7,
        "Sprite - 07 Weapon Gun Compact TypeD VariantDark StaticSprite");

    /** 12x9px | static */
    public static final SpriteAsset WEAPON_GUN_COMPACT_TYPED_VARIANTLIGHT_STATICSPRITE = SpriteAsset.single(
        "08_Weapon_Gun_Compact_TypeD_VariantLight_StaticSprite.png",
        DIR, 12, 9,
        "Sprite - 08 Weapon Gun Compact TypeD VariantLight StaticSprite");

    /** 11x9px | static */
    public static final SpriteAsset WEAPON_GUN_COMPACT_TYPEE_VARIANTDARK_STATICSPRITE = SpriteAsset.single(
        "09_Weapon_Gun_Compact_TypeE_VariantDark_StaticSprite.png",
        DIR, 11, 9,
        "Sprite - 09 Weapon Gun Compact TypeE VariantDark StaticSprite");

    /** 13x10px | static */
    public static final SpriteAsset WEAPON_GUN_COMPACT_TYPEE_VARIANTLIGHT_STATICSPRITE = SpriteAsset.single(
        "10_Weapon_Gun_Compact_TypeE_VariantLight_StaticSprite.png",
        DIR, 13, 10,
        "Sprite - 10 Weapon Gun Compact TypeE VariantLight StaticSprite");

    /** 11x9px | static */
    public static final SpriteAsset WEAPON_GUN_DETAIL_TYPEF_VARIANTDARK_STATICSPRITE = SpriteAsset.single(
        "11_Weapon_Gun_Detail_TypeF_VariantDark_StaticSprite.png",
        DIR, 11, 9,
        "Sprite - 11 Weapon Gun Detail TypeF VariantDark StaticSprite");

    /** 12x10px | static */
    public static final SpriteAsset WEAPON_GUN_DETAIL_TYPEF_VARIANTLIGHT_STATICSPRITE = SpriteAsset.single(
        "12_Weapon_Gun_Detail_TypeF_VariantLight_StaticSprite.png",
        DIR, 12, 10,
        "Sprite - 12 Weapon Gun Detail TypeF VariantLight StaticSprite");

    /** 13x9px | static */
    public static final SpriteAsset WEAPON_GUN_RIFLE_TYPEG_VARIANTDARK_STATICSPRITE = SpriteAsset.single(
        "13_Weapon_Gun_Rifle_TypeG_VariantDark_StaticSprite.png",
        DIR, 13, 9,
        "Sprite - 13 Weapon Gun Rifle TypeG VariantDark StaticSprite");

    /** 14x13px | static */
    public static final SpriteAsset WEAPON_GUN_RIFLE_TYPEG_VARIANTLIGHT_STATICSPRITE = SpriteAsset.single(
        "14_Weapon_Gun_Rifle_TypeG_VariantLight_StaticSprite.png",
        DIR, 14, 13,
        "Sprite - 14 Weapon Gun Rifle TypeG VariantLight StaticSprite");

    /** 18x8px | static */
    public static final SpriteAsset WEAPON_GUN_RIFLE_TYPEH_VARIANTDARK_STATICSPRITE = SpriteAsset.single(
        "15_Weapon_Gun_Rifle_TypeH_VariantDark_StaticSprite.png",
        DIR, 18, 8,
        "Sprite - 15 Weapon Gun Rifle TypeH VariantDark StaticSprite");

    /** 17x12px | static */
    public static final SpriteAsset WEAPON_GUN_RIFLE_TYPEH_VARIANTLIGHT_STATICSPRITE = SpriteAsset.single(
        "16_Weapon_Gun_Rifle_TypeH_VariantLight_StaticSprite.png",
        DIR, 17, 12,
        "Sprite - 16 Weapon Gun Rifle TypeH VariantLight StaticSprite");

    /** 11x10px | static */
    public static final SpriteAsset WEAPON_GUN_RIFLE_TYPEI_VARIANTBLUE_STATICSPRITE = SpriteAsset.single(
        "17_Weapon_Gun_Rifle_TypeI_VariantBlue_StaticSprite.png",
        DIR, 11, 10,
        "Sprite - 17 Weapon Gun Rifle TypeI VariantBlue StaticSprite");

    /** 13x12px | static */
    public static final SpriteAsset WEAPON_GUN_RIFLE_TYPEI_VARIANTBLUEALT_STATICSPRITE = SpriteAsset.single(
        "18_Weapon_Gun_Rifle_TypeI_VariantBlueAlt_StaticSprite.png",
        DIR, 13, 12,
        "Sprite - 18 Weapon Gun Rifle TypeI VariantBlueAlt StaticSprite");

    /** 14x10px | static */
    public static final SpriteAsset WEAPON_GUN_SPECIAL_TYPEJ_VARIANTTEAL_STATICSPRITE = SpriteAsset.single(
        "19_Weapon_Gun_Special_TypeJ_VariantTeal_StaticSprite.png",
        DIR, 14, 10,
        "Sprite - 19 Weapon Gun Special TypeJ VariantTeal StaticSprite");

    /** 14x12px | static */
    public static final SpriteAsset WEAPON_GUN_SPECIAL_TYPEJ_VARIANTRED_STATICSPRITE = SpriteAsset.single(
        "20_Weapon_Gun_Special_TypeJ_VariantRed_StaticSprite.png",
        DIR, 14, 12,
        "Sprite - 20 Weapon Gun Special TypeJ VariantRed StaticSprite");

    /** Total number of assets in this group */
    public static final int COUNT = 20;

    private WeaponSet1GunAssets() { } // no instantiation
}
