package assets.weapons;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: weapons/2/2 Guns
 * Total assets: 20
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class WeaponSet2GunAssets {

    private static final String DIR = "Resources/industrial-zone/weapons/2/2 Guns/";

    /** 26x12px | static */
    public static final SpriteAsset A_1 = SpriteAsset.single(
        "10_1.png",
        DIR, 26, 12,
        "Asset - 10 1");

    /** 24x23px | static */
    public static final SpriteAsset A_2 = SpriteAsset.single(
        "10_2.png",
        DIR, 24, 23,
        "Asset - 10 2");

    /** 26x7px | static */
    public static final SpriteAsset A_1_2 = SpriteAsset.single(
        "1_1.png",
        DIR, 26, 7,
        "Asset - 1 1");

    /** 21x20px | static */
    public static final SpriteAsset A_2_2 = SpriteAsset.single(
        "1_2.png",
        DIR, 21, 20,
        "Asset - 1 2");

    /** 22x8px | static */
    public static final SpriteAsset A_1_3 = SpriteAsset.single(
        "2_1.png",
        DIR, 22, 8,
        "Asset - 2 1");

    /** 19x17px | static */
    public static final SpriteAsset A_2_3 = SpriteAsset.single(
        "2_2.png",
        DIR, 19, 17,
        "Asset - 2 2");

    /** 27x9px | static */
    public static final SpriteAsset A_1_4 = SpriteAsset.single(
        "3_1.png",
        DIR, 27, 9,
        "Asset - 3 1");

    /** 22x21px | static */
    public static final SpriteAsset A_2_4 = SpriteAsset.single(
        "3_2.png",
        DIR, 22, 21,
        "Asset - 3 2");

    /** 29x11px | static */
    public static final SpriteAsset A_1_5 = SpriteAsset.single(
        "4_1.png",
        DIR, 29, 11,
        "Asset - 4 1");

    /** 23x23px | static */
    public static final SpriteAsset A_2_5 = SpriteAsset.single(
        "4_2.png",
        DIR, 23, 23,
        "Asset - 4 2");

    /** 28x16px | static */
    public static final SpriteAsset A_1_6 = SpriteAsset.single(
        "5_1.png",
        DIR, 28, 16,
        "Asset - 5 1");

    /** 24x23px | static */
    public static final SpriteAsset A_2_6 = SpriteAsset.single(
        "5_2.png",
        DIR, 24, 23,
        "Asset - 5 2");

    /** 31x15px | static */
    public static final SpriteAsset A_1_7 = SpriteAsset.single(
        "6_1.png",
        DIR, 31, 15,
        "Asset - 6 1");

    /** 27x23px | static */
    public static final SpriteAsset A_2_7 = SpriteAsset.single(
        "6_2.png",
        DIR, 27, 23,
        "Asset - 6 2");

    /** 27x14px | static */
    public static final SpriteAsset A_1_8 = SpriteAsset.single(
        "7_1.png",
        DIR, 27, 14,
        "Asset - 7 1");

    /** 25x22px | static */
    public static final SpriteAsset A_2_8 = SpriteAsset.single(
        "7_2.png",
        DIR, 25, 22,
        "Asset - 7 2");

    /** 25x14px | static */
    public static final SpriteAsset A_1_9 = SpriteAsset.single(
        "8_1.png",
        DIR, 25, 14,
        "Asset - 8 1");

    /** 24x23px | static */
    public static final SpriteAsset A_2_9 = SpriteAsset.single(
        "8_2.png",
        DIR, 24, 23,
        "Asset - 8 2");

    /** 27x16px | static */
    public static final SpriteAsset A_1_10 = SpriteAsset.single(
        "9_1.png",
        DIR, 27, 16,
        "Asset - 9 1");

    /** 24x24px | static */
    public static final SpriteAsset A_2_10 = SpriteAsset.single(
        "9_2.png",
        DIR, 24, 24,
        "Asset - 9 2");

    /** Total number of assets in this group */
    public static final int COUNT = 20;

    private WeaponSet2GunAssets() { } // no instantiation
}
