package assets.weapons;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: weapons/1/4 Shoot_effects
 * Total assets: 10
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class WeaponSet1ShootAssets {

    private static final String DIR = "Resources/industrial-zone/weapons/1/4 Shoot_effects/";

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WEAPON_SHOOTFX_TRACER_TYPEA_VARIANTNARROW_STATICSPRITE = SpriteAsset.single(
        "01_Weapon_ShootFX_Tracer_TypeA_VariantNarrow_StaticSprite.png",
        DIR, 288, 48,
        "Sprite - 01 Weapon ShootFX Tracer TypeA VariantNarrow StaticSprite");

    /** 256x48px | ~5 frames */
    public static final SpriteAsset WEAPON_SHOOTFX_TRACER_TYPEA_VARIANTSCATTER_STATICSPRITE = SpriteAsset.single(
        "02_Weapon_ShootFX_Tracer_TypeA_VariantScatter_StaticSprite.png",
        DIR, 256, 48,
        "Sprite - 02 Weapon ShootFX Tracer TypeA VariantScatter StaticSprite");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WEAPON_SHOOTFX_TRACER_TYPEB_VARIANTDOTTED_STATICSPRITE = SpriteAsset.single(
        "03_Weapon_ShootFX_Tracer_TypeB_VariantDotted_StaticSprite.png",
        DIR, 288, 48,
        "Sprite - 03 Weapon ShootFX Tracer TypeB VariantDotted StaticSprite");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WEAPON_SHOOTFX_TRACER_TYPEB_VARIANTSLASH_STATICSPRITE = SpriteAsset.single(
        "04_Weapon_ShootFX_Tracer_TypeB_VariantSlash_StaticSprite.png",
        DIR, 288, 48,
        "Sprite - 04 Weapon ShootFX Tracer TypeB VariantSlash StaticSprite");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WEAPON_SHOOTFX_TRACER_TYPEC_VARIANTHEAVY_STATICSPRITE = SpriteAsset.single(
        "05_Weapon_ShootFX_Tracer_TypeC_VariantHeavy_StaticSprite.png",
        DIR, 288, 48,
        "Sprite - 05 Weapon ShootFX Tracer TypeC VariantHeavy StaticSprite");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WEAPON_SHOOTFX_TRACER_TYPEC_VARIANTBOLD_STATICSPRITE = SpriteAsset.single(
        "06_Weapon_ShootFX_Tracer_TypeC_VariantBold_StaticSprite.png",
        DIR, 288, 48,
        "Sprite - 06 Weapon ShootFX Tracer TypeC VariantBold StaticSprite");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WEAPON_SHOOTFX_TRACER_TYPED_VARIANTWAVE_STATICSPRITE = SpriteAsset.single(
        "07_Weapon_ShootFX_Tracer_TypeD_VariantWave_StaticSprite.png",
        DIR, 288, 48,
        "Sprite - 07 Weapon ShootFX Tracer TypeD VariantWave StaticSprite");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WEAPON_SHOOTFX_TRACER_TYPED_VARIANTJAGGED_STATICSPRITE = SpriteAsset.single(
        "08_Weapon_ShootFX_Tracer_TypeD_VariantJagged_StaticSprite.png",
        DIR, 288, 48,
        "Sprite - 08 Weapon ShootFX Tracer TypeD VariantJagged StaticSprite");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WEAPON_SHOOTFX_TRACER_TYPEE_VARIANTLASER_STATICSPRITE = SpriteAsset.single(
        "09_Weapon_ShootFX_Tracer_TypeE_VariantLaser_StaticSprite.png",
        DIR, 288, 48,
        "Sprite - 09 Weapon ShootFX Tracer TypeE VariantLaser StaticSprite");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset WEAPON_SHOOTFX_TRACER_TYPEE_VARIANTOUTLINE_STATICSPRITE = SpriteAsset.single(
        "10_Weapon_ShootFX_Tracer_TypeE_VariantOutline_StaticSprite.png",
        DIR, 288, 48,
        "Sprite - 10 Weapon ShootFX Tracer TypeE VariantOutline StaticSprite");

    /** Total number of assets in this group */
    public static final int COUNT = 10;

    private WeaponSet1ShootAssets() { } // no instantiation
}
