package assets.enemies;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/enemies/sci-fi-antagonists/1
 * Total assets: 13
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Antagonist1Assets {

    private static final String DIR = "Resources/industrial-zone/characters/enemies/sci-fi-antagonists/1/";

    /** 384x96px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset ENEMY_COMBATTANK_IDLE_TURRETIDLEPATROL_DEFAULTIDLE = SpriteAsset.loop(
        "01_Enemy_CombatTank_Idle_4Frames1Row_TurretIdlePatrol_DefaultIdle_Loop_150ms.png",
        DIR, 384, 96, 150,
        "01 Enemy CombatTank Idle 4Frames1Row TurretIdlePatrol DefaultIdle Loop 150ms");

    /** 384x96px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset ENEMY_COMBATTANK_WALK_VEHICLEDRIVINGADVANCE_MOVEMENT = SpriteAsset.loop(
        "02_Enemy_CombatTank_Walk_4Frames1Row_VehicleDrivingAdvance_Movement_Loop_100ms.png",
        DIR, 384, 96, 100,
        "02 Enemy CombatTank Walk 4Frames1Row VehicleDrivingAdvance Movement Loop 100ms");

    /** 384x96px | ~4 frames | 80ms/f */
    public static final SpriteAsset ENEMY_COMBATTANK_ATTACK1_TURRETSTRAIGHTSHOT_RANGEDATTACK = SpriteAsset.once(
        "03_Enemy_CombatTank_Attack1_4Frames1Row_TurretStraightShot_RangedAttack_PlayOnce_80ms.png",
        DIR, 384, 96, 80,
        "03 Enemy CombatTank Attack1 4Frames1Row TurretStraightShot RangedAttack PlayOnce 80ms");

    /** 384x96px | ~4 frames | 80ms/f */
    public static final SpriteAsset ENEMY_COMBATTANK_ATTACK2_TURRETANGLEDSHOT_RANGEDATTACK = SpriteAsset.once(
        "04_Enemy_CombatTank_Attack2_4Frames1Row_TurretAngledShot_RangedAttack_PlayOnce_80ms.png",
        DIR, 384, 96, 80,
        "04 Enemy CombatTank Attack2 4Frames1Row TurretAngledShot RangedAttack PlayOnce 80ms");

    /** 384x96px | ~4 frames | 80ms/f */
    public static final SpriteAsset ENEMY_COMBATTANK_ATTACK3A_MULTIATTACKPART1_COMBOATTACK = SpriteAsset.once(
        "05_Enemy_CombatTank_Attack3a_4Frames1Row_MultiAttackPart1_ComboAttack_PlayOnce_80ms.png",
        DIR, 384, 96, 80,
        "05 Enemy CombatTank Attack3a 4Frames1Row MultiAttackPart1 ComboAttack PlayOnce 80ms");

    /** 384x96px | ~4 frames | 80ms/f */
    public static final SpriteAsset ENEMY_COMBATTANK_ATTACK3B_LASERBEAMFIRE_COMBOATTACK = SpriteAsset.once(
        "06_Enemy_CombatTank_Attack3b_4Frames1Row_LaserBeamFire_ComboAttack_PlayOnce_80ms.png",
        DIR, 384, 96, 80,
        "06 Enemy CombatTank Attack3b 4Frames1Row LaserBeamFire ComboAttack PlayOnce 80ms");

    /** 384x96px | ~4 frames | 80ms/f */
    public static final SpriteAsset ENEMY_COMBATTANK_ATTACK3C_MULTIATTACKPART3_COMBOATTACK = SpriteAsset.once(
        "07_Enemy_CombatTank_Attack3c_4Frames1Row_MultiAttackPart3_ComboAttack_PlayOnce_80ms.png",
        DIR, 384, 96, 80,
        "07 Enemy CombatTank Attack3c 4Frames1Row MultiAttackPart3 ComboAttack PlayOnce 80ms");

    /** 384x96px | ~4 frames | 100ms/f */
    public static final SpriteAsset ENEMY_COMBATTANK_ATTACK4A_HEAVYATTACKWINDUP_HEAVYATTACK = SpriteAsset.once(
        "08_Enemy_CombatTank_Attack4a_4Frames1Row_HeavyAttackWindup_HeavyAttack_PlayOnce_100ms.png",
        DIR, 384, 96, 100,
        "08 Enemy CombatTank Attack4a 4Frames1Row HeavyAttackWindup HeavyAttack PlayOnce 100ms");

    /** 384x96px | ~4 frames | 100ms/f */
    public static final SpriteAsset ENEMY_COMBATTANK_ATTACK4B_ENERGYBLASTRELEASE_HEAVYATTACK = SpriteAsset.once(
        "09_Enemy_CombatTank_Attack4b_4Frames1Row_EnergyBlastRelease_HeavyAttack_PlayOnce_100ms.png",
        DIR, 384, 96, 100,
        "09 Enemy CombatTank Attack4b 4Frames1Row EnergyBlastRelease HeavyAttack PlayOnce 100ms");

    /** 384x96px | ~4 frames | 100ms/f */
    public static final SpriteAsset ENEMY_COMBATTANK_ATTACK4C_HEAVYATTACKFOLLOWTHRU_HEAVYATTACK = SpriteAsset.once(
        "10_Enemy_CombatTank_Attack4c_4Frames1Row_HeavyAttackFollowThru_HeavyAttack_PlayOnce_100ms.png",
        DIR, 384, 96, 100,
        "10 Enemy CombatTank Attack4c 4Frames1Row HeavyAttackFollowThru HeavyAttack PlayOnce 100ms");

    /** 576x96px | ~6 frames | 100ms/f */
    public static final SpriteAsset ENEMY_COMBATTANK_SPECIAL_OPERATORREACTSANDFIRES_SPECIALABILITY = SpriteAsset.once(
        "11_Enemy_CombatTank_Special_6Frames1Row_OperatorReactsAndFires_SpecialAbility_PlayOnce_100ms.png",
        DIR, 576, 96, 100,
        "11 Enemy CombatTank Special 6Frames1Row OperatorReactsAndFires SpecialAbility PlayOnce 100ms");

    /** 192x96px | ~2 frames | 100ms/f */
    public static final SpriteAsset ENEMY_COMBATTANK_HURT_HITREACTIONSILHOUETTE_TAKEDAMAGE = SpriteAsset.once(
        "12_Enemy_CombatTank_Hurt_2Frames1Row_HitReactionSilhouette_TakeDamage_PlayOnce_100ms.png",
        DIR, 192, 96, 100,
        "12 Enemy CombatTank Hurt 2Frames1Row HitReactionSilhouette TakeDamage PlayOnce 100ms");

    /** 576x96px | ~6 frames | 120ms/f */
    public static final SpriteAsset ENEMY_COMBATTANK_DEATH_VEHICLEDESTRUCTIONSEQUENCE_DEATH = SpriteAsset.once(
        "13_Enemy_CombatTank_Death_5Frames1Row_VehicleDestructionSequence_Death_PlayOnce_120ms.png",
        DIR, 576, 96, 120,
        "13 Enemy CombatTank Death 5Frames1Row VehicleDestructionSequence Death PlayOnce 120ms");

    /** Total number of assets in this group */
    public static final int COUNT = 13;

    private Antagonist1Assets() { } // no instantiation
}
