package assets.enemies;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/enemies/sci-fi-antagonists/3
 * Total assets: 11
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Antagonist3Assets {

    private static final String DIR = "Resources/industrial-zone/characters/enemies/sci-fi-antagonists/3/";

    /** 384x96px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset ENEMY_WINGEDWARRIOR_IDLE_STANDINGPATROLIDLE_DEFAULTIDLE = SpriteAsset.loop(
        "01_Enemy_WingedWarrior_Idle_4Frames1Row_StandingPatrolIdle_DefaultIdle_Loop_150ms.png",
        DIR, 384, 96, 150,
        "01 Enemy WingedWarrior Idle 4Frames1Row StandingPatrolIdle DefaultIdle Loop 150ms");

    /** 576x96px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset ENEMY_WINGEDWARRIOR_WALK_WALKINGADVANCE_MOVEMENT = SpriteAsset.loop(
        "02_Enemy_WingedWarrior_Walk_6Frames1Row_WalkingAdvance_Movement_Loop_100ms.png",
        DIR, 576, 96, 100,
        "02 Enemy WingedWarrior Walk 6Frames1Row WalkingAdvance Movement Loop 100ms");

    /** 576x96px | ~6 frames | 70ms/f */
    public static final SpriteAsset ENEMY_WINGEDWARRIOR_ATTACK1_KICKSTRIKECOMBO_MELEEATTACK = SpriteAsset.once(
        "03_Enemy_WingedWarrior_Attack1_6Frames1Row_KickStrikeCombo_MeleeAttack_PlayOnce_70ms.png",
        DIR, 576, 96, 70,
        "03 Enemy WingedWarrior Attack1 6Frames1Row KickStrikeCombo MeleeAttack PlayOnce 70ms");

    /** 576x96px | ~6 frames | 80ms/f */
    public static final SpriteAsset ENEMY_WINGEDWARRIOR_ATTACK2_ORBPROJECTILESHOTRETURN_RANGEDATTACK = SpriteAsset.once(
        "04_Enemy_WingedWarrior_Attack2_6Frames1Row_OrbProjectileShotReturn_RangedAttack_PlayOnce_80ms.png",
        DIR, 576, 96, 80,
        "04 Enemy WingedWarrior Attack2 6Frames1Row OrbProjectileShotReturn RangedAttack PlayOnce 80ms");

    /** 576x96px | ~6 frames | 70ms/f */
    public static final SpriteAsset ENEMY_WINGEDWARRIOR_ATTACK3_WINGCAPESLASHSWEEP_MELEEATTACK = SpriteAsset.once(
        "05_Enemy_WingedWarrior_Attack3_5Frames1Row_WingCapeSlashSweep_MeleeAttack_PlayOnce_70ms.png",
        DIR, 576, 96, 70,
        "05 Enemy WingedWarrior Attack3 5Frames1Row WingCapeSlashSweep MeleeAttack PlayOnce 70ms");

    /** 576x96px | ~6 frames | 80ms/f */
    public static final SpriteAsset ENEMY_WINGEDWARRIOR_ATTACK4_JUMPAERIALSLAMBURST_HEAVYATTACK = SpriteAsset.once(
        "06_Enemy_WingedWarrior_Attack4_6Frames1Row_JumpAerialSlamBurst_HeavyAttack_PlayOnce_80ms.png",
        DIR, 576, 96, 80,
        "06 Enemy WingedWarrior Attack4 6Frames1Row JumpAerialSlamBurst HeavyAttack PlayOnce 80ms");

    /** 384x96px | ~4 frames | 80ms/f */
    public static final SpriteAsset ENEMY_WINGEDWARRIOR_ATTACK4B_GROUNDSLAMBURSTFOLLOWTHRU_HEAVYATTACK = SpriteAsset.once(
        "07_Enemy_WingedWarrior_Attack4b_4Frames1Row_GroundSlamBurstFollowThru_HeavyAttack_PlayOnce_80ms.png",
        DIR, 384, 96, 80,
        "07 Enemy WingedWarrior Attack4b 4Frames1Row GroundSlamBurstFollowThru HeavyAttack PlayOnce 80ms");

    /** 576x96px | ~6 frames | 100ms/f */
    public static final SpriteAsset ENEMY_WINGEDWARRIOR_SPECIAL_WINGFLARECHARGEABILITY_SPECIAL = SpriteAsset.once(
        "08_Enemy_WingedWarrior_Special_6Frames1Row_WingFlareChargeAbility_Special_PlayOnce_100ms.png",
        DIR, 576, 96, 100,
        "08 Enemy WingedWarrior Special 6Frames1Row WingFlareChargeAbility Special PlayOnce 100ms");

    /** 9x2px | static | 100ms/f | loop */
    public static final SpriteAsset ENEMY_WINGEDWARRIOR_PROJECTILE_1FRAME1ROW_SINGLEREDPROJECTILE_PROJECTILE = SpriteAsset.loop(
        "09_Enemy_WingedWarrior_Projectile_1Frame1Row_SingleRedProjectile_Projectile_Loop_100ms.png",
        DIR, 9, 2, 100,
        "09 Enemy WingedWarrior Projectile 1Frame1Row SingleRedProjectile Projectile Loop 100ms");

    /** 192x96px | ~2 frames | 100ms/f */
    public static final SpriteAsset ENEMY_WINGEDWARRIOR_HURT_HITFLINCHREDGHOST_TAKEDAMAGE = SpriteAsset.once(
        "10_Enemy_WingedWarrior_Hurt_2Frames1Row_HitFlinchRedGhost_TakeDamage_PlayOnce_100ms.png",
        DIR, 192, 96, 100,
        "10 Enemy WingedWarrior Hurt 2Frames1Row HitFlinchRedGhost TakeDamage PlayOnce 100ms");

    /** 576x96px | ~6 frames | 120ms/f */
    public static final SpriteAsset ENEMY_WINGEDWARRIOR_DEATH_FALLANDSLIDEDEATH_DEATH = SpriteAsset.once(
        "11_Enemy_WingedWarrior_Death_6Frames1Row_FallAndSlideDeath_Death_PlayOnce_120ms.png",
        DIR, 576, 96, 120,
        "11 Enemy WingedWarrior Death 6Frames1Row FallAndSlideDeath Death PlayOnce 120ms");

    /** Total number of assets in this group */
    public static final int COUNT = 11;

    private Antagonist3Assets() { } // no instantiation
}
