package assets.enemies;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/enemies/sci-fi-antagonists/2
 * Total assets: 10
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Antagonist2Assets {

    private static final String DIR = "Resources/industrial-zone/characters/enemies/sci-fi-antagonists/2/";

    /** 384x96px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset ENEMY_ARMOUREDKNIGHT_IDLE_STANDINGPATROLIDLE_DEFAULTIDLE = SpriteAsset.loop(
        "01_Enemy_ArmouredKnight_Idle_4Frames1Row_StandingPatrolIdle_DefaultIdle_Loop_150ms.png",
        DIR, 384, 96, 150,
        "01 Enemy ArmouredKnight Idle 4Frames1Row StandingPatrolIdle DefaultIdle Loop 150ms");

    /** 576x96px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset ENEMY_ARMOUREDKNIGHT_WALK_WALKINGADVANCE_MOVEMENT = SpriteAsset.loop(
        "02_Enemy_ArmouredKnight_Walk_5Frames1Row_WalkingAdvance_Movement_Loop_100ms.png",
        DIR, 576, 96, 100,
        "02 Enemy ArmouredKnight Walk 5Frames1Row WalkingAdvance Movement Loop 100ms");

    /** 576x96px | ~6 frames | 70ms/f */
    public static final SpriteAsset ENEMY_ARMOUREDKNIGHT_ATTACK1_BLADESLASHFORWARD_MELEEATTACK = SpriteAsset.once(
        "03_Enemy_ArmouredKnight_Attack1_5Frames1Row_BladeSlashForward_MeleeAttack_PlayOnce_70ms.png",
        DIR, 576, 96, 70,
        "03 Enemy ArmouredKnight Attack1 5Frames1Row BladeSlashForward MeleeAttack PlayOnce 70ms");

    /** 576x96px | ~6 frames | 70ms/f */
    public static final SpriteAsset ENEMY_ARMOUREDKNIGHT_ATTACK2_EXTENDEDREACHSLASH_MELEEATTACK = SpriteAsset.once(
        "04_Enemy_ArmouredKnight_Attack2_5Frames1Row_ExtendedReachSlash_MeleeAttack_PlayOnce_70ms.png",
        DIR, 576, 96, 70,
        "04 Enemy ArmouredKnight Attack2 5Frames1Row ExtendedReachSlash MeleeAttack PlayOnce 70ms");

    /** 576x96px | ~6 frames | 80ms/f */
    public static final SpriteAsset ENEMY_ARMOUREDKNIGHT_ATTACK3_HEAVYSWINGENERGYARC_HEAVYATTACK = SpriteAsset.once(
        "05_Enemy_ArmouredKnight_Attack3_5Frames1Row_HeavySwingEnergyArc_HeavyAttack_PlayOnce_80ms.png",
        DIR, 576, 96, 80,
        "05 Enemy ArmouredKnight Attack3 5Frames1Row HeavySwingEnergyArc HeavyAttack PlayOnce 80ms");

    /** 576x96px | ~6 frames | 80ms/f */
    public static final SpriteAsset ENEMY_ARMOUREDKNIGHT_ATTACK4_GUNRANGEDSHOT_RANGEDATTACK = SpriteAsset.once(
        "06_Enemy_ArmouredKnight_Attack4_5Frames1Row_GunRangedShot_RangedAttack_PlayOnce_80ms.png",
        DIR, 576, 96, 80,
        "06 Enemy ArmouredKnight Attack4 5Frames1Row GunRangedShot RangedAttack PlayOnce 80ms");

    /** 576x96px | ~6 frames | 100ms/f */
    public static final SpriteAsset ENEMY_ARMOUREDKNIGHT_SPECIAL_ENERGYCHARGEGLOWTRANSFORM_SPECIAL = SpriteAsset.once(
        "07_Enemy_ArmouredKnight_Special_6Frames1Row_EnergyChargeGlowTransform_Special_PlayOnce_100ms.png",
        DIR, 576, 96, 100,
        "07 Enemy ArmouredKnight Special 6Frames1Row EnergyChargeGlowTransform Special PlayOnce 100ms");

    /** 13x10px | static | 100ms/f | loop */
    public static final SpriteAsset ENEMY_ARMOUREDKNIGHT_PROJECTILE_1FRAME1ROW_SINGLEPROJECTILESPRITE_PROJECTILE = SpriteAsset.loop(
        "08_Enemy_ArmouredKnight_Projectile_1Frame1Row_SingleProjectileSprite_Projectile_Loop_100ms.png",
        DIR, 13, 10, 100,
        "08 Enemy ArmouredKnight Projectile 1Frame1Row SingleProjectileSprite Projectile Loop 100ms");

    /** 192x96px | ~2 frames | 100ms/f */
    public static final SpriteAsset ENEMY_ARMOUREDKNIGHT_HURT_HITFLINCHGOLDENGHOST_TAKEDAMAGE = SpriteAsset.once(
        "09_Enemy_ArmouredKnight_Hurt_2Frames1Row_HitFlinchGoldenGhost_TakeDamage_PlayOnce_100ms.png",
        DIR, 192, 96, 100,
        "09 Enemy ArmouredKnight Hurt 2Frames1Row HitFlinchGoldenGhost TakeDamage PlayOnce 100ms");

    /** 576x96px | ~6 frames | 120ms/f */
    public static final SpriteAsset ENEMY_ARMOUREDKNIGHT_DEATH_DEATHCOLLAPSEGHOST_DEATH = SpriteAsset.once(
        "10_Enemy_ArmouredKnight_Death_6Frames1Row_DeathCollapseGhost_Death_PlayOnce_120ms.png",
        DIR, 576, 96, 120,
        "10 Enemy ArmouredKnight Death 6Frames1Row DeathCollapseGhost Death PlayOnce 120ms");

    /** Total number of assets in this group */
    public static final int COUNT = 10;

    private Antagonist2Assets() { } // no instantiation
}
