package assets.enemies;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/enemies/drones/4
 * Total assets: 4
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Drone4Assets {

    private static final String DIR = "Resources/industrial-zone/characters/enemies/drones/4/";

    /** 384x96px | ~4 frames */
    public static final SpriteAsset TRANSPORTDRONE_HANGINGCABLE_STANDBY_HOVERING = SpriteAsset.single(
        "01_TransportDrone_HangingCable_Standby_Hovering.png",
        DIR, 384, 96,
        "Asset - 01 TransportDrone HangingCable Standby Hovering");

    /** 384x96px | ~4 frames */
    public static final SpriteAsset TRANSPORTDRONE_HANGINGCABLE_TRAVERSE_HORIZONTALMOVEMENT = SpriteAsset.single(
        "02_TransportDrone_HangingCable_Traverse_HorizontalMovement.png",
        DIR, 384, 96,
        "Asset - 02 TransportDrone HangingCable Traverse HorizontalMovement");

    /** 1536x96px | ~16 frames */
    public static final SpriteAsset TRANSPORTDRONE_HANGINGCABLE_DESCENT_CONTROLLEDLOWERING = SpriteAsset.single(
        "03_TransportDrone_HangingCable_Descent_ControlledLowering.png",
        DIR, 1536, 96,
        "Asset - 03 TransportDrone HangingCable Descent ControlledLowering");

    /** 576x96px | ~6 frames */
    public static final SpriteAsset TRANSPORTDRONE_HANGINGCABLE_CABLERELEASE_DISCONNECT = SpriteAsset.single(
        "04_TransportDrone_HangingCable_CableRelease_Disconnect.png",
        DIR, 576, 96,
        "Asset - 04 TransportDrone HangingCable CableRelease Disconnect");

    /** Total number of assets in this group */
    public static final int COUNT = 4;

    private Drone4Assets() { } // no instantiation
}
