package assets.enemies;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/enemies/drones/3
 * Total assets: 7
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Drone3Assets {

    private static final String DIR = "Resources/industrial-zone/characters/enemies/drones/3/";

    /** 192x48px | ~4 frames */
    public static final SpriteAsset TRANSPORTDRONE_HOVERBOARD_IDLE_FLOATING = SpriteAsset.single(
        "01_TransportDrone_Hoverboard_Idle_Floating.png",
        DIR, 192, 48,
        "Asset - 01 TransportDrone Hoverboard Idle Floating");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset TRANSPORTDRONE_HOVERBOARD_FORWARD_MOVEMENT = SpriteAsset.single(
        "02_TransportDrone_Hoverboard_Forward_Movement.png",
        DIR, 192, 48,
        "Asset - 02 TransportDrone Hoverboard Forward Movement");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset TRANSPORTDRONE_HOVERBOARD_BACKWARD_DECELERATION = SpriteAsset.single(
        "03_TransportDrone_Hoverboard_Backward_Deceleration.png",
        DIR, 192, 48,
        "Asset - 03 TransportDrone Hoverboard Backward Deceleration");

    /** 768x48px | ~16 frames */
    public static final SpriteAsset TRANSPORTDRONE_HOVERBOARD_EMERGENCYSTOP_MODE1 = SpriteAsset.single(
        "04_TransportDrone_Hoverboard_EmergencyStop_Mode1.png",
        DIR, 768, 48,
        "Asset - 04 TransportDrone Hoverboard EmergencyStop Mode1");

    /** 768x48px | ~16 frames */
    public static final SpriteAsset TRANSPORTDRONE_HOVERBOARD_FRICTIVESTOP_MODE2 = SpriteAsset.single(
        "05_TransportDrone_Hoverboard_FrictiveStop_Mode2.png",
        DIR, 768, 48,
        "Asset - 05 TransportDrone Hoverboard FrictiveStop Mode2");

    /** 768x48px | ~16 frames */
    public static final SpriteAsset TRANSPORTDRONE_HOVERBOARD_PRECISIONSTOP_MODE3 = SpriteAsset.single(
        "06_TransportDrone_Hoverboard_PrecisionStop_Mode3.png",
        DIR, 768, 48,
        "Asset - 06 TransportDrone Hoverboard PrecisionStop Mode3");

    /** 384x48px | ~8 frames */
    public static final SpriteAsset TRANSPORTDRONE_HOVERBOARD_SYSTEMMALFUNCTION_EXPLOSION = SpriteAsset.single(
        "07_TransportDrone_Hoverboard_SystemMalfunction_Explosion.png",
        DIR, 384, 48,
        "Asset - 07 TransportDrone Hoverboard SystemMalfunction Explosion");

    /** Total number of assets in this group */
    public static final int COUNT = 7;

    private Drone3Assets() { } // no instantiation
}
