package assets.enemies;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/enemies/drones/6
 * Total assets: 4
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Drone6Assets {

    private static final String DIR = "Resources/industrial-zone/characters/enemies/drones/6/";

    /** 192x48px | ~4 frames */
    public static final SpriteAsset ENEMYDRONE_HOVERPLATFORM_ADVANCE_MOVEMENT = SpriteAsset.single(
        "01_EnemyDrone_HoverPlatform_Advance_Movement_4Frames1Row.png",
        DIR, 192, 48,
        "Tile - 01 EnemyDrone HoverPlatform Advance Movement 4Frames1Row");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset ENEMYDRONE_HOVERPLATFORM_ADVANCEVARIANT_ALTERNATIVE = SpriteAsset.single(
        "02_EnemyDrone_HoverPlatform_AdvanceVariant_Alternative_4Frames1Row.png",
        DIR, 192, 48,
        "Tile - 02 EnemyDrone HoverPlatform AdvanceVariant Alternative 4Frames1Row");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset ENEMYDRONE_HOVERPLATFORM_PLATFORMDROPATTACK = SpriteAsset.single(
        "03_EnemyDrone_HoverPlatform_PlatformDropAttack_5Frames1Row.png",
        DIR, 288, 48,
        "Tile - 03 EnemyDrone HoverPlatform PlatformDropAttack 5Frames1Row");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset ENEMYDRONE_HOVERPLATFORM_CAPSULEPROJECTILEATTACK = SpriteAsset.single(
        "04_EnemyDrone_HoverPlatform_CapsuleProjectileAttack_7Frames1Row.png",
        DIR, 288, 48,
        "Tile - 04 EnemyDrone HoverPlatform CapsuleProjectileAttack 7Frames1Row");

    /** Total number of assets in this group */
    public static final int COUNT = 4;

    private Drone6Assets() { } // no instantiation
}
