package assets.enemies;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/enemies/drones/Character animations
 * Total assets: 3
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class DroneCharAnimAssets {

    private static final String DIR = "Resources/industrial-zone/characters/enemies/drones/Character animations/";

    /** 384x48px | ~8 frames */
    public static final SpriteAsset PLAYERCHARACTER_REMOTEOPERATOR_BIKER_WALKCYCLE = SpriteAsset.single(
        "01_PlayerCharacter_RemoteOperator_Biker_WalkCycle_6Frames1Row.png",
        DIR, 384, 48,
        "Character - 01 PlayerCharacter RemoteOperator Biker WalkCycle 6Frames1Row");

    /** 384x48px | ~8 frames */
    public static final SpriteAsset PLAYERCHARACTER_REMOTEOPERATOR_PUNK_WALKCYCLE = SpriteAsset.single(
        "02_PlayerCharacter_RemoteOperator_Punk_WalkCycle_6Frames1Row.png",
        DIR, 384, 48,
        "Character - 02 PlayerCharacter RemoteOperator Punk WalkCycle 6Frames1Row");

    /** 384x48px | ~8 frames */
    public static final SpriteAsset PLAYERCHARACTER_REMOTEOPERATOR_CYBORG_WALKCYCLE = SpriteAsset.single(
        "03_PlayerCharacter_RemoteOperator_Cyborg_WalkCycle_6Frames1Row.png",
        DIR, 384, 48,
        "Character - 03 PlayerCharacter RemoteOperator Cyborg WalkCycle 6Frames1Row");

    /** Total number of assets in this group */
    public static final int COUNT = 3;

    private DroneCharAnimAssets() { } // no instantiation
}
