package assets.enemies;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/enemies/drones/5
 * Total assets: 3
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Drone5Assets {

    private static final String DIR = "Resources/industrial-zone/characters/enemies/drones/5/";

    /** 288x72px | ~4 frames */
    public static final SpriteAsset TRANSPORTDRONE_VERTICALLIFT_IDLE_STANDBYPOSITION = SpriteAsset.single(
        "01_TransportDrone_VerticalLift_Idle_StandbyPosition.png",
        DIR, 288, 72,
        "Asset - 01 TransportDrone VerticalLift Idle StandbyPosition");

    /** 288x72px | ~4 frames */
    public static final SpriteAsset TRANSPORTDRONE_VERTICALLIFT_ASCENDING_UPWARDELEVATION = SpriteAsset.single(
        "02_TransportDrone_VerticalLift_Ascending_UpwardElevation.png",
        DIR, 288, 72,
        "Asset - 02 TransportDrone VerticalLift Ascending UpwardElevation");

    /** 432x72px | ~6 frames */
    public static final SpriteAsset TRANSPORTDRONE_VERTICALLIFT_SYSTEMFAILURE_EMERGENCYCRASH = SpriteAsset.single(
        "03_TransportDrone_VerticalLift_SystemFailure_EmergencyCrash.png",
        DIR, 432, 72,
        "Asset - 03 TransportDrone VerticalLift SystemFailure EmergencyCrash");

    /** Total number of assets in this group */
    public static final int COUNT = 3;

    private Drone5Assets() { } // no instantiation
}
