package assets.enemies;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/enemies/drones/5_2
 * Total assets: 3
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Drone5bAssets {

    private static final String DIR = "Resources/industrial-zone/characters/enemies/drones/5_2/";

    /** 192x48px | ~4 frames */
    public static final SpriteAsset TRANSPORTDRONE_ZONETRANSPORTER_IDLE_READY = SpriteAsset.single(
        "01_TransportDrone_ZoneTransporter_Idle_Ready.png",
        DIR, 192, 48,
        "Asset - 01 TransportDrone ZoneTransporter Idle Ready");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset TRANSPORTDRONE_ZONETRANSPORTER_TRAVERSE_HORIZONTAL = SpriteAsset.single(
        "02_TransportDrone_ZoneTransporter_Traverse_Horizontal.png",
        DIR, 192, 48,
        "Asset - 02 TransportDrone ZoneTransporter Traverse Horizontal");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset TRANSPORTDRONE_ZONETRANSPORTER_SYSTEMOVERLOAD_MALFUNCTION = SpriteAsset.single(
        "03_TransportDrone_ZoneTransporter_SystemOverload_Malfunction.png",
        DIR, 288, 48,
        "Asset - 03 TransportDrone ZoneTransporter SystemOverload Malfunction");

    /** Total number of assets in this group */
    public static final int COUNT = 3;

    private Drone5bAssets() { } // no instantiation
}
