package assets.enemies;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/enemies/drones/1
 * Total assets: 5
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Drone1Assets {

    private static final String DIR = "Resources/industrial-zone/characters/enemies/drones/1/";

    /** 192x48px | ~4 frames */
    public static final SpriteAsset ENEMYDRONE_UFOSAUCERHOVERING_IDLE = SpriteAsset.single(
        "01_EnemyDrone_UfoSaucerHovering_Idle_4Frames1Row.png",
        DIR, 192, 48,
        "Character - 01 EnemyDrone UfoSaucerHovering Idle 4Frames1Row");

    /** 192x48px | ~4 frames */
    public static final SpriteAsset ENEMYDRONE_UFOSAUCERHOVERING_TRAVERSE = SpriteAsset.single(
        "02_EnemyDrone_UfoSaucerHovering_Traverse_4Frames1Row.png",
        DIR, 192, 48,
        "Character - 02 EnemyDrone UfoSaucerHovering Traverse 4Frames1Row");

    /** 384x48px | ~8 frames */
    public static final SpriteAsset ENEMYDRONE_UFOSAUCERHOVERING_SCANBEAMATTACK = SpriteAsset.single(
        "03_EnemyDrone_UfoSaucerHovering_ScanBeamAttack_8Frames1Row.png",
        DIR, 384, 48,
        "Character - 03 EnemyDrone UfoSaucerHovering ScanBeamAttack 8Frames1Row");

    /** 384x48px | ~8 frames */
    public static final SpriteAsset ENEMYDRONE_UFOSAUCERHOVERING_TRAVERSEWITHBEAM = SpriteAsset.single(
        "04_EnemyDrone_UfoSaucerHovering_TraverseWithBeam_6Frames1Row.png",
        DIR, 384, 48,
        "Character - 04 EnemyDrone UfoSaucerHovering TraverseWithBeam 6Frames1Row");

    /** 288x48px | ~6 frames */
    public static final SpriteAsset ENEMYDRONE_UFOSAUCERHOVERING_DESTRUCTIONSEQUENCE = SpriteAsset.single(
        "05_EnemyDrone_UfoSaucerHovering_DestructionSequence_5Frames1Row.png",
        DIR, 288, 48,
        "Character - 05 EnemyDrone UfoSaucerHovering DestructionSequence 5Frames1Row");

    /** Total number of assets in this group */
    public static final int COUNT = 5;

    private Drone1Assets() { } // no instantiation
}
