package assets.enemies;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/enemies/drones/2
 * Total assets: 2
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Drone2Assets {

    private static final String DIR = "Resources/industrial-zone/characters/enemies/drones/2/";

    /** 576x96px | ~6 frames */
    public static final SpriteAsset ENEMYDRONE_JETDRONEVARIANT_AERIALFLIGHT = SpriteAsset.single(
        "01_EnemyDrone_JetDroneVariant_AerialFlight_4Frames1Row.png",
        DIR, 576, 96,
        "Character - 01 EnemyDrone JetDroneVariant AerialFlight 4Frames1Row");

    /** 96x16px | ~6 frames */
    public static final SpriteAsset ENEMYDRONE_JETDRONEVARIANT_BOMBPAYLOADRELEASE = SpriteAsset.single(
        "02_EnemyDrone_JetDroneVariant_BombPayloadRelease_4Frames1Row.png",
        DIR, 96, 16,
        "Character - 02 EnemyDrone JetDroneVariant BombPayloadRelease 4Frames1Row");

    /** Total number of assets in this group */
    public static final int COUNT = 2;

    private Drone2Assets() { } // no instantiation
}
