package assets.input;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: KeyBoard_Keys
 * Total assets: 66
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class KeyboardKeyAssets {

    private static final String DIR = "Resources/industrial-zone/KeyBoard_Keys/";

    /** 13x13px | static */
    public static final SpriteAsset KEY_0_NUMBER_SELECTITEM5ORQUICKSLOT0_COMBATACTION = SpriteAsset.single(
        "Key_0_Number_SelectItem5OrQuickslot0_CombatAction.png",
        DIR, 13, 13,
        "UI Element - Key 0 Number SelectItem5OrQuickslot0 CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_1_NUMBER_SELECTWEAPON1ORABILITY1_COMBATACTION = SpriteAsset.single(
        "Key_1_Number_SelectWeapon1OrAbility1_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key 1 Number SelectWeapon1OrAbility1 CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_2_NUMBER_SELECTWEAPON2ORABILITY2_COMBATACTION = SpriteAsset.single(
        "Key_2_Number_SelectWeapon2OrAbility2_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key 2 Number SelectWeapon2OrAbility2 CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_3_NUMBER_SELECTWEAPON3ORABILITY3_COMBATACTION = SpriteAsset.single(
        "Key_3_Number_SelectWeapon3OrAbility3_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key 3 Number SelectWeapon3OrAbility3 CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_4_NUMBER_SELECTWEAPON4ORABILITY4_COMBATACTION = SpriteAsset.single(
        "Key_4_Number_SelectWeapon4OrAbility4_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key 4 Number SelectWeapon4OrAbility4 CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_5_NUMBER_SELECTWEAPON5ORABILITY5_COMBATACTION = SpriteAsset.single(
        "Key_5_Number_SelectWeapon5OrAbility5_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key 5 Number SelectWeapon5OrAbility5 CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_6_NUMBER_SELECTITEM1ORQUICKSLOT6_COMBATACTION = SpriteAsset.single(
        "Key_6_Number_SelectItem1OrQuickslot6_CombatAction.png",
        DIR, 13, 13,
        "UI Element - Key 6 Number SelectItem1OrQuickslot6 CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_7_NUMBER_SELECTITEM2ORQUICKSLOT7_COMBATACTION = SpriteAsset.single(
        "Key_7_Number_SelectItem2OrQuickslot7_CombatAction.png",
        DIR, 13, 13,
        "UI Element - Key 7 Number SelectItem2OrQuickslot7 CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_8_NUMBER_SELECTITEM3ORQUICKSLOT8_COMBATACTION = SpriteAsset.single(
        "Key_8_Number_SelectItem3OrQuickslot8_CombatAction.png",
        DIR, 13, 13,
        "UI Element - Key 8 Number SelectItem3OrQuickslot8 CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_9_NUMBER_SELECTITEM4ORQUICKSLOT9_COMBATACTION = SpriteAsset.single(
        "Key_9_Number_SelectItem4OrQuickslot9_CombatAction.png",
        DIR, 13, 13,
        "UI Element - Key 9 Number SelectItem4OrQuickslot9 CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_A_LETTER_MOVELEFTORSTRAFELEFT_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_A_Letter_MoveLeftOrStrafeLeft_MovementTutorial.png",
        DIR, 13, 13,
        "Asset - Key A Letter MoveLeftOrStrafeLeft MovementTutorial");

    /** 19x13px | static */
    public static final SpriteAsset KEY_ALT_MODIFIER_ALTERNATEMODEORAIM_COMBATACTION = SpriteAsset.single(
        "Key_Alt_Modifier_AlternateModeOrAim_CombatAction.png",
        DIR, 19, 13,
        "Asset - Key Alt Modifier AlternateModeOrAim CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_ARROWDOWN_DIRECTION_MOVEDOWNORCROUCH_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_ArrowDown_Direction_MoveDownOrCrouch_MovementTutorial.png",
        DIR, 13, 13,
        "Asset - Key ArrowDown Direction MoveDownOrCrouch MovementTutorial");

    /** 13x13px | static */
    public static final SpriteAsset KEY_ARROWLEFT_DIRECTION_MOVELEFTORPREVITEM_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_ArrowLeft_Direction_MoveLeftOrPrevItem_MovementTutorial.png",
        DIR, 13, 13,
        "Asset - Key ArrowLeft Direction MoveLeftOrPrevItem MovementTutorial");

    /** 13x13px | static */
    public static final SpriteAsset KEY_ARROWRIGHT_DIRECTION_MOVERIGHTORNEXTITEM_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_ArrowRight_Direction_MoveRightOrNextItem_MovementTutorial.png",
        DIR, 13, 13,
        "Asset - Key ArrowRight Direction MoveRightOrNextItem MovementTutorial");

    /** 13x13px | static */
    public static final SpriteAsset KEY_ARROWUP_DIRECTION_MOVEUPORSCROLLMENU_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_ArrowUp_Direction_MoveUpOrScrollMenu_MovementTutorial.png",
        DIR, 13, 13,
        "UI Element - Key ArrowUp Direction MoveUpOrScrollMenu MovementTutorial");

    /** 13x13px | static */
    public static final SpriteAsset KEY_B2_LETTER_BOMBORSPECIALATTACK_COMBATACTION = SpriteAsset.single(
        "Key_B2_Letter_BombOrSpecialAttack_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key B2 Letter BombOrSpecialAttack CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_B_LETTER_BLOCKORSHIELD_COMBATACTION = SpriteAsset.single(
        "Key_B_Letter_BlockOrShield_CombatAction.png",
        DIR, 13, 13,
        "Tile - Key B Letter BlockOrShield CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_C_LETTER_CROUCHORCOVERMODE_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_C_Letter_CrouchOrCoverMode_MovementTutorial.png",
        DIR, 13, 13,
        "Asset - Key C Letter CrouchOrCoverMode MovementTutorial");

    /** 23x13px | static */
    public static final SpriteAsset KEY_CAPSLOCK_SPECIAL_ALTERNATEMODIFIER_UICONTROL = SpriteAsset.single(
        "Key_CapsLock_Special_AlternateModifier_UIControl.png",
        DIR, 23, 13,
        "UI Element - Key CapsLock Special AlternateModifier UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_COMMA_SYMBOL_PREVIOUSTARGETORDECREASEZOOM_UICONTROL = SpriteAsset.single(
        "Key_Comma_Symbol_PreviousTargetOrDecreaseZoom_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key Comma Symbol PreviousTargetOrDecreaseZoom UIControl");

    /** 23x13px | static */
    public static final SpriteAsset KEY_CTRL_MODIFIER_CROUCHORSPRINTMODIFIER_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_Ctrl_Modifier_CrouchOrSprintModifier_MovementTutorial.png",
        DIR, 23, 13,
        "Asset - Key Ctrl Modifier CrouchOrSprintModifier MovementTutorial");

    /** 13x13px | static */
    public static final SpriteAsset KEY_D_LETTER_MOVERIGHTORSTRAFERIGHT_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_D_Letter_MoveRightOrStrafeRight_MovementTutorial.png",
        DIR, 13, 13,
        "Asset - Key D Letter MoveRightOrStrafeRight MovementTutorial");

    /** 13x13px | static */
    public static final SpriteAsset KEY_E_LETTER_INTERACTORUSEOBJECT_ACTIONTUTORIAL = SpriteAsset.single(
        "Key_E_Letter_InteractOrUseObject_ActionTutorial.png",
        DIR, 13, 13,
        "Asset - Key E Letter InteractOrUseObject ActionTutorial");

    /** 22x13px | static */
    public static final SpriteAsset KEY_ENTER_SPECIAL_CONFIRMORINTERACT_UINAVIGATION = SpriteAsset.single(
        "Key_Enter_Special_ConfirmOrInteract_UINavigation.png",
        DIR, 22, 13,
        "UI Element - Key Enter Special ConfirmOrInteract UINavigation");

    /** 19x13px | static */
    public static final SpriteAsset KEY_ESCAPE_FUNCTION_PAUSEORQUITGAME_UICONTROL = SpriteAsset.single(
        "Key_Escape_Function_PauseOrQuitGame_UIControl.png",
        DIR, 19, 13,
        "UI Element - Key Escape Function PauseOrQuitGame UIControl");

    /** 17x13px | static */
    public static final SpriteAsset KEY_F10_FUNCTION_EXTRAACTION2_UICONTROL = SpriteAsset.single(
        "Key_F10_Function_ExtraAction2_UIControl.png",
        DIR, 17, 13,
        "UI Element - Key F10 Function ExtraAction2 UIControl");

    /** 17x13px | static */
    public static final SpriteAsset KEY_F11_FUNCTION_FULLSCREENTOGGLE_UICONTROL = SpriteAsset.single(
        "Key_F11_Function_FullscreenToggle_UIControl.png",
        DIR, 17, 13,
        "UI Element - Key F11 Function FullscreenToggle UIControl");

    /** 17x13px | static */
    public static final SpriteAsset KEY_F12_FUNCTION_DEVELOPERCONSOLE_UICONTROL = SpriteAsset.single(
        "Key_F12_Function_DeveloperConsole_UIControl.png",
        DIR, 17, 13,
        "UI Element - Key F12 Function DeveloperConsole UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_F1_FUNCTION_HELPORTUTORIALOVERLAY_UICONTROL = SpriteAsset.single(
        "Key_F1_Function_HelpOrTutorialOverlay_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key F1 Function HelpOrTutorialOverlay UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_F2_FUNCTION_DEBUGTOGGLEORMAP_UICONTROL = SpriteAsset.single(
        "Key_F2_Function_DebugToggleOrMap_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key F2 Function DebugToggleOrMap UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_F3_FUNCTION_INVENTORYORSTATS_UICONTROL = SpriteAsset.single(
        "Key_F3_Function_InventoryOrStats_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key F3 Function InventoryOrStats UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_F4_FUNCTION_AUDIOTOGGLEORSETTINGS_UICONTROL = SpriteAsset.single(
        "Key_F4_Function_AudioToggleOrSettings_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key F4 Function AudioToggleOrSettings UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_F5_FUNCTION_QUICKSAVEORCHECKPOINT_UICONTROL = SpriteAsset.single(
        "Key_F5_Function_QuickSaveOrCheckpoint_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key F5 Function QuickSaveOrCheckpoint UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_F6_FUNCTION_QUICKLOADORRESTART_UICONTROL = SpriteAsset.single(
        "Key_F6_Function_QuickLoadOrRestart_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key F6 Function QuickLoadOrRestart UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_F7_FUNCTION_SCREENSHOTORRECORD_UICONTROL = SpriteAsset.single(
        "Key_F7_Function_ScreenshotOrRecord_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key F7 Function ScreenshotOrRecord UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_F8_FUNCTION_SPEEDTOGGLEORREWIND_UICONTROL = SpriteAsset.single(
        "Key_F8_Function_SpeedToggleOrRewind_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key F8 Function SpeedToggleOrRewind UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_F9_FUNCTION_EXTRAACTION1_UICONTROL = SpriteAsset.single(
        "Key_F9_Function_ExtraAction1_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key F9 Function ExtraAction1 UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_F_LETTER_ACTIONORFIREWEAPON_COMBATACTION = SpriteAsset.single(
        "Key_F_Letter_ActionOrFireWeapon_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key F Letter ActionOrFireWeapon CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_G_LETTER_THROWGRENADEORPICKUP_COMBATACTION = SpriteAsset.single(
        "Key_G_Letter_ThrowGrenadeOrPickup_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key G Letter ThrowGrenadeOrPickup CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_H_LETTER_HEALORHELP_COMBATACTION = SpriteAsset.single(
        "Key_H_Letter_HealOrHelp_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key H Letter HealOrHelp CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_I_LETTER_INVENTORYOPEN_UINAVIGATION = SpriteAsset.single(
        "Key_I_Letter_InventoryOpen_UINavigation.png",
        DIR, 13, 13,
        "UI Element - Key I Letter InventoryOpen UINavigation");

    /** 13x13px | static */
    public static final SpriteAsset KEY_J_LETTER_JOURNALORJUMP2_UINAVIGATION = SpriteAsset.single(
        "Key_J_Letter_JournalOrJump2_UINavigation.png",
        DIR, 13, 13,
        "UI Element - Key J Letter JournalOrJump2 UINavigation");

    /** 13x13px | static */
    public static final SpriteAsset KEY_K_LETTER_KICKORSKILLTREE_COMBATACTION = SpriteAsset.single(
        "Key_K_Letter_KickOrSkillTree_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key K Letter KickOrSkillTree CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_L_LETTER_LOCKONTARGETORLIGHT_COMBATACTION = SpriteAsset.single(
        "Key_L_Letter_LockOnTargetOrLight_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key L Letter LockOnTargetOrLight CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_L_LETTER_LOCKTARGETORLOG_COMBATACTION = SpriteAsset.single(
        "Key_L_Letter_LockTargetOrLog_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key L Letter LockTargetOrLog CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_M2_LETTER_MELEEORMOVE_COMBATACTION = SpriteAsset.single(
        "Key_M2_Letter_MeleeOrMove_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key M2 Letter MeleeOrMove CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_M_LETTER_MAPORMELEEATTACK_COMBATACTION = SpriteAsset.single(
        "Key_M_Letter_MapOrMeleeAttack_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key M Letter MapOrMeleeAttack CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_MINUS_SYMBOL_ZOOMOUTORDECREASEVALUE_UICONTROL = SpriteAsset.single(
        "Key_Minus_Symbol_ZoomOutOrDecreaseValue_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key Minus Symbol ZoomOutOrDecreaseValue UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_N2_LETTER_NEXTWEAPONORNOTIFICATION_COMBATACTION = SpriteAsset.single(
        "Key_N2_Letter_NextWeaponOrNotification_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key N2 Letter NextWeaponOrNotification CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_N_LETTER_NOTEPADORNEXTOBJECTIVE_UINAVIGATION = SpriteAsset.single(
        "Key_N_Letter_NotepadOrNextObjective_UINavigation.png",
        DIR, 13, 13,
        "UI Element - Key N Letter NotepadOrNextObjective UINavigation");

    /** 13x13px | static */
    public static final SpriteAsset KEY_O_LETTER_OBJECTIVEORMAP_UINAVIGATION = SpriteAsset.single(
        "Key_O_Letter_ObjectiveOrMap_UINavigation.png",
        DIR, 13, 13,
        "UI Element - Key O Letter ObjectiveOrMap UINavigation");

    /** 13x13px | static */
    public static final SpriteAsset KEY_P_LETTER_PAUSEGAME_UICONTROL = SpriteAsset.single(
        "Key_P_Letter_PauseGame_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key P Letter PauseGame UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_PERIOD_SYMBOL_NEXTTARGETORINCREASEZOOM_UICONTROL = SpriteAsset.single(
        "Key_Period_Symbol_NextTargetOrIncreaseZoom_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key Period Symbol NextTargetOrIncreaseZoom UIControl");

    /** 22x13px | static */
    public static final SpriteAsset KEY_Q_LETTER_SWAPWEAPONORSPECIALLEFT_COMBATACTION = SpriteAsset.single(
        "Key_Q_Letter_SwapWeaponOrSpecialLeft_CombatAction.png",
        DIR, 22, 13,
        "Asset - Key Q Letter SwapWeaponOrSpecialLeft CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_R_LETTER_RELOADORRESPAWN_COMBATACTION = SpriteAsset.single(
        "Key_R_Letter_ReloadOrRespawn_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key R Letter ReloadOrRespawn CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_S_LETTER_MOVEDOWNORCROUCH_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_S_Letter_MoveDownOrCrouch_MovementTutorial.png",
        DIR, 13, 13,
        "Asset - Key S Letter MoveDownOrCrouch MovementTutorial");

    /** 60x13px | ~4 frames */
    public static final SpriteAsset KEY_SPACEBAR_SPECIAL_JUMPORCONFIRM_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_Spacebar_Special_JumpOrConfirm_MovementTutorial.png",
        DIR, 60, 13,
        "Asset - Key Spacebar Special JumpOrConfirm MovementTutorial");

    /** 13x13px | static */
    public static final SpriteAsset KEY_T_LETTER_THROWORTAUNT_COMBATACTION = SpriteAsset.single(
        "Key_T_Letter_ThrowOrTaunt_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key T Letter ThrowOrTaunt CombatAction");

    /** 22x13px | static */
    public static final SpriteAsset KEY_TAB_SPECIAL_INVENTORYORMAPTOGGLE_UINAVIGATION = SpriteAsset.single(
        "Key_Tab_Special_InventoryOrMapToggle_UINavigation.png",
        DIR, 22, 13,
        "UI Element - Key Tab Special InventoryOrMapToggle UINavigation");

    /** 13x13px | static */
    public static final SpriteAsset KEY_U_LETTER_USEITEMORUPGRADE_COMBATACTION = SpriteAsset.single(
        "Key_U_Letter_UseItemOrUpgrade_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key U Letter UseItemOrUpgrade CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_V_LETTER_VAULTORMELEEFINISHER_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_V_Letter_VaultOrMeleeFinisher_MovementTutorial.png",
        DIR, 13, 13,
        "Asset - Key V Letter VaultOrMeleeFinisher MovementTutorial");

    /** 13x13px | static */
    public static final SpriteAsset KEY_W_LETTER_MOVEUPORFORWARD_MOVEMENTTUTORIAL = SpriteAsset.single(
        "Key_W_Letter_MoveUpOrForward_MovementTutorial.png",
        DIR, 13, 13,
        "Asset - Key W Letter MoveUpOrForward MovementTutorial");

    /** 13x13px | static */
    public static final SpriteAsset KEY_X_LETTER_EXECUTEORDODGE_COMBATACTION = SpriteAsset.single(
        "Key_X_Letter_ExecuteOrDodge_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key X Letter ExecuteOrDodge CombatAction");

    /** 13x13px | static */
    public static final SpriteAsset KEY_Y_LETTER_EXTRAACTIONORYES_UICONTROL = SpriteAsset.single(
        "Key_Y_Letter_ExtraActionOrYes_UIControl.png",
        DIR, 13, 13,
        "UI Element - Key Y Letter ExtraActionOrYes UIControl");

    /** 13x13px | static */
    public static final SpriteAsset KEY_Z_LETTER_ZOOMORROLLLEFT_COMBATACTION = SpriteAsset.single(
        "Key_Z_Letter_ZoomOrRollLeft_CombatAction.png",
        DIR, 13, 13,
        "Asset - Key Z Letter ZoomOrRollLeft CombatAction");

    /** Total number of assets in this group */
    public static final int COUNT = 66;

    private KeyboardKeyAssets() { } // no instantiation
}
