package assets.input;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: Mouse_keys
 * Total assets: 21
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class MouseKeyAssets {

    private static final String DIR = "Resources/industrial-zone/Mouse_keys/";

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_LEFTCLICK_BLUE_LEVEL1TUTORIALDISPLAY_PRIMARYACTION = SpriteAsset.single(
        "Mouse_LeftClick_Blue_Level1TutorialDisplay_PrimaryAction.png",
        DIR, 96, 96,
        "Background - Mouse LeftClick Blue Level1TutorialDisplay PrimaryAction");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_LEFTCLICK_RED_LEVEL2COMBATDISPLAY_PRIMARYATTACK = SpriteAsset.single(
        "Mouse_LeftClick_Red_Level2CombatDisplay_PrimaryAttack.png",
        DIR, 96, 96,
        "Background - Mouse LeftClick Red Level2CombatDisplay PrimaryAttack");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_MIDDLECLICK_BLUE_LEVEL1TUTORIALDISPLAY_SECONDARYACTION = SpriteAsset.single(
        "Mouse_MiddleClick_Blue_Level1TutorialDisplay_SecondaryAction.png",
        DIR, 96, 96,
        "Background - Mouse MiddleClick Blue Level1TutorialDisplay SecondaryAction");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_MIDDLECLICK_RED_LEVEL2COMBATDISPLAY_SECONDARYACTION = SpriteAsset.single(
        "Mouse_MiddleClick_Red_Level2CombatDisplay_SecondaryAction.png",
        DIR, 96, 96,
        "Background - Mouse MiddleClick Red Level2CombatDisplay SecondaryAction");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_MOVEDIAGONAL_FOURDIAGONALS_DIAGONALAIMMOVE_TUTORIAL = SpriteAsset.single(
        "Mouse_MoveDiagonal_FourDiagonals_DiagonalAimMove_Tutorial.png",
        DIR, 96, 96,
        "Asset - Mouse MoveDiagonal FourDiagonals DiagonalAimMove Tutorial");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_MOVEDOWN_ARROWDOWN_SCROLLDOWNORAIMDOWN_TUTORIAL = SpriteAsset.single(
        "Mouse_MoveDown_ArrowDown_ScrollDownOrAimDown_Tutorial.png",
        DIR, 96, 96,
        "Asset - Mouse MoveDown ArrowDown ScrollDownOrAimDown Tutorial");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_MOVELEFTRIGHT_BOTHARROWS_HORIZONTALSCROLLORAIM_TUTORIAL = SpriteAsset.single(
        "Mouse_MoveLeftRight_BothArrows_HorizontalScrollOrAim_Tutorial.png",
        DIR, 96, 96,
        "Asset - Mouse MoveLeftRight BothArrows HorizontalScrollOrAim Tutorial");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_MOVELEFT_ARROWLEFT_SCROLLLEFTORAIMLEFT_TUTORIAL = SpriteAsset.single(
        "Mouse_MoveLeft_ArrowLeft_ScrollLeftOrAimLeft_Tutorial.png",
        DIR, 96, 96,
        "Asset - Mouse MoveLeft ArrowLeft ScrollLeftOrAimLeft Tutorial");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_MOVERIGHT_ARROWRIGHT_SCROLLRIGHTORAIMRIGHT_TUTORIAL = SpriteAsset.single(
        "Mouse_MoveRight_ArrowRight_ScrollRightOrAimRight_Tutorial.png",
        DIR, 96, 96,
        "Asset - Mouse MoveRight ArrowRight ScrollRightOrAimRight Tutorial");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_MOVEUPDOWN_BOTHARROWS_VERTICALSCROLLORAIM_TUTORIAL = SpriteAsset.single(
        "Mouse_MoveUpDown_BothArrows_VerticalScrollOrAim_Tutorial.png",
        DIR, 96, 96,
        "Asset - Mouse MoveUpDown BothArrows VerticalScrollOrAim Tutorial");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_MOVEUP_ARROWUP_SCROLLUPORAIMUP_TUTORIAL = SpriteAsset.single(
        "Mouse_MoveUp_ArrowUp_ScrollUpOrAimUp_Tutorial.png",
        DIR, 96, 96,
        "Asset - Mouse MoveUp ArrowUp ScrollUpOrAimUp Tutorial");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_MOVE_FOURDIRECTIONS_CAMERAORCROSSHAIRMOVE_TUTORIAL = SpriteAsset.single(
        "Mouse_Move_FourDirections_CameraOrCrosshairMove_Tutorial.png",
        DIR, 96, 96,
        "Asset - Mouse Move FourDirections CameraOrCrosshairMove Tutorial");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_NEUTRAL_NOHIGHLIGHT_DEFAULTIDLESTATE_DISPLAY = SpriteAsset.single(
        "Mouse_Neutral_NoHighlight_DefaultIdleState_Display.png",
        DIR, 96, 96,
        "Asset - Mouse Neutral NoHighlight DefaultIdleState Display");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_RIGHTCLICK_BLUE_LEVEL1TUTORIALDISPLAY_AIMORCONTEXT = SpriteAsset.single(
        "Mouse_RightClick_Blue_Level1TutorialDisplay_AimOrContext.png",
        DIR, 96, 96,
        "Background - Mouse RightClick Blue Level1TutorialDisplay AimOrContext");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_RIGHTCLICK_RED_LEVEL2COMBATDISPLAY_AIMORSPECIALATTACK = SpriteAsset.single(
        "Mouse_RightClick_Red_Level2CombatDisplay_AimOrSpecialAttack.png",
        DIR, 96, 96,
        "Background - Mouse RightClick Red Level2CombatDisplay AimOrSpecialAttack");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_SCROLLDOWN_BLUE_LEVEL1TUTORIALDISPLAY_ZOOMOUTORPREVITEM = SpriteAsset.single(
        "Mouse_ScrollDown_Blue_Level1TutorialDisplay_ZoomOutOrPrevItem.png",
        DIR, 96, 96,
        "Background - Mouse ScrollDown Blue Level1TutorialDisplay ZoomOutOrPrevItem");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_SCROLLDOWN_RED_LEVEL2COMBATDISPLAY_ZOOMOUTORPREVWEAPON = SpriteAsset.single(
        "Mouse_ScrollDown_Red_Level2CombatDisplay_ZoomOutOrPrevWeapon.png",
        DIR, 96, 96,
        "Background - Mouse ScrollDown Red Level2CombatDisplay ZoomOutOrPrevWeapon");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_SCROLLUP_BLUE_LEVEL1TUTORIALDISPLAY_ZOOMINORNEXTITEM = SpriteAsset.single(
        "Mouse_ScrollUp_Blue_Level1TutorialDisplay_ZoomInOrNextItem.png",
        DIR, 96, 96,
        "Background - Mouse ScrollUp Blue Level1TutorialDisplay ZoomInOrNextItem");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_SCROLLUP_RED_LEVEL2COMBATDISPLAY_ZOOMINORNEXTWEAPON = SpriteAsset.single(
        "Mouse_ScrollUp_Red_Level2CombatDisplay_ZoomInOrNextWeapon.png",
        DIR, 96, 96,
        "Background - Mouse ScrollUp Red Level2CombatDisplay ZoomInOrNextWeapon");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_SCROLLWHEEL_BLUE_LEVEL1TUTORIALDISPLAY_ZOOMORWEAPONSWAP = SpriteAsset.single(
        "Mouse_ScrollWheel_Blue_Level1TutorialDisplay_ZoomOrWeaponSwap.png",
        DIR, 96, 96,
        "Background - Mouse ScrollWheel Blue Level1TutorialDisplay ZoomOrWeaponSwap");

    /** 96x96px | static */
    public static final SpriteAsset MOUSE_SCROLLWHEEL_RED_LEVEL2COMBATDISPLAY_ZOOMORWEAPONSWAP = SpriteAsset.single(
        "Mouse_ScrollWheel_Red_Level2CombatDisplay_ZoomOrWeaponSwap.png",
        DIR, 96, 96,
        "Background - Mouse ScrollWheel Red Level2CombatDisplay ZoomOrWeaponSwap");

    /** Total number of assets in this group */
    public static final int COUNT = 21;

    private MouseKeyAssets() { } // no instantiation
}
