/*
 * Decompiled with CFR 0.152.
 */
package animation;

public static class AnimationAndSpriteLoader.KeyboardKeyBindings {
    public static final String INPUT_TYPE = "keyboard_key";
    public static final String DIRECTORY = "Resources/industrial-zone/KeyBoard_Keys";
    public static final int TOTAL_KEY_BINDINGS = 100;
    public static final String[] NUMBER_KEY_BINDINGS = new String[]{"Key_0_Number_SelectItemOrQuickslot0_CombatAction.png", "Key_1_Number_SelectWeapon1OrAbility1_CombatAction.png", "Key_2_Number_SelectWeapon2OrAbility2_CombatAction.png", "Key_3_Number_SelectWeapon3OrAbility3_CombatAction.png", "Key_4_Number_SelectWeapon4OrAbility4_CombatAction.png", "Key_5_Number_SelectWeapon5OrAbility5_CombatAction.png", "Key_6_Number_SelectItem1OrQuickslot6_CombatAction.png", "Key_7_Number_SelectItem2OrQuickslot7_CombatAction.png", "Key_8_Number_SelectItem3OrQuickslot8_CombatAction.png", "Key_9_Number_SelectItem4OrQuickslot9_CombatAction.png"};
    public static final String[] LETTER_KEY_BINDINGS = new String[]{"Key_A_Letter_MoveLeftOrStrafeLeft_MovementTutorial.png", "Key_Alt_Modifier_AlternateMode_OrAim_CombatAction.png", "Key_ArrowDown_Direction_MoveDownOrCrouch_MovementTutorial.png", "Key_ArrowLeft_Direction_MoveLeft_MovementTutorial.png", "Key_ArrowRight_Direction_MoveRight_MovementTutorial.png", "Key_ArrowUp_Direction_MoveUp_OrScrollMenu_MovementTutorial.png", "Key_B_Letter_BombOrSpecialAttack_CombatAction.png", "Key_C_Letter_CrouchOrShield_CombatAction.png", "Key_Caps_Lock_Special_Alternate_Modifier_UIControl.png", "Key_Comma_Symbol_PreviousTargetOrDecreaseValue_UIControl.png", "Key_Ctrl_Modifier_CrouchOrSprintMod_MovementTutorial.png", "Key_D_Letter_MoveRightOrStrafeRight_MovementTutorial.png", "Key_E_Letter_ActionOrFireWeapon_CombatAction.png", "Key_Enter_Special_ConfirmOrInte_raction_UINavigation.png", "Key_Escape_Function_PauseGame_UIControl.png", "Key_F1_Function_DebugToggleOrMap_UIControl.png", "Key_F2_Function_ExtraAction1_UIControl.png", "Key_F3_Function_Inventory_OrStat_UIControl.png", "Key_F4_Function_Audio_ToggleOrSettings_UIControl.png", "Key_F5_Function_QuickSave_Orch_start_UIControl.png", "Key_F6_Function_QuickLoadOrRe_start_UIControl.png", "Key_F7_Function_ScreenshotOrRe_wind_UIControl.png", "Key_F8_Function_SpeedToggleOrRewind_UIControl.png", "Key_G_Letter_ThrowGrenade_OrPowerup_CombatAction.png", "Key_H_Letter_Inventory_Open_UINavigation.png", "Key_I_Letter_InventoryOpen_UINavigation.png", "Key_J_Letter_JournalOrLump_UINavigation.png", "Key_K_Letter_KickOrStillTree_CombatAction.png", "Key_L_Letter_LockOnTargetOrLight_CombatAction.png", "Key_M_Letter_MapOrMeleeAttack_CombatAction.png", "Key_Minus_Symbol_ZoomOutOrDecreaseValue_UIControl.png", "Key_N_Letter_NextObje_ctiveOrMap_UINavigation.png", "Key_O_Letter_Objective_OrMap_UINavigation.png", "Key_P_Letter_PauseGame_UIControl.png", "Key_Period_Symbol_NextTargetOrIncreaseValue_UIControl.png", "Key_Q_Letter_SwapOpenOrSpawn_CombatAction.png", "Key_R_Letter_Reload_CombatAction.png", "Key_S_Letter_MoveDown_OrCrouch_MovementTutorial.png", "Key_ScrollDown_Direction_ZoomOutOrPrevItem_UIControl.png", "Key_ScrollUp_Direction_ZoomInOrNextItem_UIControl.png", "Key_Spacebar_Special_Jump_OrConfirm_MovementTutorial.png", "Key_T_Letter_UseItemOrToggle_UIControl.png", "Key_Tab_Special_InventoryOrMap_UINavigation.png", "Key_U_Letter_UseMelecOrPowerup_CombatAction.png", "Key_V_Letter_VoiceChat_Or_ViewMode_UIControl.png", "Key_W_Letter_MoveUpOrCombat_MovementTutorial.png", "Key_X_Letter_ExecuteOrDodge_CombatAction.png", "Key_Y_Letter_ExtraAction1OrYes_UIControl.png", "Key_Z_Letter_ZoomOrRollLeft_CombatAction.png"};
    public static final String SPECIAL_KEY_ESCAPE = "Key_Escape_Function_PauseOrQuit_OrMenu_UIControl.png";
    public static final String SPECIAL_KEY_ENTER = "Key_Enter_Special_ConfirmOrInteaction_UINavigation.png";
    public static final String SPECIAL_KEY_TAB = "Key_Tab_Special_InventoryOrMap_UINavigation.png";

    public static final String getKeyBinding(String string, String string2) {
        return "Key_" + string + "_" + string2 + "_CombatAction.png";
    }
}
