package assets.animated;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/power-station-level-2/4 Animated objects
 * Total assets: 4
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level2AnimatedAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/power-station-level-2/4 Animated objects/";

    /** 192x24px | ~8 frames | 80ms/f | loop */
    public static final SpriteAsset ANIM_COLLECTIBLE_CARD_BLUESPINNINGFLOAT_PICKUPITEM = SpriteAsset.loop(
        "Anim_Collectible_Card_6Frames1Row_BlueSpinningFloat_PickupItem_Loop80ms.png",
        DIR, 192, 24, 80,
        "Anim Collectible Card 6Frames1Row BlueSpinningFloat PickupItem Loop80ms");

    /** 144x24px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset ANIM_COLLECTIBLE_MONEY_GREENBANKNOTESSPINFLIP_CURRENCYPICKUP = SpriteAsset.loop(
        "Anim_Collectible_Money_6Frames1Row_GreenBanknotesSpinFlip_CurrencyPickup_Loop80ms.png",
        DIR, 144, 24, 80,
        "Anim Collectible Money 6Frames1Row GreenBanknotesSpinFlip CurrencyPickup Loop80ms");

    /** 128x48px | ~2 frames | 120ms/f | loop */
    public static final SpriteAsset ANIM_HAZARD_TURRET_MULTIFRAME1ROW_TURRETFIRINGPROJECTILE_DAMAGEONFIRE = SpriteAsset.loop(
        "Anim_Hazard_Turret_MultiFrame1Row_TurretFiringProjectile_DamageOnFire_Loop120ms.png",
        DIR, 128, 48, 120,
        "Anim Hazard Turret MultiFrame1Row TurretFiringProjectile DamageOnFire Loop120ms");

    /** 128x32px | ~4 frames | 100ms/f */
    public static final SpriteAsset ANIM_INTERACTIVE_CHEST_BLUETEALLIDOPENSEQUENCE = SpriteAsset.once(
        "Anim_Interactive_Chest_8Frames1Row_BlueTealLidOpenSequence_PlayOnce100ms.png",
        DIR, 128, 32, 100,
        "Anim Interactive Chest 8Frames1Row BlueTealLidOpenSequence PlayOnce100ms");

    /** Total number of assets in this group */
    public static final int COUNT = 4;

    private Level2AnimatedAssets() { } // no instantiation
}
