package assets.animated;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: 1 Tiles/Industrial_zone_level_1/4 Animated objects
 * Total assets: 12
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class Level1AnimatedAssets {

    private static final String DIR = "Resources/industrial-zone/1 Tiles/Industrial_zone_level_1/4 Animated objects/";

    /** 192x24px | ~8 frames | 80ms/f | loop */
    public static final SpriteAsset ANIM_COLLECTIBLE_CARD_WHITEBLUESPINNINGFLOAT_PICKUPITEM = SpriteAsset.loop(
        "Anim_Collectible_Card_6Frames1Row_WhiteBlueSpinningFloat_PickupItem_Loop80ms.png",
        DIR, 192, 24, 80,
        "Anim Collectible Card 6Frames1Row WhiteBlueSpinningFloat PickupItem Loop80ms");

    /** 144x24px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset ANIM_COLLECTIBLE_MONEY_GREENBANKNOTESSPINFLIP_CURRENCYPICKUP = SpriteAsset.loop(
        "Anim_Collectible_Money_6Frames1Row_GreenBanknotesSpinFlip_CurrencyPickup_Loop80ms.png",
        DIR, 144, 24, 80,
        "Anim Collectible Money 6Frames1Row GreenBanknotesSpinFlip CurrencyPickup Loop80ms");

    /** 128x32px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset ANIM_DECO_SCREEN1_BLUEMONITORFLICKER_WALLPANELTECHDECO = SpriteAsset.loop(
        "Anim_Deco_Screen1_4Frames1Row_BlueMonitorFlicker_WallPanelTechDeco_Loop150ms.png",
        DIR, 128, 32, 150,
        "Anim Deco Screen1 4Frames1Row BlueMonitorFlicker WallPanelTechDeco Loop150ms");

    /** 128x42px | ~3 frames | 150ms/f | loop */
    public static final SpriteAsset ANIM_DECO_SCREEN2_REDBLUEMONITORFLICKER_WALLPANELALTDECO = SpriteAsset.loop(
        "Anim_Deco_Screen2_4Frames1Row_RedBlueMonitorFlicker_WallPanelAltDeco_Loop150ms.png",
        DIR, 128, 42, 150,
        "Anim Deco Screen2 4Frames1Row RedBlueMonitorFlicker WallPanelAltDeco Loop150ms");

    /** 256x64px | ~4 frames | 90ms/f | loop */
    public static final SpriteAsset ANIM_HAZARD_HAMMER_REDORANGESWINGARC_DAMAGEFRAMES3TO5 = SpriteAsset.loop(
        "Anim_Hazard_Hammer_6Frames1Row_RedOrangeSwingArc_DamageFrames3to5_Loop90ms.png",
        DIR, 256, 64, 90,
        "Anim Hazard Hammer 6Frames1Row RedOrangeSwingArc DamageFrames3to5 Loop90ms");

    /** 256x32px | ~8 frames | 100ms/f */
    public static final SpriteAsset ANIM_INTERACTIVE_CHEST_ORANGEREDLIDOPENSEQUENCE = SpriteAsset.once(
        "Anim_Interactive_Chest_8Frames1Row_OrangeRedLidOpenSequence_PlayOnce100ms.png",
        DIR, 256, 32, 100,
        "Anim Interactive Chest 8Frames1Row OrangeRedLidOpenSequence PlayOnce100ms");

    /** 128x32px | ~4 frames | 60ms/f | loop */
    public static final SpriteAsset ANIM_PLATFORM_CONVEYORFASTVARIANT_ALTSPEEDORDIRECTION = SpriteAsset.loop(
        "Anim_Platform_ConveyorFastVariant_4Frames1Row_AltSpeedOrDirection_Loop60ms.png",
        DIR, 128, 32, 60,
        "Anim Platform ConveyorFastVariant 4Frames1Row AltSpeedOrDirection Loop60ms");

    /** 384x32px | ~12 frames | 80ms/f | loop */
    public static final SpriteAsset ANIM_PLATFORM_CONVEYORFULL_FULLWIDTHBELTRUNNING_MOVESPLAYERRIGHT = SpriteAsset.loop(
        "Anim_Platform_ConveyorFull_4Frames1Row_FullWidthBeltRunning_MovesPlayerRight_Loop80ms.png",
        DIR, 384, 32, 80,
        "Anim Platform ConveyorFull 4Frames1Row FullWidthBeltRunning MovesPlayerRight Loop80ms");

    /** 128x32px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset ANIM_PLATFORM_CONVEYORSECTION_REPEATABLETILESEGMENT = SpriteAsset.loop(
        "Anim_Platform_ConveyorSection_4Frames1Row_RepeatableTileSegment_Loop80ms.png",
        DIR, 128, 32, 80,
        "Anim Platform ConveyorSection 4Frames1Row RepeatableTileSegment Loop80ms");

    /** 128x32px | ~4 frames | 80ms/f | loop */
    public static final SpriteAsset ANIM_PLATFORM_CONVEYORSHORTA_SHORTERBELTSEGMENT_MOVESPLAYERRIGHT = SpriteAsset.loop(
        "Anim_Platform_ConveyorShortA_4Frames1Row_ShorterBeltSegment_MovesPlayerRight_Loop80ms.png",
        DIR, 128, 32, 80,
        "Anim Platform ConveyorShortA 4Frames1Row ShorterBeltSegment MovesPlayerRight Loop80ms");

    /** 256x32px | ~8 frames | 100ms/f | loop */
    public static final SpriteAsset ANIM_PLATFORM_MOVINGRED_SLIDINGLEFTRIGHT_PLAYERRIDEABLE = SpriteAsset.loop(
        "Anim_Platform_MovingRed_6Frames1Row_SlidingLeftRight_PlayerRideable_Loop100ms.png",
        DIR, 256, 32, 100,
        "Anim Platform MovingRed 6Frames1Row SlidingLeftRight PlayerRideable Loop100ms");

    /** 256x64px | ~4 frames | 120ms/f */
    public static final SpriteAsset ANIM_PORTAL_LEVELENTRY_REDCHEVRONGATEOPENING_LEVELTRANSITION = SpriteAsset.once(
        "Anim_Portal_LevelEntry_4Frames1Row_RedChevronGateOpening_LevelTransition_PlayOnce120ms.png",
        DIR, 256, 64, 120,
        "Anim Portal LevelEntry 4Frames1Row RedChevronGateOpening LevelTransition PlayOnce120ms");

    /** Total number of assets in this group */
    public static final int COUNT = 12;

    private Level1AnimatedAssets() { } // no instantiation
}
