package assets.audio;

import assets.AudioAsset;

/**
 * Auto-generated audio asset descriptors for: audio/sfx
 * Total assets: 35
 * Type: Sound Effect
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class SfxAssets {

    private static final String DIR = "Resources/industrial-zone/audio/sfx/";

    public static final AudioAsset ALTERNATIVE_THEME_CHINESE_STREET = AudioAsset.sfx(
        "._Alternative_theme_Chinese_Street.wav", DIR,
        "Asset - . Alternative theme Chinese Street.wav");

    public static final AudioAsset BATTLE_THEME_CHINESE_STREET = AudioAsset.sfx(
        "._Battle_theme_Chinese_Street.wav", DIR,
        "Asset - . Battle theme Chinese Street.wav");

    public static final AudioAsset BELL_ON_THE_DOOR = AudioAsset.sfx(
        "._Bell_on_the_door.wav", DIR,
        "Asset - . Bell on the door.wav");

    public static final AudioAsset BOMB_DROP = AudioAsset.sfx(
        "._Bomb_drop.wav", DIR,
        "Asset - . Bomb drop.wav");

    public static final AudioAsset CALM_THEME_CHINESE_STREET = AudioAsset.sfx(
        "._Calm_theme_Chinese_Street.wav", DIR,
        "Asset - . Calm theme Chinese Street.wav");

    public static final AudioAsset CLICK_DIGITAL_1 = AudioAsset.sfx(
        "._Click_digital_1.wav", DIR,
        "Asset - . Click digital 1.wav");

    public static final AudioAsset CLICK_DIGITAL_2 = AudioAsset.sfx(
        "._Click_digital_2.wav", DIR,
        "Asset - . Click digital 2.wav");

    public static final AudioAsset CREAKING_WOODEN_DOOR = AudioAsset.sfx(
        "._Creaking_wooden_door.wav", DIR,
        "Asset - . Creaking wooden door.wav");

    public static final AudioAsset DOOR_WITH_PASSWORD = AudioAsset.sfx(
        "._Door_with_password.wav", DIR,
        "Asset - . Door with password.wav");

    public static final AudioAsset ELEVATOR_MOTOR = AudioAsset.sfx(
        "._Elevator_motor.wav", DIR,
        "Asset - . Elevator motor.wav");

    public static final AudioAsset EXPLOSION = AudioAsset.sfx(
        "._Explosion.wav", DIR,
        "Asset - . Explosion.wav");

    public static final AudioAsset FLYING_PLATFORM_ATTAK_1 = AudioAsset.sfx(
        "._Flying_platform_attak_1.wav", DIR,
        "Tile - . Flying platform attak 1.wav");

    public static final AudioAsset FLYING_PLATFORM_ATTAK_2 = AudioAsset.sfx(
        "._Flying_platform_attak_2.wav", DIR,
        "Tile - . Flying platform attak 2.wav");

    public static final AudioAsset HOVERING_ROBOT_STING = AudioAsset.sfx(
        "._Hovering_robot_sting.wav", DIR,
        "Asset - . Hovering robot sting.wav");

    public static final AudioAsset HOVERING_ROBOT_WALK_LOOPABLE = AudioAsset.sfx(
        "._Hovering_robot_walk_loopable.wav", DIR,
        "Asset - . Hovering robot walk loopable.wav");

    public static final AudioAsset KARATEKA_ATTACK = AudioAsset.sfx(
        "._Karateka_attack.wav", DIR,
        "Asset - . Karateka attack.wav");

    public static final AudioAsset LASER_SWORD_1 = AudioAsset.sfx(
        "._Laser_sword_1.wav", DIR,
        "Asset - . Laser sword 1.wav");

    public static final AudioAsset LASER_SWORD_2 = AudioAsset.sfx(
        "._Laser_sword_2.wav", DIR,
        "Asset - . Laser sword 2.wav");

    public static final AudioAsset LIFT_MECHANISM = AudioAsset.sfx(
        "._Lift_mechanism.wav", DIR,
        "Asset - . Lift mechanism.wav");

    public static final AudioAsset MAIN_THEME_CHINESE_STREET = AudioAsset.sfx(
        "._Main_theme_Chinese_Street.wav", DIR,
        "Asset - . Main theme Chinese Street.wav");

    public static final AudioAsset MELODY_OF_ATTRACTION_LOOPABLE = AudioAsset.sfx(
        "._Melody_of_attraction_loopable.wav", DIR,
        "Asset - . Melody of attraction loopable.wav");

    public static final AudioAsset MELODY_OF_THE_WIN = AudioAsset.sfx(
        "._Melody_of_the_win.wav", DIR,
        "Asset - . Melody of the win.wav");

    public static final AudioAsset PORTAL_1 = AudioAsset.sfx(
        "._Portal_1.wav", DIR,
        "Asset - . Portal 1.wav");

    public static final AudioAsset PORTAL_2 = AudioAsset.sfx(
        "._Portal_2.wav", DIR,
        "Asset - . Portal 2.wav");

    public static final AudioAsset PORTAL_CLOSING = AudioAsset.sfx(
        "._Portal_closing.wav", DIR,
        "Asset - . Portal closing.wav");

    public static final AudioAsset PORTAL_MOVING = AudioAsset.sfx(
        "._Portal_moving.wav", DIR,
        "Asset - . Portal moving.wav");

    public static final AudioAsset PUSH_SLIDE_DOOR = AudioAsset.sfx(
        "._Push_slide_door.wav", DIR,
        "Asset - . Push slide door.wav");

    public static final AudioAsset ROLLER_DOORS = AudioAsset.sfx(
        "._Roller_doors.wav", DIR,
        "Asset - . Roller doors.wav");

    public static final AudioAsset SAMURAI_DEATH = AudioAsset.sfx(
        "._Samurai_death.wav", DIR,
        "Asset - . Samurai death.wav");

    public static final AudioAsset SAMURAI_FOOTSTEP_1 = AudioAsset.sfx(
        "._Samurai_footstep_1.wav", DIR,
        "Asset - . Samurai footstep 1.wav");

    public static final AudioAsset SAMURAI_FOOTSTEP_2 = AudioAsset.sfx(
        "._Samurai_footstep_2.wav", DIR,
        "Asset - . Samurai footstep 2.wav");

    public static final AudioAsset SLIDING_DOORS = AudioAsset.sfx(
        "._Sliding_doors.wav", DIR,
        "Asset - . Sliding doors.wav");

    public static final AudioAsset STEALTHY_THEME_LOOPABLE = AudioAsset.sfx(
        "._Stealthy_theme_loopable.wav", DIR,
        "Asset - . Stealthy theme loopable.wav");

    public static final AudioAsset UNLOCKED_CHEST = AudioAsset.sfx(
        "._Unlocked_chest.wav", DIR,
        "Asset - . Unlocked chest.wav");

    public static final AudioAsset ZIPLINE_LOOPABLE = AudioAsset.sfx(
        "._Zipline_loopable.wav", DIR,
        "Asset - . Zipline loopable.wav");

    /** Total number of assets in this group */
    public static final int COUNT = 35;

    private SfxAssets() { } // no instantiation
}
