package assets.bosses;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/bosses/GolfCartSoldier
 * Total assets: 11
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class GolfCartSoldierAssets {

    private static final String DIR = "Resources/industrial-zone/characters/bosses/GolfCartSoldier/";

    /** 288x72px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset BOSS_GOLFSOLDIER_IDLE_SOLDIERSTANDINGIDLE_DEFAULTIDLE = SpriteAsset.loop(
        "01_Boss_GolfSoldier_Idle_4Frames1Row_SoldierStandingIdle_DefaultIdle_Loop_150ms.png",
        DIR, 288, 72, 150,
        "01 Boss GolfSoldier Idle 4Frames1Row SoldierStandingIdle DefaultIdle Loop 150ms");

    /** 432x72px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset BOSS_GOLFSOLDIER_WALK_SOLDIERWALKINGWITHWEAPON_MOVEMENT = SpriteAsset.loop(
        "02_Boss_GolfSoldier_Walk_5Frames1Row_SoldierWalkingWithWeapon_Movement_Loop_100ms.png",
        DIR, 432, 72, 100,
        "02 Boss GolfSoldier Walk 5Frames1Row SoldierWalkingWithWeapon Movement Loop 100ms");

    /** 432x72px | ~6 frames | 70ms/f */
    public static final SpriteAsset BOSS_GOLFSOLDIER_ATTACK_MELEEWEAPONSWEEP_MELEEATTACK = SpriteAsset.once(
        "03_Boss_GolfSoldier_Attack_5Frames1Row_MeleeWeaponSweep_MeleeAttack_PlayOnce_70ms.png",
        DIR, 432, 72, 70,
        "03 Boss GolfSoldier Attack 5Frames1Row MeleeWeaponSweep MeleeAttack PlayOnce 70ms");

    /** 144x72px | ~2 frames | 100ms/f */
    public static final SpriteAsset BOSS_GOLFSOLDIER_HURT1_HITREACTIONVARIANT_TAKEDAMAGE = SpriteAsset.once(
        "04_Boss_GolfSoldier_Hurt1_2Frames1Row_HitReactionVariant_TakeDamage_PlayOnce_100ms.png",
        DIR, 144, 72, 100,
        "04 Boss GolfSoldier Hurt1 2Frames1Row HitReactionVariant TakeDamage PlayOnce 100ms");

    /** 288x72px | ~4 frames | 120ms/f */
    public static final SpriteAsset BOSS_GOLFSOLDIER_DEATH_CRAWLINGCOLLAPSEDEATH_DEATH = SpriteAsset.once(
        "05_Boss_GolfSoldier_Death_4Frames1Row_CrawlingCollapseDeath_Death_PlayOnce_120ms.png",
        DIR, 288, 72, 120,
        "05 Boss GolfSoldier Death 4Frames1Row CrawlingCollapseDeath Death PlayOnce 120ms");

    /** 144x72px | ~2 frames | 100ms/f */
    public static final SpriteAsset BOSS_GOLFSOLDIER_HURT2_SOLDIERHURTVARIANT_TAKEDAMAGE = SpriteAsset.once(
        "06_Boss_GolfSoldier_Hurt2_2Frames1Row_SoldierHurtVariant_TakeDamage_PlayOnce_100ms.png",
        DIR, 144, 72, 100,
        "06 Boss GolfSoldier Hurt2 2Frames1Row SoldierHurtVariant TakeDamage PlayOnce 100ms");

    /** 288x72px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset BOSS_GOLFCART_IDLE_CARTIDLEDRIVERSEATED_DEFAULTIDLE = SpriteAsset.loop(
        "07_Boss_GolfCart_Idle_4Frames1Row_CartIdleDriverSeated_DefaultIdle_Loop_150ms.png",
        DIR, 288, 72, 150,
        "07 Boss GolfCart Idle 4Frames1Row CartIdleDriverSeated DefaultIdle Loop 150ms");

    /** 288x72px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset BOSS_GOLFCART_IDLEEMPTY_CARTEMPTYNODRIVER_DEFAULTIDLE = SpriteAsset.loop(
        "08_Boss_GolfCart_IdleEmpty_4Frames1Row_CartEmptyNoDriver_DefaultIdle_Loop_150ms.png",
        DIR, 288, 72, 150,
        "08 Boss GolfCart IdleEmpty 4Frames1Row CartEmptyNoDriver DefaultIdle Loop 150ms");

    /** 288x72px | ~4 frames | 100ms/f | loop */
    public static final SpriteAsset BOSS_GOLFCART_WALK_CARTMOVINGDRIVERSTEERING_MOVEMENT = SpriteAsset.loop(
        "09_Boss_GolfCart_Walk_4Frames1Row_CartMovingDriverSteering_Movement_Loop_100ms.png",
        DIR, 288, 72, 100,
        "09 Boss GolfCart Walk 4Frames1Row CartMovingDriverSteering Movement Loop 100ms");

    /** 432x72px | ~6 frames | 80ms/f | loop */
    public static final SpriteAsset BOSS_GOLFCART_FASTOUT_CARTFASTDRIVELEANINGFORWARD_MOVEMENT = SpriteAsset.loop(
        "10_Boss_GolfCart_FastOut_5Frames1Row_CartFastDriveLeaningForward_Movement_Loop_80ms.png",
        DIR, 432, 72, 80,
        "10 Boss GolfCart FastOut 5Frames1Row CartFastDriveLeaningForward Movement Loop 80ms");

    /** 432x72px | ~6 frames | 120ms/f */
    public static final SpriteAsset BOSS_GOLFCART_DEATH_CARTDESTRUCTIONDRIVERINCART_DEATH = SpriteAsset.once(
        "11_Boss_GolfCart_Death_6Frames1Row_CartDestructionDriverInCart_Death_PlayOnce_120ms.png",
        DIR, 432, 72, 120,
        "11 Boss GolfCart Death 6Frames1Row CartDestructionDriverInCart Death PlayOnce 120ms");

    /** Total number of assets in this group */
    public static final int COUNT = 11;

    private GolfCartSoldierAssets() { } // no instantiation
}
