package assets.bosses;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/bosses/GreenMech
 * Total assets: 10
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class GreenMechAssets {

    private static final String DIR = "Resources/industrial-zone/characters/bosses/GreenMech/";

    /** 288x72px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset BOSS_GREENMECH_IDLE1_MECHSTANDINGIDLECANNONSREADY_DEFAULTIDLE = SpriteAsset.loop(
        "01_Boss_GreenMech_Idle1_4Frames1Row_MechStandingIdleCannonsReady_DefaultIdle_Loop_150ms.png",
        DIR, 288, 72, 150,
        "01 Boss GreenMech Idle1 4Frames1Row MechStandingIdleCannonsReady DefaultIdle Loop 150ms");

    /** 288x72px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset BOSS_GREENMECH_IDLE2_MECHSTANDINGIDLEVARIANT_DEFAULTIDLE = SpriteAsset.loop(
        "02_Boss_GreenMech_Idle2_4Frames1Row_MechStandingIdleVariant_DefaultIdle_Loop_150ms.png",
        DIR, 288, 72, 150,
        "Asset - 02 Boss GreenMech Idle2 4Frames1Row MechStandingIdleVariant DefaultIdle Loop 150ms");

    /** 432x72px | ~6 frames | 150ms/f | loop */
    public static final SpriteAsset BOSS_GREENMECH_IDLE3_MECHSTANDINGIDLEALTVARIANT_DEFAULTIDLE = SpriteAsset.loop(
        "03_Boss_GreenMech_Idle3_4Frames1Row_MechStandingIdleAltVariant_DefaultIdle_Loop_150ms.png",
        DIR, 432, 72, 150,
        "03 Boss GreenMech Idle3 4Frames1Row MechStandingIdleAltVariant DefaultIdle Loop 150ms");

    /** 432x72px | ~6 frames | 150ms/f | loop */
    public static final SpriteAsset BOSS_GREENMECH_IDLE4_MECHSTANDINGIDLEFINALVARIANT_DEFAULTIDLE = SpriteAsset.loop(
        "04_Boss_GreenMech_Idle4_4Frames1Row_MechStandingIdleFinalVariant_DefaultIdle_Loop_150ms.png",
        DIR, 432, 72, 150,
        "04 Boss GreenMech Idle4 4Frames1Row MechStandingIdleFinalVariant DefaultIdle Loop 150ms");

    /** 432x72px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset BOSS_GREENMECH_WALK_MECHSTEPPINGFORWARDMOVEMENT_MOVEMENT = SpriteAsset.loop(
        "05_Boss_GreenMech_Walk_5Frames1Row_MechSteppingForwardMovement_Movement_Loop_100ms.png",
        DIR, 432, 72, 100,
        "Asset - 05 Boss GreenMech Walk 5Frames1Row MechSteppingForwardMovement Movement Loop 100ms");

    /** 576x72px | ~8 frames | 200ms/f */
    public static final SpriteAsset BOSS_GREENMECH_CHARGE_MECHCHARGINGENERGYATTACK_CHARGEABILITY_BUILDUP = SpriteAsset.once(
        "06_Boss_GreenMech_Charge_6Frames1Row_MechChargingEnergyAttack_ChargeAbility_BuildUp_200ms.png",
        DIR, 576, 72, 200,
        "06 Boss GreenMech Charge 6Frames1Row MechChargingEnergyAttack ChargeAbility BuildUp 200ms");

    /** 432x72px | ~6 frames | 100ms/f */
    public static final SpriteAsset BOSS_GREENMECH_ATTACK1_STATIONARYHEAVYCANNONBLAST_RANGEDATTACK = SpriteAsset.once(
        "07_Boss_GreenMech_Attack1_4Frames1Row_StationaryHeavyCannonBlast_RangedAttack_PlayOnce_100ms.png",
        DIR, 432, 72, 100,
        "07 Boss GreenMech Attack1 4Frames1Row StationaryHeavyCannonBlast RangedAttack PlayOnce 100ms");

    /** 144x72px | ~2 frames | 100ms/f */
    public static final SpriteAsset BOSS_GREENMECH_ATTACK2_LEGSTOMPWITHFIRECOMBOPUNCH_HEAVYATTACK = SpriteAsset.once(
        "08_Boss_GreenMech_Attack2_5Frames1Row_LegStompWithFireComboPunch_HeavyAttack_PlayOnce_100ms.png",
        DIR, 144, 72, 100,
        "08 Boss GreenMech Attack2 5Frames1Row LegStompWithFireComboPunch HeavyAttack PlayOnce 100ms");

    /** 12x6px | static | 100ms/f */
    public static final SpriteAsset BOSS_GREENMECH_HIT_MECHTAKINGDAMAGEREACTION_TAKEDAMAGE = SpriteAsset.once(
        "09_Boss_GreenMech_Hit_2Frames1Row_MechTakingDamageReaction_TakeDamage_PlayOnce_100ms.png",
        DIR, 12, 6, 100,
        "09 Boss GreenMech Hit 2Frames1Row MechTakingDamageReaction TakeDamage PlayOnce 100ms");

    /** 432x72px | ~6 frames | 120ms/f */
    public static final SpriteAsset BOSS_GREENMECH_DEATH_MECHCOLLAPSING_DEATHSEQUENCE = SpriteAsset.once(
        "10_Boss_GreenMech_Death_4Frames1Row_MechCollapsing_DeathSequence_PlayOnce_120ms.png",
        DIR, 432, 72, 120,
        "Asset - 10 Boss GreenMech Death 4Frames1Row MechCollapsing DeathSequence PlayOnce 120ms");

    /** Total number of assets in this group */
    public static final int COUNT = 10;

    private GreenMechAssets() { } // no instantiation
}
