package assets.bosses;

import assets.SpriteAsset;

/**
 * Auto-generated sprite asset descriptors for: characters/bosses/RugbyGuy
 * Total assets: 6
 *
 * Frame counts are auto-calculated by SpriteAsset:
 *   width > 32px  →  spritesheet  →  frames = width / height
 *   width <= 32px →  single sprite →  frames = 1
 *
 * Generated by generate_asset_classes.py — do not edit manually.
 */
public final class RugbyGuyAssets {

    private static final String DIR = "Resources/industrial-zone/characters/bosses/RugbyGuy/";

    /** 288x72px | ~4 frames | 150ms/f | loop */
    public static final SpriteAsset BOSS_GREENMECH_IDLE2_MECHIDLEVARIANT_SECONDARYIDLE = SpriteAsset.loop(
        "02_Boss_GreenMech_Idle2_4Frames1Row_MechIdleVariant_SecondaryIdle_Loop_150ms.png",
        DIR, 288, 72, 150,
        "Asset - 02 Boss GreenMech Idle2 4Frames1Row MechIdleVariant SecondaryIdle Loop 150ms");

    /** 432x72px | ~6 frames | 100ms/f | loop */
    public static final SpriteAsset BOSS_GREENMECH_WALK2_MECHWALKINGVARIANT_MOVEMENT = SpriteAsset.loop(
        "04_Boss_GreenMech_Walk2_5Frames1Row_MechWalkingVariant_Movement_Loop_100ms.png",
        DIR, 432, 72, 100,
        "Asset - 04 Boss GreenMech Walk2 5Frames1Row MechWalkingVariant Movement Loop 100ms");

    /** 12x8px | static | 100ms/f | loop */
    public static final SpriteAsset BOSS_GREENMECH_BALL_1FRAME1ROW_CANNONBALLPROJECTILE_PROJECTILE = SpriteAsset.loop(
        "11_Boss_GreenMech_Ball_1Frame1Row_CannonBallProjectile_Projectile_Loop_100ms.png",
        DIR, 12, 8, 100,
        "Tile - 11 Boss GreenMech Ball 1Frame1Row CannonBallProjectile Projectile Loop 100ms");

    /** 432x72px | ~6 frames | 120ms/f */
    public static final SpriteAsset BOSS_GOLFSOLDIER_SNEER2_TAUNTVARIANT_TAUNT = SpriteAsset.once(
        "17_Boss_GolfSoldier_Sneer2_5Frames1Row_TauntVariant_Taunt_PlayOnce_120ms.png",
        DIR, 432, 72, 120,
        "Asset - 17 Boss GolfSoldier Sneer2 5Frames1Row TauntVariant Taunt PlayOnce 120ms");

    /** 144x72px | ~2 frames | 100ms/f */
    public static final SpriteAsset BOSS_GOLFSOLDIER_HURT1_HITREACTIONREDGHOST_TAKEDAMAGE = SpriteAsset.once(
        "18_Boss_GolfSoldier_Hurt1_2Frames1Row_HitReactionRedGhost_TakeDamage_PlayOnce_100ms.png",
        DIR, 144, 72, 100,
        "Asset - 18 Boss GolfSoldier Hurt1 2Frames1Row HitReactionRedGhost TakeDamage PlayOnce 100ms");

    /** 432x72px | ~6 frames | 120ms/f */
    public static final SpriteAsset BOSS_GOLFSOLDIER_DEATH1_DEATHFALLSEQUENCE_DEATH = SpriteAsset.once(
        "20_Boss_GolfSoldier_Death1_5Frames1Row_DeathFallSequence_Death_PlayOnce_120ms.png",
        DIR, 432, 72, 120,
        "Asset - 20 Boss GolfSoldier Death1 5Frames1Row DeathFallSequence Death PlayOnce 120ms");

    /** Total number of assets in this group */
    public static final int COUNT = 6;

    private RugbyGuyAssets() { } // no instantiation
}
